Repository FuelLabs/sway, pull requests merged in 2022-04, with the labels that each got.

#1112 Remove duplicated errors and warnings.
  sway-core/src/lib.rs
Labels: bug, compiler

#1121 Add an `is_reference_type::<T>()` builtin.
  sway-core/src/asm_generation/expression/mod.rs
  sway-core/src/asm_generation/expression/subfield.rs
  sway-core/src/asm_generation/mod.rs
  sway-core/src/control_flow_analysis/dead_code_analysis.rs
  sway-core/src/optimize.rs
  sway-core/src/parse_tree/expression/mod.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression_variant.rs
  sway-core/src/semantic_analysis/node_dependencies.rs
  sway-core/src/sway.pest
  sway-core/src/type_engine/type_info.rs
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/should_pass/language/is_reference_type/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/is_reference_type/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/is_reference_type/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/language/is_reference_type/src/main.sw
Labels: enhancement, compiler

#1115 Add a reentrancy module
  sway-lib-std/src/context/call_frames.sw
  sway-lib-std/src/lib.sw
  sway-lib-std/src/reentrancy.sw
  sway-lib-std/tests/test_artifacts/reentrancy_attacker_abi/.gitignore
  sway-lib-std/tests/test_artifacts/reentrancy_attacker_abi/Forc.lock
  sway-lib-std/tests/test_artifacts/reentrancy_attacker_abi/Forc.toml
  sway-lib-std/tests/test_artifacts/reentrancy_attacker_abi/src/main.sw
  sway-lib-std/tests/test_artifacts/reentrancy_attacker_contract/.gitignore
  sway-lib-std/tests/test_artifacts/reentrancy_attacker_contract/Forc.lock
  sway-lib-std/tests/test_artifacts/reentrancy_attacker_contract/Forc.toml
  sway-lib-std/tests/test_artifacts/reentrancy_attacker_contract/src/main.sw
  sway-lib-std/tests/test_artifacts/reentrancy_target_abi/.gitignore
  sway-lib-std/tests/test_artifacts/reentrancy_target_abi/Forc.lock
  sway-lib-std/tests/test_artifacts/reentrancy_target_abi/Forc.toml
  sway-lib-std/tests/test_artifacts/reentrancy_target_abi/src/main.sw
  sway-lib-std/tests/test_artifacts/reentrancy_target_contract/.gitignore
  sway-lib-std/tests/test_artifacts/reentrancy_target_contract/Forc.lock
  sway-lib-std/tests/test_artifacts/reentrancy_target_contract/Forc.toml
  sway-lib-std/tests/test_artifacts/reentrancy_target_contract/src/main.sw
  sway-lib-std/tests/test_projects/context/mod.rs
  sway-lib-std/tests/test_projects/harness.rs
  sway-lib-std/tests/test_projects/reentrancy/mod.rs
Labels: enhancement, lib: std, testing

#1132 Misc minor docs fixes.
  docs/src/advanced/generic_types.md
  docs/src/advanced/traits.md
  docs/src/basics/built_in_types.md
  docs/src/basics/methods_and_associated_functions.md
  docs/src/basics/structs_and_tuples.md
  docs/src/reference/rust_differences.md
  docs/src/sway-program-types/libraries.md
Labels: The Sway Book

#1133 Clean up SDK references in Book.
  docs/src/SUMMARY.md
  docs/src/frontend/index.md
  docs/src/frontend/typescript_sdk.md
  docs/src/sdks/index.md
  docs/src/sdks/rust-sdk.md
  docs/src/testing/index.md
  docs/src/testing/testing-with-rust.md
  docs/src/testing/testing-with-typescript.md
Labels: The Sway Book

#1134 Calling Contracts
  docs/src/blockchain-development/calling_contracts.md
Labels: The Sway Book

#1130 Switch all `--use-ir` build config options to `--use-orig-asm`.
  forc-pkg/src/pkg.rs
  forc/src/cli/commands/build.rs
  forc/src/cli/commands/deploy.rs
  forc/src/cli/commands/run.rs
  forc/src/ops/forc_build.rs
  forc/src/ops/forc_deploy.rs
  forc/src/ops/forc_run.rs
  sway-core/src/asm_generation/from_ir.rs
  sway-core/src/build_config.rs
  sway-core/src/error.rs
  sway-core/src/lib.rs
  sway-core/src/optimize.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-lib-std/tests/test_projects/context/mod.rs
  sway-lib-std/tests/test_projects/token_ops/mod.rs
  sway-lib-std/tests/test_projects/tx_fields/mod.rs
  test/src/e2e_vm_tests/harness.rs
Labels: ir

#1142 Fix typo in book
  docs/src/basics/control_flow.md
Labels: The Sway Book

#1141 Updating contract tests after IR. Also, some cleanup.
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/bal_opcode/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/bal_opcode/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_basic_storage/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_increment_contract/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/caller_auth_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/caller_context_test/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/caller_context_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/contract_call/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/contract_call/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/contract_call/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/contract_call/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/storage_access_caller/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/storage_access_caller/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/storage_access_caller/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/token_ops_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/test_abis/context_testing_abi/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/test_abis/storage_access_abi/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/test_abis/test_fuel_coin_abi/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/test_abis/test_fuel_coin_abi/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/auth_testing_contract/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/balance_test_contract/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/balance_test_contract/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/basic_storage/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/basic_storage/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/context_testing_contract/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/context_testing_contract/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/contract_abi_impl/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/contract_abi_impl/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/contract_abi_impl/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/contract_abi_impl/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/storage_access_contract/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/storage_access_contract/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/test_fuel_coin_contract/src/main.sw
Labels: testing

#1046 Fix Lsp Symbol Rename Bug
  sway-lsp/src/capabilities/rename.rs
  sway-lsp/src/core/token.rs
  sway-lsp/src/utils/lsp_helpers.rs
  sway-lsp/src/utils/mod.rs
Labels: language server

#1157 Use const values for offsets in call_frames module
  sway-lib-std/src/context/call_frames.sw
Labels: lib: std, code quality

#1154 Adding token minting helper functions.
  sway-lib-std/src/token.sw
  sway-lib-std/tests/test_projects/token_ops/mod.rs
  sway-lib-std/tests/test_projects/token_ops/src/main.sw
Labels: enhancement, lib: std

#1149 Add a reverse map for looking up metadata location indices.
  sway-ir/src/context.rs
  sway-ir/src/metadata.rs
Labels: code quality, ir

#1166 Implement `EQ` trait for `B512`
  sway-lib-std/src/b512.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/b512_test/src/main.sw
Labels: enhancement, lib: std

#1144 Added error msg to `forc-init` when `proj-name` is `test`
  forc-util/src/lib.rs
  forc/src/ops/forc_init.rs
Labels: bug, forc

#1139 Add Cargo.toml linting to the CI pipeline
  .github/workflows/ci.yml
  forc/Cargo.toml
  sway-core/Cargo.toml
  sway-lib-std/tests/Cargo.toml
  sway-lsp/Cargo.toml
  test/Cargo.toml
Labels: ci

#1174 Explicitly declare `[lib]` and `[[bin]]` targets for `forc`
  forc/Cargo.toml
  forc/src/cli/mod.rs
  forc/src/lib.rs
  forc/src/main.rs
Labels: forc, code quality

#1176 Remove `#![allow(dead_code)]` from `forc` along with dead code
  forc/src/cli/commands/addr2line.rs
  forc/src/lib.rs
  forc/src/ops/forc_explorer.rs
  forc/src/ops/forc_init.rs
  forc/src/utils/client.rs
  forc/src/utils/mod.rs
Labels: forc, code quality

#1148 print all parsed LSP tokens as warnings in VScode
  Cargo.lock
  forc/src/cli/commands/lsp.rs
  forc/src/cli/mod.rs
  forc/src/ops/forc_lsp.rs
  forc/src/ops/mod.rs
  sway-lsp/src/lib.rs
  sway-lsp/src/server.rs
  sway-lsp/src/utils/debug.rs
  sway-lsp/src/utils/mod.rs
Labels: language server

#1173 Fix reassignment of struct members in impl self
  sway-core/src/optimize.rs
  sway-core/tests/sway_to_ir/impl_self_reassignment.ir
  sway-core/tests/sway_to_ir/impl_self_reassignment.sw
  sway-core/tests/sway_to_ir/let_reassign_while_loop.ir
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/should_pass/language/self_impl_reassignment/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/self_impl_reassignment/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/self_impl_reassignment/src/main.sw
Labels: bug, compiler

#1178 Add support for `forc` CLI plugins
  forc/src/cli/mod.rs
  forc/src/cli/plugin.rs
Labels: enhancement, forc

#1193 Appease clippy's latest gripes for CI
  forc/src/ops/forc_explorer.rs
Labels: bug, ci

#1181 Allow forwarding options and arguments from `forc test` to `cargo test`
  forc/src/cli/commands/test.rs
Labels: enhancement, forc, testing

#1179 Move `forc`'s LSP support into a dedicated `forc-lsp` plugin crate
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  forc-lsp/Cargo.toml
  forc-lsp/src/main.rs
  forc/Cargo.toml
  forc/src/cli/commands/lsp.rs
  forc/src/cli/commands/mod.rs
  forc/src/cli/mod.rs
  forc/src/ops/forc_lsp.rs
  forc/src/ops/mod.rs
Labels: enhancement, forc, language server

#1171 Make ec_recover funcs return Results
  sway-lib-std/src/ecr.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/ec_recover_test/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/ec_recover_test/src/main.sw
Labels: lib: std, code quality

#1180 Move `forc`'s block explorer support into a dedicated `forc-explore` plugin crate
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  forc-explore/Cargo.toml
  forc-explore/src/main.rs
  forc/Cargo.toml
  forc/src/cli/commands/explorer.rs
  forc/src/cli/commands/mod.rs
  forc/src/cli/mod.rs
  forc/src/ops/forc_explorer.rs
  forc/src/ops/mod.rs
Labels: enhancement, forc, code quality

#1195 Parse document for tokens on every LSP on_change event
  sway-lsp/src/capabilities/text_sync.rs
  sway-lsp/src/core/session.rs
  sway-lsp/src/server.rs
Labels: language server

#1187 Introduce the `ContractCaller<AbiName>` type
  sway-core/src/control_flow_analysis/analyze_return_paths.rs
  sway-core/src/control_flow_analysis/dead_code_analysis.rs
  sway-core/src/error.rs
  sway-core/src/optimize.rs
  sway-core/src/parse_tree/call_path.rs
  sway-core/src/parse_tree/expression/mod.rs
  sway-core/src/semantic_analysis/ast_node/declaration.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/method_application.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression_variant.rs
  sway-core/src/semantic_analysis/node_dependencies.rs
  sway-core/src/sway.pest
  sway-core/src/type_engine/engine.rs
  sway-core/src/type_engine/type_info.rs
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/should_fail/different_contract_caller_types/.gitignore
  test/src/e2e_vm_tests/test_programs/should_fail/different_contract_caller_types/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/different_contract_caller_types/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/different_contract_caller_types/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/contract_caller_as_type/.gitignore
  test/src/e2e_vm_tests/test_programs/should_pass/language/contract_caller_as_type/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/contract_caller_as_type/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/contract_caller_as_type/src/main.sw
Labels: compiler, language feature

#1197 Add a CI job that checks for unused crate dependencies
  .github/workflows/ci.yml
  Cargo.lock
  docstrings/Cargo.toml
  parser/Cargo.toml
  sway-types/Cargo.toml
Labels: ci, code quality

#1196 Move `forc`'s `fmt` command support into a dedicated `forc-fmt` plugin crate
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  forc-fmt/Cargo.toml
  forc-fmt/src/main.rs
  forc/Cargo.toml
  forc/src/cli/commands/format.rs
  forc/src/cli/commands/mod.rs
  forc/src/cli/mod.rs
  forc/src/ops/mod.rs
Labels: enhancement, forc, code quality, formatter

#1204 IR syntax highlighting
  .gitattributes
Labels: bikeshedding

#1199 Add a `forc plugins` command for listing all plugins
  Cargo.lock
  forc/Cargo.toml
  forc/src/cli/commands/mod.rs
  forc/src/cli/commands/plugins.rs
  forc/src/cli/mod.rs
  forc/src/cli/plugin.rs
Labels: enhancement, forc

#1208 Update Sway book examples to use new features
  examples/counter/src/main.sw
  examples/fizzbuzz/src/main.sw
  examples/hello_world/src/main.sw
  examples/subcurrency/src/main.sw
  examples/wallet_smart_contract/src/main.sw
Labels: The Sway Book

#1219 Remove duplicate errors
  forc-util/src/lib.rs
Labels: bug, compiler

#1207 bump to v0.10.0
  Cargo.lock
  forc-explore/Cargo.toml
  forc-fmt/Cargo.toml
  forc-lsp/Cargo.toml
  forc-pkg/Cargo.toml
  forc-util/Cargo.toml
  forc/Cargo.toml
  parser/Cargo.toml
  sway-core/Cargo.toml
  sway-fmt/Cargo.toml
  sway-ir/Cargo.toml
  sway-lsp/Cargo.toml
  sway-types/Cargo.toml
  sway-utils/Cargo.toml
  test/Cargo.toml
Labels: release

#1194 Update `forc init` to include a more realistic test and contract skeleton
  forc/src/ops/forc_init.rs
  forc/src/utils/defaults.rs
Labels: forc

#1221 Removing a println! that slipped through
  sway-core/src/asm_generation/from_ir.rs
Labels: compiler

#1226 Remove `std` from the list of dependencies in the default Forc.toml
  forc/src/utils/defaults.rs
Labels: forc

#1205 Checking E2E contract test receipts
  forc/src/ops/forc_run.rs
  test/src/e2e_vm_tests/harness.rs
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_increment_contract/src/main.sw
Labels: forc, testing

#1223 Exposing methods of a trait to its subtraits and some additional things
  sway-core/src/semantic_analysis/ast_node/mod.rs
  test/src/e2e_vm_tests/test_programs/should_pass/language/supertraits/src/main.sw
Labels: bug, compiler

#1245 Fix forc init --template counter
  forc/src/ops/forc_init.rs
  forc/src/utils/defaults.rs
Labels: bug, forc

#1232 Updated `from_dir` to check parent directories
  forc-pkg/src/manifest.rs
  forc-pkg/src/pkg.rs
  forc/src/ops/forc_abi_json.rs
  forc/src/ops/forc_build.rs
  forc/src/ops/forc_deploy.rs
  forc/src/ops/forc_run.rs
  forc/src/ops/forc_update.rs
Labels: forc, code quality

#1250 Missing span for TypeProperty
  sway-core/src/asm_generation/expression/mod.rs
  sway-core/src/optimize.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression_variant.rs
Labels: bug, compiler

#1247 Fix typo stabilized
  docs/src/examples/counter.md
Labels: The Sway Book

#1253 Added optional trailing `,` to `use` statements in `sway-pest`
  sway-core/src/sway.pest
Labels: bug, compiler

#1251 Properly handle TypeProperty in `dead_code_analysis`
  sway-core/src/control_flow_analysis/dead_code_analysis.rs
Labels: bug, compiler

#1249 Introduce a path-aware `ManifestFile` type
  forc-pkg/src/lib.rs
  forc-pkg/src/manifest.rs
  forc-pkg/src/pkg.rs
  forc/src/ops/forc_abi_json.rs
  forc/src/ops/forc_build.rs
  forc/src/ops/forc_deploy.rs
  forc/src/ops/forc_run.rs
  forc/src/ops/forc_update.rs
Labels: forc, code quality

#1228 Expanding storage documentation
  docs/src/blockchain-development/storage.md
  examples/storage_example/Forc.lock
  examples/storage_example/Forc.toml
  examples/storage_example/src/main.sw
Labels: The Sway Book

#1255 Update tx.sw to use const values
  sway-lib-std/src/tx.sw
Labels: lib: std, code quality

#1264 Remove workaround for including `lib-std` from the Sway Book
  docs/src/advanced/assembly.md
  docs/src/basics/blockchain_types.md
  docs/src/reference/temporary_workarounds.md
Labels: The Sway Book

#1269 Added test for trailing `,` in import lists
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/should_pass/language/import_trailing_comma/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/import_trailing_comma/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/import_trailing_comma/src/lib.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/import_trailing_comma/src/main.sw
Labels: compiler, testing

#1259 add log_b256 method to std library
  sway-lib-std/src/chain.sw
  sway-lib-std/tests/Cargo.toml
  sway-lib-std/tests/test_projects/harness.rs
  sway-lib-std/tests/test_projects/logging/Forc.lock
  sway-lib-std/tests/test_projects/logging/Forc.toml
  sway-lib-std/tests/test_projects/logging/mod.rs
  sway-lib-std/tests/test_projects/logging/src/main.sw
Labels: enhancement, lib: std

#1266 Specify Rust version in install docs
  docs/src/introduction/installation.md
Labels: enhancement, The Sway Book

#1257 forc init welcome message
  forc/src/ops/forc_init.rs
Labels: enhancement, forc

#1275 docs: add short instruction to install forc lsp
  docs/src/introduction/sway-toolchain.md
Labels: The Sway Book

#1272 Re-introduce the single arg contract call optimisation for IR.
  sway-core/src/asm_generation/from_ir.rs
  sway-core/src/optimize.rs
  sway-core/tests/ir_to_asm/nested_single_word_struct.asm
  sway-core/tests/ir_to_asm/simple_contract.asm
  sway-core/tests/sway_to_ir/simple_contract_call.ir
  sway-lib-std/tests/test_projects/context/mod.rs
  sway-lib-std/tests/test_projects/token_ops/mod.rs
  sway-lib-std/tests/test_projects/tx_fields/mod.rs
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_basic_storage/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_increment_contract/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/caller_context_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/storage_access_caller/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/token_ops_test/src/main.sw
Labels: bug, compiler, lib: std

#1287 Fix import of submodules within `std::context`
  sway-lib-std/src/context.sw
Labels: bug, compiler, lib: std

#1289 Fix bug where `forc` panics if dependency declared with both `package` and `path`
  forc-pkg/src/pkg.rs
  test/src/e2e_vm_tests/test_programs/should_pass/forc/dependency_package_field/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/forc/dependency_package_field/Forc.toml
Labels: bug, forc, testing

#1290 Bump to 0.10.2
  Cargo.lock
  forc-explore/Cargo.toml
  forc-fmt/Cargo.toml
  forc-lsp/Cargo.toml
  forc-pkg/Cargo.toml
  forc-util/Cargo.toml
  forc/Cargo.toml
  parser/Cargo.toml
  sway-core/Cargo.toml
  sway-fmt/Cargo.toml
  sway-ir/Cargo.toml
  sway-lsp/Cargo.toml
  sway-types/Cargo.toml
  sway-utils/Cargo.toml
  test/Cargo.toml
Labels: release

#1293 Don't publish `forc` documenter
  Cargo.lock
  scripts/forc-documenter/Cargo.toml
Labels: bug, forc

#1294 Bump to 0.10.3
  Cargo.lock
  forc-explore/Cargo.toml
  forc-fmt/Cargo.toml
  forc-lsp/Cargo.toml
  forc-pkg/Cargo.toml
  forc-util/Cargo.toml
  forc/Cargo.toml
  parser/Cargo.toml
  sway-core/Cargo.toml
  sway-fmt/Cargo.toml
  sway-ir/Cargo.toml
  sway-lsp/Cargo.toml
  sway-types/Cargo.toml
  sway-utils/Cargo.toml
  test/Cargo.toml
Labels: release

#1279 Docs: add example of asm tuple return
  docs/src/advanced/assembly.md
  examples/asm_return_tuple_pointer/.gitignore
  examples/asm_return_tuple_pointer/Forc.lock
  examples/asm_return_tuple_pointer/Forc.toml
  examples/asm_return_tuple_pointer/src/main.sw
Labels: documentation, The Sway Book

#1285 Shorthand for build and test
  forc/src/cli/mod.rs
Labels: forc

#1283 Fixed issue where sway formatter was operating on a pathless AST
  Cargo.lock
  forc-fmt/Cargo.toml
  forc-fmt/src/main.rs
  sway-fmt/src/fmt.rs
  sway-lsp/src/capabilities/formatting.rs
Labels: bug, formatter

#1284 Added option to not include std implicitly
  forc-pkg/src/manifest.rs
Labels: enhancement, forc

#1282 Format `storage` similar to `struct`s
  sway-fmt/src/fmt.rs
  sway-fmt/src/traversal.rs
Labels: formatter

#1312 Sway Book counter init code
  docs/src/examples/counter.md
Labels: enhancement, The Sway Book

#1278 Doc Fixes - `forc-documenter`, assembly, tuples, smart-contracts link
  docs/README.md
  docs/src/advanced/assembly.md
  docs/src/basics/structs_and_tuples.md
  docs/src/blockchain-development/storage.md
Labels: documentation, The Sway Book

#1314 Handle removed dep in manifest during path reconstruction from graph
  forc-pkg/src/pkg.rs
Labels: bug, forc

#1322 Update CI to install forc and build sway examples
  .github/workflows/ci.yml
Labels: ci

#1310 Access Control Documentation
  docs/src/SUMMARY.md
  docs/src/blockchain-development/access_control.md
  docs/src/blockchain-development/index.md
  examples/msg_sender/Forc.lock
  examples/msg_sender/Forc.toml
  examples/msg_sender/src/main.sw
Labels: enhancement, The Sway Book

#1330 forc plugins
  docs/src/introduction/installation.md
Labels: enhancement, The Sway Book

#1317 Expand Native Asset Examples in Sway Book
  docs/src/blockchain-development/native_assets.md
  examples/liquidity_pool/Forc.lock
  examples/liquidity_pool/Forc.toml
  examples/liquidity_pool/src/main.sw
  examples/native_token/Forc.lock
  examples/native_token/Forc.toml
  examples/native_token/src/main.sw
Labels: enhancement, The Sway Book

#1276 Add binary_xor function
  sway-lib-core/src/ops.sw
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/should_pass/language/u64_ops/.gitignore
  test/src/e2e_vm_tests/test_programs/should_pass/language/u64_ops/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/u64_ops/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/u64_ops/src/main.sw
Labels: enhancement, lib: std

#1338 Make Forc docs nicer
  docs/src/forc/index.md
Labels: enhancement, The Sway Book

#1292 Correct handling string return values
  sway-core/src/asm_generation/from_ir.rs
  sway-core/tests/ir_to_asm/enum_struct_string.asm
  sway-ir/src/irtype.rs
  test/src/e2e_vm_tests/test_programs/should_pass/language/is_reference_type/src/main.sw
Labels: bug, compiler

#1344 Temporarily disable u64_ops test lines that fail to compile with new parser
  test/src/e2e_vm_tests/test_programs/should_pass/language/u64_ops/src/main.sw
Labels: bug, compiler, ci, testing

#1326 Show hexdump instead of decimal arrays in parse-bytecode
  forc/src/cli/commands/parse_bytecode.rs
Labels: enhancement, forc

#1306 Forc deploy docs update
  docs/src/forc/commands/forc_deploy.md
  scripts/forc-documenter/src/constants.rs
Labels: The Sway Book

#1349 Add minimal forc manifest back to stlib test suite
  test/src/sdk-harness/Forc.lock
  test/src/sdk-harness/Forc.toml
  test/src/sdk-harness/src/main.sw
  test/src/sdk-harness/test_projects/logging/src/main.sw
Labels: bug, lib: std, testing

#1352 Update readme for stdlib tests
  test/src/sdk-harness/README.md
Labels: documentation

#1340 Add dependency section to the Forc chapter
  docs/src/SUMMARY.md
  docs/src/forc/dependencies.md
  docs/src/introduction/forc_project.md
Labels: The Sway Book

#1334 Add specification link
  docs/src/blockchain-development/calling_contracts.md
Labels: enhancement, The Sway Book

#1353 Enable ^, << & >> and add new BitwiseOps traits.
  sway-core/src/convert_parse_tree.rs
  sway-lib-core/src/ops.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/u64_ops/src/main.sw
Labels: enhancement, code quality, lib: core

#1364 Fix CI - Concat `forc`'s stdout and stderr output in `forc-documenter`
  scripts/forc-documenter/src/main.rs
Labels: ci, testing, The Sway Book

#1348 Remove explicit `std` in getting started example
  docs/src/introduction/overview.md
Labels: code quality, The Sway Book

#1372 Remove visual clutter from build script output
  test/src/sdk-harness/build.sh
Labels: testing

#1379 Add --path to forc fmt.
  forc-fmt/src/main.rs
Labels: enhancement, forc, formatter

#1384 Check examples formatting in CI
  .github/workflows/ci.yml
  examples/build-all-examples/src/main.rs
  examples/counter/src/main.sw
  examples/hello_world/src/main.sw
  examples/liquidity_pool/src/main.sw
  examples/msg_sender/src/main.sw
  examples/native_token/src/main.sw
  examples/storage_example/src/main.sw
  examples/subcurrency/src/main.sw
  examples/wallet_smart_contract/src/main.sw
Labels: ci, formatter

#1354 Hide Forc.lock creation warn behind verbosity
  forc/src/ops/forc_build.rs
Labels: enhancement, forc

#1390 Fix leading comma being inserted by formatter
  sway-fmt/src/traversal_helper.rs
Labels: bug, formatter

#1360 Replace `hello_world` example with `counter` example
  docs/src/introduction/forc_project.md
  docs/src/testing/testing-with-rust.md
  examples/hello_world/Forc.lock
  examples/hello_world/Forc.toml
  examples/hello_world/src/main.sw
  forc/src/ops/forc_init.rs
Labels: forc, code quality

#1351 Updated `forc-init` to accept `program_type` parameters
  docs/src/forc/commands/forc_init.md
  forc/src/cli/commands/init.rs
  forc/src/ops/forc_init.rs
  forc/src/utils/defaults.rs
  forc/src/utils/mod.rs
  forc/src/utils/program_type.rs
  sway-utils/src/constants.rs
Labels: enhancement, forc

#1396 Add the bitcast instruction to the IR.
  sway-core/src/asm_generation/from_ir.rs
  sway-core/src/optimize.rs
  sway-core/tests/sway_to_ir/simple_contract_call.ir
  sway-ir/src/error.rs
  sway-ir/src/instruction.rs
  sway-ir/src/optimize/inline.rs
  sway-ir/src/parser.rs
  sway-ir/src/printer.rs
  sway-ir/src/verify.rs
  sway-ir/tests/ir_to_ir/constants_contract_calls.in_ir
  sway-ir/tests/ir_to_ir/constants_contract_calls.out_ir
Labels: bug, compiler, ir

#1388 Allow type arguments in struct call paths
  sway-core/src/convert_parse_tree.rs
  sway-core/src/optimize.rs
  sway-parse/src/keywords.rs
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/should_fail/primitive_type_argument/.gitignore
  test/src/e2e_vm_tests/test_programs/should_fail/primitive_type_argument/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/primitive_type_argument/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/primitive_type_argument/src/bar/baz.sw
  test/src/e2e_vm_tests/test_programs/should_fail/primitive_type_argument/src/foo.sw
  test/src/e2e_vm_tests/test_programs/should_fail/primitive_type_argument/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/primitive_type_argument/.gitignore
  test/src/e2e_vm_tests/test_programs/should_pass/language/primitive_type_argument/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/primitive_type_argument/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/primitive_type_argument/src/bar/baz.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/primitive_type_argument/src/bar/quux.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/primitive_type_argument/src/foo.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/primitive_type_argument/src/main.sw
Labels: enhancement, compiler

#1403 specify local dep for `asm_return_tuple_pointer` to prevent pulling in git dep
  examples/asm_return_tuple_pointer/Forc.lock
  examples/asm_return_tuple_pointer/Forc.toml
Labels: documentation, forc

#1402 v0.11.0
  Cargo.lock
  forc-explore/Cargo.toml
  forc-fmt/Cargo.toml
  forc-lsp/Cargo.toml
  forc-pkg/Cargo.toml
  forc-util/Cargo.toml
  forc/Cargo.toml
  sway-core/Cargo.toml
  sway-fmt/Cargo.toml
  sway-ir/Cargo.toml
  sway-lsp/Cargo.toml
  sway-parse/Cargo.toml
  sway-types/Cargo.toml
  sway-utils/Cargo.toml
  test/Cargo.toml
Labels: release

#1410 Update the `Forc.lock` files for the `should_fail` E2E tests.
  test/src/e2e_vm_tests/test_programs/should_fail/array_oob/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/asm_missing_return/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/asm_should_not_have_return/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/bad_generic_annotation/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/bad_generic_var_annotation/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/chained_if_let_missing_branch/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/contract_pure_calls_impure/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/dependency_parsing_error/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/different_contract_caller_types/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/disallow_turbofish/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/disallowed_gm/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/empty_impl/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/enum_if_let_invalid_variable/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/excess_fn_arguments/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/generic_shadows_generic/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/generics_unhelpful_error/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/item_used_without_import/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/literal_too_large_for_type/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/match_expressions_enums/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/match_expressions_non_exhaustive/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/match_expressions_wrong_struct/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/missing_fn_arguments/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/missing_func_from_supertrait_impl/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/missing_supertrait_impl/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/name_shadowing/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/nested_impure/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/predicate_calls_impure/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/pure_calls_impure/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/recursive_calls/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/script_calls_impure/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/shadow_import/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/star_import_alias/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/supertrait_does_not_exist/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/top_level_vars/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/unify_identical_unknowns/Forc.lock
Labels: testing

#1370 Added examples from examples repo
  forc/src/ops/forc_init.rs
Labels: good first issue, forc

#1397 Return a unit type constant when a function has no return value
  sway-core/src/optimize.rs
  sway-core/tests/sway_to_ir/impl_self_reassignment.ir
  sway-core/tests/sway_to_ir/ret_unit.ir
  sway-core/tests/sway_to_ir/ret_unit.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_basic_storage/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_increment_contract/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/token_ops_test/src/main.sw
Labels: bug, compiler

#1374 ECRECOVER ethereum addresses
  Cargo.lock
  sway-lib-std/src/lib.sw
  sway-lib-std/src/vm/evm/ecr.sw
  sway-lib-std/src/vm/evm/lib.sw
  sway-lib-std/src/vm/lib.sw
  test-sig-gen-util/Cargo.toml
  test-sig-gen-util/src/main.rs
  test/src/sdk-harness/build.sh
  test/src/sdk-harness/test_projects/evm_ecr/.gitignore
  test/src/sdk-harness/test_projects/evm_ecr/Forc.lock
  test/src/sdk-harness/test_projects/evm_ecr/Forc.toml
  test/src/sdk-harness/test_projects/evm_ecr/mod.rs
  test/src/sdk-harness/test_projects/evm_ecr/src/main.sw
  test/src/sdk-harness/test_projects/harness.rs
Labels: enhancement, lib: std

#1414 Add contract type and use wallet_lib::Wallet in wallet_contract example
  docs/src/introduction/overview.md
Labels: The Sway Book

#1416 Updating Cargo.lock
  Cargo.lock
Labels: dependencies

#1413 change lib.sw to mod.sw for submodules
  sway-lib-std/src/lib.sw
  sway-lib-std/src/vm/evm/mod.sw
  sway-lib-std/src/vm/mod.sw
Labels: lib: std

#1415 Some code cleanup in `register_allocator.rs`
  sway-core/src/asm_generation/register_allocator.rs
Labels: compiler, code quality

#1419 Switch the IR unit tests to use FileCheck.
  Cargo.lock
  sway-ir/Cargo.toml
  sway-ir/tests/constants/contract_calls.ir
  sway-ir/tests/constants/insert_value.ir
  sway-ir/tests/inline/bigger.ir
  sway-ir/tests/inline/fiddly.ir
  sway-ir/tests/inline/simple.ir
  sway-ir/tests/ir_to_ir/constants_contract_calls.out_ir
  sway-ir/tests/ir_to_ir/constants_insert_value.out_ir
  sway-ir/tests/ir_to_ir/constants_storage_load.out_ir
  sway-ir/tests/ir_to_ir/constants_storage_store.out_ir
  sway-ir/tests/ir_to_ir/inline_bigger.out_ir
  sway-ir/tests/ir_to_ir/inline_fiddly.out_ir
  sway-ir/tests/ir_to_ir/inline_simple.out_ir
  sway-ir/tests/serialize/storage_load.ir
  sway-ir/tests/serialize/storage_store.ir
  sway-ir/tests/tests.rs
Labels: enhancement, testing, ir

#1431 Temporarily remove rename capabilities from language server
  sway-lsp/src/server.rs
Labels: language server

#1434 add test for type inference via return type
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/should_pass/language/generic-type-inference/.gitignore
  test/src/e2e_vm_tests/test_programs/should_pass/language/generic-type-inference/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/generic-type-inference/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/generic-type-inference/src/main.sw
Labels: compiler, testing

#1435 Script test helper
  test/src/sdk-harness/Cargo.toml
  test/src/sdk-harness/test-helpers/Cargo.toml
  test/src/sdk-harness/test-helpers/src/lib.rs
  test/src/sdk-harness/test_projects/contract_id_type/mod.rs
  test/src/sdk-harness/test_projects/evm_ecr/mod.rs
Labels: enhancement, lib: std, testing

#1394 Fix annotation span bug #1365
  forc-util/src/lib.rs
Labels: compiler

#1417 Support `jnzi` in the compiler
  .github/workflows/ci.yml
  Cargo.lock
  forc/Cargo.toml
  forc/src/utils/defaults.rs
  sway-core/Cargo.toml
  sway-core/src/asm_generation/from_ir.rs
  sway-core/src/asm_generation/mod.rs
  sway-core/src/asm_generation/register_allocator.rs
  sway-core/src/asm_lang/allocated_ops.rs
  sway-core/src/asm_lang/mod.rs
  sway-core/src/asm_lang/virtual_ops.rs
  sway-core/src/error.rs
  sway-core/src/parse_tree/expression/asm.rs
  sway-core/tests/ir_to_asm/enum_struct_string.asm
  sway-core/tests/ir_to_asm/if_expr.asm
  sway-core/tests/ir_to_asm/lazy_binops.asm
  sway-core/tests/ir_to_asm/let_reassign_while_loop.asm
  sway-core/tests/ir_to_asm/nested_single_word_struct.asm
  sway-core/tests/ir_to_asm/simple_contract.asm
  sway-core/tests/ir_to_asm/simple_if_let.asm
  sway-core/tests/ir_to_asm/storage_load.asm
  sway-core/tests/ir_to_asm/storage_store.asm
  sway-core/tests/ir_to_asm/struct_in_union.asm
  sway-types/Cargo.toml
  sway-utils/src/constants.rs
  test-sig-gen-util/Cargo.toml
  test/Cargo.toml
  test/src/e2e_vm_tests/harness.rs
  test/src/e2e_vm_tests/test_programs/should_fail/array_bad_index/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/bal_opcode/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_basic_storage/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_increment_contract/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/caller_auth_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/caller_context_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/nested_struct_args_caller/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/storage_access_caller/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/token_ops_test/src/main.sw
  test/src/sdk-harness/Cargo.toml
  test/src/sdk-harness/test-helpers/Cargo.toml
  test/src/sdk-harness/test-helpers/src/lib.rs
  test/src/sdk-harness/test_projects/auth/mod.rs
  test/src/sdk-harness/test_projects/call_frames/mod.rs
  test/src/sdk-harness/test_projects/context/mod.rs
  test/src/sdk-harness/test_projects/logging/mod.rs
  test/src/sdk-harness/test_projects/option/mod.rs
  test/src/sdk-harness/test_projects/reentrancy/mod.rs
  test/src/sdk-harness/test_projects/registers/mod.rs
  test/src/sdk-harness/test_projects/result/mod.rs
  test/src/sdk-harness/test_projects/token_ops/mod.rs
  test/src/sdk-harness/test_projects/tx_fields/mod.rs
Labels: enhancement, compiler
