Repository FuelLabs/sway, pull requests merged in 2022-03, with the labels that each got.

#804 function to disallow whitespace & special characters in Forc manifest file
  Cargo.lock
  forc/Cargo.toml
  forc/src/utils/helpers.rs
  forc/src/utils/mod.rs
  forc/src/utils/restricted_names.rs
Labels: bug, forc, internship

#852 Big old bag of IR fixes.
  sway-core/src/asm_generation/from_ir.rs
  sway-core/src/optimize.rs
  sway-core/src/parse_tree/literal.rs
  sway-core/src/semantic_analysis/ast_node/mod.rs
  sway-core/tests/ir_to_asm/lazy_binops.asm
  sway-core/tests/ir_to_asm/let_reassign_while_loop.asm
  sway-core/tests/sway_to_ir/asm_block.ir
  sway-core/tests/sway_to_ir/asm_block.sw
  sway-core/tests/sway_to_ir/b256_immeds.ir
  sway-core/tests/sway_to_ir/enum.ir
  sway-core/tests/sway_to_ir/fn_call.ir
  sway-core/tests/sway_to_ir/shadowed_struct_init.ir
  sway-core/tests/sway_to_ir/trait.ir
  sway-ir/src/block.rs
  sway-ir/src/error.rs
  sway-ir/src/instruction.rs
  sway-ir/src/optimize/inline.rs
  sway-ir/src/parser.rs
  sway-ir/src/printer.rs
  sway-ir/src/verify.rs
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/inline_if_expr_const/Forc.toml
  test/src/e2e_vm_tests/test_programs/inline_if_expr_const/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/inline_if_expr_const/src/main.sw
  test/src/e2e_vm_tests/test_programs/method_on_empty_struct/Forc.toml
  test/src/e2e_vm_tests/test_programs/method_on_empty_struct/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/method_on_empty_struct/src/main.sw
Labels: bug, compiler, testing, ir

#864 Generate tab-autocompletion scripts for zsh, bash, fish, & powershell shells
  Cargo.lock
  forc/Cargo.toml
  forc/src/cli/commands/completions.rs
  forc/src/cli/commands/mod.rs
  forc/src/cli/mod.rs
Labels: enhancement, forc

#860 adds anyhow where result used to be
  Cargo.lock
  forc/src/cli/commands/addr2line.rs
  forc/src/cli/commands/build.rs
  forc/src/cli/commands/clean.rs
  forc/src/cli/commands/completions.rs
  forc/src/cli/commands/deploy.rs
  forc/src/cli/commands/explorer.rs
  forc/src/cli/commands/format.rs
  forc/src/cli/commands/init.rs
  forc/src/cli/commands/json_abi.rs
  forc/src/cli/commands/lsp.rs
  forc/src/cli/commands/parse_bytecode.rs
  forc/src/cli/commands/run.rs
  forc/src/cli/commands/test.rs
  forc/src/cli/commands/update.rs
  forc/src/cli/mod.rs
  forc/src/main.rs
  forc/src/ops/forc_abi_json.rs
  forc/src/ops/forc_build.rs
  forc/src/ops/forc_clean.rs
  forc/src/ops/forc_dep_check.rs
  forc/src/ops/forc_deploy.rs
  forc/src/ops/forc_fmt.rs
  forc/src/ops/forc_init.rs
  forc/src/utils/cli_error.rs
  forc/src/utils/client.rs
  forc/src/utils/dependency.rs
  forc/src/utils/helpers.rs
  forc/src/utils/restricted_names.rs
  test/Cargo.toml
  test/src/e2e_vm_tests/harness.rs
  test/src/e2e_vm_tests/mod.rs
Labels: forc, code quality

#871 Fix Project Manifest File Names
  forc/src/ops/forc_init.rs
Labels: forc

#874 Address seemingly new clippy nits that block unrelated PRs
  .github/workflows/ci.yml
  sway-core/src/asm_generation/from_ir.rs
  sway-core/src/optimize.rs
  sway-ir/tests/tests.rs
Labels: compiler, ci, code quality

#877 Update to Rust 2021 edition.
  docs/book.toml
  forc/Cargo.toml
  sway-core/Cargo.toml
  sway-fmt/Cargo.toml
  sway-server/Cargo.toml
  sway-types/Cargo.toml
  test/Cargo.toml
Labels: dependencies

#873 Update `forc` README for recent `out/` directory and lock file changes
  forc/README.md
Labels: forc

#879 Fix panic on empty contract impl with expected return value
  forc/src/utils/helpers.rs
  sway-core/src/control_flow_analysis/analyze_return_paths.rs
Labels: bug, compiler

#866 Provision IR for future storage API.
  sway-core/src/asm_generation/from_ir.rs
  sway-core/src/optimize.rs
  sway-core/tests/ir_to_asm/bigger_asm_block.asm
  sway-core/tests/ir_to_asm/bigger_asm_block.ir
  sway-core/tests/ir_to_asm/let_reassign_while_loop.ir
  sway-core/tests/ir_to_asm/mutable_struct.asm
  sway-core/tests/ir_to_asm/mutable_struct.ir
  sway-core/tests/ir_to_asm/simple_array.asm
  sway-core/tests/ir_to_asm/simple_array.ir
  sway-core/tests/ir_to_asm/simple_enum.asm
  sway-core/tests/ir_to_asm/simple_enum.ir
  sway-core/tests/ir_to_asm/simple_struct.asm
  sway-core/tests/ir_to_asm/simple_struct.ir
  sway-core/tests/sway_to_ir/array_simple.ir
  sway-core/tests/sway_to_ir/b256_immeds.ir
  sway-core/tests/sway_to_ir/enum.ir
  sway-core/tests/sway_to_ir/let_reassign_while_loop.ir
  sway-core/tests/sway_to_ir/mutable_struct.ir
  sway-core/tests/sway_to_ir/shadowed_locals.ir
  sway-core/tests/sway_to_ir/shadowed_struct_init.ir
  sway-core/tests/sway_to_ir/struct.ir
  sway-core/tests/sway_to_ir/struct_enum.ir
  sway-core/tests/sway_to_ir/struct_struct.ir
  sway-core/tests/sway_to_ir/trait.ir
  sway-ir/src/instruction.rs
  sway-ir/src/optimize/inline.rs
  sway-ir/src/parser.rs
  sway-ir/src/pointer.rs
  sway-ir/src/printer.rs
  sway-ir/src/verify.rs
  sway-ir/tests/ir_to_ir/constants_insert_value.in_ir
  sway-ir/tests/ir_to_ir/constants_insert_value.out_ir
  sway-ir/tests/ir_to_ir/constants_storage.in_ir
  sway-ir/tests/ir_to_ir/constants_storage.out_ir
  sway-ir/tests/ir_to_ir/inline_bigger.in_ir
  sway-ir/tests/ir_to_ir/inline_bigger.out_ir
  sway-ir/tests/tests.rs
Labels: enhancement, compiler, ir

#859 New syntax for contract method calls
  sway-core/src/asm_generation/expression/contract_call.rs
  sway-core/src/asm_generation/expression/mod.rs
  sway-core/src/asm_generation/expression/subfield.rs
  sway-core/src/asm_generation/mod.rs
  sway-core/src/constants.rs
  sway-core/src/error.rs
  sway-core/src/parse_tree/expression/mod.rs
  sway-core/src/semantic_analysis/ast_node/declaration/function.rs
  sway-core/src/semantic_analysis/ast_node/expression/func_app_instantiation.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/method_application.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression_variant.rs
  sway-core/src/sway.pest
  test/src/e2e_vm_tests/test_programs/auth_testing_abi/Forc.toml
  test/src/e2e_vm_tests/test_programs/auth_testing_abi/src/main.sw
  test/src/e2e_vm_tests/test_programs/auth_testing_contract/Forc.toml
  test/src/e2e_vm_tests/test_programs/auth_testing_contract/src/main.sw
  test/src/e2e_vm_tests/test_programs/bal_opcode/Forc.toml
  test/src/e2e_vm_tests/test_programs/bal_opcode/src/main.sw
  test/src/e2e_vm_tests/test_programs/balance_test_abi/Forc.toml
  test/src/e2e_vm_tests/test_programs/balance_test_abi/src/main.sw
  test/src/e2e_vm_tests/test_programs/balance_test_contract/Forc.toml
  test/src/e2e_vm_tests/test_programs/balance_test_contract/src/main.sw
  test/src/e2e_vm_tests/test_programs/basic_storage/Forc.toml
  test/src/e2e_vm_tests/test_programs/basic_storage/src/main.sw
  test/src/e2e_vm_tests/test_programs/basic_storage_abi/Forc.toml
  test/src/e2e_vm_tests/test_programs/basic_storage_abi/src/main.sw
  test/src/e2e_vm_tests/test_programs/call_basic_storage/Forc.toml
  test/src/e2e_vm_tests/test_programs/call_basic_storage/src/main.sw
  test/src/e2e_vm_tests/test_programs/call_increment_contract/Forc.toml
  test/src/e2e_vm_tests/test_programs/call_increment_contract/src/main.sw
  test/src/e2e_vm_tests/test_programs/caller_auth_test/Forc.toml
  test/src/e2e_vm_tests/test_programs/caller_auth_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/caller_context_test/Forc.toml
  test/src/e2e_vm_tests/test_programs/caller_context_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/context_testing_abi/Forc.toml
  test/src/e2e_vm_tests/test_programs/context_testing_abi/src/main.sw
  test/src/e2e_vm_tests/test_programs/context_testing_contract/Forc.toml
  test/src/e2e_vm_tests/test_programs/context_testing_contract/src/main.sw
  test/src/e2e_vm_tests/test_programs/contract_abi_impl/Forc.toml
  test/src/e2e_vm_tests/test_programs/contract_abi_impl/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/contract_abi_impl/json_abi_output.json
  test/src/e2e_vm_tests/test_programs/contract_abi_impl/src/main.sw
  test/src/e2e_vm_tests/test_programs/contract_call/Forc.toml
  test/src/e2e_vm_tests/test_programs/contract_call/src/main.sw
  test/src/e2e_vm_tests/test_programs/contract_pure_calls_impure/src/main.sw
  test/src/e2e_vm_tests/test_programs/increment_abi/Forc.toml
  test/src/e2e_vm_tests/test_programs/increment_abi/src/main.sw
  test/src/e2e_vm_tests/test_programs/increment_contract/Forc.toml
  test/src/e2e_vm_tests/test_programs/increment_contract/src/main.sw
  test/src/e2e_vm_tests/test_programs/test_fuel_coin_abi/src/main.sw
  test/src/e2e_vm_tests/test_programs/test_fuel_coin_contract/src/main.sw
  test/src/e2e_vm_tests/test_programs/token_ops_test/Forc.toml
  test/src/e2e_vm_tests/test_programs/token_ops_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/valid_impurity/Forc.toml
  test/src/e2e_vm_tests/test_programs/valid_impurity/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/valid_impurity/src/main.sw
Labels: enhancement, compiler

#867 refactor: replace the use of the `launch_and_deploy` function
  examples/hello_world/tests/harness.rs
  forc/README.md
Labels: The Sway Book

#886 Bump dependencies.
  .github/workflows/ci.yml
  Cargo.lock
  forc/Cargo.toml
  sway-core/Cargo.toml
  sway-types/Cargo.toml
  sway-types/src/lib.rs
  test-sig-gen-util/Cargo.toml
  test-sig-gen-util/src/main.rs
  test/Cargo.toml
Labels: dependencies

#887 Add --version to Forc
  forc/src/cli/mod.rs
Labels: forc

#888 Remove forced args for example contracts.
  examples/hello_world/src/main.sw
  examples/subcurrency/src/main.sw
  examples/wallet_smart_contract/src/main.sw
Labels: documentation

#890 changes format to join in path creation
  forc/src/ops/forc_init.rs
Labels: bug, forc

#894 Avoid adding an unnecessary `move` from the body(ies) of an if/else block
  sway-core/src/asm_generation/expression/if_exp.rs
Labels: bug, compiler

#897 Bump to v0.6.0
  Cargo.lock
  forc/Cargo.toml
  parser/Cargo.toml
  sway-core/Cargo.toml
  sway-fmt/Cargo.toml
  sway-ir/Cargo.toml
  sway-server/Cargo.toml
  sway-types/Cargo.toml
  sway-utils/Cargo.toml
  test/Cargo.toml
Labels: release

#836 Forc init project from template
  Cargo.lock
  forc/Cargo.toml
  forc/src/cli/commands/init.rs
  forc/src/cli/mod.rs
  forc/src/ops/forc_init.rs
  forc/src/pkg.rs
  sway-core/Cargo.toml
  sway-utils/src/constants.rs
Labels: enhancement, forc

#857 Fix new `size_of` for IR.
  sway-core/src/asm_generation/from_ir.rs
  sway-core/src/optimize.rs
Labels: bug, compiler, ir

#902 Rename `sway-server` to `sway-lsp`
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  forc/Cargo.toml
  forc/src/cli/commands/lsp.rs
  sway-lsp/Cargo.toml
  sway-lsp/src/capabilities/completion.rs
  sway-lsp/src/capabilities/diagnostic.rs
  sway-lsp/src/capabilities/document_symbol.rs
  sway-lsp/src/capabilities/file_sync.rs
  sway-lsp/src/capabilities/formatting.rs
  sway-lsp/src/capabilities/go_to.rs
  sway-lsp/src/capabilities/highlight.rs
  sway-lsp/src/capabilities/hover.rs
  sway-lsp/src/capabilities/mod.rs
  sway-lsp/src/capabilities/rename.rs
  sway-lsp/src/capabilities/semantic_tokens.rs
  sway-lsp/src/capabilities/text_sync.rs
  sway-lsp/src/core/document.rs
  sway-lsp/src/core/mod.rs
  sway-lsp/src/core/session.rs
  sway-lsp/src/core/token.rs
  sway-lsp/src/core/token_type.rs
  sway-lsp/src/lib.rs
  sway-lsp/src/server.rs
  sway-lsp/src/sway_config.rs
  sway-lsp/src/utils/common.rs
  sway-lsp/src/utils/function.rs
  sway-lsp/src/utils/lsp_helpers.rs
  sway-lsp/src/utils/mod.rs
Labels: language server

#901 Move forc's util and pkg related code into `forc-util`, `forc-pkg`
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  forc-pkg/Cargo.toml
  forc-pkg/src/lib.rs
  forc-pkg/src/lock.rs
  forc-pkg/src/manifest.rs
  forc-pkg/src/pkg.rs
  forc-util/Cargo.toml
  forc-util/src/lib.rs
  forc-util/src/restricted.rs
  forc/Cargo.toml
  forc/src/cli/commands/addr2line.rs
  forc/src/lib.rs
  forc/src/main.rs
  forc/src/ops/forc_build.rs
  forc/src/ops/forc_clean.rs
  forc/src/ops/forc_deploy.rs
  forc/src/ops/forc_explorer.rs
  forc/src/ops/forc_fmt.rs
  forc/src/ops/forc_run.rs
  forc/src/ops/forc_update.rs
  forc/src/utils/defaults.rs
  forc/src/utils/dependency.rs
  forc/src/utils/manifest.rs
  forc/src/utils/mod.rs
Labels: forc, code quality

#911 Reverting parts of PR907
  sway-core/src/asm_generation/expression/subfield.rs
  sway-core/src/type_engine/type_info.rs
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/nested_structs/Forc.lock
  test/src/e2e_vm_tests/test_programs/nested_structs/Forc.toml
  test/src/e2e_vm_tests/test_programs/nested_structs/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/nested_structs/src/main.sw
Labels: bug, compiler

#917 Fix concurrent `forc` updates/builds with a unique `fetch_id`
  forc-pkg/src/pkg.rs
Labels: bug, forc

#921 Bump to v0.6.1
  Cargo.lock
  forc-pkg/Cargo.toml
  forc-util/Cargo.toml
  forc/Cargo.toml
  parser/Cargo.toml
  sway-core/Cargo.toml
  sway-fmt/Cargo.toml
  sway-ir/Cargo.toml
  sway-lsp/Cargo.toml
  sway-types/Cargo.toml
  sway-utils/Cargo.toml
  test/Cargo.toml
Labels: release

#930 Produce an error rather than panicking on unsupported dependency type
  forc-pkg/src/pkg.rs
Labels: forc

#889 Create nightly-cargo-audit.yml
  .github/workflows/nightly-cargo-audit.yml
Labels: ci

#880 Update docs with getting started guide
  docs/src/README.md
  docs/src/SUMMARY.md
  docs/src/getting-started/forc_project.md
  docs/src/introduction/forc_project.md
  docs/src/introduction/index.md
  docs/src/introduction/installation.md
  docs/src/introduction/overview.md
  docs/src/introduction/sway-toolchain.md
  docs/src/reference/index.md
  docs/src/reference/rust_differences.md
  docs/src/reference/solidity_differences.md
  docs/src/reference/temporary_workarounds.md
  docs/src/sdks/index.md
  docs/src/sdks/rust-sdk.md
  docs/src/sdks/typescript-sdk.md
  docs/src/sway-on-chain/scripts.md
  docs/src/testing/index.md
  docs/src/testing/testing-with-rust.md
  docs/src/testing/testing-with-typescript.md
Labels: The Sway Book

#942 checks if an entry point exists during manifest validation
  forc-pkg/src/manifest.rs
Labels: forc, code quality

#943 IR changes for storage accesses
  sway-core/src/asm_generation/from_ir.rs
  sway-core/src/optimize.rs
  sway-core/tests/ir_to_asm/bigger_asm_block.ir
  sway-core/tests/ir_to_asm/let_reassign_while_loop.ir
  sway-core/tests/ir_to_asm/mutable_struct.ir
  sway-core/tests/ir_to_asm/simple_array.ir
  sway-core/tests/ir_to_asm/simple_enum.ir
  sway-core/tests/ir_to_asm/simple_struct.ir
  sway-core/tests/ir_to_asm/storage_load.asm
  sway-core/tests/ir_to_asm/storage_load.ir
  sway-core/tests/ir_to_asm/storage_store.asm
  sway-core/tests/ir_to_asm/storage_store.ir
  sway-core/tests/sway_to_ir/array_simple.ir
  sway-core/tests/sway_to_ir/b256_immeds.ir
  sway-core/tests/sway_to_ir/enum.ir
  sway-core/tests/sway_to_ir/let_reassign_while_loop.ir
  sway-core/tests/sway_to_ir/mutable_struct.ir
  sway-core/tests/sway_to_ir/shadowed_locals.ir
  sway-core/tests/sway_to_ir/shadowed_struct_init.ir
  sway-core/tests/sway_to_ir/struct.ir
  sway-core/tests/sway_to_ir/struct_enum.ir
  sway-core/tests/sway_to_ir/struct_struct.ir
  sway-core/tests/sway_to_ir/trait.ir
  sway-ir/src/instruction.rs
  sway-ir/src/optimize/inline.rs
  sway-ir/src/parser.rs
  sway-ir/src/printer.rs
  sway-ir/src/verify.rs
  sway-ir/tests/ir_to_ir/constants_insert_value.in_ir
  sway-ir/tests/ir_to_ir/constants_insert_value.out_ir
  sway-ir/tests/ir_to_ir/constants_storage.in_ir
  sway-ir/tests/ir_to_ir/constants_storage.out_ir
  sway-ir/tests/ir_to_ir/constants_storage_load.in_ir
  sway-ir/tests/ir_to_ir/constants_storage_load.out_ir
  sway-ir/tests/ir_to_ir/constants_storage_store.in_ir
  sway-ir/tests/ir_to_ir/constants_storage_store.out_ir
  sway-ir/tests/ir_to_ir/inline_bigger.in_ir
  sway-ir/tests/ir_to_ir/inline_bigger.out_ir
Labels: enhancement, compiler

#951 Additional updates to the Sway book regarding the new contract call syntax
  docs/src/reference/temporary_workarounds.md
  docs/src/sway-on-chain/smart_contracts.md
Labels: The Sway Book

#956 Migrate from using lspower to tower-lsp
  sway-lsp/Cargo.toml
  sway-lsp/src/capabilities/completion.rs
  sway-lsp/src/capabilities/diagnostic.rs
  sway-lsp/src/capabilities/document_symbol.rs
  sway-lsp/src/capabilities/file_sync.rs
  sway-lsp/src/capabilities/formatting.rs
  sway-lsp/src/capabilities/go_to.rs
  sway-lsp/src/capabilities/highlight.rs
  sway-lsp/src/capabilities/hover.rs
  sway-lsp/src/capabilities/rename.rs
  sway-lsp/src/capabilities/semantic_tokens.rs
  sway-lsp/src/capabilities/text_sync.rs
  sway-lsp/src/core/document.rs
  sway-lsp/src/core/session.rs
  sway-lsp/src/core/token.rs
  sway-lsp/src/lib.rs
  sway-lsp/src/server.rs
  sway-lsp/src/utils/lsp_helpers.rs
Labels: language server, dependencies

#945 removes forc clean cargo toml error
  forc/src/ops/forc_clean.rs
  sway-utils/src/helpers.rs
Labels: bug, forc

#959 IR generation for storage accesses
  Cargo.lock
  sway-core/Cargo.toml
  sway-core/src/control_flow_analysis/analyze_return_paths.rs
  sway-core/src/control_flow_analysis/dead_code_analysis.rs
  sway-core/src/optimize.rs
  sway-core/src/semantic_analysis.rs
  sway-core/src/semantic_analysis/ast_node/declaration.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression_variant.rs
  sway-core/src/semantic_analysis/ast_node/mod.rs
  sway-types/src/lib.rs
  sway-types/src/state.rs
  sway-utils/src/constants.rs
Labels: enhancement, compiler

#960 Add tests and docs for while loops
  docs/src/SUMMARY.md
  docs/src/control-flow/index.md
  docs/src/control-flow/loops.md
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/while_loops/.gitignore
  test/src/e2e_vm_tests/test_programs/while_loops/Forc.lock
  test/src/e2e_vm_tests/test_programs/while_loops/Forc.toml
  test/src/e2e_vm_tests/test_programs/while_loops/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/while_loops/src/main.sw
Labels: documentation, testing, The Sway Book

#961 Space out errors and warnings for readability
  forc-util/src/lib.rs
Labels: enhancement, compiler

#966 Update lockfile
  Cargo.lock
Labels: dependencies

#962 Add a contributing section to the sway book
  README.md
  docs/src/SUMMARY.md
  docs/src/reference/contributing_to_sway.md
  docs/src/reference/index.md
Labels: documentation, The Sway Book

#969 Document Supertraits and `where` clauses
  docs/src/advanced/generic_types.md
  docs/src/advanced/traits.md
Labels: The Sway Book

#973 Update default Forc manifest
  forc/src/utils/defaults.rs
Labels: forc, code quality

#971 Force all non-copy types to return using `RETD` regardless of their size.
  sway-core/src/asm_generation/expression/array.rs
  sway-core/src/asm_generation/mod.rs
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/should_pass/language/retd_small_array/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/retd_small_array/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/retd_small_array/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/language/retd_small_array/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/retd_zero_len_array/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/retd_zero_len_array/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/retd_zero_len_array/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/language/retd_zero_len_array/src/main.sw
Labels: bug, compiler

#974 Update default Forc manifest Fuel dependencies.
  forc/src/utils/defaults.rs
Labels: forc

#975 Fix comment on default Forc manifest gen.
  forc/src/utils/defaults.rs
Labels: forc

#982 docs: remove WIP mention for `Tuples` type
  docs/src/basics/built_in_types.md
Labels: The Sway Book

#985 Minor fixes to book.
  docs/src/sway-on-chain/libraries.md
Labels: bug, The Sway Book

#964 Abort control flow upon a `return`, `RET`, or `RVRT`.
  sway-core/src/semantic_analysis/ast_node/code_block.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/ast_node/mod.rs
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/abort_control_flow/Forc.lock
  test/src/e2e_vm_tests/test_programs/abort_control_flow/Forc.toml
  test/src/e2e_vm_tests/test_programs/abort_control_flow/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/abort_control_flow/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/abort_control_flow/.gitignore
  test/src/e2e_vm_tests/test_programs/should_fail/abort_control_flow/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/abort_control_flow/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/abort_control_flow/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/abort_control_flow/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/abort_control_flow/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/abort_control_flow/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/language/abort_control_flow/src/main.sw
Labels: enhancement, compiler

#987 Book fix: only include stdlib.
  docs/src/introduction/overview.md
  docs/src/reference/temporary_workarounds.md
  docs/src/sway-on-chain/libraries.md
Labels: The Sway Book

#986 Add tests to sway-lsp
  Cargo.lock
  sway-lsp/Cargo.toml
  sway-lsp/src/core/token.rs
  sway-lsp/src/server.rs
Labels: forc, language server, testing

#989 Use explicit branch for tests.
  examples/counter/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/abort_control_flow/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/abort_control_flow/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/nested_structs/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/tuple_in_struct/Forc.toml
Labels: testing

#990 delete outdated test folder
  test/src/e2e_vm_tests/test_programs/abort_control_flow/Forc.lock
  test/src/e2e_vm_tests/test_programs/abort_control_flow/Forc.toml
  test/src/e2e_vm_tests/test_programs/abort_control_flow/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/abort_control_flow/src/main.sw
Labels: code quality, testing

#994 Remove unneeded core dep for test.
  test/src/e2e_vm_tests/test_programs/should_pass/language/while_loops/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/while_loops/Forc.toml
Labels: code quality, testing, dependencies

#995 General cleanup of test manifest files.
  test/src/e2e_vm_tests/test_programs/should_fail/enum_bad_type_inference/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/enum_if_let_invalid_variable/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/match_expressions_enums/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/match_expressions_wrong_struct/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/enum_destructuring/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/enum_if_let/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/enum_if_let_large_type/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/enum_type_inference/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/fix_opcode_bug/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/if_elseif_enum/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/inline_if_expr_const/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/match_expressions/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/match_expressions_structs/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/method_on_empty_struct/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/nested_structs/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/supertraits/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/tuple_in_struct/Forc.toml
Labels: code quality, testing

#991 Remove core dependency from example projects.
  examples/counter/Forc.lock
  examples/counter/Forc.toml
  examples/fizzbuzz/Forc.lock
  examples/fizzbuzz/Forc.toml
  examples/hello_world/Forc.lock
  examples/hello_world/Forc.toml
  examples/subcurrency/Forc.lock
  examples/subcurrency/Forc.toml
  examples/wallet_smart_contract/Forc.lock
  examples/wallet_smart_contract/Forc.toml
Labels: code quality, testing

#701 The compiler checks for exhaustive match arms in match expressions.
  Cargo.lock
  sway-core/Cargo.toml
  sway-core/src/asm_generation/from_ir.rs
  sway-core/src/error.rs
  sway-core/src/lib.rs
  sway-core/src/optimize.rs
  sway-core/src/parse_tree/code_block.rs
  sway-core/src/parse_tree/declaration.rs
  sway-core/src/parse_tree/declaration/constant.rs
  sway-core/src/parse_tree/declaration/enum.rs
  sway-core/src/parse_tree/declaration/reassignment.rs
  sway-core/src/parse_tree/declaration/storage.rs
  sway-core/src/parse_tree/declaration/variable.rs
  sway-core/src/parse_tree/expression/asm.rs
  sway-core/src/parse_tree/expression/match_branch.rs
  sway-core/src/parse_tree/expression/match_condition.rs
  sway-core/src/parse_tree/expression/mod.rs
  sway-core/src/parse_tree/return_statement.rs
  sway-core/src/parse_tree/while_loop.rs
  sway-core/src/semantic_analysis/ast_node/expression/mod.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/method_application.rs
  sway-core/src/semantic_analysis/ast_node/expression/usefulness/constructor_factory.rs
  sway-core/src/semantic_analysis/ast_node/expression/usefulness/matrix.rs
  sway-core/src/semantic_analysis/ast_node/expression/usefulness/mod.rs
  sway-core/src/semantic_analysis/ast_node/expression/usefulness/patstack.rs
  sway-core/src/semantic_analysis/ast_node/expression/usefulness/pattern.rs
  sway-core/src/semantic_analysis/ast_node/expression/usefulness/range.rs
  sway-core/src/semantic_analysis/ast_node/expression/usefulness/witness_report.rs
  sway-core/src/semantic_analysis/node_dependencies.rs
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/should_fail/abort_control_flow/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/match_expressions_non_exhaustive/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/match_expressions_non_exhaustive/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/match_expressions_non_exhaustive/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_fail/match_expressions_non_exhaustive/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/abort_control_flow/Forc.lock
Labels: enhancement, compiler

#922 Bump to v0.7.0
  Cargo.lock
  forc-pkg/Cargo.toml
  forc-util/Cargo.toml
  forc/Cargo.toml
  parser/Cargo.toml
  sway-core/Cargo.toml
  sway-fmt/Cargo.toml
  sway-ir/Cargo.toml
  sway-lsp/Cargo.toml
  sway-types/Cargo.toml
  sway-utils/Cargo.toml
  test/Cargo.toml
Labels: release

#976 Contracts and contract calls in IR
  Cargo.lock
  sway-core/src/asm_generation/from_ir.rs
  sway-core/src/optimize.rs
  sway-core/tests/ir_to_asm/simple_contract.asm
  sway-core/tests/ir_to_asm/simple_contract.ir
  sway-core/tests/ir_to_asm/simple_contract_call.asm
  sway-core/tests/ir_to_asm/simple_contract_call.ir
  sway-core/tests/sway_to_ir/simple_contract.ir
  sway-core/tests/sway_to_ir/simple_contract.sw
  sway-core/tests/sway_to_ir/simple_contract_call.ir
  sway-core/tests/sway_to_ir/simple_contract_call.sw
  sway-ir/src/context.rs
  sway-ir/src/instruction.rs
  sway-ir/src/irtype.rs
  sway-ir/src/optimize/inline.rs
  sway-ir/src/parser.rs
  sway-ir/src/printer.rs
  sway-ir/src/verify.rs
  sway-ir/tests/ir_to_ir/constants_contract_calls.in_ir
  sway-ir/tests/ir_to_ir/constants_contract_calls.out_ir
Labels: enhancement, compiler, ir

#957 Moved `find_manifest` functions from `sway_util` into `forc_util`
  Cargo.lock
  forc-util/src/lib.rs
  forc/src/ops/forc_build.rs
  forc/src/ops/forc_clean.rs
  forc/src/ops/forc_deploy.rs
  forc/src/ops/forc_fmt.rs
  forc/src/ops/forc_run.rs
  forc/src/ops/forc_update.rs
  sway-lsp/Cargo.toml
  sway-lsp/src/server.rs
  sway-utils/src/helpers.rs
Labels: forc, code quality

#1001 ci: bump fuel-core to v0.4.2
  .github/workflows/ci.yml
Labels: ci

#1007 Add back testing with typescript link
  docs/src/SUMMARY.md
  docs/src/sdks/rust-sdk.md
Labels: bug, The Sway Book

#1009 Remove unnecessary FIXME and fix the `*-abi.json` path
  examples/hello_world/tests/harness.rs
Labels: The Sway Book

#1010 Comment out reference type section for now
  docs/src/SUMMARY.md
  docs/src/basics/index.md
Labels: The Sway Book

#1011 Simple test that uses Eq for bool
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/should_pass/language/is_prime/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/is_prime/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/is_prime/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/language/is_prime/src/main.sw
Labels: testing

#1014 Fix incrementor test
  examples/counter/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_increment_contract/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_increment_contract/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_increment_contract/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/test_abis/increment_abi/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/basic_storage/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/increment_contract/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/increment_contract/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/increment_contract/src/main.sw
Labels: testing, The Sway Book

#646 Implement storage access via storage keyword
  sway-core/src/asm_generation/from_ir.rs
  sway-core/src/constants.rs
  sway-core/src/control_flow_analysis/analyze_return_paths.rs
  sway-core/src/control_flow_analysis/dead_code_analysis.rs
  sway-core/src/control_flow_analysis/flow_graph/mod.rs
  sway-core/src/control_flow_analysis/flow_graph/namespace.rs
  sway-core/src/error.rs
  sway-core/src/optimize.rs
  sway-core/src/parse_tree/declaration/reassignment.rs
  sway-core/src/parse_tree/declaration/storage.rs
  sway-core/src/parse_tree/expression/mod.rs
  sway-core/src/semantic_analysis/ast_node/declaration.rs
  sway-core/src/semantic_analysis/ast_node/declaration/storage.rs
  sway-core/src/semantic_analysis/ast_node/declaration/variable.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/ast_node/mod.rs
  sway-core/src/semantic_analysis/namespace.rs
  sway-core/src/semantic_analysis/namespace/arena.rs
  sway-core/src/semantic_analysis/node_dependencies.rs
  sway-core/src/sway.pest
  sway-core/src/type_engine/type_info.rs
  sway-core/tests/ir_to_asm/storage_store.asm
  sway-ir/src/printer.rs
  sway-ir/tests/ir_to_ir/constants_storage_store.in_ir
  sway-ir/tests/ir_to_ir/constants_storage_store.out_ir
  sway-lsp/src/core/token.rs
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/storage_access_caller/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/storage_access_caller/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/storage_access_caller/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/storage_access_caller/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/test_abis/storage_access_abi/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/test_abis/storage_access_abi/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/test_abis/storage_access_abi/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/test_abis/storage_access_abi/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/storage_access_contract/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/storage_access_contract/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/storage_access_contract/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/storage_access_contract/src/main.sw
Labels: enhancement, compiler

#1021 Remove author manifest field.
  forc-pkg/Cargo.toml
  forc-pkg/src/manifest.rs
  forc/src/ops/forc_init.rs
Labels: forc, breaking

#1020 Some fixes to contract calls in both codegens
  sway-core/src/asm_generation/from_ir.rs
  sway-core/src/asm_generation/mod.rs
  sway-core/src/optimize.rs
  sway-core/tests/ir_to_asm/simple_contract_call.asm
  sway-core/tests/ir_to_asm/simple_contract_call.ir
  sway-core/tests/sway_to_ir/simple_contract_call.ir
  sway-core/tests/sway_to_ir/simple_contract_call.sw
  sway-ir/src/instruction.rs
  sway-ir/src/optimize/inline.rs
  sway-ir/src/parser.rs
  sway-ir/src/printer.rs
  sway-ir/src/verify.rs
  sway-ir/tests/ir_to_ir/constants_contract_calls.in_ir
  sway-ir/tests/ir_to_ir/constants_contract_calls.out_ir
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_basic_storage/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_basic_storage/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_increment_contract/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/caller_auth_test/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/caller_auth_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/storage_access_caller/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/storage_access_caller/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/storage_access_contract/Forc.lock
Labels: bug, enhancement, compiler

#1023 Add forc run tx parameters.
  forc/src/cli/commands/run.rs
  forc/src/ops/forc_run.rs
  forc/src/utils/mod.rs
  forc/src/utils/parameters.rs
Labels: enhancement, forc

#980 Reorganize Sway docs and compress some sections
  docs/src/SUMMARY.md
  docs/src/basics/blockchain_types.md
  docs/src/basics/comments_and_logging.md
  docs/src/basics/control_flow.md
  docs/src/basics/functions.md
  docs/src/basics/index.md
  docs/src/basics/methods_and_associated_functions.md
  docs/src/basics/overview.md
  docs/src/basics/structs_and_tuples.md
  docs/src/blockchain-concepts/index.md
  docs/src/blockchain-development/identifiers.md
  docs/src/blockchain-development/index.md
  docs/src/blockchain-development/native_assets.md
  docs/src/blockchain-development/purity.md
  docs/src/blockchain-development/storage.md
  docs/src/control-flow/index.md
  docs/src/control-flow/loops.md
  docs/src/reference/rust_differences.md
  docs/src/reference/style_guide.md
  docs/src/smart-contract-development/index.md
  docs/src/style/index.md
  docs/src/sway-on-chain/index.md
  docs/src/sway-program-types/index.md
  docs/src/sway-program-types/libraries.md
  docs/src/sway-program-types/predicates.md
  docs/src/sway-program-types/program_types.md
  docs/src/sway-program-types/scripts.md
  docs/src/sway-program-types/smart_contracts.md
  examples/fizzbuzz/src/main.sw
  examples/subcurrency/src/main.sw
  examples/wallet_smart_contract/src/main.sw
Labels: The Sway Book

#1026 Logical not formatting fix
  sway-fmt/src/code_builder.rs
  sway-fmt/src/code_builder_helpers.rs
  sway-fmt/src/fmt.rs
Labels: formatter

#1027 v0.8.0
  Cargo.lock
  forc-pkg/Cargo.toml
  forc-util/Cargo.toml
  forc/Cargo.toml
  parser/Cargo.toml
  sway-core/Cargo.toml
  sway-fmt/Cargo.toml
  sway-ir/Cargo.toml
  sway-lsp/Cargo.toml
  sway-types/Cargo.toml
  sway-utils/Cargo.toml
  test/Cargo.toml
Labels: release

#1029 Bunch of book fixes
  docs/src/SUMMARY.md
  docs/src/advanced/generic_types.md
  docs/src/advanced/traits.md
  docs/src/basics/blockchain_types.md
  docs/src/basics/built_in_types.md
  docs/src/basics/comments_and_logging.md
  docs/src/basics/control_flow.md
  docs/src/basics/index.md
  docs/src/basics/reference_types.md
  docs/src/basics/variables.md
  docs/src/blockchain-development/storage.md
  docs/src/introduction/forc_project.md
  docs/src/introduction/index.md
  docs/src/introduction/overview.md
  docs/src/reference/index.md
  docs/src/reference/rust_differences.md
  docs/src/reference/temporary_workarounds.md
  docs/src/sway-program-types/libraries.md
  docs/src/sway-program-types/program_types.md
  docs/src/sway-program-types/scripts.md
  docs/src/sway-program-types/smart_contracts.md
  docs/src/testing/testing-with-rust.md
  examples/wallet_smart_contract/src/main.sw
Labels: The Sway Book

#1034 More IR updates.
  sway-core/src/asm_generation/compiler_constants.rs
  sway-core/src/asm_generation/from_ir.rs
  sway-core/src/optimize.rs
  sway-core/tests/ir_to_asm/let_reassign_while_loop.asm
  sway-core/tests/ir_to_asm/simple_contract_call.asm
  sway-core/tests/ir_to_asm/simple_if_let.asm
  sway-core/tests/ir_to_asm/storage_load.asm
  sway-core/tests/ir_to_asm/storage_store.asm
  sway-ir/src/irtype.rs
  test/src/e2e_vm_tests/test_programs/should_pass/language/fix_opcode_bug/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/fix_opcode_bug/Forc.toml
Labels: compiler, ir

#1036 Fix for node dependency order for enum instantiations.
  sway-core/src/semantic_analysis/node_dependencies.rs
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/should_pass/language/enum_init_fn_call/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/enum_init_fn_call/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/enum_init_fn_call/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/language/enum_init_fn_call/src/main.sw
Labels: bug, compiler

#1032 Use `stable` Rust toolchain when installing Forc -- update installation.md
  docs/src/introduction/installation.md
Labels: The Sway Book

#1040 Remove unused Rust files for examples.
  examples/fizzbuzz/Cargo.toml
  examples/fizzbuzz/tests/harness.rs
  examples/hello_world/Cargo.toml
  examples/hello_world/tests/harness.rs
  examples/subcurrency/Cargo.toml
  examples/subcurrency/tests/harness.rs
  examples/wallet_smart_contract/Cargo.toml
  examples/wallet_smart_contract/tests/harness.rs
Labels: code quality, testing

#1039 Remove redundant `std` dependency.
  test/src/e2e_vm_tests/test_programs/should_fail/match_expressions_non_exhaustive/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/match_expressions_non_exhaustive/Forc.toml
Labels: code quality, testing

#1038 Change to authors from author.
  test/src/e2e_vm_tests/test_programs/should_fail/match_expressions_non_exhaustive/Forc.toml
Labels: code quality, testing

#1037 Bump fuel-core and add missing instructions.
  Cargo.lock
  forc/Cargo.toml
  forc/src/utils/defaults.rs
  sway-core/Cargo.toml
  sway-core/src/asm_lang/allocated_ops.rs
  sway-core/src/asm_lang/mod.rs
  sway-core/src/asm_lang/virtual_ops.rs
  sway-types/Cargo.toml
  test-sig-gen-util/Cargo.toml
  test/Cargo.toml
Labels: compiler, dependencies, breaking

#1048 Handle ImplicitReturnExpression variant when parsing lsp tokens
  sway-lsp/src/core/token.rs
Labels: language server

#1049 Add WhileLoop variant for Lsp token parsing
  sway-core/src/parse_tree/while_loop.rs
  sway-lsp/src/core/token.rs
Labels: language server

#1050 Add ReturnStatement variant for Lsp token parsing
  sway-lsp/src/core/token.rs
Labels: language server

#978 Walk git dependency repo to discover nested forc dependencies
  Cargo.lock
  forc-pkg/Cargo.toml
  forc-pkg/src/pkg.rs
Labels: enhancement, forc

#1031 Updating `forc init` defaults
  forc/src/utils/defaults.rs
Labels: forc

#1041 Small fix to liveness analysis
  sway-core/src/asm_generation/register_allocator.rs
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/should_pass/language/nested_while_and_if/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/nested_while_and_if/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/nested_while_and_if/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/language/nested_while_and_if/src/main.sw
Labels: bug, compiler

#1043 Bump to v0.9.0
  Cargo.lock
  forc-pkg/Cargo.toml
  forc-util/Cargo.toml
  forc/Cargo.toml
  parser/Cargo.toml
  sway-core/Cargo.toml
  sway-fmt/Cargo.toml
  sway-ir/Cargo.toml
  sway-lsp/Cargo.toml
  sway-types/Cargo.toml
  sway-utils/Cargo.toml
  test/Cargo.toml
Labels: release

#1051 Handle parsing tokens within FunctionApplication and TraitDeclaration
  sway-core/src/parse_tree/declaration/trait.rs
  sway-lsp/src/core/token.rs
Labels: language server

#1089 Fix unhelpful error with incorrect number of type arguments.
  sway-core/src/semantic_analysis/ast_node/declaration.rs
  sway-core/src/semantic_analysis/ast_node/declaration/function.rs
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/should_fail/generics_unhelpful_error/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/generics_unhelpful_error/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/generics_unhelpful_error/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_fail/generics_unhelpful_error/src/main.sw
Labels: bug, compiler

#1095 Add build script for stdlib test projects
  build.sh
Labels: lib: std, testing

#1096 Add Forc lockfiles to test projects
  sway-lib-std/tests/Cargo.toml
  sway-lib-std/tests/test_artifacts/auth_caller_contract/Forc.lock
  sway-lib-std/tests/test_artifacts/auth_caller_script/Forc.lock
  sway-lib-std/tests/test_artifacts/auth_testing_abi/Forc.lock
  sway-lib-std/tests/test_artifacts/auth_testing_contract/Forc.lock
  sway-lib-std/tests/test_artifacts/balance_contract/Forc.lock
  sway-lib-std/tests/test_artifacts/balance_contract/Forc.toml
  sway-lib-std/tests/test_artifacts/call_frames_test_abi/Forc.lock
  sway-lib-std/tests/test_artifacts/context_caller_contract/Forc.lock
  sway-lib-std/tests/test_artifacts/context_testing_abi/Forc.lock
  sway-lib-std/tests/test_artifacts/tx_contract/Forc.lock
  sway-lib-std/tests/test_projects/auth/Forc.lock
  sway-lib-std/tests/test_projects/call_frames/Forc.lock
  sway-lib-std/tests/test_projects/context/Forc.lock
  sway-lib-std/tests/test_projects/contract_id_type/Forc.lock
  sway-lib-std/tests/test_projects/option/Forc.lock
  sway-lib-std/tests/test_projects/registers/Forc.lock
  sway-lib-std/tests/test_projects/registers/Forc.toml
  sway-lib-std/tests/test_projects/result/Forc.lock
  sway-lib-std/tests/test_projects/token_ops/Forc.lock
  sway-lib-std/tests/test_projects/token_ops/Forc.toml
Labels: bug, lib: std, testing

#1093 Change default stdlib to point to this repo.
  forc/src/utils/defaults.rs
Labels: forc

#1094 Fix tests and docs to point stdlib to this repo.
  docs/src/introduction/overview.md
  docs/src/reference/temporary_workarounds.md
  test/src/e2e_vm_tests/test_programs/should_pass/forc/dependency_package_field/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/forc/dependency_package_field/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/forc/dependency_package_field/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/nested_while_and_if/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/nested_while_and_if/Forc.toml
Labels: testing, The Sway Book

#1092 Fix ge/le/neq implementation and improve supertraits
  sway-core/src/semantic_analysis/ast_node/mod.rs
  sway-lib-core/src/ops.sw
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/should_pass/language/supertraits/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/ge_test/.gitignore
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/ge_test/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/ge_test/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/ge_test/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/ge_test/src/main.sw
Labels: bug, compiler, lib: core

#1099 v0.9.2
  Cargo.lock
  forc-pkg/Cargo.toml
  forc-util/Cargo.toml
  forc/Cargo.toml
  parser/Cargo.toml
  sway-core/Cargo.toml
  sway-fmt/Cargo.toml
  sway-ir/Cargo.toml
  sway-lsp/Cargo.toml
  sway-types/Cargo.toml
  sway-utils/Cargo.toml
  test/Cargo.toml
Labels: release

#1102 Fix nits with type arguments error messages
  sway-core/src/parse_tree/expression/mod.rs
  sway-core/src/semantic_analysis/ast_node/declaration.rs
  sway-core/src/semantic_analysis/ast_node/expression/func_app_instantiation.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/namespace/arena.rs
  sway-core/src/sway.pest
  sway-fmt/src/traversal.rs
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/should_fail/disallow_turbofish/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/disallow_turbofish/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/disallow_turbofish/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_fail/disallow_turbofish/src/main.sw
Labels: bug, compiler

#1108 println_with_color & print_with_color should expect Result
  forc-pkg/src/manifest.rs
  forc-pkg/src/pkg.rs
  forc-util/src/lib.rs
  forc/src/ops/forc_fmt.rs
Labels: compiler

#1110 Compiler should fail if a generic in a method shadows a generic in a struct
  sway-core/src/error.rs
  sway-core/src/semantic_analysis/ast_node/declaration/function.rs
  sway-core/src/semantic_analysis/ast_node/mod.rs
  sway-core/src/semantic_analysis/namespace.rs
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/should_fail/generic_shadows_generic/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/generic_shadows_generic/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/generic_shadows_generic/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_fail/generic_shadows_generic/src/main.sw
Labels: bug, compiler

#1097 Add test for force transfer.
  .github/workflows/ci.yml
  sway-lib-std/build.sh
  sway-lib-std/tests/README.md
  sway-lib-std/tests/test_projects/token_ops/mod.rs
  sway-lib-std/tests/test_projects/tx_fields/mod.rs
Labels: lib: std, testing

#1114 Subcurrency Explanation
  docs/src/examples/subcurrency.md
Labels: The Sway Book

#1113 Improve strings for IR.
  sway-core/src/asm_generation/from_ir.rs
  sway-core/src/optimize.rs
  sway-core/tests/ir_to_asm/enum_struct_string.asm
  sway-core/tests/ir_to_asm/enum_struct_string.ir
  sway-core/tests/ir_to_asm/simple_enum.ir
  sway-core/tests/ir_to_asm/simple_if_let.ir
  sway-core/tests/sway_to_ir/enum.ir
  sway-core/tests/sway_to_ir/enum_enum.ir
  sway-core/tests/sway_to_ir/enum_struct.ir
  sway-core/tests/sway_to_ir/enum_struct_string.ir
  sway-core/tests/sway_to_ir/enum_struct_string.sw
  sway-core/tests/sway_to_ir/if_let_simple.ir
  sway-core/tests/sway_to_ir/lazy_binops.ir
  sway-core/tests/sway_to_ir/struct_enum.ir
  sway-ir/src/constant.rs
  sway-ir/src/irtype.rs
  sway-ir/src/parser.rs
  sway-ir/src/printer.rs
  sway-ir/tests/ir_to_ir/inline_fiddly.out_ir
Labels: bug, enhancement, compiler, ir
