Repository FuelLabs/sway, pull requests merged in 2022-02, with the labels that each got.

#731 Move subcurrency example to examples directory
  docs/src/examples/subcurrency.md
  examples/subcurrency/Cargo.toml
  examples/subcurrency/Forc.toml
  examples/subcurrency/src/main.sw
  examples/subcurrency/tests/harness.rs
Labels: The Sway Book

#728 Fixing an issue where library items are available without them being imported
  sway-core/src/semantic_analysis/ast_node/mod.rs
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/item_used_without_import/Forc.toml
  test/src/e2e_vm_tests/test_programs/item_used_without_import/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/item_used_without_import/src/bar.sw
  test/src/e2e_vm_tests/test_programs/item_used_without_import/src/main.sw
Labels: bug, compiler

#681 Implementing tuple access via desugaring and indexing.
  Cargo.lock
  sway-core/Cargo.toml
  sway-core/src/asm_generation/from_ir.rs
  sway-core/src/build_config.rs
  sway-core/src/error.rs
  sway-core/src/optimize.rs
  sway-core/src/parse_tree/code_block.rs
  sway-core/src/parse_tree/declaration.rs
  sway-core/src/parse_tree/declaration/variable.rs
  sway-core/src/parse_tree/expression/mod.rs
  sway-core/src/parse_tree/ident.rs
  sway-core/src/parse_tree/literal.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression_variant.rs
  sway-core/src/semantic_analysis/node_dependencies.rs
  sway-core/src/sway.pest
  test/src/e2e_vm_tests/harness.rs
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/tuple_access/Forc.toml
  test/src/e2e_vm_tests/test_programs/tuple_access/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/tuple_access/src/main.sw
  test/src/e2e_vm_tests/test_programs/tuple_indexing/Forc.toml
  test/src/e2e_vm_tests/test_programs/tuple_indexing/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/tuple_indexing/src/main.sw
Labels: enhancement, compiler

#734 Fix E2E tests for IR.
  sway-core/src/asm_generation/from_ir.rs
  sway-core/src/optimize.rs
  sway-core/src/semantic_analysis/ast_node/declaration/function.rs
  sway-core/src/semantic_analysis/ast_node/declaration/variable.rs
  sway-core/src/semantic_analysis/ast_node/mod.rs
  sway-core/tests/ir_to_asm/bigger_asm_block.asm
  sway-core/tests/ir_to_asm/mutable_struct.asm
  sway-core/tests/ir_to_asm/simple_array.asm
  sway-core/tests/ir_to_asm/simple_enum.asm
  sway-core/tests/ir_to_asm/simple_struct.asm
  sway-core/tests/ir_to_asm/tiny_asm_block.asm
  sway-ir/src/block.rs
  sway-ir/src/optimize/constants.rs
  sway-ir/src/optimize/inline.rs
  test/src/e2e_vm_tests/mod.rs
Labels: compiler

#725 Update ec_recover test to use updated B512 data structure.
  test/src/e2e_vm_tests/harness.rs
  test/src/e2e_vm_tests/test_programs/ec_recover_test/Forc.toml
  test/src/e2e_vm_tests/test_programs/ec_recover_test/src/main.sw
Labels: stdlib, testing

#729 Multi import statements with self syntax
  sway-core/src/error.rs
  sway-core/src/parse_tree/use_statement.rs
  sway-core/src/semantic_analysis/ast_node/mod.rs
  sway-core/src/semantic_analysis/namespace/arena.rs
  sway-core/src/sway.pest
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/multi_item_import/src/main.sw
  test/src/e2e_vm_tests/test_programs/star_import_alias/Forc.toml
  test/src/e2e_vm_tests/test_programs/star_import_alias/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/star_import_alias/src/bar.sw
  test/src/e2e_vm_tests/test_programs/star_import_alias/src/main.sw
Labels: enhancement, compiler

#739 Importing the same item multiple times should be a compile error
  sway-core/src/error.rs
  sway-core/src/semantic_analysis/namespace/arena.rs
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/multi_item_import/src/main.sw
  test/src/e2e_vm_tests/test_programs/shadow_import/Forc.toml
  test/src/e2e_vm_tests/test_programs/shadow_import/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/shadow_import/src/bar.sw
  test/src/e2e_vm_tests/test_programs/shadow_import/src/main.sw
Labels: enhancement, compiler

#740 Rename fuels-rs to fuels-contract
  docs/src/getting-started/forc_project.md
  forc/README.md
  forc/src/utils/defaults.rs
Labels: forc, The Sway Book

#735 Document how `dep` works
  docs/src/sway-on-chain/libraries.md
Labels: The Sway Book

#736 Fixing a generic types resolution bug
  sway-core/src/semantic_analysis/namespace.rs
  sway-core/src/semantic_analysis/namespace/arena.rs
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/funcs_with_generic_types/Forc.toml
  test/src/e2e_vm_tests/test_programs/funcs_with_generic_types/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/funcs_with_generic_types/src/main.sw
Labels: bug, compiler

#750 Update built_in_types.md
  docs/src/basics/built_in_types.md
Labels: bug, The Sway Book

#745 Bump fuel-tx, fuel-vm, and fuel-core versions.
  .github/workflows/ci.yml
  Cargo.lock
  forc/Cargo.toml
  forc/src/ops/forc_deploy.rs
  forc/src/ops/forc_run.rs
  sway-core/Cargo.toml
  sway-types/Cargo.toml
  test-sig-gen-util/Cargo.toml
  test/Cargo.toml
  test/src/e2e_vm_tests/harness.rs
Labels: dependencies

#754 Arrange forc.toml fields alphabetically
  forc/src/utils/defaults.rs
Labels: forc, internship, formatter

#759 Turning an instance of HashSet into BTreeSet in `asm_generation`
  sway-core/src/asm_generation/mod.rs
  sway-core/src/asm_lang/virtual_ops.rs
  sway-core/src/asm_lang/virtual_register.rs
Labels: bug, compiler

#761 fix misspelled cargo in docs
  docs/src/getting-started/forc_project.md
Labels: documentation

#768 adding slack notify to CI steps
  .github/workflows/ci.yml
Labels: ci

#756 Add build cache
  .github/workflows/ci.yml
Labels: ci

#752 Supertraits implementation
  sway-core/src/error.rs
  sway-core/src/parse_tree/declaration/trait.rs
  sway-core/src/semantic_analysis/ast_node/mod.rs
  sway-core/src/semantic_analysis/node_dependencies.rs
  sway-core/src/sway.pest
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/missing_supertrait/Forc.toml
  test/src/e2e_vm_tests/test_programs/missing_supertrait/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/missing_supertrait/src/main.sw
  test/src/e2e_vm_tests/test_programs/missing_supertrait_impl/Forc.toml
  test/src/e2e_vm_tests/test_programs/missing_supertrait_impl/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/missing_supertrait_impl/src/main.sw
  test/src/e2e_vm_tests/test_programs/supertraits_1/Forc.toml
  test/src/e2e_vm_tests/test_programs/supertraits_1/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/supertraits_1/src/main.sw
  test/src/e2e_vm_tests/test_programs/supertraits_2/Forc.toml
  test/src/e2e_vm_tests/test_programs/supertraits_2/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/supertraits_2/src/main.sw
  test/src/e2e_vm_tests/test_programs/supertraits_dup_methods_1/Forc.toml
  test/src/e2e_vm_tests/test_programs/supertraits_dup_methods_1/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/supertraits_dup_methods_1/src/main.sw
  test/src/e2e_vm_tests/test_programs/supertraits_dup_methods_2/Forc.toml
  test/src/e2e_vm_tests/test_programs/supertraits_dup_methods_2/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/supertraits_dup_methods_2/src/main.sw
Labels: enhancement, compiler

#741 addr2line command for inverse source mapping
  Cargo.lock
  forc/src/cli/commands/addr2line.rs
  forc/src/cli/commands/mod.rs
  forc/src/cli/mod.rs
  forc/src/ops/forc_build.rs
  sway-core/Cargo.toml
  sway-core/src/source_map.rs
Labels: enhancement

#775 Bump lockfile internal deps to v0.4.0.
  Cargo.lock
Labels: dependencies

#773 fix: fix formatter adding `--` to multiple `use` statements
  docs/src/getting-started/temporary_workarounds.md
  sway-fmt/src/fmt.rs
  sway-fmt/src/traversal.rs
Labels: bug, formatter

#786 Descriptive error instead of allowing starting a node with `forc run`
  forc/src/ops/forc_run.rs
  forc/src/utils/cli_error.rs
Labels: forc

#785 Make missing manifest file error the same as Rust's.
  forc/src/ops/forc_abi_json.rs
  forc/src/ops/forc_build.rs
  forc/src/utils/cli_error.rs
Labels: enhancement, forc

#787 Fix typo seralizatio -> serialization
  forc/src/ops/forc_build.rs
Labels: forc

#789 Clean up forc run no node error string.
  forc/src/utils/cli_error.rs
Labels: forc

#791 Fix forc explorer error string
  forc/src/ops/forc_explorer.rs
Labels: bug, forc

#792 Make forc explorer print out a valid URL.
  forc/src/ops/forc_explorer.rs
Labels: enhancement, forc

#794 Code is not guaranteed to run on Rust 1.53 stable.
  sway-core/README.md
Labels: documentation, compiler

#793 Allow trailing comma for function parameters.
  sway-core/src/parser.rs
  sway-core/src/sway.pest
Labels: enhancement, compiler

#803 Add `build-all-examples` to Cargo.lock
  Cargo.lock
Labels: ci

#797 Reorder import items of a use statement lexicographically.
  sway-fmt/src/fmt.rs
  sway-fmt/src/traversal_helper.rs
Labels: enhancement, formatter

#796 Add `--output-directory` to `forc build` and related commands
  .gitignore
  examples/hello_world/my-contract-abi.json
  examples/hello_world/tests/harness.rs
  forc/src/cli/commands/build.rs
  forc/src/cli/commands/clean.rs
  forc/src/cli/commands/deploy.rs
  forc/src/cli/commands/json_abi.rs
  forc/src/cli/commands/mod.rs
  forc/src/cli/commands/run.rs
  forc/src/cli/commands/test.rs
  forc/src/cli/mod.rs
  forc/src/ops/forc_abi_json.rs
  forc/src/ops/forc_build.rs
  forc/src/ops/forc_clean.rs
  forc/src/ops/forc_deploy.rs
  forc/src/ops/forc_fmt.rs
  forc/src/ops/forc_init.rs
  forc/src/ops/forc_run.rs
  forc/src/ops/mod.rs
  forc/src/utils/defaults.rs
  forc/src/utils/helpers.rs
  sway-core/src/lib.rs
  test/src/e2e_vm_tests/harness.rs
  test/src/e2e_vm_tests/test_programs/contract_abi_impl/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/contract_abi_impl/json_abi_output.json
  test/src/e2e_vm_tests/test_programs/valid_impurity/json_abi_oracle.json
Labels: forc

#812 fix incorrect error printout when compiling a library with no errors
  forc/src/ops/forc_build.rs
Labels: bug, forc

#774 fix: prevent panic when parsing empty string
  sway-core/src/error.rs
  sway-core/src/lib.rs
Labels: bug, compiler

#809 forc: Add util `user_forc_directory` function
  forc/src/ops/forc_dep_check.rs
  forc/src/ops/forc_explorer.rs
  forc/src/ops/forc_update.rs
  forc/src/utils/dependency.rs
  forc/src/utils/helpers.rs
  sway-utils/src/constants.rs
Labels: forc

#826 Remove the unused `&mut dependency_graph` throughout `sway-core`
  forc/src/ops/forc_build.rs
  sway-core/src/lib.rs
  sway-core/src/optimize.rs
  sway-core/src/semantic_analysis/ast_node/code_block.rs
  sway-core/src/semantic_analysis/ast_node/declaration/function.rs
  sway-core/src/semantic_analysis/ast_node/expression/enum_instantiation.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/method_application.rs
  sway-core/src/semantic_analysis/ast_node/impl_trait.rs
  sway-core/src/semantic_analysis/ast_node/mod.rs
  sway-core/src/semantic_analysis/syntax_tree.rs
  sway-core/src/semantic_analysis/type_check_arguments.rs
  sway-core/src/source_map.rs
  sway-core/utils/selector_debug.rs
Labels: compiler

#808 Add spans via metadata to IR.
  Cargo.lock
  sway-core/Cargo.toml
  sway-core/src/asm_generation/from_ir.rs
  sway-core/src/optimize.rs
  sway-core/tests/sway_to_ir/array_simple.ir
  sway-core/tests/sway_to_ir/asm_block.ir
  sway-core/tests/sway_to_ir/b256_immeds.ir
  sway-core/tests/sway_to_ir/enum.ir
  sway-core/tests/sway_to_ir/enum_enum.ir
  sway-core/tests/sway_to_ir/enum_struct.ir
  sway-core/tests/sway_to_ir/fn_call.ir
  sway-core/tests/sway_to_ir/if_expr.ir
  sway-core/tests/sway_to_ir/impl_ret_int.ir
  sway-core/tests/sway_to_ir/lazy_binops.ir
  sway-core/tests/sway_to_ir/let_reassign_while_loop.ir
  sway-core/tests/sway_to_ir/mutable_struct.ir
  sway-core/tests/sway_to_ir/shadowed_locals.ir
  sway-core/tests/sway_to_ir/shadowed_struct_init.ir
  sway-core/tests/sway_to_ir/struct.ir
  sway-core/tests/sway_to_ir/struct_enum.ir
  sway-core/tests/sway_to_ir/struct_struct.ir
  sway-core/tests/sway_to_ir/trait.ir
  sway-ir/src/asm.rs
  sway-ir/src/block.rs
  sway-ir/src/constant.rs
  sway-ir/src/context.rs
  sway-ir/src/function.rs
  sway-ir/src/instruction.rs
  sway-ir/src/lib.rs
  sway-ir/src/metadata.rs
  sway-ir/src/module.rs
  sway-ir/src/optimize/constants.rs
  sway-ir/src/optimize/inline.rs
  sway-ir/src/parser.rs
  sway-ir/src/printer.rs
  sway-ir/src/value.rs
  sway-ir/src/verify.rs
  sway-ir/tests/tests.rs
Labels: enhancement, compiler, ir

#807 Attempt to split up CI build steps into separate jobs
  .github/workflows/ci.yml
  .github/workflows/clippy_check.yml
Labels: ci

#472 Allow prefixes in any call path.
  sway-core/src/asm_generation/expression/mod.rs
  sway-core/src/control_flow_analysis/dead_code_analysis.rs
  sway-core/src/error.rs
  sway-core/src/parse_tree/call_path.rs
  sway-core/src/parse_tree/declaration/impl_trait.rs
  sway-core/src/parse_tree/declaration/struct.rs
  sway-core/src/parse_tree/expression/method_name.rs
  sway-core/src/parse_tree/expression/mod.rs
  sway-core/src/parse_tree/expression/unary_op.rs
  sway-core/src/semantic_analysis/ast_node/expression/func_app_instantiation.rs
  sway-core/src/semantic_analysis/ast_node/expression/mod.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/method_application.rs
  sway-core/src/semantic_analysis/ast_node/impl_trait.rs
  sway-core/src/semantic_analysis/ast_node/mod.rs
  sway-core/src/semantic_analysis/namespace.rs
  sway-core/src/semantic_analysis/node_dependencies.rs
  sway-core/src/sway.pest
  sway-server/src/utils/common.rs
  sway-utils/src/helpers.rs
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/dependencies/src/main.sw
  test/src/e2e_vm_tests/test_programs/dependency_parsing_error/Forc.toml
  test/src/e2e_vm_tests/test_programs/dependency_parsing_error/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/dependency_parsing_error/src/a_dependency.sw
  test/src/e2e_vm_tests/test_programs/dependency_parsing_error/src/bar.sw
  test/src/e2e_vm_tests/test_programs/dependency_parsing_error/src/inner/bar.sw
  test/src/e2e_vm_tests/test_programs/dependency_parsing_error/src/inner/double_inner/double_bar.sw
  test/src/e2e_vm_tests/test_programs/dependency_parsing_error/src/main.sw
  test/src/e2e_vm_tests/test_programs/dependency_parsing_error/src/nested_dependency/bar/bar.sw
  test/src/e2e_vm_tests/test_programs/use_full_path_names/Forc.toml
  test/src/e2e_vm_tests/test_programs/use_full_path_names/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/use_full_path_names/src/a_dependency.sw
  test/src/e2e_vm_tests/test_programs/use_full_path_names/src/b_dependency.sw
  test/src/e2e_vm_tests/test_programs/use_full_path_names/src/c_dependency.sw
  test/src/e2e_vm_tests/test_programs/use_full_path_names/src/main.sw
Labels: compiler

#828 Smaller IR changes.
  sway-core/src/asm_generation/from_ir.rs
  sway-core/src/lib.rs
  sway-core/src/optimize.rs
  sway-core/tests/ir_to_asm/bigger_asm_block.ir
  sway-core/tests/ir_to_asm/if_expr.ir
  sway-core/tests/ir_to_asm/impl_ret_int.ir
  sway-core/tests/ir_to_asm/lazy_binops.ir
  sway-core/tests/ir_to_asm/let_reassign_while_loop.ir
  sway-core/tests/ir_to_asm/mutable_struct.ir
  sway-core/tests/ir_to_asm/simple_array.ir
  sway-core/tests/ir_to_asm/simple_enum.ir
  sway-core/tests/ir_to_asm/simple_struct.ir
  sway-core/tests/ir_to_asm/tiny_asm_block.ir
  sway-core/tests/sway_to_ir/array_simple.ir
  sway-core/tests/sway_to_ir/asm_block.ir
  sway-core/tests/sway_to_ir/b256_immeds.ir
  sway-core/tests/sway_to_ir/empty.ir
  sway-core/tests/sway_to_ir/enum.ir
  sway-core/tests/sway_to_ir/enum_enum.ir
  sway-core/tests/sway_to_ir/enum_struct.ir
  sway-core/tests/sway_to_ir/fn_call.ir
  sway-core/tests/sway_to_ir/if_expr.ir
  sway-core/tests/sway_to_ir/impl_ret_int.ir
  sway-core/tests/sway_to_ir/lazy_binops.ir
  sway-core/tests/sway_to_ir/let_reassign_while_loop.ir
  sway-core/tests/sway_to_ir/mutable_struct.ir
  sway-core/tests/sway_to_ir/return_stmt.ir.disabled
  sway-core/tests/sway_to_ir/shadowed_locals.ir
  sway-core/tests/sway_to_ir/shadowed_struct_init.ir
  sway-core/tests/sway_to_ir/strings.ir.disabled
  sway-core/tests/sway_to_ir/struct.ir
  sway-core/tests/sway_to_ir/struct_enum.ir
  sway-core/tests/sway_to_ir/struct_struct.ir
  sway-core/tests/sway_to_ir/trait.ir
  sway-ir/src/bin/opt.rs
  sway-ir/src/context.rs
  sway-ir/src/error.rs
  sway-ir/src/function.rs
  sway-ir/src/irtype.rs
  sway-ir/src/lib.rs
  sway-ir/src/metadata.rs
  sway-ir/src/module.rs
  sway-ir/src/optimize/constants.rs
  sway-ir/src/optimize/inline.rs
  sway-ir/src/parser.rs
  sway-ir/src/printer.rs
  sway-ir/src/verify.rs
  sway-ir/tests/ir_to_ir/constants_insert_value.in_ir
  sway-ir/tests/ir_to_ir/constants_insert_value.out_ir
  sway-ir/tests/ir_to_ir/inline_bigger.in_ir
  sway-ir/tests/ir_to_ir/inline_bigger.out_ir
  sway-ir/tests/ir_to_ir/inline_fiddly.in_ir
  sway-ir/tests/ir_to_ir/inline_fiddly.out_ir
  sway-ir/tests/ir_to_ir/inline_simple.in_ir
  sway-ir/tests/ir_to_ir/inline_simple.out_ir
Labels: enhancement, compiler, ir

#838 Fix panic on empty trait impl
  sway-core/src/parse_tree/declaration/impl_trait.rs
Labels: bug, compiler

#839 CI is failing because the examples are trying to use a version of the standard library that is too advanced
  examples/fizzbuzz/Forc.toml
  examples/hello_world/Forc.toml
  examples/subcurrency/Forc.toml
  examples/wallet_smart_contract/Forc.toml
Labels: ci

#818 Add `size_of` functionality.
  .gitignore
  .vscode/settings.json
  sway-core/src/asm_generation/expression/mod.rs
  sway-core/src/control_flow_analysis/dead_code_analysis.rs
  sway-core/src/optimize.rs
  sway-core/src/parse_tree/expression/mod.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression_variant.rs
  sway-core/src/semantic_analysis/ast_node/mod.rs
  sway-core/src/semantic_analysis/node_dependencies.rs
  sway-core/src/sway.pest
  sway-core/src/type_engine/type_info.rs
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/size_of/Forc.toml
  test/src/e2e_vm_tests/test_programs/size_of/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/size_of/src/main.sw
Labels: compiler

#843 Avoid a panic when a Sway file starts with something unexpected
  forc/src/utils/helpers.rs
Labels: bug, compiler

#850 Use Clap V3 instead of StructOpt
  Cargo.lock
  forc/Cargo.toml
  forc/src/cli/commands/addr2line.rs
  forc/src/cli/commands/build.rs
  forc/src/cli/commands/clean.rs
  forc/src/cli/commands/deploy.rs
  forc/src/cli/commands/explorer.rs
  forc/src/cli/commands/format.rs
  forc/src/cli/commands/init.rs
  forc/src/cli/commands/json_abi.rs
  forc/src/cli/commands/lsp.rs
  forc/src/cli/commands/parse_bytecode.rs
  forc/src/cli/commands/run.rs
  forc/src/cli/commands/test.rs
  forc/src/cli/commands/update.rs
  forc/src/cli/mod.rs
  sway-core/Cargo.toml
  sway-core/utils/selector_debug.rs
Labels: forc

#853 Bump to v0.5.0.
  Cargo.lock
  forc/Cargo.toml
  parser/Cargo.toml
  sway-core/Cargo.toml
  sway-fmt/Cargo.toml
  sway-ir/Cargo.toml
  sway-server/Cargo.toml
  sway-types/Cargo.toml
  sway-utils/Cargo.toml
  test/Cargo.toml
Labels: release
