Repository FuelLabs/sway, pull requests merged in 2022-07, with the labels that each got.

#2096 Fix checking for too many function call arguments.
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/function_application.rs
  sway-core/tests/sway_to_ir/get_storage_key.ir
  sway-core/tests/sway_to_ir/get_storage_key.sw
  sway-ir/src/parser.rs
  test/src/e2e_vm_tests/test_programs/should_fail/excess_fn_arguments/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/missing_fn_arguments/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/get_storage_key_contract/src/main.sw
Labels: bug, compiler

#2194 chore: use `concurrency` to cancel previous CI runs
  .github/workflows/ci.yml
Labels: ci

#2189 Rely on `is_copy_type` when compiling `load` and `store` into `asm`
  sway-core/src/asm_generation/from_ir.rs
  sway-core/tests/ir_to_asm/struct_in_union.asm
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/mem/src/main.sw
Labels: bug, P: critical, compiler: codegen

#2112 `break` and `continue`
  sway-core/src/control_flow_analysis/analyze_return_paths.rs
  sway-core/src/control_flow_analysis/dead_code_analysis.rs
  sway-core/src/convert_parse_tree.rs
  sway-core/src/error.rs
  sway-core/src/ir_generation/compile.rs
  sway-core/src/ir_generation/function.rs
  sway-core/src/lib.rs
  sway-core/src/parse_tree/declaration.rs
  sway-core/src/semantic_analysis/ast_node/declaration.rs
  sway-core/src/semantic_analysis/ast_node/mod.rs
  sway-core/src/semantic_analysis/node_dependencies.rs
  sway-core/tests/sway_to_ir/break.ir
  sway-core/tests/sway_to_ir/break.sw
  sway-core/tests/sway_to_ir/continue.ir
  sway-core/tests/sway_to_ir/continue.sw
  sway-core/tests/sway_to_ir/let_reassign_while_loop.ir
  sway-fmt-v2/src/utils/item.rs
  sway-ir/src/block.rs
  sway-lib-std/src/token.sw
  sway-lsp/src/core/token.rs
  sway-lsp/src/core/traverse_typed_tree.rs
  sway-parse/src/expr/mod.rs
  sway-parse/src/item/item_control_flow.rs
  sway-parse/src/item/mod.rs
  sway-parse/src/keywords.rs
  sway-parse/src/lib.rs
  sway-parse/src/priv_prelude.rs
  test/src/e2e_vm_tests/test_programs/should_fail/illegal_break/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/illegal_break/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/illegal_break/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/illegal_break/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/illegal_continue/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/illegal_continue/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/illegal_continue/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/illegal_continue/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/break_and_continue/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/break_and_continue/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/break_and_continue/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/language/break_and_continue/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/break_and_continue/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/storage_declaration/Forc.lock
Labels: enhancement, compiler: ir, language feature, compiler: frontend, compiler: parser

#2193 Bump `sway-core` to use `fuel-asm` version `0.6`
  Cargo.lock
  forc/Cargo.toml
  sway-core/Cargo.toml
  sway-core/src/asm_lang/allocated_ops.rs
  sway-core/src/asm_lang/mod.rs
  sway-core/src/asm_lang/virtual_ops.rs
  sway-types/Cargo.toml
  test/Cargo.toml
Labels: good first issue, code quality

#2175 Distinguish between `forc init` and `forc new` (Copy over changes from PR#1669)
  .github/workflows/ci.yml
  docs/src/SUMMARY.md
  docs/src/forc/commands/forc_new.md
  docs/src/introduction/forc_project.md
  docs/src/introduction/overview.md
  docs/src/introduction/standard_library.md
  docs/src/testing/testing-with-rust.md
  forc/src/cli/commands/init.rs
  forc/src/cli/commands/mod.rs
  forc/src/cli/commands/new.rs
  forc/src/cli/commands/test.rs
  forc/src/cli/mod.rs
  forc/src/ops/forc_init.rs
  scripts/mdbook-forc-documenter/examples/forc_new.md
  scripts/mdbook-forc-documenter/examples/forc_parse-bytecode.md
  scripts/mdbook-forc-documenter/examples/forc_test.md
Labels: forc, breaking

#2174 Bump to v0.17.0
  Cargo.lock
  forc-gm/Cargo.toml
  forc-pkg/Cargo.toml
  forc-plugins/forc-explore/Cargo.toml
  forc-plugins/forc-fmt-v2/Cargo.toml
  forc-plugins/forc-fmt/Cargo.toml
  forc-plugins/forc-lsp/Cargo.toml
  forc-util/Cargo.toml
  forc/Cargo.toml
  sway-core/Cargo.toml
  sway-fmt-v2/Cargo.toml
  sway-fmt/Cargo.toml
  sway-ir/Cargo.toml
  sway-lsp/Cargo.toml
  sway-parse/Cargo.toml
  sway-types/Cargo.toml
  sway-utils/Cargo.toml
Labels: release

#2200 Update author entry in manifest test for `e2e/.../language/modulo_uint_test`
  test/src/e2e_vm_tests/test_programs/should_pass/language/modulo_uint_test/Forc.toml
Labels: good first issue, code quality

#2127 Warning about using zero address as ownership in SwayBook
  docs/src/blockchain-development/access_control.md
  examples/identity/src/main.sw
  examples/ownership/Forc.lock
  examples/ownership/Forc.toml
  examples/ownership/src/main.sw
Labels: The Sway Book

#2185 Check for unknown file check directives and fix a broken test.
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/should_fail/match_expressions_rest/test.toml
Labels: bug, compiler

#1984 Add `std::tx::get_predicate_data`
  sway-lib-std/src/tx.sw
  test/src/sdk-harness/test_projects/harness.rs
  test/src/sdk-harness/test_projects/predicate_data_simple/Forc.lock
  test/src/sdk-harness/test_projects/predicate_data_simple/Forc.toml
  test/src/sdk-harness/test_projects/predicate_data_simple/mod.rs
  test/src/sdk-harness/test_projects/predicate_data_simple/src/main.sw
  test/src/sdk-harness/test_projects/predicate_data_struct/Forc.lock
  test/src/sdk-harness/test_projects/predicate_data_struct/Forc.toml
  test/src/sdk-harness/test_projects/predicate_data_struct/mod.rs
  test/src/sdk-harness/test_projects/predicate_data_struct/src/main.sw
Labels: enhancement, lib: std

#2206 #2205 - Use ZERO_B256 const to initialize BASE_ASSET_ID const
  sway-lib-std/src/constants.sw
Labels: good first issue, lib: std, code quality

#2023 Bump fuel-core to v0.9.4.
  .github/workflows/ci.yml
Labels: ci

#2210 Add `parsed_to_ast` fn in `sway_core`
  sway-core/src/lib.rs
Labels: language server, compiler: frontend, compiler: parser

#2142 Refactor std::tx
  sway-lib-std/src/chain/auth.sw
  sway-lib-std/src/token.sw
  sway-lib-std/src/tx.sw
  test/src/sdk-harness/test_artifacts/tx_contract/src/main.sw
  test/src/sdk-harness/test_projects/script_bytecode/Forc.lock
  test/src/sdk-harness/test_projects/script_bytecode/Forc.toml
  test/src/sdk-harness/test_projects/script_bytecode/mod.rs
  test/src/sdk-harness/test_projects/script_bytecode/src/main.sw
  test/src/sdk-harness/test_projects/script_data/src/main.sw
  test/src/sdk-harness/test_projects/tx_fields/mod.rs
Labels: enhancement

#2201 Remove duplicate check to length of function arguments
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/function_application.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/method_application.rs
Labels: code quality

#2178 Add the `SMO` opcode to `sway-core`
  sway-core/src/asm_lang/allocated_ops.rs
  sway-core/src/asm_lang/mod.rs
  sway-core/src/asm_lang/virtual_ops.rs
  sway-parse/src/expr/op_code.rs
  test/src/e2e_vm_tests/test_programs/should_pass/language/smo_opcode/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/smo_opcode/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/smo_opcode/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/smo_opcode/test.toml
Labels: good first issue, language feature, compiler: codegen

#2187 add input/output type constants to std-lib
  sway-lib-std/src/token.sw
  sway-lib-std/src/tx.sw
Labels: enhancement, lib: std

#2214 Add a `tx_id()` function to std::tx
  sway-lib-std/src/tx.sw
  test/src/sdk-harness/test_artifacts/tx_contract/src/main.sw
  test/src/sdk-harness/test_projects/tx_fields/mod.rs
Labels: lib: std

#2208 Fix pointer types and use `std::mem` on `std::tx`
  sway-lib-std/src/tx.sw
  test/src/sdk-harness/test_artifacts/tx_contract/src/main.sw
  test/src/sdk-harness/test_projects/tx_fields/mod.rs
Labels: lib: std, breaking

#2216 Swap order of operands for `std::mem::copy`
  sway-lib-std/src/alloc.sw
  sway-lib-std/src/mem.sw
  sway-lib-std/src/vec.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/mem/src/main.sw
Labels: lib: std, breaking

#2213 Add `Span` to `break` and `continue` declarations
  sway-core/src/control_flow_analysis/analyze_return_paths.rs
  sway-core/src/control_flow_analysis/dead_code_analysis.rs
  sway-core/src/convert_parse_tree.rs
  sway-core/src/ir_generation/compile.rs
  sway-core/src/ir_generation/function.rs
  sway-core/src/parse_tree/declaration.rs
  sway-core/src/semantic_analysis/ast_node/declaration.rs
  sway-core/src/semantic_analysis/ast_node/mod.rs
  sway-core/src/semantic_analysis/node_dependencies.rs
  sway-lsp/src/core/token.rs
  sway-lsp/src/core/traverse_typed_tree.rs
Labels: enhancement, compiler: ir, compiler: frontend, compiler: parser

#2124 Add storage formatting to sway-fmt-v2
  sway-fmt-v2/src/config/heuristics.rs
  sway-fmt-v2/src/constants.rs
  sway-fmt-v2/src/fmt.rs
  sway-fmt-v2/src/items/item_enum.rs
  sway-fmt-v2/src/items/item_storage.rs
  sway-fmt-v2/src/items/item_struct.rs
  sway-fmt-v2/src/utils/item_len.rs
  sway-fmt-v2/src/utils/punctuated.rs
Labels: enhancement, formatter

#2198 Check for calling of associated functions as method calls.
  sway-core/src/error.rs
  sway-core/src/semantic_analysis/ast_node/declaration/function/function_parameter.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/method_application.rs
  sway-lib-std/src/address.sw
  sway-lib-std/src/contract_id.sw
  sway-lib-std/src/u128.sw
  sway-lib-std/src/u256.sw
  sway-lib-std/src/vm/evm/evm_address.sw
  test/src/e2e_vm_tests/test_programs/should_fail/associated_fn_as_method_call/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/associated_fn_as_method_call/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/associated_fn_as_method_call/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_fail/associated_fn_as_method_call/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/associated_fn_as_method_call/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/associated_fn_params_as_method_call/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/associated_fn_params_as_method_call/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/associated_fn_params_as_method_call/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_fail/associated_fn_params_as_method_call/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/associated_fn_params_as_method_call/test.toml
Labels: compiler

#2191 Turn `CallPath` into a wrapper type
  sway-core/src/convert_parse_tree.rs
  sway-core/src/error.rs
  sway-core/src/parse_tree/call_path.rs
  sway-core/src/parse_tree/expression/method_name.rs
  sway-core/src/parse_tree/expression/mod.rs
  sway-core/src/parse_tree/expression/scrutinee.rs
  sway-core/src/semantic_analysis/ast_node/declaration/enum.rs
  sway-core/src/semantic_analysis/ast_node/declaration/function.rs
  sway-core/src/semantic_analysis/ast_node/declaration/function/function_parameter.rs
  sway-core/src/semantic_analysis/ast_node/declaration/impl_trait.rs
  sway-core/src/semantic_analysis/ast_node/declaration/struct.rs
  sway-core/src/semantic_analysis/ast_node/declaration/trait.rs
  sway-core/src/semantic_analysis/ast_node/expression/intrinsic_function.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/method_application.rs
  sway-core/src/semantic_analysis/ast_node/mod.rs
  sway-core/src/semantic_analysis/namespace/items.rs
  sway-core/src/semantic_analysis/namespace/namespace.rs
  sway-core/src/semantic_analysis/namespace/root.rs
  sway-core/src/semantic_analysis/namespace/trait_map.rs
  sway-core/src/semantic_analysis/node_dependencies.rs
  sway-core/src/semantic_analysis/type_check_context.rs
  sway-core/src/type_engine/engine.rs
  sway-core/src/type_engine/type_id.rs
  sway-core/src/type_engine/type_info.rs
  sway-core/src/type_engine/type_mapping.rs
  sway-lib-std/src/vec.sw
  sway-lsp/src/core/token.rs
  sway-lsp/src/utils/common.rs
  test/src/e2e_vm_tests/test_programs/should_pass/language/primitive_type_argument/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/primitive_type_argument/Forc.toml
Labels: bug, compiler: frontend

#2233 Fix and clean up forc reference docs.
  forc/src/cli/commands/new.rs
  scripts/mdbook-forc-documenter/examples/forc_build.md
  scripts/mdbook-forc-documenter/examples/forc_completions.md
  scripts/mdbook-forc-documenter/examples/forc_deploy.md
  scripts/mdbook-forc-documenter/examples/forc_init.md
  scripts/mdbook-forc-documenter/examples/forc_new.md
  scripts/mdbook-forc-documenter/examples/forc_parse-bytecode.md
  scripts/mdbook-forc-documenter/examples/forc_template.md
  scripts/mdbook-forc-documenter/examples/forc_test.md
Labels: forc, The Sway Book

#2221 Switch the check if an IR block is terminated by a branch to just be a check if terminated at all.
  sway-core/src/ir_generation/function.rs
  sway-ir/src/block.rs
  test/src/ir_generation/tests/return_in_while_loop.sw
Labels: bug, compiler: ir

#2168 Add 'Ty' formatting to `sway-fmt-v2`
  sway-fmt-v2/src/fmt.rs
  sway-fmt-v2/src/items/item_enum.rs
  sway-fmt-v2/src/items/item_storage.rs
  sway-fmt-v2/src/items/item_struct.rs
  sway-fmt-v2/src/utils.rs
  sway-fmt-v2/src/utils/generics.rs
  sway-fmt-v2/src/utils/path.rs
  sway-fmt-v2/src/utils/punctuated.rs
  sway-fmt-v2/src/utils/ty.rs
Labels: enhancement, formatter

#2230 Correctly display DCA warnings and fix some incorrect warnings that showed up
  sway-core/src/control_flow_analysis/dead_code_analysis.rs
  sway-core/src/convert_parse_tree.rs
  sway-core/src/ir_generation/const_eval.rs
  sway-lib-core/src/ops.sw
  sway-lib-std/src/constants.sw
  sway-lib-std/src/tx.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/const_decl_in_library/src/earth.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/const_decl_in_library/src/heaven.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/const_decl_in_library/src/hell.sw
Labels: bug, lib: std, breaking, P: critical, compiler: frontend

#2223 Update the new ir_generation test suite a bit.
  test/src/ir_generation/README.md
  test/src/ir_generation/mod.rs
  test/src/ir_generation/tests/array_simple.sw
  test/src/ir_generation/tests/asm_block.sw
  test/src/ir_generation/tests/b256_immeds.sw
  test/src/ir_generation/tests/break.sw
  test/src/ir_generation/tests/continue.sw
  test/src/ir_generation/tests/enum.sw
  test/src/ir_generation/tests/enum_enum.sw
  test/src/ir_generation/tests/enum_in_storage_read.sw
  test/src/ir_generation/tests/enum_in_storage_write.sw
  test/src/ir_generation/tests/enum_struct.sw
  test/src/ir_generation/tests/enum_struct_string.sw
  test/src/ir_generation/tests/eq_intrinsic.sw
  test/src/ir_generation/tests/fn_call.sw
  test/src/ir_generation/tests/get_storage_key.sw
  test/src/ir_generation/tests/if_expr.sw
  test/src/ir_generation/tests/if_let_simple.sw
  test/src/ir_generation/tests/impl_ret_int.sw
  test/src/ir_generation/tests/impl_self_reassignment.sw
  test/src/ir_generation/tests/implicit_return.sw
  test/src/ir_generation/tests/lazy_binops.sw
  test/src/ir_generation/tests/let_reassign_while_loop.sw
  test/src/ir_generation/tests/local_const_init.sw
  test/src/ir_generation/tests/mutable_struct.sw
  test/src/ir_generation/tests/ret_unit.sw
  test/src/ir_generation/tests/return_in_while_loop.sw
  test/src/ir_generation/tests/return_stmt.sw
  test/src/ir_generation/tests/shadowed_locals.sw
  test/src/ir_generation/tests/shadowed_struct_init.sw
  test/src/ir_generation/tests/simple_contract.sw
  test/src/ir_generation/tests/simple_contract_call.sw
  test/src/ir_generation/tests/storage_metadata.sw
  test/src/ir_generation/tests/strings.sw
  test/src/ir_generation/tests/strings_in_storage.sw
  test/src/ir_generation/tests/struct.sw
  test/src/ir_generation/tests/struct_enum.sw
  test/src/ir_generation/tests/struct_struct.sw
  test/src/ir_generation/tests/takes_string_returns_string.sw
  test/src/ir_generation/tests/trait.sw
  test/src/ir_generation/tests/unit_type_variants.sw
Labels: testing, compiler: ir

#2234 `forc-pkg`: Refactor `BuildPlan` construction and validation to minimize fetching, improve offline support, reduce I/O, fix bugs.
  forc-pkg/src/lock.rs
  forc-pkg/src/manifest.rs
  forc-pkg/src/pkg.rs
  forc/src/ops/forc_build.rs
  forc/src/ops/forc_check.rs
  forc/src/ops/forc_update.rs
  sway-lsp/src/core/document.rs
Labels: bug, enhancement, forc, code quality, dependencies

#2250 Bump `openssl-src` to 111.22.
  Cargo.lock
Labels: dependencies

#2212 improvement(formatter): Enums and Structs are formatted to a single line first before getting their length to determine multiline formatting
  sway-fmt-v2/src/items/item_enum.rs
  sway-fmt-v2/src/items/item_storage.rs
  sway-fmt-v2/src/items/item_struct.rs
  sway-fmt-v2/src/utils.rs
  sway-fmt-v2/src/utils/item.rs
  sway-fmt-v2/src/utils/item_len.rs
Labels: enhancement, formatter

#2255 Update `sway-fmt-v2` with new `Ty` formatting and replace `push_str` with `write!`
  sway-fmt-v2/src/fmt.rs
  sway-fmt-v2/src/items/item_abi.rs
  sway-fmt-v2/src/items/item_const.rs
  sway-fmt-v2/src/items/item_enum.rs
  sway-fmt-v2/src/items/item_storage.rs
  sway-fmt-v2/src/items/item_struct.rs
  sway-fmt-v2/src/utils/attribute.rs
  sway-fmt-v2/src/utils/generics.rs
  sway-fmt-v2/src/utils/newline_style.rs
  sway-fmt-v2/src/utils/path.rs
  sway-fmt-v2/src/utils/program_type.rs
  sway-fmt-v2/src/utils/punctuated.rs
  sway-fmt-v2/src/utils/ty.rs
Labels: forc, code quality, formatter

#2270 Fix broken link to the instruction set spec in the Sway Book
  docs/src/advanced/assembly.md
Labels: bug, The Sway Book

#2262 Remove unsupported LSP Capabilities
  sway-lsp/src/server.rs
Labels: bug, language server

#2220 Return a `CompileResult` & a `CompileAstResult` from `forc_pkg::check`
  forc-pkg/src/pkg.rs
  forc/src/ops/forc_check.rs
  sway-core/src/lib.rs
  sway-core/src/semantic_analysis/module.rs
  sway-core/src/semantic_analysis/program.rs
  sway-lsp/src/core/document.rs
Labels: forc, language server, compiler: frontend

#2209 forc-pkg: Improve error handling around removed path deps and patches
  forc-pkg/src/pkg.rs
Labels: enhancement, forc

#2267 Account for characters that are larger than 1 byte when displaying warnings and errors
  forc-util/src/lib.rs
Labels: bug, forc

#2243 feat: struct destructuring
  docs/src/basics/structs_tuples_and_enums.md
  examples/structs/src/data_structures.sw
  examples/structs/src/main.sw
  sway-core/src/constants.rs
  sway-core/src/convert_parse_tree.rs
  sway-parse/src/item/mod.rs
  test/src/e2e_vm_tests/test_programs/should_pass/language/nested_struct_destructuring/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/nested_struct_destructuring/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/nested_struct_destructuring/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/language/nested_struct_destructuring/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/nested_struct_destructuring/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/struct_destructuring/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/struct_destructuring/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/struct_destructuring/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/language/struct_destructuring/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/struct_destructuring/test.toml
Labels: language feature

#2269 Remove `Spanned` and add `Format` trait to `Punctuated`
  sway-fmt-v2/src/utils/punctuated.rs
Labels: forc, code quality, formatter

#2252 Fix some small issues in compiling load and store IR instructions when the word offset is > 4096
  sway-core/src/asm_generation/from_ir.rs
  test/src/e2e_vm_tests/test_programs/should_pass/language/many_stack_variables/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/many_stack_variables/test.toml
Labels: bug, P: critical, compiler: codegen

#2271 Some code golf
  forc-pkg/src/manifest.rs
  forc/src/ops/forc_deploy.rs
  forc/src/ops/forc_template.rs
  sway-core/src/convert_parse_tree.rs
  sway-core/src/lib.rs
  sway-core/src/semantic_analysis/ast_node/declaration/enum.rs
  sway-core/src/semantic_analysis/ast_node/declaration/function.rs
  sway-core/src/semantic_analysis/ast_node/declaration/struct.rs
  sway-core/src/semantic_analysis/ast_node/mod.rs
  sway-core/src/semantic_analysis/namespace/items.rs
  sway-core/src/semantic_analysis/namespace/root.rs
  sway-core/src/semantic_analysis/node_dependencies.rs
  sway-core/src/type_engine/type_argument.rs
  sway-core/src/type_engine/type_parameter.rs
  sway-ir/src/verify.rs
  sway-parse/src/parser.rs
  sway-types/src/ident.rs
Labels: code quality

#2273 Bump to fuels 0.17.0
  forc/src/utils/defaults.rs
  test/src/sdk-harness/Cargo.toml
  test/src/sdk-harness/test_projects/auth/mod.rs
  test/src/sdk-harness/test_projects/call_frames/mod.rs
  test/src/sdk-harness/test_projects/context/mod.rs
  test/src/sdk-harness/test_projects/evm/mod.rs
  test/src/sdk-harness/test_projects/exponentiation/mod.rs
  test/src/sdk-harness/test_projects/hashing/mod.rs
  test/src/sdk-harness/test_projects/methods/mod.rs
  test/src/sdk-harness/test_projects/predicate_data_simple/mod.rs
  test/src/sdk-harness/test_projects/predicate_data_struct/mod.rs
  test/src/sdk-harness/test_projects/reentrancy/mod.rs
  test/src/sdk-harness/test_projects/registers/mod.rs
  test/src/sdk-harness/test_projects/storage/mod.rs
  test/src/sdk-harness/test_projects/storage_map/mod.rs
  test/src/sdk-harness/test_projects/token_ops/mod.rs
  test/src/sdk-harness/test_projects/tx_fields/mod.rs
Labels: forc, testing

#2268 Bump to v0.18.0
  Cargo.lock
  forc-gm/Cargo.toml
  forc-pkg/Cargo.toml
  forc-plugins/forc-explore/Cargo.toml
  forc-plugins/forc-fmt-v2/Cargo.toml
  forc-plugins/forc-fmt/Cargo.toml
  forc-plugins/forc-lsp/Cargo.toml
  forc-util/Cargo.toml
  forc/Cargo.toml
  sway-core/Cargo.toml
  sway-fmt-v2/Cargo.toml
  sway-fmt/Cargo.toml
  sway-ir/Cargo.toml
  sway-lsp/Cargo.toml
  sway-parse/Cargo.toml
  sway-types/Cargo.toml
  sway-utils/Cargo.toml
Labels: breaking, release

#2173 Adds `ItemFn` formatting to `sway-fmt-v2`
  sway-fmt-v2/src/fmt.rs
  sway-fmt-v2/src/items/item_enum.rs
  sway-fmt-v2/src/items/item_fn.rs
  sway-fmt-v2/src/items/item_storage.rs
  sway-fmt-v2/src/items/item_struct.rs
  sway-fmt-v2/src/items/item_trait.rs
  sway-fmt-v2/src/utils.rs
  sway-fmt-v2/src/utils/expr.rs
  sway-fmt-v2/src/utils/indent_style.rs
  sway-fmt-v2/src/utils/literal.rs
  sway-fmt-v2/src/utils/path.rs
  sway-fmt-v2/src/utils/pattern.rs
  sway-fmt-v2/src/utils/punctuated.rs
  sway-fmt-v2/src/utils/statement.rs
  sway-fmt-v2/src/utils/where_clause.rs
  sway-parse/src/keywords.rs
Labels: enhancement, forc, big, formatter

#2290 Expose a function that clears the type engine
  forc-pkg/src/pkg.rs
  sway-core/src/concurrent_slab.rs
  sway-core/src/lib.rs
  sway-core/src/type_engine/engine.rs
Labels: compiler, forc

#2244 Change verbosity from debug -> info in forc init
  forc/src/ops/forc_init.rs
Labels: bug, forc

#2293 Some fixes to the Sway Book
  docs/src/basics/control_flow.md
  docs/src/blockchain-development/calling_contracts.md
  docs/src/introduction/forc_project.md
  docs/src/introduction/sway-toolchain.md
  docs/src/testing/testing-with-rust.md
  examples/break_and_continue/Forc.lock
  examples/break_and_continue/Forc.toml
  examples/break_and_continue/src/main.sw
  examples/msg_sender/src/main.sw
Labels: The Sway Book

#2302 Call `sway_core::clear_lazy_statics` at the beginning of build and check
  forc-pkg/src/pkg.rs
Labels: compiler, forc

#2301 Bump `tower-lsp` dep to the latest version
  Cargo.lock
  sway-lsp/Cargo.toml
Labels: language server, dependencies

#2303 Cover arrays of generics in JSON ABI by handling their type arguments
  sway-core/src/type_engine/type_id.rs
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/abi_with_generic_types/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/abi_with_generic_types/src/main.sw
Labels: bug, P: critical, compiler: frontend

#2304 Bump to v0.18.1
  Cargo.lock
  forc-gm/Cargo.toml
  forc-pkg/Cargo.toml
  forc-plugins/forc-explore/Cargo.toml
  forc-plugins/forc-fmt-v2/Cargo.toml
  forc-plugins/forc-fmt/Cargo.toml
  forc-plugins/forc-lsp/Cargo.toml
  forc-util/Cargo.toml
  forc/Cargo.toml
  sway-core/Cargo.toml
  sway-fmt-v2/Cargo.toml
  sway-fmt/Cargo.toml
  sway-ir/Cargo.toml
  sway-lsp/Cargo.toml
  sway-parse/Cargo.toml
  sway-types/Cargo.toml
  sway-utils/Cargo.toml
Labels: release

#2312 Add `is_terminated` check before compiling return statements to IR
  sway-core/src/ir_generation/function.rs
  test/src/e2e_vm_tests/test_programs/should_pass/language/redundant_return/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/redundant_return/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/redundant_return/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/language/redundant_return/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/redundant_return/test.toml
  test/src/ir_generation/tests/redundant_return.sw
Labels: bug, compiler: ir, P: critical

#2229 Add means of comment formatting to `sway-fmt-v2`
  sway-fmt-v2/src/error.rs
  sway-fmt-v2/src/utils.rs
  sway-fmt-v2/src/utils/comments.rs
Labels: enhancement, formatter

#2195 Introduce the `TypeBinding` type
  sway-core/src/convert_parse_tree.rs
  sway-core/src/error.rs
  sway-core/src/parse_tree/expression/method_name.rs
  sway-core/src/parse_tree/expression/mod.rs
  sway-core/src/semantic_analysis/ast_node/declaration.rs
  sway-core/src/semantic_analysis/ast_node/expression/intrinsic_function.rs
  sway-core/src/semantic_analysis/ast_node/expression/match_expression/typed/typed_scrutinee.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/enum_instantiation.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/function_application.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/method_application.rs
  sway-core/src/semantic_analysis/namespace/module.rs
  sway-core/src/semantic_analysis/namespace/root.rs
  sway-core/src/semantic_analysis/node_dependencies.rs
  sway-core/src/semantic_analysis/type_check_context.rs
  sway-core/src/type_engine/engine.rs
  sway-core/src/type_engine/mod.rs
  sway-core/src/type_engine/type_binding.rs
  sway-fmt/src/traversal.rs
  sway-lsp/src/core/traverse_parse_tree.rs
  test/src/e2e_vm_tests/test_programs/should_pass/language/fixing_generic_type/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/fixing_generic_type/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/fixing_generic_type/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/language/fixing_generic_type/src/buffer.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/fixing_generic_type/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/fixing_generic_type/src/pointer.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/fixing_generic_type/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/generic_impl_self/src/main.sw
Labels: bug, P: critical, compiler: frontend

#2317 Refactor coins_owner
  sway-lib-std/src/chain/auth.sw
Labels: enhancement, lib: std, code quality, breaking

#2048 StorageVec
  sway-lib-std/src/storage.sw
  test/src/sdk-harness/build.sh
  test/src/sdk-harness/test_artifacts/storage_vec/svec_b256/.gitignore
  test/src/sdk-harness/test_artifacts/storage_vec/svec_b256/Forc.lock
  test/src/sdk-harness/test_artifacts/storage_vec/svec_b256/Forc.toml
  test/src/sdk-harness/test_artifacts/storage_vec/svec_b256/src/main.sw
  test/src/sdk-harness/test_artifacts/storage_vec/svec_bool/.gitignore
  test/src/sdk-harness/test_artifacts/storage_vec/svec_bool/Forc.lock
  test/src/sdk-harness/test_artifacts/storage_vec/svec_bool/Forc.toml
  test/src/sdk-harness/test_artifacts/storage_vec/svec_bool/src/main.sw
  test/src/sdk-harness/test_artifacts/storage_vec/svec_enum/.gitignore
  test/src/sdk-harness/test_artifacts/storage_vec/svec_enum/Forc.lock
  test/src/sdk-harness/test_artifacts/storage_vec/svec_enum/Forc.toml
  test/src/sdk-harness/test_artifacts/storage_vec/svec_enum/src/main.sw
  test/src/sdk-harness/test_artifacts/storage_vec/svec_str/.gitignore
  test/src/sdk-harness/test_artifacts/storage_vec/svec_str/Forc.lock
  test/src/sdk-harness/test_artifacts/storage_vec/svec_str/Forc.toml
  test/src/sdk-harness/test_artifacts/storage_vec/svec_str/src/main.sw
  test/src/sdk-harness/test_artifacts/storage_vec/svec_struct/.gitignore
  test/src/sdk-harness/test_artifacts/storage_vec/svec_struct/Forc.lock
  test/src/sdk-harness/test_artifacts/storage_vec/svec_struct/Forc.toml
  test/src/sdk-harness/test_artifacts/storage_vec/svec_struct/src/main.sw
  test/src/sdk-harness/test_artifacts/storage_vec/svec_u16/.gitignore
  test/src/sdk-harness/test_artifacts/storage_vec/svec_u16/Forc.lock
  test/src/sdk-harness/test_artifacts/storage_vec/svec_u16/Forc.toml
  test/src/sdk-harness/test_artifacts/storage_vec/svec_u16/src/main.sw
  test/src/sdk-harness/test_artifacts/storage_vec/svec_u32/.gitignore
  test/src/sdk-harness/test_artifacts/storage_vec/svec_u32/Forc.lock
  test/src/sdk-harness/test_artifacts/storage_vec/svec_u32/Forc.toml
  test/src/sdk-harness/test_artifacts/storage_vec/svec_u32/src/main.sw
  test/src/sdk-harness/test_artifacts/storage_vec/svec_u64/.gitignore
  test/src/sdk-harness/test_artifacts/storage_vec/svec_u64/Forc.lock
  test/src/sdk-harness/test_artifacts/storage_vec/svec_u64/Forc.toml
  test/src/sdk-harness/test_artifacts/storage_vec/svec_u64/src/main.sw
  test/src/sdk-harness/test_artifacts/storage_vec/svec_u8/.gitignore
  test/src/sdk-harness/test_artifacts/storage_vec/svec_u8/Forc.lock
  test/src/sdk-harness/test_artifacts/storage_vec/svec_u8/Forc.toml
  test/src/sdk-harness/test_artifacts/storage_vec/svec_u8/src/main.sw
  test/src/sdk-harness/test_projects/harness.rs
  test/src/sdk-harness/test_projects/storage_vec/b256/mod.rs
  test/src/sdk-harness/test_projects/storage_vec/b256/utils.rs
  test/src/sdk-harness/test_projects/storage_vec/bool/mod.rs
  test/src/sdk-harness/test_projects/storage_vec/bool/utils.rs
  test/src/sdk-harness/test_projects/storage_vec/enum/mod.rs
  test/src/sdk-harness/test_projects/storage_vec/enum/utils.rs
  test/src/sdk-harness/test_projects/storage_vec/mod.rs
  test/src/sdk-harness/test_projects/storage_vec/str/mod.rs
  test/src/sdk-harness/test_projects/storage_vec/str/utils.rs
  test/src/sdk-harness/test_projects/storage_vec/struct/mod.rs
  test/src/sdk-harness/test_projects/storage_vec/struct/utils.rs
  test/src/sdk-harness/test_projects/storage_vec/u16/mod.rs
  test/src/sdk-harness/test_projects/storage_vec/u16/utils.rs
  test/src/sdk-harness/test_projects/storage_vec/u32/mod.rs
  test/src/sdk-harness/test_projects/storage_vec/u32/utils.rs
  test/src/sdk-harness/test_projects/storage_vec/u64/mod.rs
  test/src/sdk-harness/test_projects/storage_vec/u64/utils.rs
  test/src/sdk-harness/test_projects/storage_vec/u8/mod.rs
  test/src/sdk-harness/test_projects/storage_vec/u8/utils.rs
Labels: enhancement, lib: std

#2316 Bugfix in rsh method for b256
  sway-lib-core/src/ops.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/b256_bitwise_ops/src/main.sw
Labels: bug, lib: core

#2294 Adds `ItemTrait` to `sway-fmt-v2`
  sway-fmt-v2/src/fmt.rs
  sway-fmt-v2/src/items/item_fn.rs
  sway-fmt-v2/src/items/item_trait.rs
  sway-fmt-v2/src/utils/where_clause.rs
Labels: forc, formatter

#2296 refactor: refactor call_frames to use registers read function
  sway-lib-std/src/context.sw
  sway-lib-std/src/context/call_frames.sw
  test/src/sdk-harness/test_artifacts/call_frames_test_abi/src/main.sw
  test/src/sdk-harness/test_projects/call_frames/mod.rs
  test/src/sdk-harness/test_projects/call_frames/src/main.sw
Labels: code quality

#2332 Switch `forc new` to create a test that uses a wallet with some coins in it
  forc/src/utils/defaults.rs
Labels: forc

#2329 Fix for `storage` initializers in `sway-fmt-v2`
  sway-fmt-v2/src/fmt.rs
  sway-fmt-v2/src/items/item_storage.rs
  sway-fmt-v2/src/items/item_struct.rs
  sway-fmt-v2/src/utils/expr.rs
  sway-fmt-v2/src/utils/punctuated.rs
Labels: bug, forc, formatter

#2334 Add a test to verify the order of `Option` variants
  test/src/sdk-harness/test_projects/harness.rs
  test/src/sdk-harness/test_projects/option_field_order/Forc.lock
  test/src/sdk-harness/test_projects/option_field_order/Forc.toml
  test/src/sdk-harness/test_projects/option_field_order/mod.rs
  test/src/sdk-harness/test_projects/option_field_order/src/main.sw
Labels: testing

#2336 update increment contract to new-style storage
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_increment_contract/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/test_abis/increment_abi/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/increment_contract/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/increment_contract/json_storage_slots_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/increment_contract/src/main.sw
Labels: testing

#2344 Fix bug in translating `if-let` without an `else` to `match`.
  sway-core/src/convert_parse_tree.rs
  test/src/e2e_vm_tests/test_programs/should_fail/chained_if_let_missing_branch/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/chained_if_let_missing_branch/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/chained_if_let_missing_branch/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/enum_if_let/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/enum_if_let/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/enum_if_let/src/main.sw
Labels: bug, P: critical, compiler: parser

#2343 Fix utf8 related bug in computing window for errors and warnings.
  forc-util/src/lib.rs
  test/src/e2e_vm_tests/test_programs/should_fail/utf_chars/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/utf_chars/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/utf_chars/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/utf_chars/test.toml
Labels: bug, forc

#2330 Simplify function IR generation
  sway-core/src/ir_generation/const_eval.rs
  sway-core/src/ir_generation/convert.rs
  sway-core/src/ir_generation/function.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/function_application.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression_variant.rs
  sway-ir/src/context.rs
  sway-lsp/src/core/traverse_typed_tree.rs
  test/src/e2e_vm_tests/test_programs/should_fail/storage_conflict/test.toml
  test/src/ir_generation/tests/conflicting_fns.sw
  test/src/ir_generation/tests/ret_unit.sw
Labels: code quality, compiler: ir

#2315 Add a new `__gtf` intrinsic
  sway-core/src/asm_generation/from_ir.rs
  sway-core/src/asm_lang/allocated_ops.rs
  sway-core/src/asm_lang/mod.rs
  sway-core/src/asm_lang/virtual_ops.rs
  sway-core/src/ir_generation/function.rs
  sway-core/src/semantic_analysis/ast_node/expression/intrinsic_function.rs
  sway-ir/src/error.rs
  sway-ir/src/instruction.rs
  sway-ir/src/optimize/inline.rs
  sway-ir/src/parser.rs
  sway-ir/src/printer.rs
  sway-ir/src/verify.rs
  sway-parse/src/intrinsics.rs
  test/src/e2e_vm_tests/test_programs/should_pass/language/gtf_intrinsic/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/gtf_intrinsic/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/gtf_intrinsic/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/language/gtf_intrinsic/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/gtf_intrinsic/test.toml
  test/src/ir_generation/tests/gtf.sw
Labels: compiler: ir, language feature, P: critical, compiler: frontend, compiler: parser, compiler: codegen

#2352 Remove `StorageVec` from missing features in the Sway Book
  docs/src/reference/known_issues_and_workarounds.md
Labels: The Sway Book

#2354 Fix `Span` end for unclosed multiline comments and unclosed string literals
  sway-parse/src/token.rs
  test/src/e2e_vm_tests/test_programs/should_fail/unclosed_multiline_comment/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/unclosed_multiline_comment/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/unclosed_multiline_comment/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/unclosed_multiline_comment/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/unclosed_string_literal/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/unclosed_string_literal/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/unclosed_string_literal/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/unclosed_string_literal/test.toml
Labels: bug, compiler: parser

#2359 Fix lexing of multiline comments to include the trailing '/'
  sway-fmt-v2/src/utils/comments.rs
  sway-parse/src/token.rs
Labels: bug, P: critical, compiler: parser

#2346 Parse tokens from all dependencies instead of single files in the language server
  sway-lsp/src/capabilities/completion.rs
  sway-lsp/src/capabilities/document_symbol.rs
  sway-lsp/src/capabilities/file_sync.rs
  sway-lsp/src/capabilities/formatting.rs
  sway-lsp/src/capabilities/go_to.rs
  sway-lsp/src/capabilities/highlight.rs
  sway-lsp/src/capabilities/hover.rs
  sway-lsp/src/capabilities/mod.rs
  sway-lsp/src/capabilities/rename.rs
  sway-lsp/src/capabilities/semantic_tokens.rs
  sway-lsp/src/capabilities/text_sync.rs
  sway-lsp/src/core/document.rs
  sway-lsp/src/core/session.rs
  sway-lsp/src/core/token.rs
  sway-lsp/src/core/traverse_parse_tree.rs
  sway-lsp/src/core/traverse_typed_tree.rs
  sway-lsp/src/server.rs
  sway-lsp/src/utils/common.rs
  sway-lsp/src/utils/debug.rs
Labels: language server

#2285 Move `std::assert::require` to `std::revert::require`
  examples/identity/src/main.sw
  sway-lib-std/src/assert.sw
  sway-lib-std/src/lib.sw
  sway-lib-std/src/revert.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/require/src/main.sw
  test/src/sdk-harness/test_artifacts/methods_contract/src/main.sw
Labels: lib: std, breaking

#2311 Inserting Comments
  Cargo.lock
  sway-fmt-v2/Cargo.toml
  sway-fmt-v2/src/error.rs
  sway-fmt-v2/src/fmt.rs
  sway-fmt-v2/src/items/item_abi.rs
  sway-fmt-v2/src/items/item_const.rs
  sway-fmt-v2/src/items/item_enum.rs
  sway-fmt-v2/src/items/item_fn.rs
  sway-fmt-v2/src/items/item_impl.rs
  sway-fmt-v2/src/items/item_storage.rs
  sway-fmt-v2/src/items/item_struct.rs
  sway-fmt-v2/src/items/item_trait.rs
  sway-fmt-v2/src/items/item_use.rs
  sway-fmt-v2/src/utils/attribute.rs
  sway-fmt-v2/src/utils/comments.rs
  sway-fmt-v2/src/utils/expr.rs
  sway-fmt-v2/src/utils/item.rs
  sway-fmt-v2/src/utils/literal.rs
  sway-fmt-v2/src/utils/path.rs
  sway-fmt-v2/src/utils/pattern.rs
  sway-fmt-v2/src/utils/program_type.rs
  sway-fmt-v2/src/utils/punctuated.rs
  sway-fmt-v2/src/utils/statement.rs
  sway-fmt-v2/src/utils/ty.rs
Labels: enhancement, big, formatter

#2380 Return the local struct Span as a new field on `TypedExpressionVariant::StructExpression`
  sway-core/src/control_flow_analysis/dead_code_analysis.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression_variant.rs
  sway-lsp/src/core/traverse_typed_tree.rs
Labels: compiler: frontend

#2388 Store the enum instantiation span within the EnumInstantiation variant
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/enum_instantiation.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression_variant.rs
Labels: language server, compiler: frontend

#2389 Set the CallPath prefix of `FunctionApplication` to call_path_binding suffix
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/method_application.rs
Labels: language server, compiler: frontend

#2378 Fix concurrency bug in ConcurrentSlab.replace.
  sway-core/src/concurrent_slab.rs
  test/src/e2e_vm_tests/test_programs/should_pass/language/contract_caller_as_ret/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/contract_caller_as_ret/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/contract_caller_as_ret/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/language/contract_caller_as_ret/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/contract_caller_as_ret/test.toml
Labels: bug, compiler: frontend

#2370 "Common Collections" in the Sway Book
  docs/src/SUMMARY.md
  docs/src/blockchain-development/storage.md
  docs/src/common-collections/index.md
  docs/src/common-collections/storage_map.md
  docs/src/common-collections/storage_vec.md
  docs/src/common-collections/vec.md
  docs/src/reference/known_issues_and_workarounds.md
  examples/storage_map/src/main.sw
  examples/storage_vec/Forc.lock
  examples/storage_vec/Forc.toml
  examples/storage_vec/src/main.sw
  examples/vec/Forc.lock
  examples/vec/Forc.toml
  examples/vec/src/main.sw
Labels: The Sway Book

#2394 Generalise IR metadata.
  sway-core/src/asm_generation/from_ir.rs
  sway-core/src/ir_generation/compile.rs
  sway-core/src/ir_generation/const_eval.rs
  sway-core/src/ir_generation/convert.rs
  sway-core/src/ir_generation/function.rs
  sway-core/src/ir_generation/purity.rs
  sway-core/src/lib.rs
  sway-core/src/metadata.rs
  sway-core/src/parse_tree/declaration/function/purity.rs
  sway-core/src/semantic_analysis/ast_node/declaration/storage.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/function_application.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/method_application.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression_variant.rs
  sway-core/tests/ir_to_asm/get_storage_key.ir
  sway-ir/src/asm.rs
  sway-ir/src/block.rs
  sway-ir/src/constant.rs
  sway-ir/src/context.rs
  sway-ir/src/error.rs
  sway-ir/src/function.rs
  sway-ir/src/instruction.rs
  sway-ir/src/metadata.rs
  sway-ir/src/optimize/constants.rs
  sway-ir/src/optimize/inline.rs
  sway-ir/src/parser.rs
  sway-ir/src/printer.rs
  sway-ir/src/value.rs
  sway-ir/src/verify.rs
  sway-ir/tests/inline/get_storage_key.ir
  sway-ir/tests/serialize/metadata.ir
  test/src/ir_generation/mod.rs
  test/src/ir_generation/tests/return_in_while_loop.sw
  test/src/ir_generation/tests/storage_metadata.sw
Labels: code quality, compiler: ir

#2395 Check for function parameters with an already used identifier.
  sway-core/src/convert_parse_tree.rs
  test/src/e2e_vm_tests/test_programs/should_fail/same_named_fn_params/.gitignore
  test/src/e2e_vm_tests/test_programs/should_fail/same_named_fn_params/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/same_named_fn_params/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/same_named_fn_params/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/same_named_fn_params/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/abi_with_generic_types/src/main.sw
Labels: bug, P: critical, compiler: frontend

#2393 Bump to `v0.19.0`
  Cargo.lock
  forc-pkg/Cargo.toml
  forc-plugins/forc-explore/Cargo.toml
  forc-plugins/forc-fmt-v2/Cargo.toml
  forc-plugins/forc-fmt/Cargo.toml
  forc-plugins/forc-lsp/Cargo.toml
  forc-util/Cargo.toml
  forc/Cargo.toml
  sway-core/Cargo.toml
  sway-fmt-v2/Cargo.toml
  sway-fmt/Cargo.toml
  sway-ir/Cargo.toml
  sway-lsp/Cargo.toml
  sway-parse/Cargo.toml
  sway-types/Cargo.toml
  sway-utils/Cargo.toml
Labels: release

#2371 Provide intrinsic `__addr_of`.
  sway-core/src/asm_generation/from_ir.rs
  sway-core/src/error.rs
  sway-core/src/ir_generation/function.rs
  sway-core/src/semantic_analysis/ast_node/expression/intrinsic_function.rs
  sway-core/src/type_engine/type_info.rs
  sway-ir/src/error.rs
  sway-ir/src/instruction.rs
  sway-ir/src/optimize/inline.rs
  sway-ir/src/parser.rs
  sway-ir/src/printer.rs
  sway-ir/src/verify.rs
  sway-ir/tests/serialize/intrinsic_addr_of.ir
  sway-parse/src/intrinsics.rs
  test/src/e2e_vm_tests/test_programs/should_fail/addrof_intrinsic/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/addrof_intrinsic/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/addrof_intrinsic/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_fail/addrof_intrinsic/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/addrof_intrinsic/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/addrof_intrinsic/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/addrof_intrinsic/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/addrof_intrinsic/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/language/addrof_intrinsic/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/addrof_intrinsic/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/mem/src/main.sw
Labels: enhancement, compiler

#2406 Forc init appends to .gitignore rather than overriding it
  forc/src/ops/forc_init.rs
Labels: bug, forc

#2409 Collect more tokens in the language server and store definitions
  sway-core/src/parse_tree/declaration/function.rs
  sway-core/src/parse_tree/declaration/struct.rs
  sway-core/src/semantic_analysis/ast_node/declaration.rs
  sway-core/src/semantic_analysis/ast_node/declaration/function.rs
  sway-core/src/semantic_analysis/ast_node/declaration/function/function_parameter.rs
  sway-core/src/semantic_analysis/ast_node/declaration/impl_trait.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-lsp/src/capabilities/document_symbol.rs
  sway-lsp/src/capabilities/hover.rs
  sway-lsp/src/core/session.rs
  sway-lsp/src/core/token.rs
  sway-lsp/src/core/traverse_parse_tree.rs
  sway-lsp/src/core/traverse_typed_tree.rs
  sway-lsp/src/server.rs
  sway-lsp/src/utils/debug.rs
  sway-lsp/src/utils/token.rs
Labels: language server

#2416 Refactor `sway-fmt-v2`: remove and implement old todos & add where comment handling & code clean-up
  sway-fmt-v2/src/fmt.rs
  sway-fmt-v2/src/items/item_abi.rs
  sway-fmt-v2/src/items/item_const.rs
  sway-fmt-v2/src/items/item_enum.rs
  sway-fmt-v2/src/items/item_fn.rs
  sway-fmt-v2/src/items/item_impl.rs
  sway-fmt-v2/src/items/item_storage.rs
  sway-fmt-v2/src/items/item_struct.rs
  sway-fmt-v2/src/items/item_trait.rs
  sway-fmt-v2/src/utils/attribute.rs
  sway-fmt-v2/src/utils/expr.rs
  sway-fmt-v2/src/utils/path.rs
  sway-fmt-v2/src/utils/statement.rs
  sway-fmt-v2/src/utils/ty.rs
  sway-fmt-v2/src/utils/where_clause.rs
Labels: enhancement, forc, code quality, formatter

#2418 Rely on `is_copy_type` to lower `insert_element`/`extract_element` into asm instead of type size
  sway-core/src/asm_generation/from_ir.rs
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/array_of_structs_caller/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/test_abis/array_of_structs_abi/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/array_of_structs_contract/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/array_of_structs_contract/src/main.sw
Labels: bug, P: critical, compiler: codegen

#2414 Fix parse tree regression handling while loop body implicit returns.
  sway-core/src/convert_parse_tree.rs
  test/src/e2e_vm_tests/test_programs/should_fail/while_implicit_ret/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/while_implicit_ret/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/while_implicit_ret/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/while_implicit_ret/test.toml
Labels: bug, compiler, P: critical, compiler: frontend, compiler: parser

#2431 General code quality enhancements to the standard library
  sway-lib-std/src/assert.sw
  sway-lib-std/src/chain/auth.sw
  sway-lib-std/src/context.sw
  sway-lib-std/src/context/call_frames.sw
  sway-lib-std/src/ecr.sw
  sway-lib-std/src/flags.sw
  sway-lib-std/src/mem.sw
  sway-lib-std/src/option.sw
  sway-lib-std/src/reentrancy.sw
  sway-lib-std/src/revert.sw
  sway-lib-std/src/storage.sw
  sway-lib-std/src/token.sw
  sway-lib-std/src/tx.sw
  sway-lib-std/src/u128.sw
  sway-lib-std/src/u256.sw
  sway-lib-std/src/vec.sw
  sway-lib-std/src/vm/evm/ecr.sw
Labels: lib: std, code quality
