Repository FuelLabs/sway, pull requests merged in 2022-09, with the labels that each got.

#2675 Make the `DeclarationEngine` a `lazy_static` as a semi-temporary bandaid
  sway-core/src/concurrent_slab.rs
  sway-core/src/declaration_engine/declaration_engine.rs
  sway-core/src/declaration_engine/declaration_id.rs
  sway-core/src/declaration_engine/declaration_wrapper.rs
  sway-core/src/error.rs
  sway-core/src/ir_generation.rs
  sway-core/src/ir_generation/compile.rs
  sway-core/src/lib.rs
  sway-core/src/parse_tree/visibility.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/namespace/module.rs
  sway-core/src/semantic_analysis/program.rs
  sway-core/src/semantic_analysis/type_check_context.rs
  sway-core/src/type_system/type_engine.rs
  sway-core/src/type_system/type_id.rs
Labels: compiler: frontend

#2673 Bump to `v0.22.0`
  Cargo.lock
  forc-pkg/Cargo.toml
  forc-plugins/forc-client/Cargo.toml
  forc-plugins/forc-explore/Cargo.toml
  forc-plugins/forc-fmt-v2/Cargo.toml
  forc-plugins/forc-fmt/Cargo.toml
  forc-plugins/forc-lsp/Cargo.toml
  forc-util/Cargo.toml
  forc/Cargo.toml
  sway-ast/Cargo.toml
  sway-core/Cargo.toml
  sway-fmt-v2/Cargo.toml
  sway-fmt/Cargo.toml
  sway-ir/Cargo.toml
  sway-lsp/Cargo.toml
  sway-parse/Cargo.toml
  sway-types/Cargo.toml
  sway-utils/Cargo.toml
Labels: release

#2684 Remove unnecessary logs in the standard library
  sway-lib-std/src/inputs.sw
  sway-lib-std/src/outputs.sw
Labels: bug, lib: std

#2685 Bump to `v0.22.1`
  Cargo.lock
  forc-pkg/Cargo.toml
  forc-plugins/forc-client/Cargo.toml
  forc-plugins/forc-explore/Cargo.toml
  forc-plugins/forc-fmt-v2/Cargo.toml
  forc-plugins/forc-fmt/Cargo.toml
  forc-plugins/forc-lsp/Cargo.toml
  forc-util/Cargo.toml
  forc/Cargo.toml
  sway-ast/Cargo.toml
  sway-core/Cargo.toml
  sway-fmt-v2/Cargo.toml
  sway-fmt/Cargo.toml
  sway-ir/Cargo.toml
  sway-lsp/Cargo.toml
  sway-parse/Cargo.toml
  sway-types/Cargo.toml
  sway-utils/Cargo.toml
Labels: release

#2678 Add storage to the `DeclarationEngine`
  sway-core/src/control_flow_analysis/dead_code_analysis.rs
  sway-core/src/declaration_engine/declaration_engine.rs
  sway-core/src/declaration_engine/declaration_wrapper.rs
  sway-core/src/declaration_engine/mod.rs
  sway-core/src/error.rs
  sway-core/src/lib.rs
  sway-core/src/semantic_analysis/ast_node/declaration.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/method_application.rs
  sway-core/src/semantic_analysis/ast_node/mod.rs
  sway-core/src/semantic_analysis/namespace/items.rs
  sway-core/src/semantic_analysis/program.rs
  sway-core/src/semantic_analysis/storage_only_types.rs
  sway-lsp/src/core/traverse_typed_tree.rs
Labels: compiler: frontend

#2629 feat: sign forc-deploy transactions
  Cargo.lock
  forc-plugins/forc-client/Cargo.toml
  forc-plugins/forc-client/src/ops/deploy/cmd.rs
  forc-plugins/forc-client/src/ops/deploy/op.rs
  forc-plugins/forc-client/src/ops/mod.rs
  forc-plugins/forc-client/src/ops/parameters.rs
  forc-plugins/forc-client/src/ops/run/cmd.rs
  forc-plugins/forc-client/src/ops/run/mod.rs
  forc-plugins/forc-client/src/ops/run/op.rs
  test/src/e2e_vm_tests/harness.rs
Labels: enhancement, forc

#2682 Add the `CopyTypes` trait to `DeclarationId`
  sway-core/src/declaration_engine/declaration_id.rs
  sway-core/src/declaration_engine/declaration_wrapper.rs
Labels: compiler: frontend

#2692 fix: Unformatted comment spans add extra newline
  sway-fmt-v2/src/formatter/mod.rs
  sway-fmt-v2/src/items/item_trait.rs
  sway-fmt-v2/src/utils/map/newline.rs
Labels: bug, formatter

#2697 feat: add basic comment context formatting
  sway-fmt-v2/src/formatter/mod.rs
  sway-fmt-v2/src/utils/map/comments.rs
Labels: bug, enhancement, formatter

#2698 Merge #2669 (swayfmt replacement PR) with `master` including newline formatting fixes
  Cargo.lock
  examples/break_and_continue/src/main.sw
  examples/enums/src/basic_enum.sw
  examples/match_statements/src/main.sw
  examples/storage_map/src/main.sw
  examples/storage_variables/src/main.sw
  examples/storage_vec/src/main.sw
  examples/structs/src/data_structures.sw
  examples/vec/src/main.sw
  forc-plugins/forc-client/Cargo.toml
  forc-plugins/forc-client/src/ops/deploy/cmd.rs
  forc-plugins/forc-client/src/ops/deploy/op.rs
  forc-plugins/forc-client/src/ops/mod.rs
  forc-plugins/forc-client/src/ops/parameters.rs
  forc-plugins/forc-client/src/ops/run/cmd.rs
  forc-plugins/forc-client/src/ops/run/mod.rs
  forc-plugins/forc-client/src/ops/run/op.rs
  sway-core/src/declaration_engine/declaration_id.rs
  sway-core/src/declaration_engine/declaration_wrapper.rs
  sway-fmt/src/formatter/mod.rs
  sway-fmt/src/items/item_trait.rs
  sway-fmt/src/utils/map/comments.rs
  sway-fmt/src/utils/map/newline.rs
  test/src/e2e_vm_tests/harness.rs
Labels: forc, formatter

#2701 Bump to `fuels v0.22.0` and remove the "-flat" from the name of the JSON ABI file
  forc-pkg/src/pkg.rs
  forc/src/utils/defaults.rs
  test/src/sdk-harness/Cargo.toml
  test/src/sdk-harness/test_projects/auth/mod.rs
  test/src/sdk-harness/test_projects/call_frames/mod.rs
  test/src/sdk-harness/test_projects/context/mod.rs
  test/src/sdk-harness/test_projects/evm/mod.rs
  test/src/sdk-harness/test_projects/exponentiation/mod.rs
  test/src/sdk-harness/test_projects/hashing/mod.rs
  test/src/sdk-harness/test_projects/methods/mod.rs
  test/src/sdk-harness/test_projects/option_field_order/mod.rs
  test/src/sdk-harness/test_projects/reentrancy/mod.rs
  test/src/sdk-harness/test_projects/registers/mod.rs
  test/src/sdk-harness/test_projects/storage/mod.rs
  test/src/sdk-harness/test_projects/storage_map/mod.rs
  test/src/sdk-harness/test_projects/storage_vec/array/utils.rs
  test/src/sdk-harness/test_projects/storage_vec/b256/utils.rs
  test/src/sdk-harness/test_projects/storage_vec/bool/utils.rs
  test/src/sdk-harness/test_projects/storage_vec/enum/utils.rs
  test/src/sdk-harness/test_projects/storage_vec/str/utils.rs
  test/src/sdk-harness/test_projects/storage_vec/struct/utils.rs
  test/src/sdk-harness/test_projects/storage_vec/tuple/utils.rs
  test/src/sdk-harness/test_projects/storage_vec/u16/utils.rs
  test/src/sdk-harness/test_projects/storage_vec/u32/utils.rs
  test/src/sdk-harness/test_projects/storage_vec/u64/utils.rs
  test/src/sdk-harness/test_projects/storage_vec/u8/utils.rs
  test/src/sdk-harness/test_projects/token_ops/mod.rs
  test/src/sdk-harness/test_projects/tx_fields/mod.rs
Labels: forc, testing, ABI

#2592 Allow script main fns to have args
  Cargo.lock
  sway-core/src/asm_generation/from_ir.rs
  sway-core/src/error.rs
  sway-core/src/semantic_analysis/program.rs
  test/Cargo.toml
  test/src/e2e_vm_tests/harness.rs
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/should_fail/main_args/main_args_mutation/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/main_args/main_args_mutation/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/main_args/main_args_mutation/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_fail/main_args/main_args_mutation/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/main_args/main_args_mutation/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/main_should_not_have_args/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/main_should_not_have_args/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/main_should_not_have_args/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/main_should_not_have_args/src/pred.sw
  test/src/e2e_vm_tests/test_programs/should_fail/main_should_not_have_args/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/main_args/main_args_copy/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/main_args/main_args_copy/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/main_args/main_args_copy/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/language/main_args/main_args_copy/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/main_args/main_args_copy/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/main_args/main_args_copy_copy/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/main_args/main_args_copy_copy/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/main_args/main_args_copy_copy/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/language/main_args/main_args_copy_copy/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/main_args/main_args_copy_copy/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/main_args/main_args_empty/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/main_args/main_args_empty/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/main_args/main_args_empty/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/language/main_args/main_args_empty/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/main_args/main_args_empty/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/main_args/main_args_predicate/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/main_args/main_args_predicate/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/main_args/main_args_predicate/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/language/main_args/main_args_predicate/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/main_args/main_args_predicate/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/main_args/main_args_ref/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/main_args/main_args_ref/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/main_args/main_args_ref/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/language/main_args/main_args_ref/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/main_args/main_args_ref/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/main_args/main_args_ref_copy/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/main_args/main_args_ref_copy/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/main_args/main_args_ref_copy/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/language/main_args/main_args_ref_copy/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/main_args/main_args_ref_copy/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/main_args/main_args_ref_ref/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/main_args/main_args_ref_ref/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/main_args/main_args_ref_ref/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/language/main_args/main_args_ref_ref/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/main_args/main_args_ref_ref/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/main_args/main_args_various_types/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/main_args/main_args_various_types/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/main_args/main_args_various_types/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/language/main_args/main_args_various_types/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/main_args/main_args_various_types/test.toml
Labels: enhancement, compiler, language feature

#2712 fix: Formatter removes comments at the beginning of the file
  examples/subcurrency/src/main.sw
  examples/wallet_abi/src/main.sw
  examples/wallet_smart_contract/src/main.sw
  swayfmt/src/formatter/mod.rs
  swayfmt/src/module/mod.rs
  swayfmt/src/utils/map/byte_span.rs
  swayfmt/src/utils/map/comments.rs
Labels: bug, formatter

#2703 Bump to `v0.23.0`
  Cargo.lock
  forc-pkg/Cargo.toml
  forc-plugins/forc-client/Cargo.toml
  forc-plugins/forc-explore/Cargo.toml
  forc-plugins/forc-fmt/Cargo.toml
  forc-plugins/forc-lsp/Cargo.toml
  forc-util/Cargo.toml
  forc/Cargo.toml
  sway-ast/Cargo.toml
  sway-core/Cargo.toml
  sway-ir/Cargo.toml
  sway-lsp/Cargo.toml
  sway-parse/Cargo.toml
  sway-types/Cargo.toml
  sway-utils/Cargo.toml
  swayfmt/Cargo.toml
Labels: release

#2715 fix tag verification for swayfmt
  .github/workflows/ci.yml
Labels: ci

#2656 doc: document forc-client forc-wallet interactions
  docs/src/forc_client.md
Labels: forc, documentation

#2718 Remove `println` from debugging `codeblock`
  swayfmt/src/utils/language/expr/code_block.rs
Labels: forc, code quality, formatter

#2676 feat: sign forc-run transactions
  forc-plugins/forc-client/src/ops/run/cmd.rs
  forc-plugins/forc-client/src/ops/run/op.rs
  test/src/e2e_vm_tests/harness.rs
Labels: enhancement, forc

#2727 Fixes `Shape::width` bleed from file to file
  swayfmt/src/formatter/mod.rs
  swayfmt/src/items/item_fn/mod.rs
Labels: bug, forc, formatter

#2683 Add traits to the `DeclarationEngine`
  sway-core/src/control_flow_analysis/dead_code_analysis.rs
  sway-core/src/declaration_engine/declaration_engine.rs
  sway-core/src/declaration_engine/mod.rs
  sway-core/src/lib.rs
  sway-core/src/parse_tree/declaration/trait.rs
  sway-core/src/semantic_analysis/ast_node/declaration.rs
  sway-core/src/semantic_analysis/ast_node/declaration/impl_trait.rs
  sway-core/src/semantic_analysis/ast_node/declaration/trait.rs
  sway-core/src/semantic_analysis/ast_node/mod.rs
  sway-core/src/semantic_analysis/module.rs
  sway-core/src/semantic_analysis/namespace/module.rs
  sway-core/src/semantic_analysis/program.rs
  sway-core/src/semantic_analysis/storage_only_types.rs
  sway-lsp/src/capabilities/hover.rs
  sway-lsp/src/core/traverse_typed_tree.rs
Labels: compiler: frontend

#2729 doc: added a section about interaction with the testnet
  docs/src/forc_client.md
Labels: forc, documentation

#2730 Bump to `v0.24.0`
  Cargo.lock
  forc-pkg/Cargo.toml
  forc-plugins/forc-client/Cargo.toml
  forc-plugins/forc-explore/Cargo.toml
  forc-plugins/forc-fmt/Cargo.toml
  forc-plugins/forc-lsp/Cargo.toml
  forc-util/Cargo.toml
  forc/Cargo.toml
  sway-ast/Cargo.toml
  sway-core/Cargo.toml
  sway-ir/Cargo.toml
  sway-lsp/Cargo.toml
  sway-parse/Cargo.toml
  sway-types/Cargo.toml
  sway-utils/Cargo.toml
  swayfmt/Cargo.toml
Labels: release

#2735 Removing some unnecessary opcodes in the parser
  sway-parse/src/expr/op_code.rs
Labels: compiler: parser

#2737 Add `--unsigned` to `forc deploy` in the `Getting Started` chapter
  docs/src/introduction/overview.md
Labels: The Sway Book

#2738 Update the script example in the Sway Book to use an actual example
  docs/src/sway-program-types/scripts.md
Labels: The Sway Book

#2744 Disable the generation of logged types in the JSON ABI by default
  forc-pkg/src/manifest.rs
  forc-pkg/src/pkg.rs
  forc-plugins/forc-client/src/ops/deploy/cmd.rs
  forc-plugins/forc-client/src/ops/deploy/op.rs
  forc-plugins/forc-client/src/ops/run/cmd.rs
  forc-plugins/forc-client/src/ops/run/op.rs
  forc/src/cli/commands/build.rs
  forc/src/ops/forc_build.rs
  sway-core/src/build_config.rs
  sway-core/src/lib.rs
  test/src/e2e_vm_tests/test_programs/should_pass/language/logging/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/require/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/multiple_impl/json_abi_oracle.json
Labels: forc, P: critical, ABI

#2749 Fix bad refactor
  sway-core/src/control_flow_analysis/dead_code_analysis.rs
Labels: P: critical

#2747 Bump to `v0.24.1`
  Cargo.lock
  forc-pkg/Cargo.toml
  forc-plugins/forc-client/Cargo.toml
  forc-plugins/forc-explore/Cargo.toml
  forc-plugins/forc-fmt/Cargo.toml
  forc-plugins/forc-lsp/Cargo.toml
  forc-util/Cargo.toml
  forc/Cargo.toml
  sway-ast/Cargo.toml
  sway-core/Cargo.toml
  sway-ir/Cargo.toml
  sway-lsp/Cargo.toml
  sway-parse/Cargo.toml
  sway-types/Cargo.toml
  sway-utils/Cargo.toml
  swayfmt/Cargo.toml
Labels: release

#2710 Add abi declarations to the `DeclarationEngine`
  sway-core/src/control_flow_analysis/dead_code_analysis.rs
  sway-core/src/declaration_engine/declaration_engine.rs
  sway-core/src/declaration_engine/declaration_wrapper.rs
  sway-core/src/declaration_engine/mod.rs
  sway-core/src/semantic_analysis/ast_node/declaration.rs
  sway-core/src/semantic_analysis/ast_node/declaration/impl_trait.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/ast_node/mod.rs
  sway-core/src/semantic_analysis/storage_only_types.rs
  sway-lsp/src/core/traverse_typed_tree.rs
Labels: compiler: frontend

#2741 Minor enhancements to the Sway Book
  docs/src/SUMMARY.md
  docs/src/advanced/generic_types.md
  docs/src/advanced/trait_constraints.md
  docs/src/advanced/traits.md
  docs/src/basics/comments_and_logging.md
  docs/src/basics/control_flow.md
  docs/src/basics/methods_and_associated_functions.md
  docs/src/frontend/typescript_sdk.md
  docs/src/introduction/overview.md
  docs/src/reference/known_issues_and_workarounds.md
  docs/src/testing/testing-with-rust.md
  examples/counter/src/main.sw
  examples/identity/src/main.sw
  examples/liquidity_pool/src/main.sw
  examples/match_statements/src/main.sw
  examples/msg_sender/src/main.sw
  examples/ref_mut_params/src/main.sw
  examples/storage_example/src/main.sw
  examples/storage_map/src/main.sw
  examples/storage_variables/src/main.sw
  examples/storage_vec/src/main.sw
  examples/subcurrency/src/main.sw
  examples/vec/src/main.sw
  examples/wallet_abi/src/main.sw
  examples/wallet_smart_contract/src/main.sw
Labels: code quality, The Sway Book

#2742 Remove old, no-longer-necessary mdbook patch from workspace manifest
  Cargo.lock
  Cargo.toml
Labels: bug, code quality

#2579 Adds `swayfmt` README/CONTRIBUTING
  swayfmt/CONTRIBUTING.md
  swayfmt/README.md
Labels: forc, formatter, documentation

#2714 Add constants to the `DeclarationEngine`
  sway-core/src/control_flow_analysis/dead_code_analysis.rs
  sway-core/src/declaration_engine/declaration_engine.rs
  sway-core/src/declaration_engine/declaration_wrapper.rs
  sway-core/src/ir_generation/compile.rs
  sway-core/src/ir_generation/const_eval.rs
  sway-core/src/ir_generation/function.rs
  sway-core/src/semantic_analysis/ast_node/declaration.rs
  sway-core/src/semantic_analysis/ast_node/declaration/function/function_parameter.rs
  sway-core/src/semantic_analysis/ast_node/declaration/impl_trait.rs
  sway-core/src/semantic_analysis/ast_node/expression/intrinsic_function.rs
  sway-core/src/semantic_analysis/ast_node/expression/match_expression/typed/typed_match_branch.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/ast_node/mod.rs
  sway-core/src/semantic_analysis/namespace/module.rs
  sway-core/src/semantic_analysis/program.rs
  sway-core/src/semantic_analysis/storage_only_types.rs
  sway-core/src/type_system/collect_types_metadata.rs
  sway-core/src/type_system/type_id.rs
  sway-lsp/src/core/traverse_typed_tree.rs
  sway-lsp/src/utils/token.rs
Labels: compiler: frontend

#2752 Add support for the `TIME` instruction
  sway-ast/src/expr/op_code.rs
  sway-core/src/asm_lang/allocated_ops.rs
  sway-core/src/asm_lang/mod.rs
  sway-core/src/asm_lang/virtual_ops.rs
  sway-lib-std/src/block.sw
  sway-parse/src/expr/op_code.rs
  test/src/sdk-harness/test_artifacts/block_test_abi/.gitignore
  test/src/sdk-harness/test_artifacts/block_test_abi/Forc.lock
  test/src/sdk-harness/test_artifacts/block_test_abi/Forc.toml
  test/src/sdk-harness/test_artifacts/block_test_abi/src/main.sw
  test/src/sdk-harness/test_projects/block/.gitignore
  test/src/sdk-harness/test_projects/block/Forc.lock
  test/src/sdk-harness/test_projects/block/Forc.toml
  test/src/sdk-harness/test_projects/block/mod.rs
  test/src/sdk-harness/test_projects/block/src/main.sw
  test/src/sdk-harness/test_projects/harness.rs
Labels: lib: std, compiler: parser, compiler: codegen

#2754 Improve parameter signature checking for trait functions.
  sway-core/src/convert_parse_tree.rs
  sway-core/src/error.rs
  sway-core/src/parse_tree/declaration/function.rs
  sway-core/src/semantic_analysis/ast_node/declaration/function.rs
  sway-core/src/semantic_analysis/ast_node/declaration/function/function_parameter.rs
  sway-core/src/semantic_analysis/ast_node/declaration/impl_trait.rs
  sway-core/src/semantic_analysis/ast_node/declaration/trait.rs
  sway-core/src/semantic_analysis/ast_node/mod.rs
  test/src/e2e_vm_tests/test_programs/should_fail/abi_ref_mut/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/abi_ref_mut/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/abi_ref_mut/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/abi_ref_mut/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/trait_method_signature_mismatch/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/trait_method_signature_mismatch/test.toml
Labels: compiler: frontend

#2706 Add `impl` Self's and `impl` trait's to the `DeclarationEngine`
  sway-core/src/control_flow_analysis/analyze_return_paths.rs
  sway-core/src/control_flow_analysis/dead_code_analysis.rs
  sway-core/src/declaration_engine/declaration_engine.rs
  sway-core/src/declaration_engine/declaration_wrapper.rs
  sway-core/src/ir_generation/function.rs
  sway-core/src/semantic_analysis/ast_node/declaration.rs
  sway-core/src/semantic_analysis/ast_node/mod.rs
  sway-core/src/semantic_analysis/module.rs
  sway-core/src/semantic_analysis/program.rs
  sway-core/src/semantic_analysis/storage_only_types.rs
  sway-lsp/src/core/traverse_typed_tree.rs
Labels: compiler: frontend

#2757 Update `Getting Started` to use `run` with `fuel-core`
  docs/src/introduction/overview.md
Labels: The Sway Book

#2713 Add enums to the `DeclarationEngine`
  sway-core/src/control_flow_analysis/dead_code_analysis.rs
  sway-core/src/declaration_engine/declaration_engine.rs
  sway-core/src/declaration_engine/declaration_wrapper.rs
  sway-core/src/declaration_engine/mod.rs
  sway-core/src/ir_generation/function.rs
  sway-core/src/semantic_analysis/ast_node/declaration.rs
  sway-core/src/semantic_analysis/ast_node/expression/match_expression/typed/typed_scrutinee.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/ast_node/mod.rs
  sway-core/src/semantic_analysis/namespace/items.rs
  sway-core/src/semantic_analysis/namespace/module.rs
  sway-core/src/semantic_analysis/namespace/root.rs
  sway-core/src/semantic_analysis/storage_only_types.rs
  sway-core/src/type_system/type_binding.rs
  sway-lsp/src/capabilities/hover.rs
  sway-lsp/src/core/traverse_typed_tree.rs
Labels: compiler: frontend

#2756 Bump to `v0.24.2`
  Cargo.lock
  forc-pkg/Cargo.toml
  forc-plugins/forc-client/Cargo.toml
  forc-plugins/forc-explore/Cargo.toml
  forc-plugins/forc-fmt/Cargo.toml
  forc-plugins/forc-lsp/Cargo.toml
  forc-util/Cargo.toml
  forc/Cargo.toml
  sway-ast/Cargo.toml
  sway-core/Cargo.toml
  sway-ir/Cargo.toml
  sway-lsp/Cargo.toml
  sway-parse/Cargo.toml
  sway-types/Cargo.toml
  sway-utils/Cargo.toml
  swayfmt/Cargo.toml
Labels: release

#2688 Add structs to the declaration engine
  sway-core/src/control_flow_analysis/dead_code_analysis.rs
  sway-core/src/declaration_engine/declaration_engine.rs
  sway-core/src/semantic_analysis/ast_node/declaration.rs
  sway-core/src/semantic_analysis/ast_node/expression/match_expression/typed/typed_scrutinee.rs
  sway-core/src/semantic_analysis/ast_node/mod.rs
  sway-core/src/semantic_analysis/namespace/items.rs
  sway-core/src/semantic_analysis/namespace/root.rs
  sway-core/src/semantic_analysis/storage_only_types.rs
  sway-core/src/type_system/type_binding.rs
  sway-lsp/src/capabilities/hover.rs
  sway-lsp/src/core/traverse_typed_tree.rs
  sway-lsp/src/utils/token.rs
Labels: compiler: frontend

#2743 Extend `simplify-cfg` to remove empty blocks
  sway-ir/src/block.rs
  sway-ir/src/optimize/simplify_cfg.rs
  sway-ir/tests/simplify_cfg/dead_blocks.ir
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_basic_storage/src/main.sw
Labels: compiler: optimization

#2760 Fix JSON ABI for generic tuples in structs
  sway-core/src/type_system/type_info.rs
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/abi_with_generic_types/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/abi_with_generic_types/src/main.sw
Labels: bug, P: critical, ABI

#2751 Recover `class Foo { .. }` as `struct`
  sway-ast/src/keywords.rs
  sway-parse/src/error.rs
  sway-parse/src/item/item_struct.rs
  sway-parse/src/item/mod.rs
  sway-parse/src/keywords.rs
  test/src/e2e_vm_tests/test_programs/should_fail/recover_class_as_struct/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/recover_class_as_struct/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/recover_class_as_struct/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/recover_class_as_struct/test.toml
Labels: enhancement, compiler: frontend, compiler: parser, compiler: ui

#2766 Bump to `v0.24.3`
  Cargo.lock
  forc-pkg/Cargo.toml
  forc-plugins/forc-client/Cargo.toml
  forc-plugins/forc-explore/Cargo.toml
  forc-plugins/forc-fmt/Cargo.toml
  forc-plugins/forc-lsp/Cargo.toml
  forc-util/Cargo.toml
  forc/Cargo.toml
  sway-ast/Cargo.toml
  sway-core/Cargo.toml
  sway-ir/Cargo.toml
  sway-lsp/Cargo.toml
  sway-parse/Cargo.toml
  sway-types/Cargo.toml
  sway-utils/Cargo.toml
  swayfmt/Cargo.toml
Labels: release

#2732 Make `Shape` state changes in `Format` API more robust
  examples/hashing/src/main.sw
  examples/structs/src/main.sw
  swayfmt/src/formatter/mod.rs
  swayfmt/src/formatter/shape.rs
  swayfmt/src/items/item_enum/mod.rs
  swayfmt/src/items/item_fn/mod.rs
  swayfmt/src/items/item_impl/mod.rs
  swayfmt/src/items/item_storage/mod.rs
  swayfmt/src/items/item_struct/mod.rs
  swayfmt/src/items/item_use/mod.rs
  swayfmt/src/utils/language/attribute.rs
  swayfmt/src/utils/language/expr/asm_block.rs
  swayfmt/src/utils/language/expr/conditional.rs
  swayfmt/src/utils/language/expr/mod.rs
  swayfmt/src/utils/language/generics.rs
  swayfmt/src/utils/language/pattern.rs
  swayfmt/src/utils/language/punctuated.rs
  swayfmt/src/utils/language/ty.rs
Labels: enhancement, forc, big, code quality, formatter

#2627 Correctly handle diverging expressions in blocks
  Cargo.lock
  Cargo.toml
  sway-core/src/ir_generation/function.rs
  sway-core/src/semantic_analysis/ast_node/code_block.rs
  sway-core/src/semantic_analysis/ast_node/expression/match_expression/typed/typed_match_branch.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/ast_node/mod.rs
  sway-core/src/type_system/type_info.rs
  sway-ir/Cargo.toml
  sway-ir/src/asm.rs
  sway-ir/src/block.rs
  sway-ir/src/constant.rs
  sway-ir/src/instruction.rs
  sway-ir/src/irtype.rs
  sway-ir/src/lib.rs
  sway-ir/src/parser.rs
  sway-ir/src/pointer.rs
  sway-ir/src/pretty.rs
  sway-ir/src/value.rs
  sway-ir/sway-ir-macros/Cargo.toml
  sway-ir/sway-ir-macros/src/lib.rs
  test/src/e2e_vm_tests/test_programs/should_pass/language/abort_control_flow_good/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/diverging_exprs/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/diverging_exprs/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/diverging_exprs/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/language/diverging_exprs/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/diverging_exprs/test.toml
  test/src/ir_generation/tests/redundant_return.sw
Labels: bug, compiler: ir, compiler: frontend

#2769 Add standard library prelude
  forc-pkg/src/lib.rs
  forc-pkg/src/pkg.rs
  sway-core/src/error.rs
  sway-core/src/semantic_analysis/namespace/items.rs
  sway-core/src/semantic_analysis/namespace/module.rs
  sway-core/src/semantic_analysis/namespace/root.rs
  sway-lib-std/src/lib.sw
  sway-lib-std/src/prelude.sw
  test/src/e2e_vm_tests/test_programs/should_fail/shadow_import/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/shadow_import/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/asm_expr_basic/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/prelude_access/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/prelude_access/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/prelude_access/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/language/prelude_access/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/prelude_access/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/prelude_access2/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/prelude_access2/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/prelude_access2/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/language/prelude_access2/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/prelude_access2/test.toml
Labels: enhancement, forc, lib: std, compiler: frontend

#2771 Add intrinsics for `add`, `sub`, `mul` and `div`
  sway-ast/src/intrinsics.rs
  sway-core/src/asm_generation/from_ir.rs
  sway-core/src/ir_generation/function.rs
  sway-core/src/semantic_analysis/ast_node/expression/intrinsic_function.rs
  sway-core/tests/ir_to_asm/binops.asm
  sway-core/tests/ir_to_asm/binops.ir
  sway-ir/src/error.rs
  sway-ir/src/instruction.rs
  sway-ir/src/optimize/dce.rs
  sway-ir/src/optimize/inline.rs
  sway-ir/src/parser.rs
  sway-ir/src/printer.rs
  sway-ir/src/verify.rs
  sway-lib-core/src/ops.sw
  test/src/e2e_vm_tests/test_programs/should_fail/binop_intrinsics/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/binop_intrinsics/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/binop_intrinsics/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_fail/binop_intrinsics/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/binop_intrinsics/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/binop_intrinsics/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/binop_intrinsics/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/binop_intrinsics/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/language/binop_intrinsics/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/binop_intrinsics/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_basic_storage/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_increment_contract/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/storage_access_caller/src/main.sw
Labels: compiler: ir, language feature, compiler: frontend, compiler: parser, compiler: codegen

#2778 fix contract caller types
  sway-core/src/type_system/type_engine.rs
  sway-core/src/type_system/type_info.rs
  test/src/e2e_vm_tests/test_programs/should_fail/different_contract_caller_types/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/contract_caller_as_type/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/contract_caller_as_type/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/contract_caller_as_type/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/language/contract_caller_as_type/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/contract_caller_as_type/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/contract_caller_dynamic_address/.gitignore
  test/src/e2e_vm_tests/test_programs/should_pass/language/contract_caller_dynamic_address/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/contract_caller_dynamic_address/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/contract_caller_dynamic_address/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/contract_caller_dynamic_address/test.toml
Labels: compiler, compiler: frontend

#2561 Make return into an expression
  sway-core/src/control_flow_analysis/analyze_return_paths.rs
  sway-core/src/control_flow_analysis/dead_code_analysis.rs
  sway-core/src/convert_parse_tree.rs
  sway-core/src/ir_generation/const_eval.rs
  sway-core/src/ir_generation/function.rs
  sway-core/src/parse_tree.rs
  sway-core/src/parse_tree/expression/mod.rs
  sway-core/src/semantic_analysis/ast_node/declaration/impl_trait.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression_variant.rs
  sway-core/src/semantic_analysis/ast_node/mod.rs
  sway-core/src/semantic_analysis/node_dependencies.rs
  sway-core/src/semantic_analysis/storage_only_types.rs
  sway-lsp/src/core/traverse_parse_tree.rs
  sway-lsp/src/core/traverse_typed_tree.rs
  test/src/e2e_vm_tests/test_programs/should_pass/language/const_inits/src/main.sw
Labels: code quality, compiler: frontend, compiler: parser

#2764 Replace colored printlns with tracing
  Cargo.lock
  forc-util/Cargo.toml
  forc-util/src/lib.rs
  test/src/e2e_vm_tests/harness.rs
Labels: forc

#2765 Replace println with tracing [client]
  forc-plugins/forc-client/src/bin/deploy/main.rs
  forc-plugins/forc-client/src/bin/run/main.rs
  forc-plugins/forc-client/src/ops/deploy/op.rs
  forc-plugins/forc-client/src/ops/run/op.rs
Labels: forc

#2787 Fix comments preceding `module_kind`
  swayfmt/src/formatter/mod.rs
  swayfmt/src/utils/map/comments.rs
Labels: bug, forc, formatter

#2783 Prelude docs and updating some examples
  docs/src/common-collections/vec.md
  docs/src/introduction/standard_library.md
  examples/arrays/src/main.sw
  examples/asm_return_tuple_pointer/src/main.sw
  examples/identity/src/abi.sw
  examples/identity/src/main.sw
  examples/liquidity_pool/src/main.sw
  examples/msg_sender/src/main.sw
  examples/native_token/src/main.sw
  examples/ownership/src/main.sw
  examples/ref_mut_params/src/main.sw
  examples/signatures/src/main.sw
  examples/storage_map/src/main.sw
  examples/storage_vec/src/main.sw
  examples/subcurrency/src/main.sw
  examples/vec/src/main.sw
  examples/wallet_abi/src/main.sw
  examples/wallet_contract_caller_script/src/main.sw
  examples/wallet_smart_contract/src/main.sw
Labels: The Sway Book

#2794 0.24.4
  Cargo.lock
  forc-pkg/Cargo.toml
  forc-plugins/forc-client/Cargo.toml
  forc-plugins/forc-explore/Cargo.toml
  forc-plugins/forc-fmt/Cargo.toml
  forc-plugins/forc-lsp/Cargo.toml
  forc-util/Cargo.toml
  forc/Cargo.toml
  sway-ast/Cargo.toml
  sway-core/Cargo.toml
  sway-ir/Cargo.toml
  sway-ir/sway-ir-macros/Cargo.toml
  sway-lsp/Cargo.toml
  sway-parse/Cargo.toml
  sway-types/Cargo.toml
  sway-utils/Cargo.toml
  swayfmt/Cargo.toml
Labels: release

#2781 Extend support for getting the transaction script hash in std::tx
  sway-lib-std/src/tx.sw
  test/src/sdk-harness/test_artifacts/tx_contract/src/main.sw
  test/src/sdk-harness/test_projects/tx_fields/mod.rs
Labels: lib: std

#2795 Fix publishing issue with the `sway-ir-macros` crate due to missing `derive(Debug)`
  sway-ir/sway-ir-macros/Cargo.toml
Labels: bug, compiler: ir, P: critical

#2800 Minor nits in the standard library + fmt
  sway-lib-std/src/address.sw
  sway-lib-std/src/b512.sw
  sway-lib-std/src/block.sw
  sway-lib-std/src/chain/auth.sw
  sway-lib-std/src/context.sw
  sway-lib-std/src/context/call_frames.sw
  sway-lib-std/src/context/registers.sw
  sway-lib-std/src/contract_id.sw
  sway-lib-std/src/ecr.sw
  sway-lib-std/src/identity.sw
  sway-lib-std/src/inputs.sw
  sway-lib-std/src/logging.sw
  sway-lib-std/src/mem.sw
  sway-lib-std/src/option.sw
  sway-lib-std/src/outputs.sw
  sway-lib-std/src/prelude.sw
  sway-lib-std/src/reentrancy.sw
  sway-lib-std/src/result.sw
  sway-lib-std/src/storage.sw
  sway-lib-std/src/token.sw
  sway-lib-std/src/tx.sw
  sway-lib-std/src/u128.sw
  sway-lib-std/src/u256.sw
  sway-lib-std/src/vec.sw
  sway-lib-std/src/vm/evm/ecr.sw
  sway-lib-std/src/vm/evm/evm_address.sw
Labels: lib: std

#2799 Add `Option` and `Result` to the standard library prelude
  docs/src/introduction/standard_library.md
  docs/src/sway-program-types/libraries.md
  examples/identity/src/main.sw
  examples/msg_sender/src/main.sw
  examples/ownership/src/main.sw
  examples/signatures/src/main.sw
  examples/storage_map/src/main.sw
  examples/storage_vec/src/main.sw
  examples/subcurrency/src/main.sw
  examples/vec/src/main.sw
  examples/wallet_smart_contract/src/main.sw
  sway-lib-std/src/prelude.sw
  test/src/e2e_vm_tests/test_programs/should_fail/better_type_error_message/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/better_type_error_message/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/better_type_error_message/test.toml
Labels: lib: std, The Sway Book

#2803 Standard library `README` file
  sway-lib-std/README.md
Labels: documentation

#2807 Remove unwraps in the language server when calling into the declaration engine.
  sway-lsp/src/capabilities/hover.rs
  sway-lsp/src/core/traverse_typed_tree.rs
  sway-lsp/src/utils/token.rs
Labels: language server

#2811 ci: skip publishing/building forc-client crate/bin
  .github/workflows/ci.yml
  .github/workflows/gh-pages.yml
Labels: forc, ci

#2824 feat: handle implicit_std_dep for nightly builds
  forc-pkg/src/manifest.rs
Labels: forc, dependencies

#2830 Apply new clippy lints for Rust v1.64
  sway-core/src/control_flow_analysis/analyze_return_paths.rs
  sway-core/src/ir_generation/const_eval.rs
  sway-core/src/type_system/type_id.rs
  sway-parse/src/parser.rs
Labels: code quality

#2798 Make verbose flag a global option in forc
  forc-plugins/forc-client/src/bin/deploy/main.rs
  forc-plugins/forc-client/src/bin/run/main.rs
  forc-plugins/forc-explore/src/main.rs
  forc-plugins/forc-fmt/src/main.rs
  forc-util/src/lib.rs
  forc/src/cli/commands/init.rs
  forc/src/cli/commands/new.rs
  forc/src/cli/mod.rs
  forc/src/main.rs
  forc/src/ops/forc_init.rs
  test/src/e2e_vm_tests/mod.rs
Labels: forc

#2827 Reduce redundant `TypeId` creation
  sway-core/src/type_system/type_id.rs
Labels: compiler: frontend

#2831 Bump sdk version in stdlib test suite
  forc/src/utils/defaults.rs
  test/src/sdk-harness/Cargo.toml
  test/src/sdk-harness/test_projects/evm/mod.rs
  test/src/sdk-harness/test_projects/hashing/mod.rs
  test/src/sdk-harness/test_projects/logging/mod.rs
  test/src/sdk-harness/test_projects/script_data/mod.rs
  test/src/sdk-harness/test_projects/storage/mod.rs
  test/src/sdk-harness/test_projects/storage_map/mod.rs
  test/src/sdk-harness/test_projects/storage_vec/array/mod.rs
  test/src/sdk-harness/test_projects/storage_vec/array/utils.rs
  test/src/sdk-harness/test_projects/storage_vec/b256/utils.rs
  test/src/sdk-harness/test_projects/storage_vec/str/utils.rs
  test/src/sdk-harness/test_projects/tx_fields/mod.rs
Labels: lib: std, dependencies

#2834 Add some documentation to the type engine.
  sway-core/src/type_system/type_engine.rs
Labels: documentation

#2829 Remove redundant call to `insert_type`
  sway-core/src/concurrent_slab.rs
  sway-core/src/semantic_analysis/namespace/root.rs
  sway-core/src/type_system/type_engine.rs
Labels: code quality, compiler: frontend

#2842 Remove `asm` block via function reuse
  sway-lib-std/src/block.sw
Labels: lib: std, code quality

#2833 Improve `TypeMapping`
  sway-core/src/semantic_analysis/namespace/trait_map.rs
  sway-core/src/type_system/type_argument.rs
  sway-core/src/type_system/type_engine.rs
  sway-core/src/type_system/type_id.rs
  sway-core/src/type_system/type_info.rs
  sway-core/src/type_system/type_mapping.rs
  sway-core/src/type_system/type_parameter.rs
Labels: code quality, compiler: frontend

#2840 Bump to `v0.24.5`
  Cargo.lock
  forc-pkg/Cargo.toml
  forc-plugins/forc-client/Cargo.toml
  forc-plugins/forc-explore/Cargo.toml
  forc-plugins/forc-fmt/Cargo.toml
  forc-plugins/forc-lsp/Cargo.toml
  forc-util/Cargo.toml
  forc/Cargo.toml
  sway-ast/Cargo.toml
  sway-core/Cargo.toml
  sway-ir/Cargo.toml
  sway-ir/sway-ir-macros/Cargo.toml
  sway-lsp/Cargo.toml
  sway-parse/Cargo.toml
  sway-types/Cargo.toml
  sway-utils/Cargo.toml
  swayfmt/Cargo.toml
Labels: release

#2837 Add `set` function to `Vec<T>`
  sway-lib-std/src/vec.sw
  test/src/e2e_vm_tests/test_programs/should_fail/vec_set_index_out_of_bounds/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/vec_set_index_out_of_bounds/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/vec_set_index_out_of_bounds/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/vec_set_index_out_of_bounds/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/vec/src/main.sw
Labels: enhancement, lib: std

#2801 Re-enable formatting in the `lsp`
  sway-lsp/src/core/session.rs
  sway-lsp/src/lib.rs
  sway-lsp/src/server.rs
  sway-lsp/src/sway_config.rs
  swayfmt/src/formatter/mod.rs
Labels: enhancement, forc, language server, formatter

#2366 When --offline flag specified for forc build, attempt to use local git checkouts for git dependencies before failing
  Cargo.lock
  forc-pkg/src/pkg.rs
Labels: enhancement, forc, dependencies

#2846 Remove old unused fn in LSP server
  sway-lsp/src/core/session.rs
Labels: language server, code quality

#2809 Publish error and warning diagnostics when the project cannot be parsed
  sway-lsp/src/server.rs
Labels: language server

#2792 Store attributes in the `ParseProgram` declaration types.
  sway-core/src/convert_parse_tree.rs
  sway-core/src/lib.rs
  sway-core/src/parse_tree/declaration/constant.rs
  sway-core/src/parse_tree/declaration/enum.rs
  sway-core/src/parse_tree/declaration/function.rs
  sway-core/src/parse_tree/declaration/storage.rs
  sway-core/src/parse_tree/declaration/struct.rs
  sway-core/src/parse_tree/declaration/trait.rs
  sway-core/src/semantic_analysis/ast_node/declaration/enum.rs
  sway-core/src/semantic_analysis/ast_node/declaration/struct.rs
  sway-core/src/semantic_analysis/ast_node/mod.rs
  sway-core/src/semantic_analysis/namespace/module.rs
  sway-lsp/src/utils/attributes.rs
  sway-lsp/src/utils/mod.rs
Labels: language server, compiler: frontend

#2340 Signed integers
  sway-lib-std/src/i128.sw
  sway-lib-std/src/i16.sw
  sway-lib-std/src/i256.sw
  sway-lib-std/src/i32.sw
  sway-lib-std/src/i64.sw
  sway-lib-std/src/i8.sw
  sway-lib-std/src/lib.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/i128_test/.gitignore
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/i128_test/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/i128_test/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/i128_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/i16_test/.gitignore
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/i16_test/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/i16_test/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/i16_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/i256_test/.gitignore
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/i256_test/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/i256_test/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/i256_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/i32_test/.gitignore
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/i32_test/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/i32_test/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/i32_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/i64_test/.gitignore
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/i64_test/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/i64_test/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/i64_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/i8_test/.gitignore
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/i8_test/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/i8_test/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/i8_test/src/main.sw
Labels: enhancement, lib: std

#2197 UFP64 type for std library
  sway-lib-std/src/lib.sw
  sway-lib-std/src/math.sw
  sway-lib-std/src/u128.sw
  sway-lib-std/src/ufp64.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/ufp64_div_test/.gitignore
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/ufp64_div_test/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/ufp64_div_test/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/ufp64_div_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/ufp64_exp_test/.gitignore
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/ufp64_exp_test/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/ufp64_exp_test/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/ufp64_exp_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/ufp64_mul_test/.gitignore
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/ufp64_mul_test/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/ufp64_mul_test/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/ufp64_mul_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/ufp64_pow_test/.gitignore
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/ufp64_pow_test/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/ufp64_pow_test/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/ufp64_pow_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/ufp64_root_test/.gitignore
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/ufp64_root_test/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/ufp64_root_test/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/ufp64_root_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/ufp64_test/.gitignore
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/ufp64_test/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/ufp64_test/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/ufp64_test/src/main.sw
Labels: enhancement, lib: std

#2835 Move the `resolve_types` function to the `TypeEngine`
  sway-core/src/control_flow_analysis/analyze_return_paths.rs
  sway-core/src/control_flow_analysis/dead_code_analysis.rs
  sway-core/src/convert_parse_tree.rs
  sway-core/src/ir_generation/convert.rs
  sway-core/src/ir_generation/function.rs
  sway-core/src/ir_generation/types.rs
  sway-core/src/semantic_analysis/ast_node/declaration/function.rs
  sway-core/src/semantic_analysis/ast_node/declaration/impl_trait.rs
  sway-core/src/semantic_analysis/ast_node/expression/intrinsic_function.rs
  sway-core/src/semantic_analysis/namespace/items.rs
  sway-core/src/semantic_analysis/namespace/namespace.rs
  sway-core/src/semantic_analysis/namespace/root.rs
  sway-core/src/semantic_analysis/storage_only_types.rs
  sway-core/src/type_system/mod.rs
  sway-core/src/type_system/type_engine.rs
  sway-core/src/type_system/type_info.rs
Labels: code quality, compiler: frontend

#2860 Better error message when fetching a git dependency failed
  forc-pkg/src/pkg.rs
Labels: enhancement, forc, dependencies

#2866 Re-apply a PR that got written over in a merge conflict
  sway-core/src/type_system/type_engine.rs
Labels: bug, compiler: frontend

#2377 Search locally for git sources before fetching them in online mode
  forc-pkg/src/pkg.rs
Labels: enhancement, forc, dependencies

#2882 Add `append` macro
  sway-core/src/error.rs
  sway-core/src/semantic_analysis/ast_node/code_block.rs
  sway-core/src/semantic_analysis/ast_node/declaration/function.rs
  sway-core/src/semantic_analysis/ast_node/expression/match_expression/typed/matcher.rs
  sway-core/src/semantic_analysis/ast_node/expression/match_expression/typed/typed_match_branch.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/if_expression.rs
  sway-core/src/semantic_analysis/type_check_context.rs
  sway-core/src/type_system/type_engine.rs
  sway-core/src/type_system/type_mapping.rs
Labels: code quality, compiler: frontend

#2879 Handle leading newlines and whitespaces before pre-module comments
  swayfmt/src/formatter/mod.rs
  swayfmt/src/utils/map/comments.rs
  swayfmt/src/utils/map/newline.rs
Labels: formatter, P: critical

#2870 Add --log-level and --silent to forc
  docs/src/forc/manifest_reference.md
  forc-pkg/src/manifest.rs
  forc-pkg/src/pkg.rs
  forc-plugins/forc-client/src/bin/deploy/main.rs
  forc-plugins/forc-client/src/bin/run/main.rs
  forc-plugins/forc-client/src/ops/deploy/cmd.rs
  forc-plugins/forc-client/src/ops/deploy/op.rs
  forc-plugins/forc-client/src/ops/run/cmd.rs
  forc-plugins/forc-client/src/ops/run/op.rs
  forc-plugins/forc-explore/src/main.rs
  forc-plugins/forc-fmt/src/main.rs
  forc-util/src/lib.rs
  forc/src/cli/commands/addr2line.rs
  forc/src/cli/commands/build.rs
  forc/src/cli/commands/check.rs
  forc/src/cli/commands/completions.rs
  forc/src/cli/mod.rs
  forc/src/ops/forc_build.rs
  forc/src/ops/forc_check.rs
  sway-lsp/src/core/session.rs
  test/src/e2e_vm_tests/harness.rs
  test/src/e2e_vm_tests/mod.rs
  test/src/ir_generation/mod.rs
Labels: enhancement, forc

#2892 Revert signed integers, ufp64
  sway-lib-std/src/i128.sw
  sway-lib-std/src/i16.sw
  sway-lib-std/src/i256.sw
  sway-lib-std/src/i32.sw
  sway-lib-std/src/i64.sw
  sway-lib-std/src/i8.sw
  sway-lib-std/src/lib.sw
  sway-lib-std/src/ufp64.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/i128_test/.gitignore
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/i128_test/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/i128_test/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/i128_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/i16_test/.gitignore
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/i16_test/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/i16_test/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/i16_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/i256_test/.gitignore
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/i256_test/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/i256_test/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/i256_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/i32_test/.gitignore
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/i32_test/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/i32_test/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/i32_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/i64_test/.gitignore
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/i64_test/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/i64_test/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/i64_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/i8_test/.gitignore
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/i8_test/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/i8_test/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/i8_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/ufp64_div_test/.gitignore
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/ufp64_div_test/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/ufp64_div_test/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/ufp64_div_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/ufp64_exp_test/.gitignore
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/ufp64_exp_test/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/ufp64_exp_test/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/ufp64_exp_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/ufp64_mul_test/.gitignore
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/ufp64_mul_test/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/ufp64_mul_test/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/ufp64_mul_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/ufp64_pow_test/.gitignore
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/ufp64_pow_test/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/ufp64_pow_test/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/ufp64_pow_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/ufp64_root_test/.gitignore
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/ufp64_root_test/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/ufp64_root_test/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/ufp64_root_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/ufp64_test/.gitignore
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/ufp64_test/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/ufp64_test/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/ufp64_test/src/main.sw
Labels: lib: std

#2898 Add a special revert code for `transfer_to_output`
  sway-lib-std/src/token.sw
Labels: enhancement, lib: std

#2901 Remove dead docstrings crate
  Cargo.toml
  docstrings/Cargo.toml
  docstrings/src/TODO.md
  docstrings/src/documentation.rs
  docstrings/src/documentation/documented_item.rs
  docstrings/src/documentation/item_type.rs
  docstrings/src/documentation/module.rs
  docstrings/src/documenter.rs
  docstrings/src/documenter/source_code_module.rs
  docstrings/src/error.rs
  docstrings/src/lib.rs
Labels: code quality

#2903 Add some missing keywords for mdBook syntax highlighting
  docs/theme/highlight.js
  scripts/highlightjs/sway.js
Labels: The Sway Book

#2902 Make `FunctionParameter` take a `TypeInfo`
  sway-core/src/convert_parse_tree.rs
  sway-core/src/parse_tree/declaration/function.rs
  sway-core/src/semantic_analysis/ast_node/declaration/function/function_parameter.rs
  sway-core/src/semantic_analysis/ast_node/declaration/trait.rs
  sway-core/src/semantic_analysis/ast_node/mod.rs
  sway-core/src/semantic_analysis/node_dependencies.rs
  sway-core/src/type_system/type_engine.rs
  sway-lsp/src/core/traverse_parse_tree.rs
Labels: compiler: frontend

#2908 Update lock file since the `docstring` crate was removed
  Cargo.lock
Labels: dependencies
