Repository FuelLabs/sway, pull requests merged in 2022-08, with the labels that each got.

#2432 Additional checks for unnecessary visibility qualifier (ABI definitions, ABI impls and trait impls)
  sway-lib-core/src/ops.sw
  sway-lib-std/src/u128.sw
  sway-lib-std/src/u256.sw
  sway-parse/src/item/item_abi.rs
  sway-parse/src/item/item_impl.rs
  test/src/e2e_vm_tests/test_programs/should_fail/abi_impl_pub_fn/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/abi_impl_pub_fn/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/abi_impl_pub_fn/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/abi_impl_pub_fn/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/abi_pub_fn_interface/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/abi_pub_fn_interface/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/abi_pub_fn_interface/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/abi_pub_fn_interface/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/abi_pub_fn_method/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/abi_pub_fn_method/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/abi_pub_fn_method/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/abi_pub_fn_method/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/trait_impl_pub_fn/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/trait_impl_pub_fn/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/trait_impl_pub_fn/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/trait_impl_pub_fn/test.toml
Labels: enhancement, compiler: frontend, compiler: ui

#2437 Bump to `v0.19.1`
  Cargo.lock
  forc-pkg/Cargo.toml
  forc-plugins/forc-explore/Cargo.toml
  forc-plugins/forc-fmt-v2/Cargo.toml
  forc-plugins/forc-fmt/Cargo.toml
  forc-plugins/forc-lsp/Cargo.toml
  forc-util/Cargo.toml
  forc/Cargo.toml
  sway-core/Cargo.toml
  sway-fmt-v2/Cargo.toml
  sway-fmt/Cargo.toml
  sway-ir/Cargo.toml
  sway-lsp/Cargo.toml
  sway-parse/Cargo.toml
  sway-types/Cargo.toml
  sway-utils/Cargo.toml
Labels: release

#2390 Adds `LineStyle` to `Shape`
  sway-fmt-v2/src/constants.rs
  sway-fmt-v2/src/fmt.rs
  sway-fmt-v2/src/items/item_abi.rs
  sway-fmt-v2/src/items/item_enum.rs
  sway-fmt-v2/src/items/item_fn.rs
  sway-fmt-v2/src/items/item_storage.rs
  sway-fmt-v2/src/items/item_struct.rs
  sway-fmt-v2/src/items/item_trait.rs
  sway-fmt-v2/src/utils/attribute.rs
  sway-fmt-v2/src/utils/expr.rs
  sway-fmt-v2/src/utils/indent_style.rs
  sway-fmt-v2/src/utils/statement.rs
  sway-fmt-v2/src/utils/where_clause.rs
Labels: forc, code quality, formatter

#2403 Adds `impl` formatting to `sfv2`
  sway-fmt-v2/src/fmt.rs
  sway-fmt-v2/src/items/item_fn.rs
  sway-fmt-v2/src/items/item_impl.rs
  sway-fmt-v2/src/items/item_trait.rs
  sway-fmt-v2/src/utils/where_clause.rs
Labels: enhancement, forc, formatter

#2436 Add a new 'simplify CFG` optimisation pass.
  sway-core/src/lib.rs
  sway-ir/src/bin/opt.rs
  sway-ir/src/block.rs
  sway-ir/src/error.rs
  sway-ir/src/function.rs
  sway-ir/src/optimize.rs
  sway-ir/src/optimize/simplify_cfg.rs
  sway-ir/tests/simplify_cfg/dead_blocks.ir
  sway-ir/tests/simplify_cfg/merge_all_blocks.ir
  sway-ir/tests/tests.rs
Labels: compiler: ir, compiler: optimization

#2417 Removed angle bracket trait from sway-fmt-v2
  sway-fmt-v2/src/utils/bracket.rs
  sway-fmt-v2/src/utils/generics.rs
  sway-fmt-v2/src/utils/path.rs
Labels: code quality, formatter

#2442 Fix a bug in the IR parsing.
  sway-ir/src/module.rs
  sway-ir/src/parser.rs
  sway-ir/src/value.rs
  sway-ir/tests/serialize/untyped_arg_to_call.ir
Labels: bug, compiler: ir

#2444 Add an option to print the typed program AST.
  docs/src/forc/manifest_reference.md
  forc-pkg/src/manifest.rs
  forc-pkg/src/pkg.rs
  forc/src/cli/commands/build.rs
  forc/src/cli/commands/deploy.rs
  forc/src/cli/commands/run.rs
  forc/src/ops/forc_build.rs
  forc/src/ops/forc_deploy.rs
  forc/src/ops/forc_run.rs
Labels: enhancement, compiler, forc

#2441 Implement a runnables custom method and collect typed tokens
  Cargo.lock
  sway-lsp/Cargo.toml
  sway-lsp/src/capabilities/mod.rs
  sway-lsp/src/capabilities/runnable.rs
  sway-lsp/src/core/session.rs
  sway-lsp/src/lib.rs
  sway-lsp/src/server.rs
Labels: enhancement, language server

#2446 Add an overall description to the `simplify-cfg` IR pass.
  sway-ir/src/optimize/simplify_cfg.rs
Labels: compiler: ir, compiler: optimization

#2448 Move the `SWAY_GIT_TAG` from `forc` into `forc-pkg`
  Cargo.lock
  forc-pkg/src/manifest.rs
  forc-pkg/src/pkg.rs
  forc/src/ops/forc_abi_json.rs
  forc/src/ops/forc_build.rs
  forc/src/ops/forc_check.rs
  forc/src/ops/forc_deploy.rs
  forc/src/ops/forc_run.rs
  forc/src/ops/forc_template.rs
  forc/src/ops/forc_update.rs
  forc/src/utils/mod.rs
  sway-lsp/Cargo.toml
  sway-lsp/src/core/session.rs
Labels: forc, code quality, P: critical

#2453 Identify types suited only for storage and find incorrect decls
  sway-core/src/concurrent_slab.rs
  sway-core/src/error.rs
  sway-core/src/semantic_analysis.rs
  sway-core/src/semantic_analysis/ast_node/declaration/impl_trait.rs
  sway-core/src/semantic_analysis/program.rs
  sway-core/src/semantic_analysis/storage_only_types.rs
  sway-core/src/type_engine/engine.rs
  test/src/e2e_vm_tests/test_programs/should_fail/storage_types/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/storage_types/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/storage_types/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/storage_types/test.toml
Labels: enhancement, compiler: ui

#2459 Send the program kind along with the range to the client code_lens request
  sway-lsp/src/capabilities/runnable.rs
  sway-lsp/src/core/session.rs
  sway-lsp/src/server.rs
Labels: language server

#2466 bump sdk version to v0.20 in stdlib tests and forc
  forc/src/utils/defaults.rs
  test/src/sdk-harness/Cargo.toml
  test/src/sdk-harness/test_projects/auth/mod.rs
  test/src/sdk-harness/test_projects/call_frames/mod.rs
  test/src/sdk-harness/test_projects/context/mod.rs
  test/src/sdk-harness/test_projects/evm/mod.rs
  test/src/sdk-harness/test_projects/exponentiation/mod.rs
  test/src/sdk-harness/test_projects/hashing/mod.rs
  test/src/sdk-harness/test_projects/logging/mod.rs
  test/src/sdk-harness/test_projects/methods/mod.rs
  test/src/sdk-harness/test_projects/option_field_order/mod.rs
  test/src/sdk-harness/test_projects/predicate_data_simple/mod.rs
  test/src/sdk-harness/test_projects/predicate_data_struct/mod.rs
  test/src/sdk-harness/test_projects/reentrancy/mod.rs
  test/src/sdk-harness/test_projects/registers/mod.rs
  test/src/sdk-harness/test_projects/script_data/mod.rs
  test/src/sdk-harness/test_projects/storage/mod.rs
  test/src/sdk-harness/test_projects/storage_map/mod.rs
  test/src/sdk-harness/test_projects/storage_vec/array/utils.rs
  test/src/sdk-harness/test_projects/storage_vec/b256/utils.rs
  test/src/sdk-harness/test_projects/storage_vec/bool/utils.rs
  test/src/sdk-harness/test_projects/storage_vec/enum/utils.rs
  test/src/sdk-harness/test_projects/storage_vec/str/utils.rs
  test/src/sdk-harness/test_projects/storage_vec/struct/utils.rs
  test/src/sdk-harness/test_projects/storage_vec/tuple/utils.rs
  test/src/sdk-harness/test_projects/storage_vec/u16/utils.rs
  test/src/sdk-harness/test_projects/storage_vec/u32/utils.rs
  test/src/sdk-harness/test_projects/storage_vec/u64/utils.rs
  test/src/sdk-harness/test_projects/storage_vec/u8/utils.rs
  test/src/sdk-harness/test_projects/token_ops/mod.rs
  test/src/sdk-harness/test_projects/tx_fields/mod.rs
Labels: forc, lib: std

#2481 Bump to `v0.19.2`
  Cargo.lock
  forc-pkg/Cargo.toml
  forc-plugins/forc-explore/Cargo.toml
  forc-plugins/forc-fmt-v2/Cargo.toml
  forc-plugins/forc-fmt/Cargo.toml
  forc-plugins/forc-lsp/Cargo.toml
  forc-util/Cargo.toml
  forc/Cargo.toml
  sway-ast/Cargo.toml
  sway-core/Cargo.toml
  sway-fmt-v2/Cargo.toml
  sway-fmt/Cargo.toml
  sway-ir/Cargo.toml
  sway-lsp/Cargo.toml
  sway-parse/Cargo.toml
  sway-types/Cargo.toml
  sway-utils/Cargo.toml
Labels: release

#2460 Switch between viewing typed or parsed tokens as warnings in the LSP client.
  forc-plugins/forc-lsp/src/main.rs
  sway-lsp/src/server.rs
  sway-lsp/src/utils/debug.rs
Labels: language server

#2476 2474/generic repo name
  scripts/examples-checker/src/main.rs
Labels: bug

#2471 Some preparation for function calls.
  sway-core/src/ir_generation/function.rs
  sway-ir/src/function.rs
  sway-ir/src/optimize/constants.rs
  sway-ir/src/optimize/inline.rs
  sway-ir/tests/README.md
  sway-ir/tests/inline/bigger.ir
  sway-ir/tests/inline/by_block_and_instr_count.ir
  sway-ir/tests/inline/by_block_count.ir
  sway-ir/tests/inline/by_instr_count.ir
  sway-ir/tests/inline/by_stack_count.ir
  sway-ir/tests/inline/fiddly.ir
  sway-ir/tests/inline/get_storage_key.ir
  sway-ir/tests/inline/int_to_ptr.ir
  sway-ir/tests/inline/simple.ir
  sway-ir/tests/tests.rs
  test/src/ir_generation/tests/redundant_fns.sw
Labels: compiler: ir, compiler: optimization

#2478 refactor: move build logic to `forc-pkg` from `forc`
  Cargo.lock
  forc-pkg/Cargo.toml
  forc-pkg/src/pkg.rs
  forc/src/ops/forc_build.rs
  forc/src/utils/mod.rs
Labels: forc, code quality, P: critical

#2338 Add `expr` formatting to `sway-fmt-v2`
  Cargo.lock
  sway-fmt-v2/Cargo.toml
  sway-fmt-v2/src/config/comments.rs
  sway-fmt-v2/src/config/heuristics.rs
  sway-fmt-v2/src/config/manifest.rs
  sway-fmt-v2/src/config/ordering.rs
  sway-fmt-v2/src/config/user_def.rs
  sway-fmt-v2/src/constants.rs
  sway-fmt-v2/src/fmt.rs
  sway-fmt-v2/src/items/item_enum.rs
  sway-fmt-v2/src/items/item_fn.rs
  sway-fmt-v2/src/items/item_storage.rs
  sway-fmt-v2/src/items/item_struct.rs
  sway-fmt-v2/src/lib.rs
  sway-fmt-v2/src/utils.rs
  sway-fmt-v2/src/utils/expr.rs
  sway-fmt-v2/src/utils/expr/abi_cast.rs
  sway-fmt-v2/src/utils/expr/asm_block.rs
  sway-fmt-v2/src/utils/expr/assignable.rs
  sway-fmt-v2/src/utils/expr/code_block.rs
  sway-fmt-v2/src/utils/expr/collections.rs
  sway-fmt-v2/src/utils/expr/conditional.rs
  sway-fmt-v2/src/utils/expr/mod.rs
  sway-fmt-v2/src/utils/expr/struct_field.rs
  sway-fmt-v2/src/utils/expr/tests.rs
  sway-fmt-v2/src/utils/generics.rs
  sway-fmt-v2/src/utils/item.rs
  sway-fmt-v2/src/utils/pattern.rs
  sway-fmt-v2/src/utils/punctuated.rs
  sway-fmt-v2/src/utils/shape.rs
  sway-fmt-v2/src/utils/statement.rs
  sway-fmt-v2/src/utils/ty.rs
Labels: enhancement, forc, big, formatter

#2470 Move `test` project to `clap`
  Cargo.lock
  test/Cargo.toml
  test/src/main.rs
Labels: testing

#2503 Removes outdated `todo` comments in `sfv2`
  sway-fmt-v2/src/items/item_fn.rs
  sway-fmt-v2/src/utils/expr/asm_block.rs
  sway-fmt-v2/src/utils/expr/conditional.rs
  sway-fmt-v2/src/utils/expr/struct_field.rs
  sway-fmt-v2/src/utils/expr/tests.rs
Labels: forc, code quality, formatter

#2472 2421/no main args
  sway-core/src/error.rs
  sway-core/src/semantic_analysis/program.rs
  test/src/e2e_vm_tests/test_programs/should_fail/main_should_not_have_args/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/main_should_not_have_args/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/main_should_not_have_args/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/main_should_not_have_args/src/pred.sw
  test/src/e2e_vm_tests/test_programs/should_fail/main_should_not_have_args/test.toml
Labels: compiler: ui

#2480 Misc cleanups in the parser
  sway-parse/src/attribute.rs
  sway-parse/src/expr/mod.rs
  sway-parse/src/generics.rs
  sway-parse/src/item/item_abi.rs
  sway-parse/src/item/item_enum.rs
  sway-parse/src/item/item_impl.rs
  sway-parse/src/item/item_struct.rs
  sway-parse/src/item/item_trait.rs
  sway-parse/src/item/mod.rs
  sway-parse/src/module.rs
  sway-parse/src/parse.rs
  sway-parse/src/parser.rs
  sway-parse/src/path.rs
  sway-parse/src/pattern.rs
Labels: code quality, compiler: parser

#2504 Changes `.clone().into_inner()` to `.get()` in `sfv2`
  sway-fmt-v2/src/items/item_enum.rs
  sway-fmt-v2/src/items/item_fn.rs
  sway-fmt-v2/src/items/item_impl.rs
  sway-fmt-v2/src/items/item_storage.rs
  sway-fmt-v2/src/items/item_struct.rs
  sway-fmt-v2/src/items/item_trait.rs
  sway-fmt-v2/src/utils/attribute.rs
  sway-fmt-v2/src/utils/comments.rs
  sway-fmt-v2/src/utils/expr/asm_block.rs
  sway-fmt-v2/src/utils/expr/assignable.rs
  sway-fmt-v2/src/utils/expr/conditional.rs
  sway-fmt-v2/src/utils/expr/mod.rs
  sway-fmt-v2/src/utils/generics.rs
  sway-fmt-v2/src/utils/pattern.rs
  sway-fmt-v2/src/utils/ty.rs
Labels: forc, code quality, formatter

#2513 Fix link to Forc reference in the repo
  forc/README.md
Labels: bug, documentation

#2405 Add minimum Forc version to manifest
  docs/src/forc/manifest_reference.md
  forc-pkg/Cargo.toml
  forc-pkg/src/manifest.rs
  forc-pkg/src/pkg.rs
Labels: enhancement, forc

#2488 Collect `TypedStructField` tokens in the language server.
  sway-core/src/ir_generation/const_eval.rs
  sway-core/src/ir_generation/function.rs
  sway-core/src/parse_tree/declaration/struct.rs
  sway-core/src/semantic_analysis/ast_node/declaration/storage.rs
  sway-core/src/semantic_analysis/ast_node/declaration/struct.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/struct_field_access.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression_variant.rs
  sway-core/src/type_system/type_argument.rs
  sway-lsp/src/core/session.rs
  sway-lsp/src/core/traverse_parse_tree.rs
  sway-lsp/src/core/traverse_typed_tree.rs
  sway-lsp/src/server.rs
  sway-lsp/src/utils/token.rs
Labels: language server, compiler: frontend

#2518 Fix new clippy lints (with rust version 1.63)
  scripts/mdbook-forc-documenter/src/formatter.rs
  sway-core/src/convert_parse_tree.rs
  sway-core/src/error.rs
  sway-core/src/ir_generation/const_eval.rs
  sway-core/src/parse_tree/expression/mod.rs
  sway-core/src/semantic_analysis/ast_node/declaration/impl_trait.rs
  sway-core/src/semantic_analysis/ast_node/expression/struct_expr_field.rs
  sway-core/src/semantic_analysis/storage_only_types.rs
  sway-core/src/type_system/type_info.rs
  sway-fmt-v2/src/config/lists.rs
  sway-fmt/src/code_line.rs
  sway-ir/src/parser.rs
  sway-parse/src/error.rs
  sway-parse/src/lib.rs
Labels: code quality

#2507 Add separate expression kind types
  sway-ast/src/lib.rs
  sway-core/src/convert_parse_tree.rs
  sway-core/src/lib.rs
  sway-core/src/parse_tree/declaration/reassignment.rs
  sway-core/src/parse_tree/expression/mod.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/method_application.rs
  sway-core/src/semantic_analysis/ast_node/mod.rs
  sway-core/src/semantic_analysis/node_dependencies.rs
  sway-fmt/src/traversal.rs
  sway-lsp/src/capabilities/completion.rs
  sway-lsp/src/capabilities/document_symbol.rs
  sway-lsp/src/capabilities/semantic_tokens.rs
  sway-lsp/src/core/traverse_parse_tree.rs
  sway-lsp/src/utils/debug.rs
Labels: bug, language server, compiler: frontend, compiler: parser

#2519 Temporarily disable the 3 LSP tests that open a file
  sway-lsp/src/server.rs
Labels: bug, ci, language server

#2510 Remove send address check
  examples/subcurrency/src/main.sw
Labels: The Sway Book

#2520 Small cleanup / refactoring for `forc-client` plugin PR
  Cargo.lock
  forc/Cargo.toml
Labels: forc, code quality, documentation

#2516 Add Outer DocComment Parsing
  Cargo.lock
  sway-ast/src/punctuated.rs
  sway-ast/src/token.rs
  sway-fmt-v2/src/fmt.rs
  sway-lib-std/src/context/call_frames.sw
  sway-parse/Cargo.toml
  sway-parse/src/attribute.rs
  sway-parse/src/error.rs
  sway-parse/src/expr/mod.rs
  sway-parse/src/item/mod.rs
  sway-parse/src/parser.rs
  sway-parse/src/token.rs
  sway-types/src/ident.rs
  test/src/e2e_vm_tests/test_programs/should_fail/main_should_not_have_args/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/main_should_not_have_args/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/ec_recover_test/src/main.sw
  test/src/sdk-harness/test_artifacts/reentrancy_target_contract/src/main.sw
Labels: language feature, compiler: parser

#2526 fix: Incorrect call parameter should be a compiler error
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/method_application.rs
  test/src/e2e_vm_tests/test_programs/should_fail/invalid_method_call_param/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/invalid_method_call_param/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/invalid_method_call_param/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/invalid_method_call_param/test.toml
Labels: bug, P: critical, compiler: parser, compiler: ui

#2529 fix: Setting the contract ID in an abi cast to a storage access fails to compile
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression_variant.rs
Labels: bug, P: critical, compiler: frontend

#2527 Fix support for parser recovery
  sway-core/src/lib.rs
  sway-fmt-v2/src/error.rs
  sway-fmt-v2/src/fmt.rs
  sway-fmt-v2/src/items/item_use/tests.rs
  sway-fmt-v2/src/utils/comments.rs
  sway-fmt-v2/src/utils/expr/tests.rs
  sway-parse/src/handler.rs
  sway-parse/src/item/item_struct.rs
  sway-parse/src/item/item_use.rs
  sway-parse/src/item/mod.rs
  sway-parse/src/lib.rs
  sway-parse/src/parser.rs
  test/src/e2e_vm_tests/test_programs/should_fail/pub_abi/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/pub_abi/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/pub_abi/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/pub_abi/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/pub_impl/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/pub_impl/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/pub_impl/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/pub_impl/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/pub_storage/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/pub_storage/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/pub_storage/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/pub_storage/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/trait_pub_fn_method/src/main.sw
Labels: enhancement, compiler: parser, compiler: ui

#2502 Organize imports in `sfv2`
  sway-fmt-v2/src/config/comments.rs
  sway-fmt-v2/src/config/expr.rs
  sway-fmt-v2/src/config/heuristics.rs
  sway-fmt-v2/src/config/imports.rs
  sway-fmt-v2/src/config/items.rs
  sway-fmt-v2/src/config/lists.rs
  sway-fmt-v2/src/config/literals.rs
  sway-fmt-v2/src/config/manifest.rs
  sway-fmt-v2/src/config/ordering.rs
  sway-fmt-v2/src/config/user_def.rs
  sway-fmt-v2/src/config/user_opts.rs
  sway-fmt-v2/src/config/whitespace.rs
  sway-fmt-v2/src/fmt.rs
  sway-fmt-v2/src/items/item_abi.rs
  sway-fmt-v2/src/items/item_const.rs
  sway-fmt-v2/src/items/item_enum.rs
  sway-fmt-v2/src/items/item_fn.rs
  sway-fmt-v2/src/items/item_storage.rs
  sway-fmt-v2/src/items/item_struct.rs
  sway-fmt-v2/src/utils/attribute.rs
  sway-fmt-v2/src/utils/expr/mod.rs
  sway-fmt-v2/src/utils/generics.rs
  sway-fmt-v2/src/utils/path.rs
  sway-fmt-v2/src/utils/pattern.rs
  sway-fmt-v2/src/utils/program_type.rs
  sway-fmt-v2/src/utils/punctuated.rs
  sway-fmt-v2/src/utils/ty.rs
  sway-fmt-v2/src/utils/where_clause.rs
Labels: forc, code quality, formatter

#2523 Fix: `Impl` formatting without generics generates unparsable output
  sway-fmt-v2/src/fmt.rs
  sway-fmt-v2/src/items/item_impl.rs
Labels: bug, formatter

#2530 Adds multiline formatting for `match` statements in `sfv2`
  sway-fmt-v2/src/utils/expr/conditional.rs
  sway-fmt-v2/src/utils/expr/mod.rs
  sway-fmt-v2/src/utils/expr/tests.rs
Labels: forc, formatter

#2534 Create markdown-lint.yml
  .github/workflows/markdown-lint.yml
  .markdownlint.yaml
  docs/README.md
  docs/src/advanced/generic_types.md
  docs/src/advanced/trait_constraints.md
  docs/src/basics/blockchain_types.md
  docs/src/basics/structs_tuples_and_enums.md
  docs/src/common-collections/storage_map.md
  docs/src/common-collections/storage_vec.md
  docs/src/forc/commands/index.md
  docs/src/forc/plugins.md
  docs/src/introduction/installation.md
  docs/src/reference/contributing_to_sway.md
  docs/src/sway-program-types/smart_contracts.md
  docstrings/src/TODO.md
  scripts/highlightjs/README.md
  scripts/mdbook-forc-documenter/examples/forc_build.md
  scripts/mdbook-forc-documenter/examples/forc_completions.md
  scripts/mdbook-forc-documenter/examples/forc_deploy.md
  scripts/mdbook-forc-documenter/examples/forc_init.md
  scripts/mdbook-forc-documenter/examples/forc_new.md
  scripts/mdbook-forc-documenter/examples/forc_parse-bytecode.md
  scripts/mdbook-forc-documenter/examples/forc_template.md
  scripts/mdbook-forc-documenter/examples/forc_test.md
  scripts/prism/README.md
  sway-ir/tests/README.md
  test/src/e2e_vm_tests/test_programs/README.md
  test/src/ir_generation/README.md
Labels: enhancement, ci

#2536 break and continue are not items
  sway-ast/src/expr/mod.rs
  sway-ast/src/item/item_control_flow.rs
  sway-ast/src/item/mod.rs
  sway-ast/src/lib.rs
  sway-ast/src/priv_prelude.rs
  sway-core/src/convert_parse_tree.rs
  sway-fmt-v2/src/utils/expr/mod.rs
  sway-fmt-v2/src/utils/item.rs
  sway-parse/src/expr/mod.rs
  sway-parse/src/item/item_control_flow.rs
  sway-parse/src/item/mod.rs
Labels: code quality, compiler: parser

#2538 Check for self parameters in free functions.
  sway-core/src/convert_parse_tree.rs
  test/src/e2e_vm_tests/test_programs/should_fail/free_fn_self/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/free_fn_self/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/free_fn_self/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/free_fn_self/test.toml
Labels: compiler, compiler: frontend

#2544 Store the variable decl Ident in VariableExpression and pass on the type_ascription_span
  sway-core/src/ir_generation/const_eval.rs
  sway-core/src/ir_generation/function.rs
  sway-core/src/semantic_analysis/ast_node/declaration/function/function_parameter.rs
  sway-core/src/semantic_analysis/ast_node/declaration/variable.rs
  sway-core/src/semantic_analysis/ast_node/expression/match_expression/typed/typed_match_branch.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression_variant.rs
  sway-core/src/semantic_analysis/ast_node/mod.rs
  sway-lsp/src/core/traverse_parse_tree.rs
  sway-lsp/src/core/traverse_typed_tree.rs
Labels: language server, compiler: frontend

#2542 Documentation for `ref mut` in the Sway Book
  docs/src/basics/functions.md
  docs/src/basics/methods_and_associated_functions.md
  examples/ref_mut_params/Forc.lock
  examples/ref_mut_params/Forc.toml
  examples/ref_mut_params/src/main.sw
Labels: The Sway Book

#2528 Annotate TypeFields
  sway-ast/src/item/item_enum.rs
  sway-ast/src/item/item_struct.rs
  sway-core/src/convert_parse_tree.rs
  sway-fmt-v2/src/items/item_enum.rs
  sway-fmt-v2/src/items/item_fn.rs
  sway-fmt-v2/src/items/item_struct.rs
  sway-fmt-v2/src/utils/attribute.rs
  sway-fmt-v2/src/utils/item.rs
  sway-parse/src/item/mod.rs
Labels: language feature, compiler: parser

#2545 Update 'Sway toolchain' references to 'Fuel toolchain' where appropriate
  docs/src/SUMMARY.md
  docs/src/introduction/fuel-toolchain.md
  docs/src/introduction/index.md
  docs/src/introduction/installation.md
  docs/src/introduction/overview.md
Labels: The Sway Book, documentation

#2547 Diagnose Unrecognized Annotations
  sway-core/src/constants.rs
  sway-core/src/convert_parse_tree.rs
  sway-core/src/error.rs
  test/src/e2e_vm_tests/test_programs/should_pass/language/diagnose_unknown_annotations/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/diagnose_unknown_annotations/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/diagnose_unknown_annotations/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/diagnose_unknown_annotations/test.toml
Labels: compiler: frontend

#2560 Speed improvements and bug fixes for `simplify-cfg`.
  sway-core/src/lib.rs
  sway-ir/src/block.rs
  sway-ir/src/function.rs
  sway-ir/src/optimize/simplify_cfg.rs
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_basic_storage/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/caller_context_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/get_storage_key_caller/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/storage_access_caller/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/token_ops_test/src/main.sw
Labels: compiler: ir, compiler: optimization

#2539 Adds better formatting to `match_branch_kind`
  sway-fmt-v2/src/items/item_fn.rs
  sway-fmt-v2/src/utils/expr/code_block.rs
  sway-fmt-v2/src/utils/expr/conditional.rs
  sway-fmt-v2/src/utils/expr/tests.rs
Labels: forc, formatter

#2440 Split client interaction commands into a forc-client plugin
  .github/workflows/ci.yml
  .github/workflows/gh-pages.yml
  Cargo.lock
  Cargo.toml
  docs/src/SUMMARY.md
  docs/src/forc_client.md
  docs/src/forc_deploy.md
  docs/src/forc_run.md
  forc-plugins/forc-client/Cargo.toml
  forc-plugins/forc-client/src/bin/deploy/main.rs
  forc-plugins/forc-client/src/bin/run/main.rs
  forc-plugins/forc-client/src/lib.rs
  forc-plugins/forc-client/src/ops/deploy/cmd.rs
  forc-plugins/forc-client/src/ops/deploy/mod.rs
  forc-plugins/forc-client/src/ops/deploy/op.rs
  forc-plugins/forc-client/src/ops/mod.rs
  forc-plugins/forc-client/src/ops/run/cmd.rs
  forc-plugins/forc-client/src/ops/run/mod.rs
  forc-plugins/forc-client/src/ops/run/op.rs
  forc-plugins/forc-client/src/ops/run/parameters.rs
  forc/Cargo.toml
  forc/src/cli/commands/mod.rs
  forc/src/cli/mod.rs
  forc/src/lib.rs
  forc/src/ops/mod.rs
  forc/src/utils/defaults.rs
  forc/src/utils/mod.rs
  scripts/mdbook-forc-documenter/src/lib.rs
  scripts/mdbook-forc-documenter/src/plugins.rs
  test/Cargo.toml
  test/src/e2e_vm_tests/harness.rs
Labels: enhancement, forc, code quality, P: critical

#2564 Adds formatting for `if_else` control flow blocks
  sway-fmt-v2/src/utils/expr/conditional.rs
  sway-fmt-v2/src/utils/expr/tests.rs
Labels: enhancement, forc, formatter

#2521 Update forc plugin docs with a note on multi-command plugins
  docs/src/forc/plugins.md
Labels: forc, documentation

#2570 Provide LSP extension for printing the parsed or typed AST in VS Code
  sway-lsp/src/core/session.rs
  sway-lsp/src/lib.rs
  sway-lsp/src/server.rs
Labels: language server, compiler: ui

#2573 Fixing the defaults for `forc new`
  forc/src/utils/defaults.rs
Labels: forc, P: critical

#2524 New JSON ABI format supporting generics
  .gitignore
  forc-pkg/src/pkg.rs
  sway-core/src/convert_parse_tree.rs
  sway-core/src/ir_generation/convert.rs
  sway-core/src/semantic_analysis/ast_node/declaration.rs
  sway-core/src/semantic_analysis/ast_node/declaration/enum.rs
  sway-core/src/semantic_analysis/ast_node/declaration/function.rs
  sway-core/src/semantic_analysis/ast_node/declaration/function/function_parameter.rs
  sway-core/src/semantic_analysis/ast_node/declaration/storage.rs
  sway-core/src/semantic_analysis/ast_node/declaration/struct.rs
  sway-core/src/semantic_analysis/ast_node/declaration/trait.rs
  sway-core/src/semantic_analysis/ast_node/expression/intrinsic_function.rs
  sway-core/src/semantic_analysis/ast_node/expression/match_expression/typed/typed_scrutinee.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/ast_node/mod.rs
  sway-core/src/semantic_analysis/namespace/root.rs
  sway-core/src/semantic_analysis/node_dependencies.rs
  sway-core/src/semantic_analysis/program.rs
  sway-core/src/type_system/mod.rs
  sway-core/src/type_system/type_argument.rs
  sway-core/src/type_system/type_engine.rs
  sway-core/src/type_system/type_id.rs
  sway-core/src/type_system/type_info.rs
  sway-core/src/type_system/type_mapping.rs
  sway-core/src/type_system/type_parameter.rs
  sway-types/src/lib.rs
  test/src/e2e_vm_tests/harness.rs
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/abi_with_generic_types/json_abi_oracle_flat.json
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/abi_with_generic_types/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/abi_with_tuples_contract/json_abi_oracle_flat.json
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/abi_with_tuples_contract/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/array_of_structs_contract/json_abi_oracle_flat.json
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/array_of_structs_contract/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/auth_testing_contract/json_abi_oracle_flat.json
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/auth_testing_contract/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/balance_test_contract/json_abi_oracle_flat.json
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/balance_test_contract/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/basic_storage/json_abi_oracle_flat.json
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/basic_storage/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/context_testing_contract/json_abi_oracle_flat.json
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/context_testing_contract/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/get_storage_key_contract/json_abi_oracle_flat.json
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/get_storage_key_contract/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/increment_contract/json_abi_oracle_flat.json
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/increment_contract/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/issue_1512_repro/json_abi_oracle_flat.json
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/issue_1512_repro/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/nested_struct_args_contract/json_abi_oracle_flat.json
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/nested_struct_args_contract/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/storage_access_contract/json_abi_oracle_flat.json
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/storage_access_contract/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/test_fuel_coin_contract/json_abi_oracle_flat.json
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/test_fuel_coin_contract/test.toml
Labels: P: critical, ABI, compiler: frontend, compiler: parser

#2549 Introduce configuration-time constants in `Forc.toml`
  Cargo.lock
  forc-pkg/Cargo.toml
  forc-pkg/src/manifest.rs
  forc-pkg/src/pkg.rs
  sway-core/Cargo.toml
  sway-core/src/convert_parse_tree.rs
  sway-core/src/error.rs
  sway-core/src/semantic_analysis/namespace/items.rs
  sway-core/src/semantic_analysis/namespace/module.rs
  sway-types/src/lib.rs
  test/src/e2e_vm_tests/test_programs/should_fail/config_time_constants/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/config_time_constants/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/config_time_constants/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_fail/config_time_constants/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/config_time_constants/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/config_time_constants/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/config_time_constants/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/config_time_constants/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/language/config_time_constants/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/config_time_constants/test.toml
Labels: language feature

#2565 Bump to `v0.20.0`
  Cargo.lock
  forc-pkg/Cargo.toml
  forc-plugins/forc-client/Cargo.toml
  forc-plugins/forc-explore/Cargo.toml
  forc-plugins/forc-fmt-v2/Cargo.toml
  forc-plugins/forc-fmt/Cargo.toml
  forc-plugins/forc-lsp/Cargo.toml
  forc-util/Cargo.toml
  forc/Cargo.toml
  sway-ast/Cargo.toml
  sway-core/Cargo.toml
  sway-fmt-v2/Cargo.toml
  sway-fmt/Cargo.toml
  sway-ir/Cargo.toml
  sway-lsp/Cargo.toml
  sway-parse/Cargo.toml
  sway-types/Cargo.toml
  sway-utils/Cargo.toml
Labels: release

#2532 Adds `control_flow` items to `sfv2`
  sway-fmt-v2/src/utils/expr/assignable.rs
  sway-fmt-v2/src/utils/expr/mod.rs
  sway-fmt-v2/src/utils/expr/tests.rs
  sway-fmt-v2/src/utils/statement.rs
Labels: enhancement, forc, formatter

#2577 Add `forc-client` metadata to `Cargo.toml`
  forc-plugins/forc-client/Cargo.toml
Labels: forc

#2578 Bump to `v0.20.1`
  Cargo.lock
  forc-pkg/Cargo.toml
  forc-plugins/forc-client/Cargo.toml
  forc-plugins/forc-explore/Cargo.toml
  forc-plugins/forc-fmt-v2/Cargo.toml
  forc-plugins/forc-fmt/Cargo.toml
  forc-plugins/forc-lsp/Cargo.toml
  forc-util/Cargo.toml
  forc/Cargo.toml
  sway-ast/Cargo.toml
  sway-core/Cargo.toml
  sway-fmt-v2/Cargo.toml
  sway-fmt/Cargo.toml
  sway-ir/Cargo.toml
  sway-lsp/Cargo.toml
  sway-parse/Cargo.toml
  sway-types/Cargo.toml
  sway-utils/Cargo.toml
Labels: release

#2582 Fix binary release; add verify tag
  .github/workflows/ci.yml
Labels: bug, ci

#2584 Bump to `v0.20.2`
  Cargo.lock
  forc-pkg/Cargo.toml
  forc-plugins/forc-client/Cargo.toml
  forc-plugins/forc-explore/Cargo.toml
  forc-plugins/forc-fmt-v2/Cargo.toml
  forc-plugins/forc-fmt/Cargo.toml
  forc-plugins/forc-lsp/Cargo.toml
  forc-util/Cargo.toml
  forc/Cargo.toml
  sway-ast/Cargo.toml
  sway-core/Cargo.toml
  sway-fmt-v2/Cargo.toml
  sway-fmt/Cargo.toml
  sway-ir/Cargo.toml
  sway-lsp/Cargo.toml
  sway-parse/Cargo.toml
  sway-types/Cargo.toml
  sway-utils/Cargo.toml
Labels: release

#2537 feat: `sway-fmt-v2` preserves newline with given threshold
  sway-fmt-v2/src/config/user_opts.rs
  sway-fmt-v2/src/config/whitespace.rs
  sway-fmt-v2/src/constants.rs
  sway-fmt-v2/src/error.rs
  sway-fmt-v2/src/fmt.rs
  sway-fmt-v2/src/items/item_abi.rs
  sway-fmt-v2/src/items/item_const.rs
  sway-fmt-v2/src/items/item_enum.rs
  sway-fmt-v2/src/items/item_fn.rs
  sway-fmt-v2/src/items/item_impl.rs
  sway-fmt-v2/src/items/item_storage.rs
  sway-fmt-v2/src/items/item_struct.rs
  sway-fmt-v2/src/items/item_trait.rs
  sway-fmt-v2/src/items/item_use.rs
  sway-fmt-v2/src/utils.rs
  sway-fmt-v2/src/utils/attribute.rs
  sway-fmt-v2/src/utils/byte_span.rs
  sway-fmt-v2/src/utils/comments.rs
  sway-fmt-v2/src/utils/expr/abi_cast.rs
  sway-fmt-v2/src/utils/expr/asm_block.rs
  sway-fmt-v2/src/utils/expr/assignable.rs
  sway-fmt-v2/src/utils/expr/code_block.rs
  sway-fmt-v2/src/utils/expr/collections.rs
  sway-fmt-v2/src/utils/expr/conditional.rs
  sway-fmt-v2/src/utils/expr/mod.rs
  sway-fmt-v2/src/utils/expr/struct_field.rs
  sway-fmt-v2/src/utils/item.rs
  sway-fmt-v2/src/utils/literal.rs
  sway-fmt-v2/src/utils/newline.rs
  sway-fmt-v2/src/utils/path.rs
  sway-fmt-v2/src/utils/pattern.rs
  sway-fmt-v2/src/utils/program_type.rs
  sway-fmt-v2/src/utils/punctuated.rs
  sway-fmt-v2/src/utils/statement.rs
  sway-fmt-v2/src/utils/ty.rs
  sway-fmt-v2/src/utils/where_clause.rs
Labels: enhancement, formatter

#2580 Remove `forc json-abi` because it's not very useful on its own
  docs/src/SUMMARY.md
  docs/src/forc/commands/forc_json-abi.md
  forc/src/cli/commands/json_abi.rs
  forc/src/cli/commands/mod.rs
  forc/src/cli/mod.rs
  forc/src/lib.rs
  forc/src/ops/forc_abi_json.rs
  forc/src/ops/mod.rs
Labels: forc, breaking

#2590 Remove known issue and fix issue number for another
  docs/src/reference/known_issues_and_workarounds.md
Labels: The Sway Book

#2588 Annotate ItemStorage fields
  sway-ast/src/item/item_storage.rs
  sway-core/src/convert_parse_tree.rs
  sway-fmt-v2/src/items/item_storage.rs
  test/src/e2e_vm_tests/test_programs/should_pass/language/doc_comments/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/doc_comments/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/doc_comments/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/doc_comments/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/doc_strings/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/language/doc_strings/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/doc_strings/test.toml
Labels: language feature, compiler: parser

#2445 Add math & bitwise ops to U256 type 2
  sway-lib-std/src/u256.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/u256_div_test/.gitignore
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/u256_div_test/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/u256_div_test/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/u256_div_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/u256_mul_test/.gitignore
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/u256_mul_test/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/u256_mul_test/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/u256_mul_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/u256_ops_test/.gitignore
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/u256_ops_test/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/u256_ops_test/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/u256_ops_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/u256_test/src/main.sw
Labels: lib: std

#2533 Update getting started section
  docs/src/introduction/overview.md
Labels: The Sway Book, documentation

#2593 Adds multiline formatting for `array`
  sway-fmt-v2/src/utils/expr/collections.rs
  sway-fmt-v2/src/utils/expr/mod.rs
  sway-fmt-v2/src/utils/expr/tests.rs
Labels: enhancement, forc, formatter

#2576 Adds docstring for test macros
  sway-fmt-v2/src/utils/expr/tests.rs
Labels: formatter, documentation

#2596 feat: check for dependency program type in dependency manifest validation
  forc-pkg/src/pkg.rs
Labels: enhancement, forc

#2602 Fix IR gen for explicit return of structs.
  sway-core/src/ir_generation/function.rs
  test/src/ir_generation/tests/return_stmt_structs.sw
Labels: compiler: ir, P: critical

#2611 Adds the optional type of integer literals
  sway-fmt-v2/src/utils/literal.rs
Labels: bug, forc, formatter

#2610 Removes extra space from `if let` logic
  sway-fmt-v2/src/utils/expr/conditional.rs
Labels: bug, forc, formatter

#2613 Add missing `gtf` support to compiler
  sway-ast/src/expr/op_code.rs
  sway-core/src/asm_lang/mod.rs
  sway-parse/src/expr/op_code.rs
Labels: bug, P: high, compiler: collection

#2612 Reorganize module tree and modules
  sway-fmt-v2/src/config/mod.rs
  sway-fmt-v2/src/formatter/mod.rs
  sway-fmt-v2/src/formatter/shape.rs
  sway-fmt-v2/src/items/item_abi.rs
  sway-fmt-v2/src/items/item_const.rs
  sway-fmt-v2/src/items/item_enum.rs
  sway-fmt-v2/src/items/item_fn/mod.rs
  sway-fmt-v2/src/items/item_impl.rs
  sway-fmt-v2/src/items/item_storage.rs
  sway-fmt-v2/src/items/item_struct.rs
  sway-fmt-v2/src/items/item_trait.rs
  sway-fmt-v2/src/items/item_use/mod.rs
  sway-fmt-v2/src/items/mod.rs
  sway-fmt-v2/src/lib.rs
  sway-fmt-v2/src/module/dependency.rs
  sway-fmt-v2/src/module/item.rs
  sway-fmt-v2/src/module/mod.rs
  sway-fmt-v2/src/utils/language/attribute.rs
  sway-fmt-v2/src/utils/language/expr/abi_cast.rs
  sway-fmt-v2/src/utils/language/expr/asm_block.rs
  sway-fmt-v2/src/utils/language/expr/assignable.rs
  sway-fmt-v2/src/utils/language/expr/code_block.rs
  sway-fmt-v2/src/utils/language/expr/collections.rs
  sway-fmt-v2/src/utils/language/expr/conditional.rs
  sway-fmt-v2/src/utils/language/expr/mod.rs
  sway-fmt-v2/src/utils/language/expr/struct_field.rs
  sway-fmt-v2/src/utils/language/expr/tests.rs
  sway-fmt-v2/src/utils/language/generics.rs
  sway-fmt-v2/src/utils/language/literal.rs
  sway-fmt-v2/src/utils/language/mod.rs
  sway-fmt-v2/src/utils/language/path.rs
  sway-fmt-v2/src/utils/language/pattern.rs
  sway-fmt-v2/src/utils/language/punctuated.rs
  sway-fmt-v2/src/utils/language/statement.rs
  sway-fmt-v2/src/utils/language/ty.rs
  sway-fmt-v2/src/utils/language/where_clause.rs
  sway-fmt-v2/src/utils/map/byte_span.rs
  sway-fmt-v2/src/utils/map/comments.rs
  sway-fmt-v2/src/utils/map/mod.rs
  sway-fmt-v2/src/utils/map/newline.rs
  sway-fmt-v2/src/utils/map/newline_style.rs
  sway-fmt-v2/src/utils/mod.rs
  sway-fmt-v2/src/utils/program_type.rs
Labels: enhancement, forc, code quality, formatter

#2614 Handles annotated fields
  sway-fmt-v2/src/items/item_abi.rs
  sway-fmt-v2/src/items/item_enum/mod.rs
  sway-fmt-v2/src/items/item_enum/tests.rs
  sway-fmt-v2/src/items/item_fn/mod.rs
  sway-fmt-v2/src/items/item_impl.rs
  sway-fmt-v2/src/items/item_storage.rs
  sway-fmt-v2/src/items/item_struct/mod.rs
  sway-fmt-v2/src/items/item_struct/tests.rs
  sway-fmt-v2/src/items/item_trait.rs
  sway-fmt-v2/src/utils/language/attribute.rs
Labels: bug, forc, formatter

#2535 Reassignment expressions
  sway-core/src/control_flow_analysis/analyze_return_paths.rs
  sway-core/src/control_flow_analysis/dead_code_analysis.rs
  sway-core/src/convert_parse_tree.rs
  sway-core/src/ir_generation/compile.rs
  sway-core/src/ir_generation/const_eval.rs
  sway-core/src/ir_generation/function.rs
  sway-core/src/parse_tree/declaration.rs
  sway-core/src/parse_tree/declaration/reassignment.rs
  sway-core/src/parse_tree/expression/mod.rs
  sway-core/src/semantic_analysis/ast_node/declaration.rs
  sway-core/src/semantic_analysis/ast_node/declaration/impl_trait.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression_variant.rs
  sway-core/src/semantic_analysis/ast_node/mod.rs
  sway-core/src/semantic_analysis/node_dependencies.rs
  sway-core/src/semantic_analysis/storage_only_types.rs
  sway-lsp/src/capabilities/completion.rs
  sway-lsp/src/capabilities/document_symbol.rs
  sway-lsp/src/core/token.rs
  sway-lsp/src/core/traverse_parse_tree.rs
  sway-lsp/src/core/traverse_typed_tree.rs
Labels: code quality, compiler: frontend, compiler: parser

#2607 Added missing END to ANCHOR
  examples/ref_mut_params/src/main.sw
Labels: bug, The Sway Book

#2616 Fixed typo
  docs/src/basics/methods_and_associated_functions.md
Labels: bug, The Sway Book

#2569 Collect SymbolKind info and generate correct semantic tokens
  sway-core/src/parse_tree/declaration/function.rs
  sway-core/src/type_system/mod.rs
  sway-lsp/src/capabilities/completion.rs
  sway-lsp/src/capabilities/document_symbol.rs
  sway-lsp/src/capabilities/semantic_tokens.rs
  sway-lsp/src/core/session.rs
  sway-lsp/src/core/token.rs
  sway-lsp/src/core/traverse_parse_tree.rs
  sway-lsp/src/server.rs
  sway-lsp/src/utils/token.rs
Labels: language server

#2625 fix: ForwardSlash span collection
  sway-parse/src/token.rs
Labels: bug, P: critical, compiler: parser

#2618 Fix `storage` blocks
  sway-fmt-v2/src/items/item_storage/mod.rs
  sway-fmt-v2/src/items/item_storage/tests.rs
  sway-fmt-v2/src/utils/language/expr/mod.rs
  sway-fmt-v2/src/utils/language/path.rs
  sway-fmt-v2/src/utils/language/punctuated.rs
Labels: bug, forc, formatter

#2630 Add the declaration engine skeleton code
  sway-core/src/concurrent_slab.rs
  sway-core/src/declaration_engine/declaration_engine.rs
  sway-core/src/declaration_engine/declaration_id.rs
  sway-core/src/declaration_engine/declaration_wrapper.rs
  sway-core/src/declaration_engine/mod.rs
  sway-core/src/lib.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/namespace/module.rs
  sway-core/src/semantic_analysis/program.rs
  sway-core/src/semantic_analysis/type_check_context.rs
Labels: compiler: frontend, compiler: collection

#2645 Fix in how the `__gtf` intrinsic is lowered to asm
  sway-core/src/asm_generation/from_ir.rs
  sway-core/tests/ir_to_asm/gtf.asm
  sway-core/tests/ir_to_asm/gtf.ir
Labels: bug, P: critical, compiler: codegen

#2640 Fix warning regression when handling break and continue expressions.
  sway-core/src/semantic_analysis/ast_node/mod.rs
  test/src/e2e_vm_tests/test_programs/should_fail/illegal_break/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/illegal_continue/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/break_and_continue_block_ret/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/break_and_continue_block_ret/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/break_and_continue_block_ret/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/break_and_continue_block_ret/test.toml
Labels: P: critical, compiler: frontend

#2642 Pass the `Declaration Engine` to IR gen
  sway-core/src/declaration_engine/declaration_engine.rs
  sway-core/src/declaration_engine/declaration_wrapper.rs
  sway-core/src/ir_generation.rs
  sway-core/src/ir_generation/compile.rs
  sway-core/src/lib.rs
  sway-core/src/semantic_analysis/program.rs
Labels: compiler: ir, compiler: frontend

#2620 Collect missing tokens in the language server
  sway-core/src/convert_parse_tree.rs
  sway-core/src/parse_tree/declaration/constant.rs
  sway-core/src/parse_tree/declaration/enum.rs
  sway-core/src/parse_tree/declaration/function.rs
  sway-core/src/parse_tree/declaration/impl_trait.rs
  sway-core/src/parse_tree/declaration/storage.rs
  sway-core/src/parse_tree/declaration/struct.rs
  sway-core/src/parse_tree/declaration/trait.rs
  sway-core/src/semantic_analysis/ast_node/declaration.rs
  sway-core/src/semantic_analysis/ast_node/declaration/enum.rs
  sway-core/src/semantic_analysis/ast_node/declaration/function.rs
  sway-core/src/semantic_analysis/ast_node/declaration/impl_trait.rs
  sway-core/src/semantic_analysis/ast_node/declaration/storage.rs
  sway-core/src/semantic_analysis/ast_node/declaration/struct.rs
  sway-core/src/semantic_analysis/ast_node/mod.rs
  sway-core/src/type_system/mod.rs
  sway-core/src/type_system/type_parameter.rs
  sway-lsp/src/capabilities/completion.rs
  sway-lsp/src/capabilities/document_symbol.rs
  sway-lsp/src/capabilities/semantic_tokens.rs
  sway-lsp/src/core/token.rs
  sway-lsp/src/core/traverse_parse_tree.rs
  sway-lsp/src/core/traverse_typed_tree.rs
Labels: language server, compiler: frontend

#2651 Bump to `v0.21.0`
  Cargo.lock
  forc-pkg/Cargo.toml
  forc-plugins/forc-client/Cargo.toml
  forc-plugins/forc-explore/Cargo.toml
  forc-plugins/forc-fmt-v2/Cargo.toml
  forc-plugins/forc-fmt/Cargo.toml
  forc-plugins/forc-lsp/Cargo.toml
  forc-util/Cargo.toml
  forc/Cargo.toml
  sway-ast/Cargo.toml
  sway-core/Cargo.toml
  sway-fmt-v2/Cargo.toml
  sway-fmt/Cargo.toml
  sway-ir/Cargo.toml
  sway-lsp/Cargo.toml
  sway-parse/Cargo.toml
  sway-types/Cargo.toml
  sway-utils/Cargo.toml
Labels: release

#2653 fix: `swayfmt-v2` deletes empty tuples
  sway-fmt-v2/src/items/item_impl/tests.rs
  sway-fmt-v2/src/utils/language/expr/collections.rs
Labels: bug, formatter

#2597 Adds formatting for long conditional statements
  sway-fmt-v2/src/formatter/shape.rs
  sway-fmt-v2/src/items/item_fn/tests.rs
  sway-fmt-v2/src/utils/language/expr/asm_block.rs
  sway-fmt-v2/src/utils/language/expr/code_block.rs
  sway-fmt-v2/src/utils/language/expr/conditional.rs
  sway-fmt-v2/src/utils/language/expr/mod.rs
  sway-fmt-v2/src/utils/language/expr/tests.rs
  sway-fmt-v2/src/utils/language/path.rs
  sway-fmt-v2/src/utils/language/pattern.rs
  sway-fmt-v2/src/utils/language/statement.rs
Labels: enhancement, forc, formatter

#2644 Better error handling in the `Declaration Engine`
  sway-core/src/declaration_engine/declaration_engine.rs
  sway-core/src/declaration_engine/declaration_wrapper.rs
Labels: compiler: frontend

#2663 Fixes consecutive `fn_sig` formatting
  sway-fmt-v2/src/items/item_fn/mod.rs
Labels: bug, forc, formatter

#2665 fix: sway-fmt-v2 newline/comment handler makes duplicate searches
  sway-fmt-v2/src/utils/map/comments.rs
  sway-fmt-v2/src/utils/map/newline.rs
Labels: bug, formatter

#2668 feat: doc comment formatting
  sway-fmt-v2/src/formatter/mod.rs
  sway-fmt-v2/src/utils/language/attribute.rs
Labels: bug, formatter

#2667 Disallow non-literal config-time constants and add docs
  docs/src/basics/variables.md
  docs/src/reference/known_issues_and_workarounds.md
  examples/config_time_constants/Forc.lock
  examples/config_time_constants/Forc.toml
  examples/config_time_constants/src/main.sw
  sway-core/src/error.rs
  sway-core/src/semantic_analysis/namespace/module.rs
  test/src/e2e_vm_tests/test_programs/should_fail/config_time_constants_non_literal/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/config_time_constants_non_literal/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/config_time_constants_non_literal/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_fail/config_time_constants_non_literal/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/config_time_constants_non_literal/test.toml
Labels: The Sway Book, P: critical, compiler: frontend

#2482 Refactor std::tx to use gtf intrinsic
  .github/workflows/ci.yml
  Cargo.lock
  forc-pkg/Cargo.toml
  forc-pkg/src/pkg.rs
  forc-plugins/forc-client/Cargo.toml
  forc-plugins/forc-client/src/ops/deploy/op.rs
  forc-plugins/forc-client/src/ops/run/op.rs
  forc-plugins/forc-client/src/ops/run/parameters.rs
  forc/Cargo.toml
  forc/src/utils/defaults.rs
  sway-ast/src/expr/op_code.rs
  sway-core/Cargo.toml
  sway-core/src/asm_lang/allocated_ops.rs
  sway-core/src/asm_lang/mod.rs
  sway-core/src/asm_lang/virtual_ops.rs
  sway-core/src/semantic_analysis/ast_node/expression/match_expression/analysis/pattern.rs
  sway-lib-std/src/chain/auth.sw
  sway-lib-std/src/inputs.sw
  sway-lib-std/src/lib.sw
  sway-lib-std/src/outputs.sw
  sway-lib-std/src/storage.sw
  sway-lib-std/src/token.sw
  sway-lib-std/src/tx.sw
  sway-parse/src/expr/op_code.rs
  sway-types/Cargo.toml
  test-sig-gen-util/Cargo.toml
  test/Cargo.toml
  test/src/e2e_vm_tests/harness.rs
  test/src/sdk-harness/Cargo.toml
  test/src/sdk-harness/test_artifacts/tx_contract/src/main.sw
  test/src/sdk-harness/test_projects/auth/mod.rs
  test/src/sdk-harness/test_projects/context/mod.rs
  test/src/sdk-harness/test_projects/exponentiation/mod.rs
  test/src/sdk-harness/test_projects/logging/mod.rs
  test/src/sdk-harness/test_projects/methods/mod.rs
  test/src/sdk-harness/test_projects/predicate_data_simple/mod.rs
  test/src/sdk-harness/test_projects/predicate_data_simple/src/main.sw
  test/src/sdk-harness/test_projects/predicate_data_struct/mod.rs
  test/src/sdk-harness/test_projects/predicate_data_struct/src/main.sw
  test/src/sdk-harness/test_projects/reentrancy/mod.rs
  test/src/sdk-harness/test_projects/script_data/mod.rs
  test/src/sdk-harness/test_projects/token_ops/mod.rs
  test/src/sdk-harness/test_projects/tx_fields/mod.rs
Labels: lib: std, big, breaking, P: critical, blocked
