Repository FuelLabs/sway, pull requests merged in 2022-05, with the labels that each got.

#1441 Fix `forc run` default URL
  docs/src/forc/commands/forc_run.md
  forc/src/cli/commands/run.rs
Labels: bug, forc

#1421 Parse patterns in function parameter position
  sway-core/src/convert_parse_tree.rs
  sway-parse/src/item/mod.rs
  sway-parse/src/lib.rs
Labels: enhancement, compiler

#1430 Collect tokens from missing SwayParseTree variants
  sway-core/src/parse_tree/declaration.rs
  sway-core/src/parse_tree/declaration/abi.rs
  sway-core/src/parse_tree/declaration/enum.rs
  sway-core/src/parse_tree/declaration/function.rs
  sway-core/src/parse_tree/declaration/impl_trait.rs
  sway-core/src/parse_tree/declaration/struct.rs
  sway-core/src/parse_tree/declaration/trait.rs
  sway-core/src/parse_tree/expression/asm.rs
  sway-core/src/parse_tree/expression/method_name.rs
  sway-core/src/parse_tree/expression/mod.rs
  sway-lsp/src/capabilities/completion.rs
  sway-lsp/src/capabilities/document_symbol.rs
  sway-lsp/src/capabilities/hover.rs
  sway-lsp/src/capabilities/semantic_tokens.rs
  sway-lsp/src/core/token.rs
  sway-lsp/src/core/token_type.rs
  sway-lsp/src/utils/function.rs
Labels: language server

#1443 Clearer failure message for forc-documenter
  scripts/forc-documenter/src/constants.rs
Labels: documentation, forc

#1398 Move build all examples
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  examples/build-all-examples/Cargo.toml
  examples/build-all-examples/src/main.rs
  scripts/examples-checker/Cargo.toml
  scripts/examples-checker/src/main.rs
Labels: code quality, testing

#1409 Add build-forc-test-project to ci
  .github/workflows/ci.yml
Labels: ci

#1454 Adding a `bitcast` to make sure that the IR generated for storage accesses is legal
  sway-core/src/optimize.rs
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/storage_access_caller/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/test_abis/storage_access_abi/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/storage_access_contract/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/storage_access_contract/src/main.sw
Labels: bug, compiler

#1445 Updated toml file to exclude all examples using glob operator
  Cargo.toml
Labels: good first issue, code quality

#1459 Update manifest for build-forc-test-project
  .github/workflows/ci.yml
Labels: ci

#1457 Bump to 0.12.0
  Cargo.lock
  forc-explore/Cargo.toml
  forc-fmt/Cargo.toml
  forc-gm/Cargo.toml
  forc-lsp/Cargo.toml
  forc-pkg/Cargo.toml
  forc-util/Cargo.toml
  forc/Cargo.toml
  sway-core/Cargo.toml
  sway-fmt/Cargo.toml
  sway-ir/Cargo.toml
  sway-lsp/Cargo.toml
  sway-parse/Cargo.toml
  sway-types/Cargo.toml
  sway-utils/Cargo.toml
  test/Cargo.toml
Labels: release

#1466 Rename test/src/sdk-harness/test-helpers to test_helpers.
  test/src/sdk-harness/Cargo.toml
  test/src/sdk-harness/build.sh
  test/src/sdk-harness/test_helpers/Cargo.toml
  test/src/sdk-harness/test_helpers/src/lib.rs
Labels: lib: std, code quality

#1471 Stop publishing `forc-gm` temporarily
  forc-gm/Cargo.toml
Labels: forc

#1473 Bump to 0.12.1
  Cargo.lock
  forc-explore/Cargo.toml
  forc-fmt/Cargo.toml
  forc-gm/Cargo.toml
  forc-lsp/Cargo.toml
  forc-pkg/Cargo.toml
  forc-util/Cargo.toml
  forc/Cargo.toml
  sway-core/Cargo.toml
  sway-fmt/Cargo.toml
  sway-ir/Cargo.toml
  sway-lsp/Cargo.toml
  sway-parse/Cargo.toml
  sway-types/Cargo.toml
  sway-utils/Cargo.toml
Labels: release

#1467 Update parse bytecode example
  docs/src/forc/commands/forc_parse-bytecode.md
  scripts/forc-documenter/src/constants.rs
Labels: forc, The Sway Book

#1479 Revert 1477 braqzen #1476 and update formatting
  docs/README.md
Labels: documentation

#1438 Rust 1.60 docker update
  .github/workflows/ci.yml
  deployment/Dockerfile
  sway-ir/Cargo.toml
Labels: ci, dependencies

#1453 Add --describe -d opt to forc plugins
  docs/src/forc/commands/forc_plugins.md
  forc/src/cli/commands/plugins.rs
Labels: enhancement, forc

#1461 Add [workspace] to forc manifest
  .github/workflows/ci.yml
Labels: ci

#1469 Hide use orig asm and parser in the help text for forc build, deploy, run
  docs/src/forc/commands/forc_build.md
  docs/src/forc/commands/forc_deploy.md
  docs/src/forc/commands/forc_run.md
  forc/src/cli/commands/build.rs
  forc/src/cli/commands/deploy.rs
  forc/src/cli/commands/run.rs
Labels: enhancement, good first issue, forc

#1482 Fixes to the Forc Project section with the recent updates to `forc init`
  docs/src/introduction/forc_project.md
Labels: The Sway Book

#1422 Span/String/Ident fixups
  forc-util/src/lib.rs
  sway-core/src/control_flow_analysis/dead_code_analysis.rs
  sway-core/src/control_flow_analysis/flow_graph/mod.rs
  sway-core/src/convert_parse_tree.rs
  sway-core/src/error.rs
  sway-core/src/semantic_analysis/ast_node/declaration/storage.rs
  sway-core/src/semantic_analysis/ast_node/declaration/variable.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/ast_node/mod.rs
  sway-core/src/semantic_analysis/namespace.rs
  sway-core/src/semantic_analysis/namespace/arena.rs
  sway-core/src/semantic_analysis/node_dependencies.rs
  sway-core/src/semantic_analysis/syntax_tree.rs
Labels: compiler, code quality

#1486 Some fixes to storage in the Sway Book
  docs/src/blockchain-development/purity.md
  docs/src/blockchain-development/storage.md
  docs/src/reference/temporary_workarounds.md
  docs/src/testing/testing-with-rust.md
Labels: The Sway Book

#1362 Hashing and Cryptography
  docs/src/SUMMARY.md
  docs/src/blockchain-development/hashing_and_cryptography.md
  docs/src/blockchain-development/index.md
  examples/hashing/Forc.lock
  examples/hashing/Forc.toml
  examples/hashing/src/main.sw
  examples/signatures/Forc.lock
  examples/signatures/Forc.toml
  examples/signatures/src/main.sw
Labels: enhancement, The Sway Book

#1355 match expressions take 2
  docs/src/basics/control_flow.md
  examples/match_statements/Forc.lock
  examples/match_statements/Forc.toml
  examples/match_statements/src/main.sw
Labels: The Sway Book

#1485 Moved name & version keys to the top of [package]
  docs/src/forc/commands/forc_completions.md
  forc/src/utils/defaults.rs
Labels: good first issue, forc, code quality

#1490 Small fix to `hash_u64`
  sway-lib-std/src/hash.sw
  test/src/sdk-harness/test_projects/harness.rs
  test/src/sdk-harness/test_projects/hashing/.gitignore
  test/src/sdk-harness/test_projects/hashing/Forc.lock
  test/src/sdk-harness/test_projects/hashing/Forc.toml
  test/src/sdk-harness/test_projects/hashing/mod.rs
  test/src/sdk-harness/test_projects/hashing/src/main.sw
Labels: bug, lib: std

#1496 Changed default manifest dependency ordering
  forc/src/utils/defaults.rs
Labels: good first issue, forc, code quality

#1337 Remove `sway_types::{JsonABI, Function, Property}` in favour of `fuels_types`
  Cargo.lock
  forc-pkg/Cargo.toml
  forc-pkg/src/pkg.rs
  sway-core/Cargo.toml
  sway-core/src/parse_tree/declaration/function.rs
  sway-core/src/semantic_analysis/ast_node/declaration.rs
  sway-core/src/semantic_analysis/ast_node/declaration/function.rs
  sway-core/src/type_engine.rs
  sway-types/src/lib.rs
Labels: compiler, forc, code quality

#1481 Fix for forc test doesn't return with error code if Cargo manifest is invalid #1464
  forc/src/cli/commands/test.rs
Labels: bug, forc

#1494 Changes `panic` to `revert` in `sway-lib-std`
  examples/msg_sender/src/main.sw
  examples/signatures/src/main.sw
  examples/subcurrency/src/main.sw
  examples/wallet_smart_contract/src/main.sw
  sway-lib-std/src/assert.sw
  sway-lib-std/src/chain.sw
  sway-lib-std/src/lib.sw
  sway-lib-std/src/option.sw
  sway-lib-std/src/result.sw
  sway-lib-std/src/revert.sw
  sway-lib-std/src/token.sw
  test/src/e2e_vm_tests/test_programs/should_fail/abort_control_flow/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/abort_control_flow/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/ec_recover_test/src/main.sw
  test/src/sdk-harness/test_artifacts/reentrancy_attacker_contract/src/main.sw
  test/src/sdk-harness/test_artifacts/reentrancy_target_contract/src/main.sw
  test/src/sdk-harness/test_projects/option/src/main.sw
  test/src/sdk-harness/test_projects/result/src/main.sw
Labels: lib: std, breaking

#1497 Remove `Cargo.lock` from top-level `.gitignore`. Track `Cargo.lock` for std lib test harness.
  .gitignore
Labels: ci, testing

#1213 Remove global `Namespace` arena in favour of structural sharing. Refactor to use absolute paths.
  Cargo.lock
  forc-pkg/src/pkg.rs
  sway-core/Cargo.toml
  sway-core/src/asm_generation/mod.rs
  sway-core/src/error.rs
  sway-core/src/lib.rs
  sway-core/src/optimize.rs
  sway-core/src/parse_tree/call_path.rs
  sway-core/src/parse_tree/declaration/enum.rs
  sway-core/src/semantic_analysis.rs
  sway-core/src/semantic_analysis/ast_node/code_block.rs
  sway-core/src/semantic_analysis/ast_node/declaration.rs
  sway-core/src/semantic_analysis/ast_node/declaration/function.rs
  sway-core/src/semantic_analysis/ast_node/expression/enum_instantiation.rs
  sway-core/src/semantic_analysis/ast_node/expression/func_app_instantiation.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/method_application.rs
  sway-core/src/semantic_analysis/ast_node/impl_trait.rs
  sway-core/src/semantic_analysis/ast_node/mod.rs
  sway-core/src/semantic_analysis/namespace.rs
  sway-core/src/semantic_analysis/namespace/arena.rs
  sway-core/src/semantic_analysis/syntax_tree.rs
  sway-core/src/semantic_analysis/type_check_arguments.rs
  sway-core/utils/selector_debug.rs
  test/src/e2e_vm_tests/test_programs/should_fail/primitive_type_argument/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/primitive_type_argument/Forc.toml
Labels: compiler, code quality

#1503 Publish Diagnostics from language server even when no errors or warnings detected
  sway-lsp/src/capabilities/diagnostic.rs
  sway-lsp/src/server.rs
Labels: bug, language server

#1488 Add declaration attributes to the parser.
  sway-core/src/convert_parse_tree.rs
  sway-parse/src/attribute.rs
  sway-parse/src/error.rs
  sway-parse/src/item/mod.rs
  sway-parse/src/keywords.rs
  sway-parse/src/lib.rs
  sway-parse/src/priv_prelude.rs
  sway-parse/src/statement.rs
  sway-parse/src/token.rs
Labels: enhancement, language feature

#1504 Extract forc documentation examples from constants.rs into examples.rs
  scripts/forc-documenter/src/constants.rs
  scripts/forc-documenter/src/examples.rs
  scripts/forc-documenter/src/main.rs
Labels: documentation, code quality, The Sway Book

#1248 move `forc completions` help text into the book
  docs/src/forc/commands/forc_completions.md
  forc/src/cli/commands/completions.rs
  forc/src/cli/mod.rs
  scripts/forc-documenter/src/examples.rs
  scripts/forc-documenter/src/main.rs
Labels: documentation, forc

#1505 Improve forc documenter
  scripts/forc-documenter/src/checkers.rs
  scripts/forc-documenter/src/constants.rs
  scripts/forc-documenter/src/main.rs
Labels: ci, code quality

#1507 Updated example to show how to call a private function
  docs/src/blockchain-development/calling_contracts.md
Labels: documentation, enhancement, good first issue, The Sway Book

#1487 Manifest files use env variable to set author or default back to the …
  forc/src/utils/defaults.rs
  sway-utils/src/constants.rs
Labels: enhancement, good first issue, forc

#1450 Add --locked to cargo CI
  .github/workflows/ci.yml
  test/src/sdk-harness/build.sh
Labels: ci

#1442 Add --locked to forc
  docs/src/forc/commands/forc_build.md
  docs/src/forc/commands/forc_deploy.md
  docs/src/forc/commands/forc_run.md
  forc/src/cli/commands/build.rs
  forc/src/cli/commands/deploy.rs
  forc/src/cli/commands/run.rs
  forc/src/ops/forc_build.rs
  forc/src/ops/forc_deploy.rs
  forc/src/ops/forc_run.rs
Labels: enhancement, forc

#1480 Format long use stmnts + tests
  examples/liquidity_pool/src/main.sw
  examples/msg_sender/src/main.sw
  examples/subcurrency/src/main.sw
  examples/wallet_smart_contract/src/main.sw
  sway-fmt/src/code_builder_helpers.rs
  sway-fmt/src/traversal_helper.rs
Labels: enhancement, formatter

#1500 Add `require` function.
  sway-lib-std/src/assert.sw
  test/src/sdk-harness/test_projects/harness.rs
  test/src/sdk-harness/test_projects/require/.gitignore
  test/src/sdk-harness/test_projects/require/Forc.lock
  test/src/sdk-harness/test_projects/require/Forc.toml
  test/src/sdk-harness/test_projects/require/mod.rs
  test/src/sdk-harness/test_projects/require/src/main.sw
Labels: enhancement, lib: std

#1520 Bump fuels* to 0.12
  Cargo.lock
  forc-pkg/Cargo.toml
  forc/src/utils/defaults.rs
  sway-core/Cargo.toml
Labels: dependencies

#1515 Add numeric constants.
  sway-lib-core/src/lib.sw
  sway-lib-core/src/num.sw
Labels: enhancement, lib: core

#1528 Bump to v0.12.2
  Cargo.lock
  forc-explore/Cargo.toml
  forc-fmt/Cargo.toml
  forc-gm/Cargo.toml
  forc-lsp/Cargo.toml
  forc-pkg/Cargo.toml
  forc-util/Cargo.toml
  forc/Cargo.toml
  sway-core/Cargo.toml
  sway-fmt/Cargo.toml
  sway-ir/Cargo.toml
  sway-lsp/Cargo.toml
  sway-parse/Cargo.toml
  sway-types/Cargo.toml
  sway-utils/Cargo.toml
Labels: release

#1537 Make sure global const delcarations are not misreported as unused.
  sway-core/src/control_flow_analysis/dead_code_analysis.rs
Labels: bug, compiler, P: critical

#1539 Remove `rand` dependency from default Cargo.toml
  forc/src/utils/defaults.rs
Labels: forc, code quality

#1541 Fix asm for `get_ptr` when the offset is > 4096
  sway-core/src/asm_generation/from_ir.rs
  sway-core/tests/ir_to_asm/bigger_asm_block.asm
  sway-core/tests/ir_to_asm/enum_struct_string.asm
  sway-core/tests/ir_to_asm/let_reassign_while_loop.asm
  sway-core/tests/ir_to_asm/mutable_struct.asm
  sway-core/tests/ir_to_asm/simple_array.asm
  sway-core/tests/ir_to_asm/simple_contract_call.asm
  sway-core/tests/ir_to_asm/simple_enum.asm
  sway-core/tests/ir_to_asm/simple_if_let.asm
  sway-core/tests/ir_to_asm/simple_struct.asm
  sway-core/tests/ir_to_asm/storage_load.asm
  sway-core/tests/ir_to_asm/storage_store.asm
  sway-core/tests/ir_to_asm/struct_in_union.asm
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/should_pass/language/is_prime/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/many_stack_variables/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/many_stack_variables/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/many_stack_variables/src/main.sw
Labels: bug, compiler

#1542 Fix non-deterministic tuple names
  sway-core/src/constants.rs
  sway-core/src/convert_parse_tree.rs
Labels: bug, compiler, P: critical

#1524 Fix formatting aliases
  sway-fmt/src/traversal_helper.rs
Labels: bug, formatter

#1538 Add more detailed Forc.toml manifest reference documentation
  docs/src/SUMMARY.md
  docs/src/forc/manifest_reference.md
Labels: documentation, forc, The Sway Book

#1547 Added block comment example
  docs/src/basics/comments_and_logging.md
Labels: good first issue, The Sway Book

#1514 Adding `b256` bitwise operators (`&`, `|`, `^`)
  sway-lib-core/src/ops.sw
  test/src/sdk-harness/test_projects/b256_ops/.gitignore
  test/src/sdk-harness/test_projects/b256_ops/Forc.lock
  test/src/sdk-harness/test_projects/b256_ops/Forc.toml
  test/src/sdk-harness/test_projects/b256_ops/mod.rs
  test/src/sdk-harness/test_projects/b256_ops/src/main.sw
  test/src/sdk-harness/test_projects/context/mod.rs
  test/src/sdk-harness/test_projects/harness.rs
Labels: enhancement, lib: core

#1551 Update book links to `sway-lib-core` in Section 3.2
  docs/src/sway-program-types/libraries.md
Labels: The Sway Book

#1554 Impl Ord for b256
  sway-lib-core/src/ops.sw
  test/src/sdk-harness/test_projects/b256_ops/src/main.sw
Labels: enhancement, lib: core

#1562 Fixed Typo in book advanced Calls. #1561
  docs/src/blockchain-development/calling_contracts.md
Labels: The Sway Book

#1565 Update traits.md
  docs/src/advanced/traits.md
Labels: The Sway Book

#1566 Fixing the handling of constant strings by properly accounting for their size
  sway-core/src/asm_generation/from_ir.rs
  sway-core/tests/ir_to_asm/ret_string_in_struct.asm
  sway-core/tests/ir_to_asm/ret_string_in_struct.ir
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/should_pass/language/ret_string_in_struct/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/ret_string_in_struct/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/ret_string_in_struct/src/main.sw
Labels: bug, compiler, P: critical

#1545 Use forc-documenter as an mdbook preprocessor instead
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  docs/README.md
  docs/book.toml
  docs/src/forc/commands/forc_addr2line.md
  docs/src/forc/commands/forc_build.md
  docs/src/forc/commands/forc_clean.md
  docs/src/forc/commands/forc_completions.md
  docs/src/forc/commands/forc_deploy.md
  docs/src/forc/commands/forc_init.md
  docs/src/forc/commands/forc_json-abi.md
  docs/src/forc/commands/forc_parse-bytecode.md
  docs/src/forc/commands/forc_plugins.md
  docs/src/forc/commands/forc_run.md
  docs/src/forc/commands/forc_test.md
  docs/src/forc/commands/forc_update.md
  docs/src/forc/commands/index.md
  scripts/forc-documenter/Cargo.toml
  scripts/forc-documenter/README.md
  scripts/forc-documenter/src/checkers.rs
  scripts/forc-documenter/src/constants.rs
  scripts/forc-documenter/src/main.rs
  scripts/mdbook-forc-documenter/Cargo.toml
  scripts/mdbook-forc-documenter/README.md
  scripts/mdbook-forc-documenter/examples/forc_build.md
  scripts/mdbook-forc-documenter/examples/forc_completions.md
  scripts/mdbook-forc-documenter/examples/forc_deploy.md
  scripts/mdbook-forc-documenter/examples/forc_init.md
  scripts/mdbook-forc-documenter/examples/forc_parse-bytecode.md
  scripts/mdbook-forc-documenter/examples/forc_test.md
  scripts/mdbook-forc-documenter/src/bin/mdbook-forc-documenter.rs
  scripts/mdbook-forc-documenter/src/formatter.rs
  scripts/mdbook-forc-documenter/src/lib.rs
Labels: documentation, forc, The Sway Book

#1569 Fix CI not installing mdbook-forc-documenter preprocessor. Fix out-of-date `Cargo.lock` file missing pest dependencies.
  .github/workflows/ci.yml
  .github/workflows/gh-pages.yml
  Cargo.lock
Labels: bug, ci, The Sway Book, P: critical

#1559 Add a Spanned trait to the parser
  sway-core/src/convert_parse_tree.rs
  sway-parse/src/assignable.rs
  sway-parse/src/attribute.rs
  sway-parse/src/brackets.rs
  sway-parse/src/dependency.rs
  sway-parse/src/expr/asm.rs
  sway-parse/src/expr/mod.rs
  sway-parse/src/expr/op_code.rs
  sway-parse/src/generics.rs
  sway-parse/src/item/item_abi.rs
  sway-parse/src/item/item_const.rs
  sway-parse/src/item/item_enum.rs
  sway-parse/src/item/item_fn.rs
  sway-parse/src/item/item_impl.rs
  sway-parse/src/item/item_storage.rs
  sway-parse/src/item/item_struct.rs
  sway-parse/src/item/item_trait.rs
  sway-parse/src/item/item_use.rs
  sway-parse/src/item/mod.rs
  sway-parse/src/keywords.rs
  sway-parse/src/literal.rs
  sway-parse/src/path.rs
  sway-parse/src/pattern.rs
  sway-parse/src/priv_prelude.rs
  sway-parse/src/program.rs
  sway-parse/src/span.rs
  sway-parse/src/statement.rs
  sway-parse/src/token.rs
  sway-parse/src/ty/mod.rs
  sway-parse/src/where_clause.rs
  sway-types/src/span.rs
Labels: enhancement, compiler

#1576 Remove compiler warnings
  sway-lib-core/src/num.sw
  sway-lib-core/src/ops.sw
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/should_pass/language/numeric_constants/.gitignore
  test/src/e2e_vm_tests/test_programs/should_pass/language/numeric_constants/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/numeric_constants/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/numeric_constants/src/main.sw
Labels: code quality, lib: core

#1586 Refactoring for readability and maintainability
  sway-core/src/semantic_analysis/ast_node/declaration.rs
  sway-core/src/semantic_analysis/ast_node/declaration/enum.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/namespace.rs
  sway-core/src/semantic_analysis/namespace/items.rs
  sway-core/src/semantic_analysis/namespace/mod.rs
  sway-core/src/semantic_analysis/namespace/module.rs
  sway-core/src/semantic_analysis/namespace/namespace.rs
  sway-core/src/semantic_analysis/namespace/root.rs
  sway-core/src/semantic_analysis/namespace/submodule_namespace.rs
  sway-core/src/semantic_analysis/namespace/trait_map.rs
Labels: compiler, code quality

#1544 Added generic sha256
  examples/hashing/src/main.sw
  sway-lib-std/src/hash.sw
  test/src/sdk-harness/Cargo.toml
  test/src/sdk-harness/test_projects/hashing/mod.rs
  test/src/sdk-harness/test_projects/hashing/src/main.sw
Labels: enhancement, good first issue, lib: std

#1588 Improvements to namespace API and declaration ABI.
  sway-core/src/error.rs
  sway-core/src/semantic_analysis/ast_node/declaration.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/method_application.rs
  sway-core/src/semantic_analysis/ast_node/mod.rs
  sway-core/src/semantic_analysis/namespace/namespace.rs
  sway-core/src/semantic_analysis/namespace/root.rs
Labels: compiler

#1573 Adding an intrinsics module
  sway-lib-std/src/intrinsics.sw
  sway-lib-std/src/lib.sw
  test/src/sdk-harness/test_projects/harness.rs
  test/src/sdk-harness/test_projects/intrinsics/.gitignore
  test/src/sdk-harness/test_projects/intrinsics/Forc.lock
  test/src/sdk-harness/test_projects/intrinsics/Forc.toml
  test/src/sdk-harness/test_projects/intrinsics/mod.rs
  test/src/sdk-harness/test_projects/intrinsics/src/main.sw
Labels: lib: std

#1572 Adding a generic `log` function
  examples/hashing/src/main.sw
  examples/signatures/src/main.sw
  sway-lib-std/src/assert.sw
  sway-lib-std/src/chain.sw
  sway-lib-std/src/lib.sw
  sway-lib-std/src/logging.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/u64_ops/src/main.sw
  test/src/sdk-harness/test_projects/b256_ops/src/main.sw
  test/src/sdk-harness/test_projects/logging/src/main.sw
Labels: enhancement, lib: std, breaking

#1599 Cleanup constants.sw & add impl b256 to core/num
  examples/hashing/src/main.sw
  sway-lib-core/src/num.sw
  sway-lib-std/src/constants.sw
  sway-lib-std/src/hash.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/caller_context_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/b512_test/src/main.sw
  test/src/sdk-harness/test_artifacts/auth_caller_contract/src/main.sw
  test/src/sdk-harness/test_artifacts/reentrancy_attacker_contract/src/main.sw
  test/src/sdk-harness/test_artifacts/reentrancy_target_contract/src/main.sw
  test/src/sdk-harness/test_projects/b256_ops/src/main.sw
  test/src/sdk-harness/test_projects/hashing/src/main.sw
  test/src/sdk-harness/test_projects/intrinsics/src/main.sw
Labels: lib: std, code quality, lib: core

#1603 Fix space formatting between parenthesis and opening quotation marks
  examples/hashing/src/main.sw
  sway-fmt/src/code_builder.rs
  sway-fmt/src/fmt.rs
Labels: bug, formatter

#1518 Replace the `impure` keyword with `#[storage(...)]` annotations.
  docs/src/blockchain-development/purity.md
  sway-core/src/constants.rs
  sway-core/src/convert_parse_tree.rs
  sway-core/src/error.rs
  sway-core/src/parse_tree/declaration/function.rs
  sway-core/src/parse_tree/declaration/function/purity.rs
  sway-core/src/parse_tree/declaration/trait.rs
  sway-core/src/semantic_analysis/ast_node/declaration.rs
  sway-core/src/semantic_analysis/ast_node/expression/func_app_instantiation.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/method_application.rs
  sway-core/src/semantic_analysis/ast_node/impl_trait.rs
  sway-core/src/semantic_analysis/ast_node/mod.rs
  sway-core/src/semantic_analysis/syntax_tree.rs
  sway-fmt-v2/src/fmt.rs
  sway-parse/src/attribute.rs
  sway-parse/src/expr/mod.rs
  sway-parse/src/item/item_abi.rs
  sway-parse/src/item/item_impl.rs
  sway-parse/src/item/item_trait.rs
  sway-parse/src/item/mod.rs
  sway-parse/src/keywords.rs
  sway-parse/src/lib.rs
  sway-parse/src/priv_prelude.rs
  sway-parse/src/statement.rs
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/should_fail/abi_impl_purity_mismatch/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/abi_impl_purity_mismatch/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/abi_impl_purity_mismatch/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/abi_pure_calls_impure/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/abi_pure_calls_impure/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/abi_pure_calls_impure/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/contract_pure_calls_impure/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/impure_abi_read_calls_impure_write/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/impure_abi_read_calls_impure_write/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/impure_abi_read_calls_impure_write/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/impure_read_calls_impure_write/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/impure_read_calls_impure_write/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/impure_read_calls_impure_write/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/impure_trait_read_calls_impure_write/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/impure_trait_read_calls_impure_write/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/impure_trait_read_calls_impure_write/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/nested_impure/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/predicate_calls_impure/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/pure_calls_impure/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/script_calls_impure/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/trait_impl_purity_mismatch/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/trait_impl_purity_mismatch/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/trait_impl_purity_mismatch/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/trait_pure_calls_impure/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/trait_pure_calls_impure/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/trait_pure_calls_impure/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/valid_impurity/src/main.sw
Labels: enhancement, compiler

#1558 Parse tuple field reassignments
  sway-core/src/convert_parse_tree.rs
  sway-parse/src/assignable.rs
  sway-parse/src/expr/mod.rs
Labels: enhancement, compiler

#1420 Disallow assigning to fields of non-mutable structs
  sway-core/src/semantic_analysis/ast_node/mod.rs
  sway-core/tests/sway_to_ir/impl_self_reassignment.ir.disabled
  sway-core/tests/sway_to_ir/impl_self_reassignment.sw.disabled
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/should_fail/assign_to_field_of_non_mutable_struct/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/assign_to_field_of_non_mutable_struct/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/assign_to_field_of_non_mutable_struct/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/nested_structs/src/main.sw
Labels: bug, compiler

#1604 Fix Shiftable trait to shift by u64.
  sway-lib-core/src/ops.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/if_implicit_unit/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/trait_import_with_star/src/shiftable.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/trait_override_bug/src/main.sw
Labels: bug, lib: core, P: critical

#1606 Added generic keccak256 function
  examples/hashing/src/main.sw
  sway-lib-std/src/hash.sw
  test/src/sdk-harness/Cargo.toml
  test/src/sdk-harness/test_projects/hashing/mod.rs
  test/src/sdk-harness/test_projects/hashing/src/main.sw
Labels: enhancement, good first issue, lib: std

#1610 Deprecating old functions
  docs/src/reference/temporary_workarounds.md
  examples/hashing/src/main.sw
  examples/subcurrency/src/main.sw
  sway-fmt/src/fmt.rs
  sway-lib-std/src/ecr.sw
  sway-lib-std/src/hash.sw
  sway-lib-std/src/vm/evm/ecr.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/b256_ops/src/main.sw
  test/src/sdk-harness/test_projects/hashing/mod.rs
  test/src/sdk-harness/test_projects/hashing/src/main.sw
Labels: good first issue, lib: std, code quality

#1589 Introduce the `CopyTypes` trait and the `TypeMapping` type.
  sway-core/src/parse_tree/declaration/enum.rs
  sway-core/src/parse_tree/declaration/type_parameter.rs
  sway-core/src/semantic_analysis/ast_node/code_block.rs
  sway-core/src/semantic_analysis/ast_node/copy_types.rs
  sway-core/src/semantic_analysis/ast_node/declaration.rs
  sway-core/src/semantic_analysis/ast_node/declaration/enum.rs
  sway-core/src/semantic_analysis/ast_node/declaration/function.rs
  sway-core/src/semantic_analysis/ast_node/declaration/function/function_parameter.rs
  sway-core/src/semantic_analysis/ast_node/declaration/struct.rs
  sway-core/src/semantic_analysis/ast_node/declaration/variable.rs
  sway-core/src/semantic_analysis/ast_node/expression/struct_expr_field.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression_variant.rs
  sway-core/src/semantic_analysis/ast_node/mod.rs
  sway-core/src/semantic_analysis/ast_node/return_statement.rs
  sway-core/src/semantic_analysis/namespace/items.rs
Labels: compiler

#1590 Introduce the `CreateTypeId` trait.
  Cargo.lock
  sway-core/src/asm_generation/expression/enums.rs
  sway-core/src/semantic_analysis/ast_node/declaration.rs
  sway-core/src/semantic_analysis/ast_node/declaration/create_type_id.rs
  sway-core/src/semantic_analysis/ast_node/declaration/enum.rs
  sway-core/src/semantic_analysis/ast_node/declaration/struct.rs
  sway-core/src/semantic_analysis/ast_node/expression/enum_instantiation.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/namespace/root.rs
Labels: compiler

#1607 Enable to deploy a contract to another node with --url option
  forc/src/cli/commands/deploy.rs
  forc/src/ops/forc_deploy.rs
Labels: enhancement, forc, P: critical

#1618 Fix bug where `mdbook-forc-documenter` would panic if `mdbook build` called not in Sway root
  scripts/mdbook-forc-documenter/src/lib.rs
  scripts/mdbook-forc-documenter/src/plugins.rs
Labels: bug, The Sway Book

#1575 Transition to tracing in forc (and throughout sway) over println
  Cargo.lock
  forc-explore/Cargo.toml
  forc-explore/src/main.rs
  forc-fmt/Cargo.toml
  forc-fmt/src/main.rs
  forc-pkg/Cargo.toml
  forc-pkg/src/pkg.rs
  forc-util/Cargo.toml
  forc-util/src/lib.rs
  forc/Cargo.toml
  forc/src/cli/commands/addr2line.rs
  forc/src/cli/commands/parse_bytecode.rs
  forc/src/cli/commands/plugins.rs
  forc/src/cli/commands/test.rs
  forc/src/main.rs
  forc/src/ops/forc_abi_json.rs
  forc/src/ops/forc_build.rs
  forc/src/ops/forc_deploy.rs
  forc/src/ops/forc_init.rs
  forc/src/ops/forc_run.rs
  forc/src/ops/forc_update.rs
  forc/src/utils/defaults.rs
  scripts/examples-checker/Cargo.toml
  scripts/mdbook-forc-documenter/Cargo.toml
  sway-core/Cargo.toml
  sway-core/src/asm_generation/finalized_asm.rs
  sway-core/src/asm_generation/from_ir.rs
  sway-core/src/asm_generation/mod.rs
  sway-core/src/control_flow_analysis/flow_graph/mod.rs
  sway-core/src/lib.rs
  sway-core/src/optimize.rs
  sway-core/src/parse_tree/expression/matcher.rs
  sway-core/src/parse_tree/expression/mod.rs
  sway-ir/Cargo.toml
  sway-ir/src/bin/opt.rs
  sway-ir/tests/tests.rs
  test-sig-gen-util/Cargo.toml
  test-sig-gen-util/src/main.rs
  test/Cargo.toml
  test/src/e2e_vm_tests/harness.rs
  test/src/e2e_vm_tests/mod.rs
Labels: enhancement, forc

#1611 Fixing how the number of predecessors of an IR block is calculated
  sway-core/tests/sway_to_ir/implicit_return.ir
  sway-core/tests/sway_to_ir/implicit_return.sw
  sway-ir/src/block.rs
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/should_pass/language/implicit_return/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/implicit_return/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/implicit_return/src/main.sw
Labels: bug, compiler, P: critical

#1595 Finish parsing `where` clauses
  sway-core/src/convert_parse_tree.rs
  sway-core/src/error.rs
  sway-core/src/parse_tree/declaration/type_parameter.rs
  sway-core/src/semantic_analysis/ast_node/impl_trait.rs
  sway-core/src/semantic_analysis/ast_node/mod.rs
  sway-core/src/semantic_analysis/node_dependencies.rs
  sway-parse/src/item/item_impl.rs
Labels: enhancement, compiler, language feature

#1624 Test suite does not print details with SWAY_TEST_VERBOSE=1
  forc-util/src/lib.rs
Labels: bug, forc

#1625 Bump SDK version to Fuels `v0.13`
  forc/src/utils/defaults.rs
  test/src/sdk-harness/Cargo.toml
  test/src/sdk-harness/test_helpers/Cargo.toml
  test/src/sdk-harness/test_projects/auth/mod.rs
  test/src/sdk-harness/test_projects/call_frames/mod.rs
  test/src/sdk-harness/test_projects/context/mod.rs
  test/src/sdk-harness/test_projects/hashing/mod.rs
  test/src/sdk-harness/test_projects/reentrancy/mod.rs
  test/src/sdk-harness/test_projects/registers/mod.rs
  test/src/sdk-harness/test_projects/token_ops/mod.rs
  test/src/sdk-harness/test_projects/tx_fields/mod.rs
Labels: testing, dependencies

#1341 standard library introduction
  docs/src/SUMMARY.md
  docs/src/introduction/index.md
  docs/src/introduction/standard_library.md
Labels: The Sway Book

#1630 Fixing how the tx receipts root is obtained
  sway-lib-std/src/tx.sw
  test/src/sdk-harness/test_projects/tx_fields/mod.rs
Labels: bug, lib: std

#1582 document native plugins within the Sway book
  .github/workflows/ci.yml
  .github/workflows/gh-pages.yml
  Cargo.toml
  docs/src/SUMMARY.md
  docs/src/forc_explore.md
  docs/src/forc_fmt.md
  docs/src/forc_lsp.md
  forc-plugins/forc-explore/Cargo.toml
  forc-plugins/forc-explore/src/main.rs
  forc-plugins/forc-fmt/Cargo.toml
  forc-plugins/forc-fmt/src/main.rs
  forc-plugins/forc-lsp/Cargo.toml
  forc-plugins/forc-lsp/src/main.rs
  scripts/mdbook-forc-documenter/src/commands.rs
  scripts/mdbook-forc-documenter/src/formatter.rs
  scripts/mdbook-forc-documenter/src/lib.rs
  scripts/mdbook-forc-documenter/src/plugins.rs
Labels: documentation, forc, ci, The Sway Book

#1592 Improvements to monomorphization + bug fixes
  sway-core/src/asm_generation/expression/mod.rs
  sway-core/src/control_flow_analysis/dead_code_analysis.rs
  sway-core/src/optimize.rs
  sway-core/src/parse_tree/declaration/enum.rs
  sway-core/src/semantic_analysis/ast_node/declaration/enum.rs
  sway-core/src/semantic_analysis/ast_node/declaration/function.rs
  sway-core/src/semantic_analysis/ast_node/declaration/monomorphize.rs
  sway-core/src/semantic_analysis/ast_node/declaration/struct.rs
  sway-core/src/semantic_analysis/ast_node/expression/enum_instantiation.rs
  sway-core/src/semantic_analysis/ast_node/expression/func_app_instantiation.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/method_application.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression_variant.rs
  sway-core/src/semantic_analysis/ast_node/impl_trait.rs
  sway-core/src/semantic_analysis/ast_node/mod.rs
  sway-core/src/semantic_analysis/namespace/namespace.rs
  sway-core/src/semantic_analysis/namespace/root.rs
  sway-core/src/semantic_analysis/node_dependencies.rs
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_abi_with_tuples/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_abi_with_tuples/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_abi_with_tuples/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_abi_with_tuples/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/test_abis/abi_with_tuples/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/test_abis/abi_with_tuples/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/test_abis/abi_with_tuples/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/test_abis/abi_with_tuples/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/test_abis/context_testing_abi/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/abi_with_tuples_contract/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/abi_with_tuples_contract/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/abi_with_tuples_contract/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/abi_with_tuples_contract/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/context_testing_contract/src/main.sw
Labels: compiler, P: critical

#1614 forc template implementation
  Cargo.lock
  docs/src/SUMMARY.md
  docs/src/forc/commands/forc_template.md
  forc-pkg/src/pkg.rs
  forc/Cargo.toml
  forc/src/cli/commands/init.rs
  forc/src/cli/commands/mod.rs
  forc/src/cli/commands/template.rs
  forc/src/cli/mod.rs
  forc/src/ops/forc_init.rs
  forc/src/ops/forc_template.rs
  forc/src/ops/mod.rs
  scripts/mdbook-forc-documenter/examples/forc_template.md
Labels: enhancement, forc

#1632 Fixing JSON ABI and the function selector for arrays
  sway-core/src/type_engine.rs
  sway-core/src/type_engine/type_info.rs
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/array_of_structs_caller/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/array_of_structs_caller/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/array_of_structs_caller/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/array_of_structs_caller/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/test_abis/array_of_structs_abi/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/test_abis/array_of_structs_abi/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/test_abis/array_of_structs_abi/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/test_abis/array_of_structs_abi/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/array_of_structs_contract/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/array_of_structs_contract/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/array_of_structs_contract/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/array_of_structs_contract/src/main.sw
Labels: bug, compiler, P: critical, ABI

#1658 Add missing dependency in 2 test cases to supress unnecessary warnings
  test/src/e2e_vm_tests/test_programs/should_fail/match_expressions_enums/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/match_expressions_non_exhaustive/Forc.toml
Labels: bug, testing

#1647 Add booleans to the keywords in the parser
  sway-core/src/convert_parse_tree.rs
  sway-parse/src/expr/mod.rs
  sway-parse/src/keywords.rs
  sway-parse/src/literal.rs
  sway-parse/src/pattern.rs
  sway-parse/src/priv_prelude.rs
Labels: compiler, code quality

#1654 Adding `jnzi` to `parse_bytecode` and fixing some notes
  Cargo.lock
  forc/Cargo.toml
  forc/src/cli/commands/parse_bytecode.rs
  sway-core/Cargo.toml
  sway-types/Cargo.toml
  test/Cargo.toml
Labels: enhancement, compiler

#1666 Adding `update_type()` to refactor some code used in `copy_types()`
  sway-core/src/semantic_analysis/ast_node/copy_types.rs
  sway-core/src/semantic_analysis/ast_node/declaration.rs
  sway-core/src/semantic_analysis/ast_node/declaration/enum.rs
  sway-core/src/semantic_analysis/ast_node/declaration/function.rs
  sway-core/src/semantic_analysis/ast_node/declaration/function/function_parameter.rs
  sway-core/src/semantic_analysis/ast_node/declaration/struct.rs
  sway-core/src/semantic_analysis/ast_node/declaration/variable.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression_variant.rs
Labels: compiler, code quality

#1662 Updated welcome message colors
  forc-util/src/lib.rs
  forc/src/ops/forc_init.rs
Labels: enhancement, good first issue, forc

#1653 Fixing JSON ABI for tuples
  sway-core/src/parse_tree/declaration/type_argument.rs
  sway-core/src/type_engine.rs
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_abi_with_tuples/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/abi_with_tuples_contract/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/basic_storage/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/issue_1512_repro/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/storage_access_contract/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/test_fuel_coin_contract/json_abi_oracle.json
Labels: bug, compiler, P: critical, ABI

#1672 Small improvements to the Sway Book
  docs/src/basics/control_flow.md
  docs/src/reference/rust_differences.md
  examples/msg_sender/src/main.sw
  examples/signatures/src/main.sw
  examples/wallet_smart_contract/src/main.sw
Labels: The Sway Book

#1642 Expand match expressions to encompass enums
  sway-core/src/asm_generation/expression/mod.rs
  sway-core/src/asm_generation/mod.rs
  sway-core/src/control_flow_analysis/dead_code_analysis.rs
  sway-core/src/convert_parse_tree.rs
  sway-core/src/optimize.rs
  sway-core/src/parse_tree/expression/matcher.rs
  sway-core/src/parse_tree/expression/mod.rs
  sway-core/src/parse_tree/expression/scrutinee.rs
  sway-core/src/semantic_analysis/ast_node/code_block.rs
  sway-core/src/semantic_analysis/ast_node/expression/match_expression/analysis/constructor_factory.rs
  sway-core/src/semantic_analysis/ast_node/expression/match_expression/analysis/patstack.rs
  sway-core/src/semantic_analysis/ast_node/expression/match_expression/analysis/pattern.rs
  sway-core/src/semantic_analysis/ast_node/expression/match_expression/analysis/range.rs
  sway-core/src/semantic_analysis/ast_node/expression/match_expression/analysis/usefulness.rs
  sway-core/src/semantic_analysis/ast_node/expression/match_expression/mod.rs
  sway-core/src/semantic_analysis/ast_node/expression/match_expression/typed/matcher.rs
  sway-core/src/semantic_analysis/ast_node/expression/match_expression/typed/mod.rs
  sway-core/src/semantic_analysis/ast_node/expression/match_expression/typed/typed_match_expression.rs
  sway-core/src/semantic_analysis/ast_node/expression/match_expression/typed/typed_scrutinee.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/unsafe_downcast.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression_variant.rs
  sway-core/src/semantic_analysis/node_dependencies.rs
  sway-core/src/type_engine/type_info.rs
  sway-core/src/type_engine/unresolved_type_check.rs
  sway-core/tests/sway_to_ir/enum_struct_string.ir.disabled
  sway-core/tests/sway_to_ir/enum_struct_string.sw.disabled
  sway-core/tests/sway_to_ir/if_let_simple.ir.disabled
  sway-core/tests/sway_to_ir/if_let_simple.sw.disabled
  sway-lsp/src/core/token.rs
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/should_fail/abort_control_flow_bad/.gitignore
  test/src/e2e_vm_tests/test_programs/should_fail/abort_control_flow_bad/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/abort_control_flow_bad/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/abort_control_flow_bad/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/match_expressions_empty_arms/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/match_expressions_empty_arms/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/match_expressions_empty_arms/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/match_expressions_enums/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/match_expressions_enums/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_fail/match_expressions_enums/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/match_expressions_wrong_struct/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/abort_control_flow_good/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/abort_control_flow_good/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/abort_control_flow_good/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/match_expressions_enums/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/match_expressions_enums/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/match_expressions_enums/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/match_expressions_mismatched/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/match_expressions_mismatched/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/match_expressions_mismatched/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/match_expressions_nested/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/match_expressions_nested/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/match_expressions_nested/src/main.sw
Labels: enhancement, compiler, language feature, P: critical

#1668 Bump to v0.13.2
  Cargo.lock
  forc-gm/Cargo.toml
  forc-pkg/Cargo.toml
  forc-plugins/forc-explore/Cargo.toml
  forc-plugins/forc-fmt/Cargo.toml
  forc-plugins/forc-lsp/Cargo.toml
  forc-util/Cargo.toml
  forc/Cargo.toml
  sway-core/Cargo.toml
  sway-fmt-v2/Cargo.toml
  sway-fmt/Cargo.toml
  sway-ir/Cargo.toml
  sway-lsp/Cargo.toml
  sway-parse/Cargo.toml
  sway-types/Cargo.toml
  sway-utils/Cargo.toml
Labels: release

#1543 Docker Fixes
  .github/workflows/ci.yml
  deployment/Dockerfile
Labels: bug, forc

#1678 Fix incorrect collection of tokens from tuples in the language server
  sway-lsp/src/core/token.rs
Labels: bug, language server

#1680 Remove `forc-gm` in the docs for now
  docs/src/forc/plugins.md
Labels: The Sway Book, P: high

#1683 Bump fuel-core to v0.8, and sub-deps.
  .github/workflows/ci.yml
  Cargo.lock
  forc/Cargo.toml
  forc/src/ops/forc_deploy.rs
  forc/src/utils/parameters.rs
  sway-core/Cargo.toml
  sway-types/Cargo.toml
  test-sig-gen-util/Cargo.toml
  test/Cargo.toml
  test/src/e2e_vm_tests/harness.rs
  test/src/e2e_vm_tests/test_programs/should_pass/language/u64_ops/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/array_of_structs_caller/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/bal_opcode/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_abi_with_tuples/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_basic_storage/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_increment_contract/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/caller_auth_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/caller_context_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/nested_struct_args_caller/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/storage_access_caller/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/token_ops_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/u128_test/src/main.sw
Labels: dependencies, breaking

#1549 Implement left & right shift for `b256`
  sway-lib-core/src/ops.sw
  test/src/sdk-harness/test_projects/b256_ops/src/main.sw
Labels: enhancement, lib: core

#1690 Fix the `template` command for the `counter` example
  docs/src/examples/counter.md
Labels: The Sway Book

#1695 Fix comment location in testing with rust
  docs/src/testing/testing-with-rust.md
Labels: bug, The Sway Book

#1687 Move unnecessary usage of SDK for tests to e2e tests
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/should_pass/language/b256_bitwise_ops/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/b256_bitwise_ops/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/b256_bitwise_ops/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/contract_id_type/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/contract_id_type/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/contract_id_type/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/evm_ecr/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/evm_ecr/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/evm_ecr/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/intrinsics/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/intrinsics/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/intrinsics/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/option/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/option/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/option/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/require/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/require/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/require/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/result/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/result/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/result/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/u128_div_test/.gitignore
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/u128_mul_test/.gitignore
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/u128_test/.gitignore
  test/src/sdk-harness/test_projects/b256_ops/.gitignore
  test/src/sdk-harness/test_projects/b256_ops/Forc.toml
  test/src/sdk-harness/test_projects/b256_ops/mod.rs
  test/src/sdk-harness/test_projects/contract_id_type/.gitignore
  test/src/sdk-harness/test_projects/contract_id_type/mod.rs
  test/src/sdk-harness/test_projects/evm_ecr/.gitignore
  test/src/sdk-harness/test_projects/evm_ecr/mod.rs
  test/src/sdk-harness/test_projects/harness.rs
  test/src/sdk-harness/test_projects/intrinsics/.gitignore
  test/src/sdk-harness/test_projects/intrinsics/mod.rs
  test/src/sdk-harness/test_projects/option/mod.rs
  test/src/sdk-harness/test_projects/require/.gitignore
  test/src/sdk-harness/test_projects/require/mod.rs
  test/src/sdk-harness/test_projects/result/mod.rs
Labels: code quality, testing

#1699 Add more highlighted languages
  docs/theme/highlight.js
  scripts/highlightjs/build.sh
Labels: The Sway Book

#1700 Remove sdk-harness script lib.
  test/src/sdk-harness/Cargo.toml
  test/src/sdk-harness/Forc.lock
  test/src/sdk-harness/Forc.toml
  test/src/sdk-harness/README.md
  test/src/sdk-harness/src/main.sw
  test/src/sdk-harness/test_helpers/Cargo.toml
  test/src/sdk-harness/test_helpers/src/lib.rs
Labels: lib: std, testing

#1703 Remove fuels-signers from SDK harness.
  test/src/sdk-harness/Cargo.toml
  test/src/sdk-harness/test_projects/auth/mod.rs
Labels: lib: std, testing

#1704 Remove rand from SDK harness.
  test/src/sdk-harness/Cargo.toml
Labels: lib: std, testing

#1688 New intrinsic for generating a unique `b256` key
  sway-core/src/asm_generation/from_ir.rs
  sway-core/src/constants.rs
  sway-core/src/control_flow_analysis/dead_code_analysis.rs
  sway-core/src/convert_parse_tree.rs
  sway-core/src/optimize.rs
  sway-core/src/parse_tree/expression/mod.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression_variant.rs
  sway-core/src/semantic_analysis/node_dependencies.rs
  sway-core/src/type_engine/unresolved_type_check.rs
  sway-core/tests/ir_to_asm/generate_uid.asm
  sway-core/tests/ir_to_asm/generate_uid.ir
  sway-core/tests/sway_to_ir/generate_uid.ir
  sway-core/tests/sway_to_ir/generate_uid.sw
  sway-ir/src/instruction.rs
  sway-ir/src/optimize/inline.rs
  sway-ir/src/parser.rs
  sway-ir/src/printer.rs
  sway-ir/src/verify.rs
  sway-lsp/src/core/token.rs
  sway-parse/src/intrinsics.rs
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/should_pass/language/generate_uid/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/generate_uid/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/generate_uid/src/main.sw
Labels: enhancement, compiler, language feature

#1709 Bump SDK harness fuels-rs to 0.14
  test/src/sdk-harness/Cargo.toml
  test/src/sdk-harness/test_projects/auth/mod.rs
  test/src/sdk-harness/test_projects/call_frames/mod.rs
  test/src/sdk-harness/test_projects/context/mod.rs
  test/src/sdk-harness/test_projects/hashing/mod.rs
  test/src/sdk-harness/test_projects/logging/mod.rs
  test/src/sdk-harness/test_projects/reentrancy/mod.rs
  test/src/sdk-harness/test_projects/registers/mod.rs
  test/src/sdk-harness/test_projects/token_ops/mod.rs
  test/src/sdk-harness/test_projects/tx_fields/mod.rs
Labels: testing, dependencies

#1711 Improve installation docs.
  docs/src/introduction/installation.md
Labels: The Sway Book

#1708 Bump fuels-rs init version to 0.14
  forc/src/utils/defaults.rs
Labels: forc

#1235 Storage with more than one word.
  sway-lib-std/src/storage.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_basic_storage/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_increment_contract/src/main.sw
  test/src/sdk-harness/test_projects/harness.rs
  test/src/sdk-harness/test_projects/storage/.gitignore
  test/src/sdk-harness/test_projects/storage/Forc.lock
  test/src/sdk-harness/test_projects/storage/Forc.toml
  test/src/sdk-harness/test_projects/storage/mod.rs
  test/src/sdk-harness/test_projects/storage/src/main.sw
Labels: enhancement, lib: std

#1721 Add a note saying that the storage attributes are still WIP
  docs/src/blockchain-development/purity.md
Labels: The Sway Book

#1722 Adding some known issues to the docs
  docs/src/SUMMARY.md
  docs/src/reference/index.md
  docs/src/reference/known_issues_and_workarounds.md
  docs/src/reference/temporary_workarounds.md
Labels: The Sway Book

#1725 Update the Rust SDK test
  docs/src/testing/testing-with-rust.md
Labels: The Sway Book

#1727 Update the logging section in the Sway Book
  docs/src/basics/comments_and_logging.md
Labels: The Sway Book

#1731 Improve stdlib section in book.
  docs/src/introduction/standard_library.md
Labels: The Sway Book

#1728 update README related to Forc commands/plugins
  docs/README.md
  scripts/mdbook-forc-documenter/README.md
Labels: documentation, The Sway Book

#1735 Adding an `else` in the U128 library to bypass a bogus warning
  sway-lib-std/src/u128.sw
Labels: lib: std, P: critical

#1736 Update examples.
  docs/src/examples/counter.md
  docs/src/examples/fizzbuzz.md
  docs/src/examples/subcurrency.md
  docs/src/examples/wallet_smart_contract.md
  examples/subcurrency/src/main.sw
  examples/wallet_smart_contract/src/main.sw
Labels: The Sway Book

#1732 Change any instance of `if let .. { .. } else { .. }` in the standard library to use match expressions
  sway-lib-std/src/chain/auth.sw
  sway-lib-std/src/option.sw
  sway-lib-std/src/result.sw
  sway-lib-std/src/vm/evm/ecr.sw
Labels: compiler, code quality

#1737 v0.14.2
  Cargo.lock
  forc-gm/Cargo.toml
  forc-pkg/Cargo.toml
  forc-plugins/forc-explore/Cargo.toml
  forc-plugins/forc-fmt/Cargo.toml
  forc-plugins/forc-lsp/Cargo.toml
  forc-util/Cargo.toml
  forc/Cargo.toml
  sway-core/Cargo.toml
  sway-fmt-v2/Cargo.toml
  sway-fmt/Cargo.toml
  sway-ir/Cargo.toml
  sway-lsp/Cargo.toml
  sway-parse/Cargo.toml
  sway-types/Cargo.toml
  sway-utils/Cargo.toml
Labels: release

#1729 Improve Sway toolchain docs.
  docs/src/introduction/sway-toolchain.md
Labels: The Sway Book

#1739 Remove a known issue from the book related to #1682
  docs/src/reference/known_issues_and_workarounds.md
Labels: The Sway Book

#1717 forc run output is formatted such that key! types and data fields are…
  forc/src/ops/forc_run.rs
Labels: enhancement, forc

#1743 Standardize "notes" in the Sway Book
  docs/src/basics/comments_and_logging.md
  docs/src/basics/structs_and_tuples.md
  docs/src/blockchain-development/calling_contracts.md
  docs/src/blockchain-development/hashing_and_cryptography.md
  docs/src/blockchain-development/storage.md
  docs/src/introduction/installation.md
  docs/src/introduction/overview.md
  docs/src/introduction/sway-toolchain.md
Labels: The Sway Book

#1745 Improve the libraries section
  docs/src/sway-program-types/libraries.md
Labels: The Sway Book

#1720 Test suite does not print test names, tracing usage in test suite fixed
  Cargo.lock
  forc-util/src/lib.rs
  test/Cargo.toml
  test/src/e2e_vm_tests/mod.rs
Labels: bug, forc

#1744 Add an exponentiation trait
  sway-lib-std/src/math.sw
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/exponentiation_test/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/exponentiation_test/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/exponentiation_test/src/main.sw
  test/src/sdk-harness/test_artifacts/pow/.gitignore
  test/src/sdk-harness/test_artifacts/pow/Forc.lock
  test/src/sdk-harness/test_artifacts/pow/Forc.toml
  test/src/sdk-harness/test_artifacts/pow/src/main.sw
  test/src/sdk-harness/test_projects/exponentiation/mod.rs
  test/src/sdk-harness/test_projects/harness.rs
Labels: enhancement, lib: std

#1746 Fix bugs with resolving type parameters
  sway-core/src/semantic_analysis/ast_node/declaration/enum.rs
  sway-core/src/semantic_analysis/ast_node/declaration/function.rs
  sway-core/src/semantic_analysis/ast_node/declaration/struct.rs
  sway-core/src/type_engine/type_info.rs
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/should_fail/type_mismatch_error_message/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/type_mismatch_error_message/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/type_mismatch_error_message/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/generic_inside_generic/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/generic_inside_generic/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/generic_inside_generic/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/match_expressions_inside_generic_functions/src/main.sw
Labels: bug, compiler, P: critical

#1749 Bump to v0.14.3
  Cargo.lock
  forc-gm/Cargo.toml
  forc-pkg/Cargo.toml
  forc-plugins/forc-explore/Cargo.toml
  forc-plugins/forc-fmt/Cargo.toml
  forc-plugins/forc-lsp/Cargo.toml
  forc-util/Cargo.toml
  forc/Cargo.toml
  sway-core/Cargo.toml
  sway-fmt-v2/Cargo.toml
  sway-fmt/Cargo.toml
  sway-ir/Cargo.toml
  sway-lsp/Cargo.toml
  sway-parse/Cargo.toml
  sway-types/Cargo.toml
  sway-utils/Cargo.toml
Labels: release

#1752 refactor(forc-pkg): use vendored openssl and git2
  Cargo.lock
  forc-pkg/Cargo.toml
Labels: forc, dependencies

#1753 Bump to v0.14.4
  Cargo.lock
  forc-gm/Cargo.toml
  forc-pkg/Cargo.toml
  forc-plugins/forc-explore/Cargo.toml
  forc-plugins/forc-fmt/Cargo.toml
  forc-plugins/forc-lsp/Cargo.toml
  forc-util/Cargo.toml
  forc/Cargo.toml
  sway-core/Cargo.toml
  sway-fmt-v2/Cargo.toml
  sway-fmt/Cargo.toml
  sway-ir/Cargo.toml
  sway-lsp/Cargo.toml
  sway-parse/Cargo.toml
  sway-types/Cargo.toml
  sway-utils/Cargo.toml
Labels: release

#1751 Update how receipts look like in the Sway Book after #1717
  docs/src/basics/comments_and_logging.md
  docs/src/introduction/overview.md
Labels: The Sway Book

#1741 Add instructions to use fuelup.
  docs/src/introduction/installation.md
Labels: The Sway Book

#1754 `StorageMap` implementation and test
  sway-lib-std/src/storage.sw
  test/src/sdk-harness/test_projects/harness.rs
  test/src/sdk-harness/test_projects/storage_map/.gitignore
  test/src/sdk-harness/test_projects/storage_map/Forc.lock
  test/src/sdk-harness/test_projects/storage_map/Forc.toml
  test/src/sdk-harness/test_projects/storage_map/mod.rs
  test/src/sdk-harness/test_projects/storage_map/src/main.sw
Labels: enhancement, lib: std

#1763 docs: add paragraph about predicates debugging
  docs/src/sway-program-types/predicates.md
Labels: documentation, The Sway Book

#1762 Add an `enum` matching example
  docs/src/basics/control_flow.md
  examples/match_statements/src/main.sw
Labels: The Sway Book

#1758 Adding a new `flags.sw` module
  sway-lib-std/src/flags.sw
  sway-lib-std/src/lib.sw
  sway-lib-std/src/u128.sw
Labels: lib: std, code quality

#1767 Improve the error message for when using unsupported RHS values in const declarations.
  docs/src/reference/known_issues_and_workarounds.md
  sway-core/src/error.rs
  sway-core/src/optimize.rs
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/should_fail/non_literal_const_decl/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/non_literal_const_decl/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/non_literal_const_decl/src/main.sw
Labels: enhancement, compiler: frontend

#1770 Change the dead code analysis for `if` expressions.
  sway-core/src/control_flow_analysis/dead_code_analysis.rs
  sway-lib-std/src/u128.sw
Labels: bug, compiler: frontend

#1772 Format the `exponentiation` std-lib test
  test/src/sdk-harness/test_projects/exponentiation/mod.rs
Labels: code quality, testing

#1768 Prevent recursive enums and structs from getting converted from parse nodes to AST nodes.
  sway-core/src/convert_parse_tree.rs
  sway-core/src/error.rs
  sway-core/src/semantic_analysis/node_dependencies.rs
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/should_fail/recursive_enum/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/recursive_enum/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/recursive_enum/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/recursive_struct/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/recursive_struct/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/recursive_struct/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/recursive_type_chain/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/recursive_type_chain/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/recursive_type_chain/src/main.sw
Labels: bug, compiler

#1775 Collect tokens from the `TypedParseTree` for the language server.
  Cargo.lock
  sway-core/src/parse_tree.rs
  sway-core/src/semantic_analysis/ast_node/code_block.rs
  sway-core/src/semantic_analysis/ast_node/declaration.rs
  sway-core/src/semantic_analysis/ast_node/declaration/enum.rs
  sway-core/src/semantic_analysis/ast_node/declaration/function.rs
  sway-core/src/semantic_analysis/ast_node/declaration/function/function_parameter.rs
  sway-core/src/semantic_analysis/ast_node/declaration/storage.rs
  sway-core/src/semantic_analysis/ast_node/declaration/struct.rs
  sway-core/src/semantic_analysis/ast_node/declaration/variable.rs
  sway-core/src/semantic_analysis/ast_node/expression/mod.rs
  sway-core/src/semantic_analysis/ast_node/expression/struct_expr_field.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression_variant.rs
  sway-core/src/semantic_analysis/ast_node/mod.rs
  sway-core/src/semantic_analysis/ast_node/return_statement.rs
  sway-core/src/semantic_analysis/ast_node/while_loop.rs
  sway-core/src/semantic_analysis/syntax_tree.rs
  sway-core/src/type_engine/engine.rs
  sway-lsp/Cargo.toml
  sway-lsp/src/core/document.rs
  sway-lsp/src/core/mod.rs
  sway-lsp/src/core/token.rs
  sway-lsp/src/core/traverse_typed_tree.rs
  sway-lsp/src/core/typed_token_type.rs
  sway-lsp/src/server.rs
  sway-lsp/src/utils/common.rs
  sway-lsp/src/utils/debug.rs
Labels: language server
