Repository FuelLabs/sway, pull requests merged in 2022-06, with the labels that each got.

#1783 Add additional operators as syntactic sugar
  sway-core/src/convert_parse_tree.rs
  sway-parse/src/expr/mod.rs
  sway-parse/src/keywords.rs
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/should_pass/language/reassignment_operators/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/reassignment_operators/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/reassignment_operators/src/main.sw
Labels: enhancement, compiler: parser

#1776 Eliminating the need for `new()` to use `StorageMap`
  sway-core/src/asm_generation/expression/mod.rs
  sway-core/src/asm_generation/from_ir.rs
  sway-core/src/constants.rs
  sway-core/src/control_flow_analysis/dead_code_analysis.rs
  sway-core/src/convert_parse_tree.rs
  sway-core/src/optimize.rs
  sway-core/src/parse_tree/expression/mod.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/function_application.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/method_application.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression_variant.rs
  sway-core/src/semantic_analysis/node_dependencies.rs
  sway-core/src/type_engine/unresolved_type_check.rs
  sway-core/tests/ir_to_asm/generate_uid.asm
  sway-core/tests/ir_to_asm/generate_uid.ir
  sway-core/tests/ir_to_asm/get_storage_key.asm
  sway-core/tests/ir_to_asm/get_storage_key.ir
  sway-core/tests/sway_to_ir/generate_uid.ir
  sway-core/tests/sway_to_ir/generate_uid.sw
  sway-core/tests/sway_to_ir/get_storage_key.ir
  sway-core/tests/sway_to_ir/get_storage_key.sw
  sway-ir/src/block.rs
  sway-ir/src/instruction.rs
  sway-ir/src/metadata.rs
  sway-ir/src/optimize/constants.rs
  sway-ir/src/optimize/inline.rs
  sway-ir/src/parser.rs
  sway-ir/src/printer.rs
  sway-ir/src/value.rs
  sway-ir/src/verify.rs
  sway-ir/tests/inline/get_storage_key.ir
  sway-lib-std/src/storage.sw
  sway-lsp/src/core/token.rs
  sway-lsp/src/core/traverse_typed_tree.rs
  sway-parse/src/intrinsics.rs
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/should_pass/language/generate_uid/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/generate_uid/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/get_storage_key_caller/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/get_storage_key_caller/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/get_storage_key_caller/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/get_storage_key_caller/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/test_abis/get_storage_key_abi/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/test_abis/get_storage_key_abi/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/test_abis/get_storage_key_abi/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/test_abis/get_storage_key_abi/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/get_storage_key_contract/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/get_storage_key_contract/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/get_storage_key_contract/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/get_storage_key_contract/src/main.sw
  test/src/sdk-harness/test_projects/storage_map/mod.rs
  test/src/sdk-harness/test_projects/storage_map/src/main.sw
Labels: lib: std, compiler: ir, language feature, compiler: frontend, compiler: parser, compiler: codegen

#1794 More updates to the Sway Book related to `storage`
  docs/src/blockchain-development/storage.md
  docs/src/reference/known_issues_and_workarounds.md
  examples/subcurrency/src/main.sw
Labels: The Sway Book

#1802 Remove old codegen path
  forc-pkg/src/pkg.rs
  forc/src/cli/commands/build.rs
  forc/src/cli/commands/deploy.rs
  forc/src/ops/forc_build.rs
  forc/src/ops/forc_deploy.rs
  forc/src/ops/forc_run.rs
  sway-core/src/asm_generation/abstract_instruction_set.rs
  sway-core/src/asm_generation/data_section.rs
  sway-core/src/asm_generation/declaration/const_decl.rs
  sway-core/src/asm_generation/declaration/fn_decl.rs
  sway-core/src/asm_generation/declaration/mod.rs
  sway-core/src/asm_generation/declaration/reassignment.rs
  sway-core/src/asm_generation/declaration/var_decl.rs
  sway-core/src/asm_generation/expression/array.rs
  sway-core/src/asm_generation/expression/contract_call.rs
  sway-core/src/asm_generation/expression/enums.rs
  sway-core/src/asm_generation/expression/if_exp.rs
  sway-core/src/asm_generation/expression/lazy_op.rs
  sway-core/src/asm_generation/expression/mod.rs
  sway-core/src/asm_generation/expression/structs.rs
  sway-core/src/asm_generation/expression/subfield.rs
  sway-core/src/asm_generation/finalized_asm.rs
  sway-core/src/asm_generation/from_ir.rs
  sway-core/src/asm_generation/instruction_set.rs
  sway-core/src/asm_generation/jump_optimized_asm_set.rs
  sway-core/src/asm_generation/mod.rs
  sway-core/src/asm_generation/register_allocated_asm_set.rs
  sway-core/src/asm_generation/while_loop.rs
  sway-core/src/build_config.rs
  sway-core/src/error.rs
  sway-core/src/lib.rs
  sway-core/src/optimize.rs
  sway-core/src/semantic_analysis/ast_node/code_block.rs
  sway-core/src/semantic_analysis/ast_node/declaration.rs
  sway-core/src/semantic_analysis/ast_node/declaration/function.rs
  sway-core/src/semantic_analysis/ast_node/expression/match_expression/typed/typed_match_branch.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/ast_node/mod.rs
  sway-core/src/type_engine/type_info.rs
  test/src/e2e_vm_tests/harness.rs
Labels: forc, code quality, breaking, compiler: codegen

#1686 On Forc.toml change, forc should try to update only package nodes that appear in the lock::Diff
  forc-pkg/src/pkg.rs
  forc/src/ops/forc_build.rs
Labels: enhancement, forc

#1791 Add `Identity` type
  examples/msg_sender/src/main.sw
  examples/subcurrency/src/main.sw
  examples/wallet_smart_contract/src/main.sw
  sway-lib-std/src/chain/auth.sw
  sway-lib-std/src/identity.sw
  sway-lib-std/src/lib.sw
  sway-lib-std/src/option.sw
  sway-lib-std/src/result.sw
  sway-lib-std/src/token.sw
  sway-lib-std/src/vm/evm/ecr.sw
  test/src/sdk-harness/test_artifacts/auth_testing_contract/src/main.sw
  test/src/sdk-harness/test_artifacts/reentrancy_attacker_contract/src/main.sw
  test/src/sdk-harness/test_artifacts/reentrancy_target_contract/src/main.sw
  test/src/sdk-harness/test_projects/token_ops/mod.rs
  test/src/sdk-harness/test_projects/token_ops/src/main.sw
Labels: enhancement, lib: std, breaking

#1803 Adds `forc-fmt-v2` plugin
  Cargo.lock
  Cargo.toml
  forc-plugins/forc-fmt-v2/Cargo.toml
  forc-plugins/forc-fmt-v2/src/main.rs
  sway-fmt-v2/Cargo.toml
  sway-fmt-v2/src/fmt.rs
  sway-fmt-v2/src/lib.rs
Labels: forc, formatter

#1774 Make tuple annotation more specific
  docs/src/basics/built_in_types.md
  sway-core/src/convert_parse_tree.rs
  sway-parse/src/ty/mod.rs
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/should_pass/language/tuple_single_element/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/tuple_single_element/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/tuple_single_element/src/main.sw
Labels: bug, compiler, compiler: parser

#1822 Removed file sway.pest
  sway-core/src/sway.pest
Labels: code quality, compiler: parser

#1814 Refactor `token` module functions
  examples/native_token/src/main.sw
  sway-lib-std/src/token.sw
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/test_fuel_coin_contract/src/main.sw
  test/src/sdk-harness/test_projects/token_ops/src/main.sw
Labels: bikeshedding, lib: std, code quality, breaking

#1828 Fix broken link in the Sway Book
  docs/src/README.md
Labels: The Sway Book

#1834 Reduce conservatism in the allocation algorithm
  sway-core/src/asm_generation/abstract_instruction_set.rs
  sway-core/src/asm_generation/register_allocator.rs
Labels: enhancement, P: critical, compiler: codegen

#1829 Make match var return name deterministic
  Cargo.lock
  sway-core/Cargo.toml
  sway-core/src/asm_generation/from_ir.rs
  sway-core/src/build_config.rs
  sway-core/src/constants.rs
  sway-core/src/convert_parse_tree.rs
  sway-core/src/optimize.rs
  sway-core/src/parse_tree.rs
  sway-core/src/parse_tree/ident.rs
Labels: bug, P: critical, compiler: parser

#1826 Allow `enums` and `strings` in a `storage` blocks
  Cargo.lock
  sway-core/Cargo.toml
  sway-core/src/optimize.rs
  sway-core/tests/ir_to_asm/enum_in_storage_read.asm
  sway-core/tests/ir_to_asm/enum_in_storage_read.ir
  sway-core/tests/ir_to_asm/enum_in_storage_write.asm
  sway-core/tests/ir_to_asm/enum_in_storage_write.ir
  sway-core/tests/ir_to_asm/strings_in_storage.asm
  sway-core/tests/ir_to_asm/strings_in_storage.ir
  sway-core/tests/sway_to_ir/enum_in_storage_read.ir
  sway-core/tests/sway_to_ir/enum_in_storage_read.sw
  sway-core/tests/sway_to_ir/enum_in_storage_write.ir
  sway-core/tests/sway_to_ir/enum_in_storage_write.sw
  sway-core/tests/sway_to_ir/strings_in_storage.ir
  sway-core/tests/sway_to_ir/strings_in_storage.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/storage_access_caller/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/storage_access_caller/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/storage_access_caller/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/test_abis/storage_access_abi/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/storage_access_contract/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/storage_access_contract/src/main.sw
Labels: enhancement, compiler: ir, language feature

#1831 Actually use some of the existing traits
  forc-pkg/src/pkg.rs
  sway-core/src/asm_generation/data_section.rs
  sway-core/src/control_flow_analysis/analyze_return_paths.rs
  sway-core/src/error.rs
  sway-core/src/parse_tree/declaration/function.rs
  sway-core/src/parse_tree/declaration/type_argument.rs
  sway-core/src/parse_tree/declaration/type_parameter.rs
  sway-core/src/parse_tree/literal.rs
  sway-core/src/semantic_analysis/ast_node/copy_types.rs
  sway-core/src/semantic_analysis/ast_node/declaration.rs
  sway-core/src/semantic_analysis/ast_node/declaration/enum.rs
  sway-core/src/semantic_analysis/ast_node/declaration/function.rs
  sway-core/src/semantic_analysis/ast_node/declaration/function/function_parameter.rs
  sway-core/src/semantic_analysis/ast_node/declaration/monomorphize.rs
  sway-core/src/semantic_analysis/ast_node/declaration/struct.rs
  sway-core/src/semantic_analysis/ast_node/declaration/variable.rs
  sway-core/src/semantic_analysis/ast_node/expression/mod.rs
  sway-core/src/semantic_analysis/ast_node/expression/struct_expr_field.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/enum_instantiation.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/if_expression.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/method_application.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression_variant.rs
  sway-core/src/semantic_analysis/ast_node/impl_trait.rs
  sway-core/src/semantic_analysis/ast_node/mod.rs
  sway-core/src/semantic_analysis/module.rs
  sway-core/src/semantic_analysis/namespace/items.rs
  sway-core/src/semantic_analysis/namespace/mod.rs
  sway-core/src/semantic_analysis/namespace/root.rs
  sway-core/src/type_engine/copy_types.rs
  sway-core/src/type_engine/mod.rs
  sway-core/src/type_engine/resolved_type.rs
  sway-core/src/type_engine/type_id.rs
  sway-core/src/type_engine/type_info.rs
  sway-core/src/type_engine/type_mapping.rs
  sway-core/src/type_engine/update_types.rs
  sway-core/src/types.rs
  sway-core/src/types/friendly_type_string.rs
  sway-core/src/types/json_abi_string.rs
  sway-core/src/types/mod.rs
  sway-core/src/types/to_json_abi.rs
  sway-lib-std/src/option.sw
Labels: compiler, code quality

#1837 Change color of forc init output
  forc-util/src/lib.rs
  forc/src/ops/forc_init.rs
Labels: enhancement, forc

#1842 Fix how the state index metadata is inlined
  sway-ir/src/optimize/inline.rs
  sway-ir/tests/inline/get_storage_key.ir
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/get_storage_key_caller/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/test_abis/get_storage_key_abi/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/get_storage_key_contract/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/get_storage_key_contract/src/main.sw
  test/src/sdk-harness/test_projects/storage_map/src/main.sw
Labels: bug, compiler: ir, P: critical

#1841 Rework `forc new` in terms of `forc init`. Based on #1669.
  forc/src/cli/commands/init.rs
  forc/src/cli/commands/new.rs
  forc/src/ops/forc_new.rs
  forc/src/ops/mod.rs
Labels: enhancement, forc

#1830 Report type name in the error when a type is unknown
  examples/signatures/src/main.sw
  sway-core/src/error.rs
  sway-core/src/semantic_analysis/ast_node/mod.rs
  sway-core/src/semantic_analysis/namespace/root.rs
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/should_fail/better_type_error_message/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/better_type_error_message/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/better_type_error_message/src/main.sw
  test/src/sdk-harness/test_artifacts/reentrancy_attacker_contract/src/main.sw
  test/src/sdk-harness/test_artifacts/reentrancy_target_contract/src/main.sw
Labels: bug, compiler: frontend

#1800 Introduce forc build [profile]s in anticipation of introduction of compiler optimisation passes
  docs/src/forc/manifest_reference.md
  forc-pkg/src/manifest.rs
  forc-pkg/src/pkg.rs
  forc/src/cli/commands/build.rs
  forc/src/cli/commands/deploy.rs
  forc/src/ops/forc_build.rs
  forc/src/ops/forc_deploy.rs
  forc/src/ops/forc_run.rs
Labels: enhancement, compiler, forc

#1853 Made transfer_to a little more generic
  sway-lib-std/src/token.sw
Labels: good first issue, lib: std, code quality

#1855 Removed unused and rogue function
  sway-lib-std/src/hash.sw
Labels: good first issue, lib: std, code quality

#1843 Adds `from_dir` to new formatter
  forc-plugins/forc-fmt-v2/src/main.rs
  sway-fmt-v2/src/fmt.rs
Labels: forc, code quality, formatter

#1788 Tuple field reassignments
  sway-core/src/optimize.rs
  sway-core/src/semantic_analysis/ast_node/declaration.rs
  sway-core/src/semantic_analysis/ast_node/mod.rs
  sway-core/src/semantic_analysis/namespace/items.rs
  sway-lsp/src/core/traverse_typed_tree.rs
  sway-lsp/src/core/typed_token_type.rs
  sway-lsp/src/utils/debug.rs
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/should_pass/language/tuple_field_reassignment/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/tuple_field_reassignment/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/tuple_field_reassignment/src/main.sw
Labels: enhancement, compiler: ir, compiler: frontend, compiler: parser, compiler: codegen

#1859 Add missing oracle file to `tuple_field_reassignment` test
  test/src/e2e_vm_tests/test_programs/should_pass/language/tuple_field_reassignment/json_abi_oracle.json
Labels: bug, ci, testing

#1863 better mdbook <> mdbook-forc-documenter setup instructions
  docs/README.md
Labels: documentation, The Sway Book

#1835 Bump to v0.15.0
  Cargo.lock
  forc-gm/Cargo.toml
  forc-pkg/Cargo.toml
  forc-plugins/forc-explore/Cargo.toml
  forc-plugins/forc-fmt-v2/Cargo.toml
  forc-plugins/forc-fmt/Cargo.toml
  forc-plugins/forc-lsp/Cargo.toml
  forc-util/Cargo.toml
  forc/Cargo.toml
  sway-core/Cargo.toml
  sway-fmt-v2/Cargo.toml
  sway-fmt/Cargo.toml
  sway-ir/Cargo.toml
  sway-lsp/Cargo.toml
  sway-parse/Cargo.toml
  sway-types/Cargo.toml
  sway-utils/Cargo.toml
Labels: release

#1850 Use the `uint` crate instead of `bigint`
  Cargo.lock
  sway-core/Cargo.toml
  sway-core/src/optimize.rs
Labels: code quality, compiler: ir

#1871 Bump to v0.15.1
  Cargo.lock
  forc-gm/Cargo.toml
  forc-pkg/Cargo.toml
  forc-plugins/forc-explore/Cargo.toml
  forc-plugins/forc-fmt-v2/Cargo.toml
  forc-plugins/forc-fmt/Cargo.toml
  forc-plugins/forc-lsp/Cargo.toml
  forc-util/Cargo.toml
  forc/Cargo.toml
  sway-core/Cargo.toml
  sway-fmt-v2/Cargo.toml
  sway-fmt/Cargo.toml
  sway-ir/Cargo.toml
  sway-lsp/Cargo.toml
  sway-parse/Cargo.toml
  sway-types/Cargo.toml
  sway-utils/Cargo.toml
Labels: release

#1874 Disallowing storage declarations in non-contracts
  sway-core/src/error.rs
  sway-core/src/parse_tree/program.rs
  sway-core/src/semantic_analysis/ast_node/declaration/storage.rs
  sway-core/src/semantic_analysis/program.rs
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/should_fail/storage_in_library/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/storage_in_library/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/storage_in_library/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_fail/storage_in_library/src/inner.sw
  test/src/e2e_vm_tests/test_programs/should_fail/storage_in_library/src/lib.sw
  test/src/e2e_vm_tests/test_programs/should_fail/storage_in_library/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/storage_in_predicate/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/storage_in_predicate/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/storage_in_predicate/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_fail/storage_in_predicate/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/storage_in_script/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/storage_in_script/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/storage_in_script/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_fail/storage_in_script/src/main.sw
Labels: enhancement, compiler: frontend

#1879 Create the `DeterministicallyAborts` trait
  sway-core/src/semantic_analysis/ast_node/code_block.rs
  sway-core/src/semantic_analysis/ast_node/expression/match_expression/typed/typed_match_branch.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/ast_node/mod.rs
  sway-core/src/types/deterministically_aborts.rs
  sway-core/src/types/mod.rs
Labels: compiler, code quality

#1875 Minor updates to `storage` in the Sway Book
  docs/src/blockchain-development/storage.md
  docs/src/reference/known_issues_and_workarounds.md
Labels: The Sway Book

#1878 Move the impls for UnresolvedTypeCheck to match the location of the other impls for each type
  sway-core/src/semantic_analysis/ast_node/declaration.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/ast_node/mod.rs
  sway-core/src/type_engine/type_id.rs
  sway-core/src/type_engine/unresolved_type_check.rs
Labels: compiler, code quality

#1882 Remove dead code
  sway-core/src/parse_tree/expression/mod.rs
Labels: compiler, code quality

#1883 Replace manual string methods with `Display`
  sway-core/src/control_flow_analysis/analyze_return_paths.rs
  sway-core/src/error.rs
  sway-core/src/parse_tree/call_path.rs
  sway-core/src/parse_tree/declaration/function.rs
  sway-core/src/parse_tree/declaration/type_argument.rs
  sway-core/src/parse_tree/literal.rs
  sway-core/src/semantic_analysis/ast_node/declaration.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/enum_instantiation.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/if_expression.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/method_application.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression_variant.rs
  sway-core/src/semantic_analysis/ast_node/impl_trait.rs
  sway-core/src/semantic_analysis/ast_node/mod.rs
  sway-core/src/semantic_analysis/ast_node/while_loop.rs
  sway-core/src/semantic_analysis/module.rs
  sway-core/src/semantic_analysis/namespace/items.rs
  sway-core/src/semantic_analysis/namespace/root.rs
  sway-core/src/semantic_analysis/node_dependencies.rs
  sway-core/src/type_engine/integer_bits.rs
  sway-core/src/type_engine/type_id.rs
  sway-core/src/type_engine/type_info.rs
  sway-core/src/types/friendly_type_string.rs
  sway-core/src/types/mod.rs
  sway-lsp/src/utils/debug.rs
  sway-types/src/ident.rs
Labels: compiler, code quality

#1885 Items under [project] sorted alphabetically during `forc init`
  forc/src/utils/defaults.rs
Labels: good first issue, forc

#1881 Use the `Spanned` trait everywhere
  Cargo.lock
  forc-util/Cargo.toml
  forc-util/src/lib.rs
  sway-core/src/asm_generation/from_ir.rs
  sway-core/src/asm_lang/mod.rs
  sway-core/src/control_flow_analysis/dead_code_analysis.rs
  sway-core/src/convert_parse_tree.rs
  sway-core/src/error.rs
  sway-core/src/optimize.rs
  sway-core/src/parse_tree/call_path.rs
  sway-core/src/parse_tree/code_block.rs
  sway-core/src/parse_tree/declaration/reassignment.rs
  sway-core/src/parse_tree/declaration/type_parameter.rs
  sway-core/src/parse_tree/expression/mod.rs
  sway-core/src/parse_tree/expression/scrutinee.rs
  sway-core/src/semantic_analysis/ast_node/declaration.rs
  sway-core/src/semantic_analysis/ast_node/declaration/enum.rs
  sway-core/src/semantic_analysis/ast_node/declaration/function.rs
  sway-core/src/semantic_analysis/ast_node/declaration/monomorphize.rs
  sway-core/src/semantic_analysis/ast_node/declaration/storage.rs
  sway-core/src/semantic_analysis/ast_node/declaration/struct.rs
  sway-core/src/semantic_analysis/ast_node/expression/match_expression/typed/typed_match_branch.rs
  sway-core/src/semantic_analysis/ast_node/expression/match_expression/typed/typed_scrutinee.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/enum_instantiation.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/function_application.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/method_application.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression_variant.rs
  sway-core/src/semantic_analysis/ast_node/impl_trait.rs
  sway-core/src/semantic_analysis/ast_node/mod.rs
  sway-core/src/semantic_analysis/module.rs
  sway-core/src/semantic_analysis/namespace/items.rs
  sway-core/src/semantic_analysis/namespace/module.rs
  sway-core/src/semantic_analysis/namespace/namespace.rs
  sway-core/src/semantic_analysis/namespace/root.rs
  sway-core/src/semantic_analysis/node_dependencies.rs
  sway-core/src/semantic_analysis/program.rs
  sway-core/src/style.rs
  sway-core/src/type_engine/type_id.rs
  sway-core/src/type_engine/type_info.rs
  sway-lsp/src/core/token.rs
  sway-lsp/src/core/traverse_typed_tree.rs
  sway-lsp/src/utils/debug.rs
  sway-parse/src/assignable.rs
  sway-parse/src/attribute.rs
  sway-parse/src/dependency.rs
  sway-parse/src/expr/asm.rs
  sway-parse/src/expr/mod.rs
  sway-parse/src/item/item_trait.rs
  sway-parse/src/item/mod.rs
  sway-parse/src/module.rs
  sway-parse/src/parse.rs
  sway-parse/src/path.rs
  sway-parse/src/pattern.rs
  sway-parse/src/token.rs
  sway-parse/src/where_clause.rs
  sway-types/src/ident.rs
Labels: compiler, code quality

#1886 Remove dead code
  sway-core/src/parse_tree/declaration/function.rs
Labels: compiler, code quality

#1870 remove_deps cannot handle removed dependencies correctly when there are multiple roots after edge removal
  forc-pkg/src/pkg.rs
Labels: forc, dependencies

#1840 Error on multiple function definitions
  sway-core/src/error.rs
  sway-core/src/semantic_analysis/ast_node/impl_trait.rs
  sway-core/src/semantic_analysis/program.rs
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/should_fail/multiple_impl_abi/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/multiple_impl_abi/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/multiple_impl_abi/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/multiple_impl_fns/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/multiple_impl_fns/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/multiple_impl_fns/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/multiple_impl/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/multiple_impl/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/multiple_impl/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/multiple_impl/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/multiple_impl/src/testlib.sw
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/multiple_impl/src/testlib2.sw
Labels: bug, compiler: frontend

#1891 Fix clippy failure after #1840
  sway-core/src/error.rs
Labels: compiler, code quality

#1884 Refactor the representation of intrinsic functions in the AST
  sway-core/src/control_flow_analysis/dead_code_analysis.rs
  sway-core/src/convert_parse_tree.rs
  sway-core/src/optimize.rs
  sway-core/src/parse_tree/expression/intrinsic_function.rs
  sway-core/src/parse_tree/expression/mod.rs
  sway-core/src/semantic_analysis/ast_node/expression/intrinsic_function.rs
  sway-core/src/semantic_analysis/ast_node/expression/mod.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression_variant.rs
  sway-core/src/semantic_analysis/node_dependencies.rs
  sway-lsp/src/core/token.rs
  sway-lsp/src/core/traverse_typed_tree.rs
Labels: compiler, code quality

#1894 Adds associated functions for `NewlineStyle`
  sway-fmt-v2/src/config/whitespace.rs
  sway-fmt-v2/src/constants.rs
  sway-fmt-v2/src/lib.rs
  sway-fmt-v2/src/newline_style.rs
Labels: forc, formatter

#1889 Bump fuel-vm version in test harness
  test/src/sdk-harness/Cargo.toml
Labels: lib: std, testing, dependencies

#1901 Fix incorrect `CallPath` suffix on `TypedImplTrait`
  sway-core/src/semantic_analysis/ast_node/declaration/function.rs
  sway-core/src/semantic_analysis/ast_node/declaration/impl_trait.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-lsp/src/core/traverse_typed_tree.rs
Labels: bug, language server, compiler: frontend

#1902 Make `BuildConfig` an `Option` for the `compile_to_ast` fn
  forc-pkg/src/pkg.rs
  sway-core/src/lib.rs
  sway-lsp/src/core/document.rs
Labels: compiler: frontend

#1905 Fix for accidentally skipping the print_intermediate_asm user config item.
  forc/src/ops/forc_build.rs
Labels: bug, forc

#1861 Fix bug where forc_pkg::add_deps ignores that dependency name might differ from package name
  forc-pkg/src/pkg.rs
Labels: bug, forc, dependencies

#1844 Disallow repeated `struct`/`storage` fields and `enum` variants
  sway-core/src/convert_parse_tree.rs
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/should_fail/repeated_enum_variant/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/repeated_enum_variant/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/repeated_enum_variant/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_fail/repeated_enum_variant/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/repeated_storage_field/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/repeated_storage_field/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/repeated_storage_field/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_fail/repeated_storage_field/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/repeated_struct_field/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/repeated_struct_field/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/repeated_struct_field/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_fail/repeated_struct_field/src/main.sw
Labels: bug, compiler: parser

#1911 Adds associated functions for handling of indentation
  sway-fmt-v2/src/constants.rs
  sway-fmt-v2/src/fmt.rs
  sway-fmt-v2/src/lib.rs
  sway-fmt-v2/src/utils.rs
  sway-fmt-v2/src/utils/indent_style.rs
  sway-fmt-v2/src/utils/newline_style.rs
Labels: forc, formatter

#1897 Fix how `enum` constants are initialized in codegen
  sway-core/src/asm_generation/from_ir.rs
  sway-core/tests/ir_to_asm/enum_in_storage_write.asm
  sway-core/tests/ir_to_asm/enum_padding.asm
  sway-core/tests/ir_to_asm/enum_padding.ir
  sway-ir/src/parser.rs
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/should_pass/language/enum_padding/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/enum_padding/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/enum_padding/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/language/enum_padding/src/main.sw
Labels: bug, P: critical, compiler: codegen

#1910 Dependency cycles are explicitly printed
  forc-pkg/src/pkg.rs
Labels: enhancement, forc

#1917 General enhancements to arrays in the Sway Book
  docs/src/basics/built_in_types.md
  docs/src/reference/known_issues_and_workarounds.md
  examples/arrays/Forc.lock
  examples/arrays/Forc.toml
  examples/arrays/src/main.sw
Labels: The Sway Book

#1920 Bump to v0.15.2
  Cargo.lock
  forc-gm/Cargo.toml
  forc-pkg/Cargo.toml
  forc-plugins/forc-explore/Cargo.toml
  forc-plugins/forc-fmt-v2/Cargo.toml
  forc-plugins/forc-fmt/Cargo.toml
  forc-plugins/forc-lsp/Cargo.toml
  forc-util/Cargo.toml
  forc/Cargo.toml
  sway-core/Cargo.toml
  sway-fmt-v2/Cargo.toml
  sway-fmt/Cargo.toml
  sway-ir/Cargo.toml
  sway-lsp/Cargo.toml
  sway-parse/Cargo.toml
  sway-types/Cargo.toml
  sway-utils/Cargo.toml
Labels: release

#1921 Bump to fuels 0.15
  forc/src/utils/defaults.rs
  test/src/sdk-harness/Cargo.toml
Labels: forc, testing

#1927 sway-fmt-v2 should actually use the newline style utils implemented before
  sway-fmt-v2/src/fmt.rs
Labels: enhancement, formatter

#1925 sway-fmt-v2 Formatter struct should have a Shape field that can keep track of the current indentation
  forc-plugins/forc-fmt-v2/src/main.rs
  sway-fmt-v2/src/fmt.rs
  sway-fmt-v2/src/items/item_abi.rs
  sway-fmt-v2/src/items/item_const.rs
  sway-fmt-v2/src/items/item_enum.rs
  sway-fmt-v2/src/items/item_fn.rs
  sway-fmt-v2/src/items/item_impl.rs
  sway-fmt-v2/src/items/item_storage.rs
  sway-fmt-v2/src/items/item_struct.rs
  sway-fmt-v2/src/items/item_trait.rs
  sway-fmt-v2/src/items/item_use.rs
  sway-fmt-v2/src/utils/indent_style.rs
Labels: enhancement, forc, formatter

#1933 Support hex and binary literals for integers
  sway-core/src/convert_parse_tree.rs
  test/src/e2e_vm_tests/test_programs/should_pass/language/basic_func_decl/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/binary_and_hex_literals/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/binary_and_hex_literals/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/binary_and_hex_literals/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/language/binary_and_hex_literals/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/struct_field_reassignment/src/main.sw
Labels: bug, P: critical, compiler: parser

#1934 Add `ReplaceSelfType` trait
  sway-core/src/parse_tree/declaration/type_argument.rs
  sway-core/src/parse_tree/declaration/type_parameter.rs
  sway-core/src/semantic_analysis/ast_node/declaration/enum.rs
  sway-core/src/semantic_analysis/ast_node/declaration/struct.rs
  sway-core/src/type_engine/engine.rs
  sway-core/src/type_engine/mod.rs
  sway-core/src/type_engine/replace_self_type.rs
  sway-core/src/type_engine/type_id.rs
Labels: compiler: frontend

#1928 Add `std::tx::get_script_data`
  sway-lib-std/src/tx.sw
  test/src/sdk-harness/Cargo.toml
  test/src/sdk-harness/test_projects/harness.rs
  test/src/sdk-harness/test_projects/script_data/Forc.lock
  test/src/sdk-harness/test_projects/script_data/Forc.toml
  test/src/sdk-harness/test_projects/script_data/mod.rs
  test/src/sdk-harness/test_projects/script_data/src/main.sw
Labels: enhancement, lib: std

#1932 Implement `ToJsonAbi` on `TypedProgramKind`
  forc-pkg/src/pkg.rs
  sway-core/src/semantic_analysis/ast_node/declaration/function.rs
  sway-core/src/semantic_analysis/program.rs
  test/src/e2e_vm_tests/test_programs/should_pass/language/generic_struct/src/main.sw
Labels: compiler, code quality

#1938 Unify type parameters inside of the `unify` function
  sway-core/src/type_engine/engine.rs
Labels: bug, compiler: frontend

#1939 Give `TypedAbiDeclaration` and `TypedTraitDeclaration` their own files.
  sway-core/src/semantic_analysis/ast_node/declaration.rs
  sway-core/src/semantic_analysis/ast_node/declaration/abi.rs
  sway-core/src/semantic_analysis/ast_node/declaration/enum.rs
  sway-core/src/semantic_analysis/ast_node/declaration/trait.rs
  sway-core/src/semantic_analysis/ast_node/expression/match_expression/typed/typed_scrutinee.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/ast_node/mod.rs
  sway-core/src/type_engine/create_type_id.rs
  sway-core/src/type_engine/mod.rs
Labels: compiler, code quality

#1949 Fix sway formatting turns `op` + `=` into `op` + ` ` + `=` which breaks the build command because it is not a valid expression
  sway-fmt/src/code_builder.rs
  sway-fmt/src/code_builder_helpers.rs
  sway-fmt/src/fmt.rs
Labels: bug, formatter

#1948 Allow more than just a `literal` in `const` initializer expressions
  sway-core/src/error.rs
  sway-core/src/optimize.rs
  sway-core/src/semantic_analysis.rs
  sway-core/src/semantic_analysis/ast_node/mod.rs
  sway-core/src/semantic_analysis/const_eval.rs
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/should_pass/language/const_inits/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/const_inits/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/const_inits/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/language/const_inits/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/non_literal_const_decl/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/non_literal_const_decl/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/non_literal_const_decl/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/language/non_literal_const_decl/src/main.sw
Labels: enhancement, compiler

#1954 Allow struct field expressions to be on function calls.
  sway-ir/src/instruction.rs
  test/src/e2e_vm_tests/test_programs/should_pass/language/array_basics/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/struct_field_access/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/struct_field_access/src/main.sw
Labels: bug, compiler: ir, compiler: frontend

#1951 Use `--locked` option when building tests to ensure up-to-date lock file
  test/src/e2e_vm_tests/harness.rs
  test/src/sdk-harness/build.sh
Labels: forc, ci, testing

#1955 Fix `master` CI error due to test that slipped by the `--locked` PR
  test/src/e2e_vm_tests/test_programs/should_pass/language/const_inits/Forc.lock
Labels: bug, forc, ci, testing

#1944 Test for cyclic dependency added to should_fail
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/should_fail/cyclic_dependency/dependency_a/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/cyclic_dependency/dependency_a/src/lib.sw
  test/src/e2e_vm_tests/test_programs/should_fail/cyclic_dependency/dependency_b/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/cyclic_dependency/dependency_b/src/lib.sw
Labels: forc, testing

#1937 Replace r#type with `type_id` and `type_info`.
  sway-core/src/convert_parse_tree.rs
  sway-core/src/optimize.rs
  sway-core/src/parse_tree/declaration/enum.rs
  sway-core/src/parse_tree/declaration/storage.rs
  sway-core/src/parse_tree/declaration/struct.rs
  sway-core/src/semantic_analysis/ast_node/declaration.rs
  sway-core/src/semantic_analysis/ast_node/declaration/enum.rs
  sway-core/src/semantic_analysis/ast_node/declaration/function.rs
  sway-core/src/semantic_analysis/ast_node/declaration/function/function_parameter.rs
  sway-core/src/semantic_analysis/ast_node/declaration/impl_trait.rs
  sway-core/src/semantic_analysis/ast_node/declaration/storage.rs
  sway-core/src/semantic_analysis/ast_node/declaration/struct.rs
  sway-core/src/semantic_analysis/ast_node/declaration/trait.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/enum_instantiation.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/function_application.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/method_application.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/struct_field_access.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/unsafe_downcast.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression_variant.rs
  sway-core/src/semantic_analysis/ast_node/mod.rs
  sway-core/src/semantic_analysis/namespace/items.rs
  sway-core/src/semantic_analysis/node_dependencies.rs
  sway-core/src/type_engine/engine.rs
  sway-core/src/type_engine/mod.rs
  sway-core/src/type_engine/type_info.rs
  sway-lsp/src/core/traverse_typed_tree.rs
Labels: compiler, code quality

#1959 Remove unnecessary `CompileResults`
  sway-core/src/semantic_analysis/namespace/items.rs
  sway-core/src/semantic_analysis/namespace/module.rs
  sway-core/src/semantic_analysis/namespace/trait_map.rs
Labels: code quality, compiler: frontend

#1940 Do not rely on `TypeMapping` when type checking declarations.
  sway-core/src/parse_tree/declaration/type_parameter.rs
  sway-core/src/semantic_analysis/ast_node/declaration.rs
  sway-core/src/semantic_analysis/ast_node/declaration/enum.rs
  sway-core/src/semantic_analysis/ast_node/declaration/function.rs
  sway-core/src/semantic_analysis/ast_node/declaration/function/function_parameter.rs
  sway-core/src/semantic_analysis/ast_node/declaration/impl_trait.rs
  sway-core/src/semantic_analysis/ast_node/declaration/struct.rs
  sway-core/src/semantic_analysis/namespace/root.rs
  sway-lsp/src/core/traverse_typed_tree.rs
Labels: bug, compiler: frontend

#1930 Rename Ethereum -> the EVM.
  docs/src/basics/blockchain_types.md
  docs/src/blockchain-development/access_control.md
  docs/src/blockchain-development/calling_contracts.md
  docs/src/blockchain-development/hashing_and_cryptography.md
  docs/src/blockchain-development/identifiers.md
  docs/src/blockchain-development/native_assets.md
  docs/src/sway-program-types/scripts.md
  test-sig-gen-util/src/main.rs
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/evm_ecr/src/main.sw
Labels: documentation, code quality, The Sway Book

#1935 Allow the transfer_to function to transfer any native asset
  sway-lib-std/src/token.sw
  test/src/sdk-harness/test_projects/token_ops/mod.rs
  test/src/sdk-harness/test_projects/token_ops/src/main.sw
Labels: enhancement, lib: std, code quality, breaking

#1964 Update test runners to accept optional `--locked` flag. Use it in CI.
  .github/workflows/ci.yml
  test/src/e2e_vm_tests/harness.rs
  test/src/e2e_vm_tests/mod.rs
  test/src/main.rs
  test/src/sdk-harness/build.sh
Labels: ci, testing

#1968 `sway-fmt-v2` brace handler and implementation for enum added
  sway-fmt-v2/src/items/item_enum.rs
  sway-fmt-v2/src/utils.rs
  sway-fmt-v2/src/utils/bracket.rs
Labels: enhancement, formatter

#1983 Remove dead code.
  sway-core/src/parse_tree/declaration/type_parameter.rs
  sway-core/src/type_engine/mod.rs
  sway-core/src/type_engine/update_types.rs
Labels: code quality, compiler: frontend

#1965 Emit a `MOVE` for a `phi` value only when needed
  sway-core/src/asm_generation/from_ir.rs
  sway-core/tests/ir_to_asm/lazy_binops.asm
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_basic_storage/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_increment_contract/src/main.sw
Labels: bug, compiler: codegen

#1966 Refactor `optimize.rs` into an `ir_generation` module.
  sway-core/src/ir_generation.rs
  sway-core/src/ir_generation/compile.rs
  sway-core/src/ir_generation/const_eval.rs
  sway-core/src/ir_generation/convert.rs
  sway-core/src/ir_generation/function.rs
  sway-core/src/ir_generation/lexical_map.rs
  sway-core/src/ir_generation/purity.rs
  sway-core/src/ir_generation/types.rs
  sway-core/src/lib.rs
  sway-core/src/semantic_analysis.rs
  sway-core/src/semantic_analysis/ast_node/mod.rs
Labels: code quality, compiler: frontend

#1987 preprocessor strictness change
  .github/workflows/ci.yml
  .github/workflows/gh-pages.yml
  Cargo.lock
  docs/README.md
  scripts/mdbook-forc-documenter/Cargo.toml
  scripts/mdbook-forc-documenter/README.md
  scripts/mdbook-forc-documenter/src/lib.rs
Labels: documentation, ci, The Sway Book

#1988 Translate assignments to `_` as variable declaration
  sway-core/src/convert_parse_tree.rs
Labels: compiler: frontend

#1992 Don't emit hashes for predicates
  forc/src/cli/commands/build.rs
  forc/src/ops/forc_build.rs
  forc/src/utils/mod.rs
Labels: bug, forc

#1942 Prevent unconstrained type parameters in `impl` blocks
  sway-core/src/error.rs
  sway-core/src/semantic_analysis/ast_node/declaration/impl_trait.rs
  sway-core/src/type_engine/type_info.rs
  sway-lib-core/src/ops.sw
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/should_fail/impl_with_bad_generic/.gitignore
  test/src/e2e_vm_tests/test_programs/should_fail/impl_with_bad_generic/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/impl_with_bad_generic/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/impl_with_bad_generic/src/main.sw
Labels: bug, compiler: frontend

#1979 Add `std::alloc`
  sway-lib-std/src/address.sw
  sway-lib-std/src/alloc.sw
  sway-lib-std/src/contract_id.sw
  sway-lib-std/src/intrinsics.sw
  sway-lib-std/src/lib.sw
  sway-lib-std/src/mem.sw
  sway-lib-std/src/vm/evm/evm_address.sw
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/alloc/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/alloc/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/alloc/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/alloc/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/intrinsics/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/mem/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/mem/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/mem/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/mem/src/main.sw
Labels: enhancement, lib: std

#1991 Adds `AngleBracket` to `utils::bracket`
  sway-fmt-v2/src/utils/bracket.rs
Labels: forc, formatter

#1989 Adds `SquareBracket` trait to `utils::bracket`
  sway-fmt-v2/src/items/item_enum.rs
  sway-fmt-v2/src/utils/bracket.rs
Labels: forc, formatter

#2000 Updates `apply_newline_style` function to use determined setting
  sway-fmt-v2/src/fmt.rs
Labels: forc, code quality, formatter

#1845 forc run simulate txs
  forc/src/cli/commands/run.rs
  forc/src/ops/forc_run.rs
  forc/src/utils/defaults.rs
  test/src/e2e_vm_tests/harness.rs
Labels: forc

#1956 Allow `self` to be mutable
  sway-core/src/convert_parse_tree.rs
  sway-core/src/error.rs
  sway-core/src/ir_generation/function.rs
  sway-core/src/parse_tree/declaration/function.rs
  sway-core/src/semantic_analysis/ast_node/declaration/function.rs
  sway-core/src/semantic_analysis/ast_node/declaration/function/function_parameter.rs
  sway-core/src/semantic_analysis/ast_node/declaration/trait.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/method_application.rs
  sway-core/src/semantic_analysis/ast_node/mod.rs
  sway-ir/src/verify.rs
  sway-parse/src/item/mod.rs
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/should_fail/method_requires_mut_var/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/method_requires_mut_var/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/method_requires_mut_var/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_fail/method_requires_mut_var/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/self_impl_reassignment/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/self_impl_reassignment/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/language/self_impl_reassignment/src/main.sw
Labels: compiler: ir, language feature, compiler: frontend, compiler: parser

#2002 Getting root hash for predicates when building
  forc/src/cli/commands/build.rs
  forc/src/ops/forc_build.rs
  forc/src/utils/mod.rs
Labels: forc

#1998 Bump to v0.16.0
  Cargo.lock
  forc-gm/Cargo.toml
  forc-pkg/Cargo.toml
  forc-plugins/forc-explore/Cargo.toml
  forc-plugins/forc-fmt-v2/Cargo.toml
  forc-plugins/forc-fmt/Cargo.toml
  forc-plugins/forc-lsp/Cargo.toml
  forc-util/Cargo.toml
  forc/Cargo.toml
  sway-core/Cargo.toml
  sway-fmt-v2/Cargo.toml
  sway-fmt/Cargo.toml
  sway-ir/Cargo.toml
  sway-lsp/Cargo.toml
  sway-parse/Cargo.toml
  sway-types/Cargo.toml
  sway-utils/Cargo.toml
Labels: release

#2013 Make sure that reallocating zero sized allocations works as expected
  sway-lib-std/src/alloc.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/alloc/src/main.sw
Labels: enhancement, lib: std

#2019 Remove known issues that have been resolved from the Sway Book
  docs/src/reference/known_issues_and_workarounds.md
Labels: The Sway Book

#1973 Improve span for missing tokens at the end of a scope
  sway-parse/src/parser.rs
Labels: bug, compiler: parser

#2009 Fix unnecessary check inside of the match exhaustivity algorithm
  sway-core/src/semantic_analysis/ast_node/expression/match_expression/analysis/constructor_factory.rs
  sway-core/src/semantic_analysis/ast_node/expression/match_expression/analysis/pattern.rs
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/should_pass/language/match_expressions_with_self/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/match_expressions_with_self/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/match_expressions_with_self/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/language/match_expressions_with_self/src/main.sw
Labels: bug, P: critical, compiler: frontend

#1970 Support `+=` and other similar operators for storage accesses
  sway-core/src/convert_parse_tree.rs
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/storage_access_caller/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/test_abis/storage_access_abi/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/storage_access_contract/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/storage_access_contract/src/main.sw
Labels: bug, compiler: parser

#1118 stdlib `Vec`
  sway-lib-std/src/lib.sw
  sway-lib-std/src/vec.sw
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/vec/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/vec/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/vec/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/vec/src/main.sw
Labels: enhancement, lib: std

#1962 Enum formating for sway-fmt-v2
  sway-fmt-v2/src/fmt.rs
  sway-fmt-v2/src/items/item_enum.rs
Labels: enhancement, formatter

#2024 Minor fix to test warning.
  test/src/sdk-harness/test_projects/logging/src/main.sw
Labels: lib: std, code quality, testing

#2025 Split book into latest and master.
  .github/workflows/gh-pages.yml
Labels: ci, The Sway Book

#2011 Add `attribute` to `utils`
  sway-fmt-v2/src/fmt.rs
  sway-fmt-v2/src/utils.rs
  sway-fmt-v2/src/utils/attributes.rs
Labels: enhancement, forc, formatter

#2028 Added Eq for identity
  sway-lib-std/src/identity.sw
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/identity_eq/.gitignore
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/identity_eq/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/identity_eq/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/identity_eq/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/identity_eq/src/main.sw
Labels: enhancement, good first issue, lib: std, P: high

#2037 Bump to v0.16.1
  Cargo.lock
  forc-gm/Cargo.toml
  forc-pkg/Cargo.toml
  forc-plugins/forc-explore/Cargo.toml
  forc-plugins/forc-fmt-v2/Cargo.toml
  forc-plugins/forc-fmt/Cargo.toml
  forc-plugins/forc-lsp/Cargo.toml
  forc-util/Cargo.toml
  forc/Cargo.toml
  sway-core/Cargo.toml
  sway-fmt-v2/Cargo.toml
  sway-fmt/Cargo.toml
  sway-ir/Cargo.toml
  sway-lsp/Cargo.toml
  sway-parse/Cargo.toml
  sway-types/Cargo.toml
  sway-utils/Cargo.toml
Labels: release

#2038 Small nits in the standard library
  sway-lib-std/src/assert.sw
  sway-lib-std/src/chain/auth.sw
  sway-lib-std/src/identity.sw
  sway-lib-std/src/option.sw
  sway-lib-std/src/result.sw
  sway-lib-std/src/storage.sw
  sway-lib-std/src/token.sw
  sway-lib-std/src/u128.sw
  sway-lib-std/src/vec.sw
  sway-lib-std/src/vm/evm/ecr.sw
Labels: lib: std, code quality

#2042 Remove extra "the"
  sway-lib-std/src/storage.sw
Labels: bug, The Sway Book

#2045 Run `cargo update`.
  Cargo.lock
Labels: dependencies

#1997 sway-fmt-v2 adds program type to the output
  sway-fmt-v2/src/fmt.rs
  sway-fmt-v2/src/utils.rs
  sway-fmt-v2/src/utils/program_type.rs
Labels: bug, forc

#2034 Handle enums and their impls for item imports
  docs/src/reference/known_issues_and_workarounds.md
  sway-core/src/semantic_analysis/ast_node/declaration.rs
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/identity_eq/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/result/src/main.sw
Labels: bug, The Sway Book, P: critical, compiler: frontend

#2041 Add `Identity` type to Sway Book
  docs/src/basics/blockchain_types.md
  examples/identity/Forc.lock
  examples/identity/Forc.toml
  examples/identity/src/abi.sw
  examples/identity/src/errors.sw
  examples/identity/src/main.sw
  sway-lib-std/src/identity.sw
Labels: good first issue, The Sway Book

#2032 Improve struct patterns with new warnings and rest pattern support.
  sway-core/src/convert_parse_tree.rs
  sway-core/src/error.rs
  sway-core/src/parse_tree/expression/scrutinee.rs
  sway-core/src/semantic_analysis/ast_node/expression/match_expression/analysis/pattern.rs
  sway-core/src/semantic_analysis/ast_node/expression/match_expression/typed/typed_scrutinee.rs
  sway-parse/src/error.rs
  sway-parse/src/keywords.rs
  sway-parse/src/pattern.rs
  test/src/e2e_vm_tests/test_programs/should_fail/match_expressions_multiple_rest/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/match_expressions_multiple_rest/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/match_expressions_multiple_rest/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/match_expressions_multiple_rest/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/match_expressions_rest/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/match_expressions_rest/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/match_expressions_rest/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/match_expressions_rest/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/match_expressions_struct_missing_fields/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/match_expressions_struct_missing_fields/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/match_expressions_struct_missing_fields/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/match_expressions_struct_missing_fields/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/match_expressions_rest/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/match_expressions_rest/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/match_expressions_rest/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/language/match_expressions_rest/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/match_expressions_rest/test.toml
Labels: enhancement, language feature, compiler: frontend, compiler: parser

#1958 Add the concept of semantic similarity to the type system
  sway-core/src/ir_generation/const_eval.rs
  sway-core/src/parse_tree/declaration/type_parameter.rs
  sway-core/src/semantic_analysis/ast_node/declaration/monomorphize.rs
  sway-core/src/semantic_analysis/namespace/items.rs
  sway-core/src/semantic_analysis/namespace/trait_map.rs
  sway-core/src/type_engine/type_info.rs
  sway-core/src/type_engine/type_mapping.rs
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/should_fail/impl_with_semantic_type_constraints/.gitignore
  test/src/e2e_vm_tests/test_programs/should_fail/impl_with_semantic_type_constraints/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/impl_with_semantic_type_constraints/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/impl_with_semantic_type_constraints/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/impl_with_semantic_type_constraints/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/test_abis/abi_with_tuples/Forc.lock
  test/src/sdk-harness/test_artifacts/methods_abi/Forc.lock
  test/src/sdk-harness/test_artifacts/methods_abi/Forc.toml
  test/src/sdk-harness/test_artifacts/methods_abi/src/main.sw
  test/src/sdk-harness/test_artifacts/methods_contract/Forc.lock
  test/src/sdk-harness/test_artifacts/methods_contract/Forc.toml
  test/src/sdk-harness/test_artifacts/methods_contract/src/main.sw
  test/src/sdk-harness/test_projects/harness.rs
  test/src/sdk-harness/test_projects/methods/mod.rs
Labels: compiler: frontend

#2060 Some updates to the known issues section
  docs/src/reference/known_issues_and_workarounds.md
Labels: The Sway Book

#2021 Constants formatting for sway-fmt-v2
  sway-fmt-v2/src/fmt.rs
  sway-fmt-v2/src/items/item_const.rs
Labels: enhancement, formatter

#1982 Make `resolve_type_with_self` and `resolve_type_without_self` take `TypeId`'s instead of `TypeInfo`'s
  sway-core/src/semantic_analysis/ast_node/declaration/enum.rs
  sway-core/src/semantic_analysis/ast_node/declaration/function.rs
  sway-core/src/semantic_analysis/ast_node/declaration/function/function_parameter.rs
  sway-core/src/semantic_analysis/ast_node/declaration/impl_trait.rs
  sway-core/src/semantic_analysis/ast_node/declaration/monomorphize.rs
  sway-core/src/semantic_analysis/ast_node/declaration/struct.rs
  sway-core/src/semantic_analysis/ast_node/declaration/trait.rs
  sway-core/src/semantic_analysis/ast_node/expression/intrinsic_function.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/ast_node/mod.rs
  sway-core/src/semantic_analysis/namespace/namespace.rs
  sway-core/src/semantic_analysis/namespace/root.rs
Labels: compiler: frontend

#2062 Bump non-transitive `dashmap` to v5.3.4.
  Cargo.lock
  sway-lsp/Cargo.toml
Labels: dependencies

#2004 Introduce a type check `Context`. Replaces `TypeCheckArguments`.
  sway-core/src/ir_generation/compile.rs
  sway-core/src/ir_generation/function.rs
  sway-core/src/parse_tree/declaration/type_parameter.rs
  sway-core/src/semantic_analysis.rs
  sway-core/src/semantic_analysis/ast_node/code_block.rs
  sway-core/src/semantic_analysis/ast_node/declaration/abi.rs
  sway-core/src/semantic_analysis/ast_node/declaration/enum.rs
  sway-core/src/semantic_analysis/ast_node/declaration/function.rs
  sway-core/src/semantic_analysis/ast_node/declaration/function/function_parameter.rs
  sway-core/src/semantic_analysis/ast_node/declaration/impl_trait.rs
  sway-core/src/semantic_analysis/ast_node/declaration/struct.rs
  sway-core/src/semantic_analysis/ast_node/declaration/trait.rs
  sway-core/src/semantic_analysis/ast_node/expression/intrinsic_function.rs
  sway-core/src/semantic_analysis/ast_node/expression/match_expression/typed/typed_match_branch.rs
  sway-core/src/semantic_analysis/ast_node/expression/match_expression/typed/typed_match_expression.rs
  sway-core/src/semantic_analysis/ast_node/expression/match_expression/typed/typed_scrutinee.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/enum_instantiation.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/function_application.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/method_application.rs
  sway-core/src/semantic_analysis/ast_node/mod.rs
  sway-core/src/semantic_analysis/module.rs
  sway-core/src/semantic_analysis/program.rs
  sway-core/src/semantic_analysis/type_check_arguments.rs
  sway-core/src/semantic_analysis/type_check_context.rs
Labels: enhancement, compiler

#2026 Add `forc check` command
  Cargo.lock
  docs/src/SUMMARY.md
  docs/src/forc/commands/forc_check.md
  forc-pkg/src/pkg.rs
  forc/src/cli/commands/check.rs
  forc/src/cli/commands/mod.rs
  forc/src/cli/mod.rs
  forc/src/lib.rs
  forc/src/ops/forc_build.rs
  forc/src/ops/forc_check.rs
  forc/src/ops/mod.rs
  sway-lsp/Cargo.toml
  sway-lsp/src/core/document.rs
  sway-lsp/src/server.rs
Labels: enhancement, forc, language server

#2079 Small fixes to the `storage_map` example
  examples/storage_map/src/main.sw
Labels: The Sway Book

#2017 Add conceptual distinction between replacing `TypeInfo::Self` and monomorphization
  sway-core/src/semantic_analysis/ast_node/declaration/impl_trait.rs
  sway-core/src/semantic_analysis/ast_node/declaration/monomorphize.rs
  sway-core/src/semantic_analysis/ast_node/mod.rs
  sway-core/src/semantic_analysis/namespace/namespace.rs
  sway-core/src/semantic_analysis/namespace/root.rs
Labels: compiler: frontend

#2044 Add `abi` handling to `sway-fmt-v2`
  sway-fmt-v2/src/fmt.rs
  sway-fmt-v2/src/items/item_abi.rs
  sway-fmt-v2/src/items/item_enum.rs
  sway-fmt-v2/src/utils/attribute.rs
Labels: forc, formatter, ABI

#2094 Refactor `forc_pkg::BuildConfig` -> `BuildProfile`, fix CLI arg handling
  forc-pkg/src/lib.rs
  forc-pkg/src/manifest.rs
  forc-pkg/src/pkg.rs
  forc/src/ops/forc_build.rs
Labels: bug, enhancement, forc, code quality

#2095 forc: Improve the `print_*_asm` CLI option docs
  forc/src/cli/commands/build.rs
  forc/src/cli/commands/deploy.rs
  forc/src/cli/commands/run.rs
Labels: documentation, forc

#2099 update fuelup related instructions
  docs/src/introduction/installation.md
Labels: documentation, The Sway Book

#2091 Adding `--time-phases` to `forc build`
  forc-pkg/src/manifest.rs
  forc-pkg/src/pkg.rs
  forc/src/cli/commands/build.rs
  forc/src/cli/commands/deploy.rs
  forc/src/cli/commands/run.rs
  forc/src/ops/forc_build.rs
  forc/src/ops/forc_deploy.rs
  forc/src/ops/forc_run.rs
Labels: enhancement, forc

#1836 Add forc feature for overriding packages in the package graph, akin to cargo's [patch] feature
  docs/src/forc/manifest_reference.md
  forc-pkg/src/manifest.rs
  forc-pkg/src/pkg.rs
  test/src/e2e_vm_tests/test_programs/should_pass/forc/dependency_patching/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/forc/dependency_patching/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/forc/dependency_patching/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/forc/dependency_patching/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/forc/dependency_patching/test.toml
Labels: enhancement, compiler, forc

#2105 Bump to v0.16.2
  Cargo.lock
  forc-gm/Cargo.toml
  forc-pkg/Cargo.toml
  forc-plugins/forc-explore/Cargo.toml
  forc-plugins/forc-fmt-v2/Cargo.toml
  forc-plugins/forc-fmt/Cargo.toml
  forc-plugins/forc-lsp/Cargo.toml
  forc-util/Cargo.toml
  forc/Cargo.toml
  sway-core/Cargo.toml
  sway-fmt-v2/Cargo.toml
  sway-fmt/Cargo.toml
  sway-ir/Cargo.toml
  sway-lsp/Cargo.toml
  sway-parse/Cargo.toml
  sway-types/Cargo.toml
  sway-utils/Cargo.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/match_expressions_rest/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/match_expressions_rest/Forc.toml
Labels: release

#2058 Add struct formatting to sway-fmt-v2
  sway-fmt-v2/src/fmt.rs
  sway-fmt-v2/src/items/item_struct.rs
  sway-fmt-v2/src/utils.rs
  sway-fmt-v2/src/utils/item_len.rs
Labels: enhancement, formatter

#2111 internal: Reduce amount of String::new() in sway-fmt-v2
  sway-fmt-v2/src/error.rs
  sway-fmt-v2/src/fmt.rs
  sway-fmt-v2/src/items/item_abi.rs
  sway-fmt-v2/src/items/item_const.rs
  sway-fmt-v2/src/items/item_enum.rs
  sway-fmt-v2/src/items/item_fn.rs
  sway-fmt-v2/src/items/item_impl.rs
  sway-fmt-v2/src/items/item_storage.rs
  sway-fmt-v2/src/items/item_struct.rs
  sway-fmt-v2/src/items/item_trait.rs
  sway-fmt-v2/src/items/item_use.rs
  sway-fmt-v2/src/utils/attribute.rs
  sway-fmt-v2/src/utils/bracket.rs
  sway-fmt-v2/src/utils/item.rs
Labels: forc, code quality, formatter

#2120 examples: fix renaming to BASE_ASSET_ID in comment
  examples/wallet_smart_contract/src/main.sw
Labels: good first issue, code quality

#2113 Added storage field alignment threshold to formatter config
  sway-fmt-v2/src/config/user_def.rs
  sway-fmt-v2/src/config/user_opts.rs
  sway-fmt-v2/src/constants.rs
Labels: enhancement, formatter

#2078 Enable storage initializers and emit a storage initialization JSON
  .gitignore
  Cargo.lock
  forc-pkg/Cargo.toml
  forc-pkg/src/pkg.rs
  forc/src/cli/commands/build.rs
  forc/src/cli/commands/deploy.rs
  forc/src/cli/commands/run.rs
  forc/src/ops/forc_build.rs
  forc/src/ops/forc_deploy.rs
  forc/src/ops/forc_run.rs
  sway-core/Cargo.toml
  sway-core/src/convert_parse_tree.rs
  sway-core/src/ir_generation.rs
  sway-core/src/ir_generation/const_eval.rs
  sway-core/src/ir_generation/convert.rs
  sway-core/src/ir_generation/function.rs
  sway-core/src/ir_generation/storage.rs
  sway-core/src/lib.rs
  sway-core/src/parse_tree/declaration/storage.rs
  sway-core/src/semantic_analysis/ast_node/declaration/storage.rs
  sway-core/src/semantic_analysis/ast_node/mod.rs
  sway-core/src/semantic_analysis/program.rs
  test/Cargo.toml
  test/src/e2e_vm_tests/harness.rs
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/should_fail/nonconst_storage_init/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/nonconst_storage_init/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/nonconst_storage_init/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/nonconst_storage_init/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/storage_access_caller/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/test_abis/storage_access_abi/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/abi_with_tuples_contract/json_storage_slots_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/abi_with_tuples_contract/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/array_of_structs_contract/json_storage_slots_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/array_of_structs_contract/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/auth_testing_contract/json_storage_slots_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/auth_testing_contract/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/balance_test_contract/json_storage_slots_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/balance_test_contract/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/basic_storage/json_storage_slots_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/basic_storage/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/context_testing_contract/json_storage_slots_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/context_testing_contract/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/get_storage_key_contract/json_storage_slots_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/get_storage_key_contract/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/increment_contract/json_storage_slots_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/increment_contract/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/issue_1512_repro/json_storage_slots_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/issue_1512_repro/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/multiple_impl/json_storage_slots_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/multiple_impl/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/nested_struct_args_contract/json_storage_slots_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/nested_struct_args_contract/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/storage_access_contract/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/storage_access_contract/json_storage_slots_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/storage_access_contract/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/storage_access_contract/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/test_fuel_coin_contract/json_storage_slots_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/test_fuel_coin_contract/test.toml
Labels: enhancement, forc, compiler: ir, language feature, compiler: frontend, compiler: parser

#2007 remove `fuels-abigen-macro` dependency
  Cargo.lock
  forc-pkg/Cargo.toml
  forc/Cargo.toml
  forc/src/ops/forc_deploy.rs
  forc/src/utils/defaults.rs
  forc/src/utils/parameters.rs
  sway-core/Cargo.toml
  sway-types/Cargo.toml
  test-sig-gen-util/Cargo.toml
  test/Cargo.toml
  test/src/e2e_vm_tests/harness.rs
  test/src/sdk-harness/Cargo.toml
  test/src/sdk-harness/test_projects/auth/mod.rs
  test/src/sdk-harness/test_projects/call_frames/mod.rs
  test/src/sdk-harness/test_projects/context/mod.rs
  test/src/sdk-harness/test_projects/exponentiation/mod.rs
  test/src/sdk-harness/test_projects/harness.rs
  test/src/sdk-harness/test_projects/hashing/mod.rs
  test/src/sdk-harness/test_projects/logging/mod.rs
  test/src/sdk-harness/test_projects/methods/mod.rs
  test/src/sdk-harness/test_projects/reentrancy/mod.rs
  test/src/sdk-harness/test_projects/registers/mod.rs
  test/src/sdk-harness/test_projects/script_data/mod.rs
  test/src/sdk-harness/test_projects/storage/mod.rs
  test/src/sdk-harness/test_projects/storage_map/mod.rs
  test/src/sdk-harness/test_projects/token_ops/mod.rs
  test/src/sdk-harness/test_projects/tx_fields/mod.rs
Labels: forc, testing

#2110 Adds `Generics` handling to `sway-fmt-v2`
  sway-fmt-v2/src/fmt.rs
  sway-fmt-v2/src/items/item_abi.rs
  sway-fmt-v2/src/items/item_enum.rs
  sway-fmt-v2/src/items/item_struct.rs
  sway-fmt-v2/src/utils.rs
  sway-fmt-v2/src/utils/attribute.rs
  sway-fmt-v2/src/utils/bracket.rs
  sway-fmt-v2/src/utils/generics.rs
  sway-fmt-v2/src/utils/punctuated.rs
Labels: forc, formatter

#2137 #2020 - changed BASE_ASSET_ID type to ContractId
  examples/identity/src/main.sw
  examples/wallet_smart_contract/src/main.sw
  sway-lib-std/src/constants.sw
  sway-lib-std/src/lib.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/caller_context_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/contract_id_type/src/main.sw
Labels: good first issue, lib: std, code quality

#2141 #2039 - add storage keyword highlighting in book
  docs/theme/highlight.js
  scripts/highlightjs/sway.js
Labels: The Sway Book

#2103 Add the U256 type
  sway-lib-std/src/lib.sw
  sway-lib-std/src/u256.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/u256_test/.gitignore
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/u256_test/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/u256_test/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/u256_test/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/u256_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/u256_test/test.toml
Labels: enhancement, lib: std

#2097 sway-fmt-v2 formatting should use tokens directly from sway-parse
  sway-fmt-v2/src/items/item_struct.rs
  sway-fmt-v2/src/utils/program_type.rs
Labels: code quality, formatter

#2093 Move monomorphization conceptually inside of the type engine
  sway-core/src/semantic_analysis/ast_node/declaration.rs
  sway-core/src/semantic_analysis/ast_node/declaration/enum.rs
  sway-core/src/semantic_analysis/ast_node/declaration/function.rs
  sway-core/src/semantic_analysis/ast_node/declaration/function/function_parameter.rs
  sway-core/src/semantic_analysis/ast_node/declaration/monomorphize.rs
  sway-core/src/semantic_analysis/ast_node/declaration/struct.rs
  sway-core/src/semantic_analysis/ast_node/expression/intrinsic_function.rs
  sway-core/src/semantic_analysis/ast_node/expression/match_expression/typed/typed_scrutinee.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/enum_instantiation.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/function_application.rs
  sway-core/src/semantic_analysis/ast_node/mod.rs
  sway-core/src/semantic_analysis/namespace/namespace.rs
  sway-core/src/semantic_analysis/namespace/root.rs
  sway-core/src/semantic_analysis/type_check_context.rs
  sway-core/src/type_engine/engine.rs
Labels: compiler: frontend

#2136 `forc-pkg` - Don't add transitive deps (besides `core`) to a package's initial namespace
  forc-pkg/src/lib.rs
  forc-pkg/src/manifest.rs
  forc-pkg/src/pkg.rs
Labels: bug, forc, lib: core, compiler: frontend

#2132 Demonstrate that `T` for `Vec` can now be inferred by arguments
  test/src/e2e_vm_tests/test_programs/should_fail/vec/.gitignore
  test/src/e2e_vm_tests/test_programs/should_fail/vec/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/vec/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/vec/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/vec/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/vec/src/main.sw
Labels: bug, P: critical, compiler: frontend

#2156 Remove unnecessary "core" str check in `Span::join`
  sway-types/src/span.rs
Labels: bug, compiler

#2160 Update the book to explicitly mention that `impl` functions can't call each other yet.
  docs/src/reference/known_issues_and_workarounds.md
Labels: documentation

#2161 Remove duplicate CI checks that already have dedicated jobs
  .github/workflows/ci.yml
Labels: enhancement, ci, code quality

#2159 Speedup `find_dead_code` pass in control flow analysis
  sway-core/src/control_flow_analysis/dead_code_analysis.rs
Labels: enhancement, compiler, code quality

#2158 const initialization: a few fixes
  sway-core/src/ir_generation/function.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/method_application.rs
  sway-core/src/semantic_analysis/ast_node/mod.rs
  sway-core/tests/sway_to_ir/local_const_init.ir
  sway-core/tests/sway_to_ir/local_const_init.sw
  test/src/e2e_vm_tests/test_programs/should_fail/const_nonconst_init/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/const_nonconst_init/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/const_nonconst_init/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/const_nonconst_init/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/const_inits/src/main.sw
Labels: compiler: frontend

#2172 Update broken link for contributing to Sway in README.md
  README.md
Labels: bug, documentation

#2169 Backport improvements to `U128` type.
  sway-lib-std/src/u128.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/u128_test/src/main.sw
Labels: lib: std, code quality, breaking

#1969 Improvements around `forc plugins` command
  forc/src/cli/commands/plugins.rs
Labels: bug, forc

#2153 Updates `user_def` with `FieldAlignment` & fix corresponding use cases
  sway-fmt-v2/src/config/heuristics.rs
  sway-fmt-v2/src/config/user_def.rs
  sway-fmt-v2/src/config/user_opts.rs
  sway-fmt-v2/src/constants.rs
  sway-fmt-v2/src/fmt.rs
  sway-fmt-v2/src/items/item_enum.rs
  sway-fmt-v2/src/items/item_struct.rs
  sway-fmt-v2/src/utils/punctuated.rs
Labels: forc, code quality, formatter

#2123 Add `lex_commented` and `CommentedTokenStream` to `sway_parse`
  sway-parse/src/lib.rs
  sway-parse/src/token.rs
Labels: enhancement, formatter, P: high, compiler: parser
