Repository FuelLabs/sway, pull requests merged in 2022-10, with the labels that each got.

#2896 Bump a few dependencies
  Cargo.lock
  forc-pkg/Cargo.toml
  forc-pkg/src/pkg.rs
  forc-plugins/forc-client/Cargo.toml
  forc-plugins/forc-client/src/ops/deploy/op.rs
  forc-plugins/forc-client/src/ops/run/op.rs
  sway-core/Cargo.toml
Labels: dependencies

#2910 Reduce use of `to_typeinfo(..).unwrap()`
  sway-core/src/ir_generation/function.rs
  sway-core/src/semantic_analysis/ast_node/expression/intrinsic_function.rs
  sway-core/src/semantic_analysis/storage_only_types.rs
Labels: code quality

#2914 Rename `visit_expr` to `expr_leaf_spans`
  swayfmt/src/utils/language/expr/mod.rs
Labels: forc, code quality, formatter

#2913 Fix `doc` comments and apply to `lib std`
  sway-lib-std/src/option.sw
  sway-lib-std/src/reentrancy.sw
  sway-lib-std/src/result.sw
  sway-lib-std/src/storage.sw
  sway-lib-std/src/token.sw
  sway-lib-std/src/vec.sw
Labels: bug, forc, lib: std, formatter

#2916 Missing changes from 2913
  swayfmt/src/utils/language/attribute.rs
Labels: bug, forc, formatter

#2924 Some minor e2e tests cleanup
  test/src/e2e_vm_tests/test_programs/should_fail/missing_type_parameters/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/missing_type_parameters/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/missing_type_parameters/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_fail/missing_type_parameters/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/missing_type_parameters/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/dca/constant_decl_expr/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/dca/constant_decl_expr/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/dca/library/fn_params_free/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/dca/library/fn_params_free/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/dca/library/fn_params_impl/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/dca/library/fn_params_impl/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/dca/library/fn_params_trait/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/dca/library/fn_params_trait/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/dca/library/unused_pub_free_fn/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/dca/unused_free_fn/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/dca/unused_free_fn/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/dca/unused_struct/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/dca/unused_struct/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/abort_control_flow/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/array_dynamic_oob/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/array_dynamic_oob/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/array_dynamic_oob/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/array_dynamic_oob/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/missing_type_parameters/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/missing_type_parameters/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/missing_type_parameters/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/language/missing_type_parameters/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/missing_type_parameters/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/xos_opcode/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/xos_opcode/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/xos_opcode/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/xos_opcode/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/nested_struct_args_caller/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/nested_struct_args_caller/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/nested_struct_args_caller/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/nested_struct_args_caller/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/contract_id_test/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/contract_id_test/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/nested_struct_args_contract/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/nested_struct_args_contract/src/main.sw
Labels: testing

#2920 ci: revert forc-client CI removals
  .github/workflows/ci.yml
  .github/workflows/gh-pages.yml
Labels: ci

#2940 Enable a `StorageMap` test case that wasn't working before
  test/src/sdk-harness/test_projects/storage_map/mod.rs
Labels: testing

#2941 Rename `transfer_to_output` to `transfer_to_address`
  examples/identity/src/main.sw
  examples/liquidity_pool/src/main.sw
  examples/native_token/src/main.sw
  examples/wallet_smart_contract/src/main.sw
  sway-lib-std/src/token.sw
  test/src/sdk-harness/test_projects/token_ops/src/main.sw
Labels: enhancement, lib: std, breaking

#2918 Fix `struct` and `tuple` destructuring formatting
  examples/arrays/src/main.sw
  examples/structs/src/main.sw
  examples/tuples/src/main.sw
  swayfmt/src/formatter/mod.rs
  swayfmt/src/formatter/shape.rs
  swayfmt/src/utils/language/expr/mod.rs
  swayfmt/src/utils/language/pattern.rs
Labels: enhancement, forc, formatter

#2890 Introduce a `__revert` intrinsic a disallow `rvrt`, `ret` and `retd` in `asm` blocks
  sway-ast/src/expr/op_code.rs
  sway-ast/src/intrinsics.rs
  sway-core/src/asm_generation/asm_builder.rs
  sway-core/src/ir_generation/compile.rs
  sway-core/src/ir_generation/function.rs
  sway-core/src/semantic_analysis/ast_node/expression/intrinsic_function.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/tests/ir_to_asm/revert.asm
  sway-core/tests/ir_to_asm/revert.ir
  sway-ir/src/asm.rs
  sway-ir/src/block.rs
  sway-ir/src/error.rs
  sway-ir/src/instruction.rs
  sway-ir/src/optimize/dce.rs
  sway-ir/src/optimize/inline.rs
  sway-ir/src/parser.rs
  sway-ir/src/printer.rs
  sway-ir/src/value.rs
  sway-ir/src/verify.rs
  sway-lib-std/src/revert.sw
  sway-parse/src/expr/op_code.rs
  test/src/e2e_vm_tests/test_programs/should_pass/language/abort_control_flow_good/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/bool_and_or/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/diverging_exprs/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/diverging_exprs/src/main.sw
  test/src/ir_generation/tests/revert.sw
Labels: compiler: ir, language feature, breaking, compiler: frontend, compiler: parser, compiler: codegen

#2942 Bump to `v0.25.0`
  Cargo.lock
  forc-pkg/Cargo.toml
  forc-plugins/forc-client/Cargo.toml
  forc-plugins/forc-explore/Cargo.toml
  forc-plugins/forc-fmt/Cargo.toml
  forc-plugins/forc-lsp/Cargo.toml
  forc-util/Cargo.toml
  forc/Cargo.toml
  sway-ast/Cargo.toml
  sway-core/Cargo.toml
  sway-ir/Cargo.toml
  sway-ir/sway-ir-macros/Cargo.toml
  sway-lsp/Cargo.toml
  sway-parse/Cargo.toml
  sway-types/Cargo.toml
  sway-utils/Cargo.toml
  swayfmt/Cargo.toml
Labels: release

#2936 Remove the `TypeInfo::Ref` variant
  sway-core/src/ir_generation/convert.rs
  sway-core/src/lib.rs
  sway-core/src/semantic_analysis/ast_node/declaration.rs
  sway-core/src/semantic_analysis/ast_node/declaration/enum.rs
  sway-core/src/semantic_analysis/ast_node/declaration/function.rs
  sway-core/src/semantic_analysis/ast_node/declaration/function/function_parameter.rs
  sway-core/src/semantic_analysis/ast_node/declaration/struct.rs
  sway-core/src/semantic_analysis/ast_node/declaration/variable.rs
  sway-core/src/semantic_analysis/ast_node/expression/intrinsic_function.rs
  sway-core/src/semantic_analysis/ast_node/expression/match_expression/analysis/constructor_factory.rs
  sway-core/src/semantic_analysis/ast_node/expression/match_expression/analysis/pattern.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression_variant.rs
  sway-core/src/semantic_analysis/node_dependencies.rs
  sway-core/src/type_system/collect_types_metadata.rs
  sway-core/src/type_system/mod.rs
  sway-core/src/type_system/type_argument.rs
  sway-core/src/type_system/type_engine.rs
  sway-core/src/type_system/type_id.rs
  sway-core/src/type_system/type_info.rs
  sway-core/src/type_system/type_mapping.rs
  sway-core/src/type_system/type_parameter.rs
  sway-lsp/src/core/traverse_parse_tree.rs
  sway-lsp/src/utils/token.rs
  test/src/e2e_vm_tests/test_programs/should_fail/insufficient_type_info/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/match_expressions_inside_generic_functions/src/main.sw
Labels: compiler: frontend

#2894 Refactor manifest handling around `forc-pkg` to accommodate workspace manifest files
  forc-pkg/src/lib.rs
  forc-pkg/src/manifest.rs
  forc-pkg/src/pkg.rs
  forc-plugins/forc-client/src/ops/deploy/op.rs
  forc-plugins/forc-client/src/ops/run/op.rs
  forc/src/ops/forc_check.rs
  forc/src/ops/forc_template.rs
  forc/src/ops/forc_update.rs
  forc/src/utils/defaults.rs
  sway-lsp/src/core/session.rs
Labels: forc, code quality, dependencies, P: high

#2958 feat: Output contract-id to .out folder with forc build
  Cargo.lock
  forc-pkg/Cargo.toml
  forc-pkg/src/pkg.rs
Labels: enhancement, forc

#2973 Bump to `v0.25.2`
  Cargo.lock
  forc-pkg/Cargo.toml
  forc-plugins/forc-client/Cargo.toml
  forc-plugins/forc-explore/Cargo.toml
  forc-plugins/forc-fmt/Cargo.toml
  forc-plugins/forc-lsp/Cargo.toml
  forc-util/Cargo.toml
  forc/Cargo.toml
  sway-ast/Cargo.toml
  sway-core/Cargo.toml
  sway-ir/Cargo.toml
  sway-ir/sway-ir-macros/Cargo.toml
  sway-lsp/Cargo.toml
  sway-parse/Cargo.toml
  sway-types/Cargo.toml
  sway-utils/Cargo.toml
  swayfmt/Cargo.toml
Labels: release

#2956 Update finalized asm example in Sway Book
  docs/src/introduction/forc_project.md
Labels: The Sway Book

#2915 Remove unused `peekable` operations from `swayfmt`
  swayfmt/src/items/item_enum/mod.rs
  swayfmt/src/items/item_storage/mod.rs
  swayfmt/src/items/item_struct/mod.rs
  swayfmt/src/module/mod.rs
  swayfmt/src/utils/language/punctuated.rs
Labels: forc, code quality, formatter

#2568 Add LSP tests back in.
  Cargo.lock
  sway-lsp/Cargo.toml
  sway-lsp/src/server.rs
  sway-lsp/src/utils/token.rs
Labels: ci, language server, testing

#2264 Remove Rust integration testing behaviour from `forc test` in anticipation of unit testing support
  .github/workflows/ci.yml
  docs/src/introduction/forc_project.md
  docs/src/testing/index.md
  docs/src/testing/testing-with-rust.md
  forc-util/src/lib.rs
  forc/src/cli/commands/clean.rs
  forc/src/cli/commands/test.rs
  forc/src/ops/forc_clean.rs
  forc/src/ops/forc_init.rs
  forc/src/ops/forc_template.rs
  forc/src/utils/defaults.rs
  scripts/mdbook-forc-documenter/examples/forc_init.md
  scripts/mdbook-forc-documenter/examples/forc_new.md
  scripts/mdbook-forc-documenter/examples/forc_test.md
  templates/README.md
  templates/sway-test-rs/README.md
  templates/sway-test-rs/template/Cargo.toml
  templates/sway-test-rs/template/cargo-generate.toml
  templates/sway-test-rs/template/tests/harness.rs
Labels: forc, testing, The Sway Book, P: high

#2979 Forward attributes from `ParseProgram` to `TyProgram`
  sway-core/src/convert_parse_tree.rs
  sway-core/src/semantic_analysis/ast_node/declaration.rs
  sway-core/src/semantic_analysis/ast_node/declaration/enum.rs
  sway-core/src/semantic_analysis/ast_node/declaration/function.rs
  sway-core/src/semantic_analysis/ast_node/declaration/storage.rs
  sway-core/src/semantic_analysis/ast_node/declaration/struct.rs
  sway-core/src/semantic_analysis/ast_node/declaration/trait.rs
  sway-core/src/semantic_analysis/ast_node/mod.rs
  sway-core/src/semantic_analysis/namespace/module.rs
  sway-lsp/src/utils/attributes.rs
Labels: compiler, compiler: frontend

#2980 Add `#[test]` to list of known attributes in `sway-core`
  sway-core/src/convert_parse_tree.rs
  sway-core/src/lib.rs
  sway-error/src/convert_parse_tree_error.rs
  sway-types/src/constants.rs
  test/src/e2e_vm_tests/test_programs/should_pass/language/test_attribute/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/test_attribute/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/test_attribute/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/test_attribute/test.toml
Labels: compiler, testing

#2982 Move the definitions for `TyExpression` and `TyExpressionVariant` to the `ty` module.
  sway-core/src/control_flow_analysis/analyze_return_paths.rs
  sway-core/src/control_flow_analysis/dead_code_analysis.rs
  sway-core/src/ir_generation/const_eval.rs
  sway-core/src/ir_generation/function.rs
  sway-core/src/language/mod.rs
  sway-core/src/language/ty/expression/expression.rs
  sway-core/src/language/ty/expression/expression_variant.rs
  sway-core/src/language/ty/expression/mod.rs
  sway-core/src/language/ty/mod.rs
  sway-core/src/semantic_analysis/ast_node/code_block.rs
  sway-core/src/semantic_analysis/ast_node/declaration.rs
  sway-core/src/semantic_analysis/ast_node/declaration/function.rs
  sway-core/src/semantic_analysis/ast_node/declaration/function/function_parameter.rs
  sway-core/src/semantic_analysis/ast_node/declaration/impl_trait.rs
  sway-core/src/semantic_analysis/ast_node/declaration/storage.rs
  sway-core/src/semantic_analysis/ast_node/declaration/variable.rs
  sway-core/src/semantic_analysis/ast_node/expression/intrinsic_function.rs
  sway-core/src/semantic_analysis/ast_node/expression/match_expression/typed/matcher.rs
  sway-core/src/semantic_analysis/ast_node/expression/match_expression/typed/typed_match_branch.rs
  sway-core/src/semantic_analysis/ast_node/expression/match_expression/typed/typed_match_expression.rs
  sway-core/src/semantic_analysis/ast_node/expression/mod.rs
  sway-core/src/semantic_analysis/ast_node/expression/struct_expr_field.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/enum_instantiation.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/function_application.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/if_expression.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/lazy_operator.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/method_application.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/struct_field_access.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/tuple_index_access.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/unsafe_downcast.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression_variant.rs
  sway-core/src/semantic_analysis/ast_node/mod.rs
  sway-core/src/semantic_analysis/ast_node/return_statement.rs
  sway-core/src/semantic_analysis/namespace/namespace.rs
  sway-core/src/semantic_analysis/namespace/root.rs
  sway-core/src/semantic_analysis/storage_only_types.rs
  sway-core/src/type_system/resolved_type.rs
  sway-core/src/type_system/type_info.rs
  sway-lsp/src/core/token.rs
  sway-lsp/src/core/traverse_typed_tree.rs
Labels: code quality, compiler: frontend, compiler: collection

#2983 Move the storage definitions to the `ty` module.
  sway-core/src/ir_generation/function.rs
  sway-core/src/ir_generation/types.rs
  sway-core/src/language/ty/expression/expression_variant.rs
  sway-core/src/language/ty/expression/mod.rs
  sway-core/src/language/ty/expression/storage.rs
  sway-core/src/semantic_analysis/ast_node/declaration/storage.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression_variant.rs
  sway-core/src/semantic_analysis/namespace/items.rs
Labels: code quality, compiler: frontend, compiler: collection

#2999 Remove dead `ReassignmentLHS` definition.
  sway-core/src/semantic_analysis/ast_node/declaration.rs
Labels: code quality

#3002 Propagate error messages in const eval instead of unwrapping
  sway-core/src/ir_generation/const_eval.rs
  test/src/e2e_vm_tests/test_programs/should_fail/const_eval_bad_struct/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/const_eval_bad_struct/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/const_eval_bad_struct/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/const_eval_bad_struct/test.toml
Labels: bug, P: critical, compiler: frontend

#3011 Remove the no-op `TyReturnStatement` type.
  sway-core/src/control_flow_analysis/dead_code_analysis.rs
  sway-core/src/ir_generation/const_eval.rs
  sway-core/src/ir_generation/function.rs
  sway-core/src/language/ty/expression/expression.rs
  sway-core/src/language/ty/expression/expression_variant.rs
  sway-core/src/semantic_analysis/ast_node/declaration/function.rs
  sway-core/src/semantic_analysis/ast_node/declaration/impl_trait.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/ast_node/mod.rs
  sway-core/src/semantic_analysis/ast_node/return_statement.rs
  sway-core/src/semantic_analysis/storage_only_types.rs
  sway-lsp/src/core/traverse_typed_tree.rs
Labels: code quality

#3013 Clarify some information about event logging in the Sway Book
  docs/src/basics/comments_and_logging.md
  examples/subcurrency/src/main.sw
Labels: The Sway Book

#2968 Move DocumentError to use thiserror
  Cargo.lock
  sway-lsp/Cargo.toml
  sway-lsp/src/core/document.rs
  sway-lsp/src/core/session.rs
  sway-lsp/src/error.rs
  sway-lsp/src/lib.rs
  sway-lsp/src/server.rs
  sway-lsp/src/test_utils.rs
  sway-lsp/test/fixtures/cats.txt
Labels: language server, code quality

#3020 Add tests for `Option` and `Result` in the ABI
  test/src/sdk-harness/test_projects/harness.rs
  test/src/sdk-harness/test_projects/option_in_abi/Forc.lock
  test/src/sdk-harness/test_projects/option_in_abi/Forc.toml
  test/src/sdk-harness/test_projects/option_in_abi/mod.rs
  test/src/sdk-harness/test_projects/option_in_abi/src/main.sw
  test/src/sdk-harness/test_projects/result_in_abi/Forc.lock
  test/src/sdk-harness/test_projects/result_in_abi/Forc.toml
  test/src/sdk-harness/test_projects/result_in_abi/mod.rs
  test/src/sdk-harness/test_projects/result_in_abi/src/main.sw
Labels: testing

#3022 Fail on mismatch in method return types for ABIs and traits
  sway-core/src/semantic_analysis/ast_node/declaration/impl_trait.rs
  sway-error/src/error.rs
  test/src/e2e_vm_tests/test_programs/should_fail/abi_method_signature_mismatch/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/abi_method_signature_mismatch/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/trait_method_signature_mismatch/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/trait_method_signature_mismatch/test.toml
Labels: enhancement, compiler: ui

#3023 Bump to `v0.26.0`
  Cargo.lock
  forc-pkg/Cargo.toml
  forc-plugins/forc-client/Cargo.toml
  forc-plugins/forc-explore/Cargo.toml
  forc-plugins/forc-fmt/Cargo.toml
  forc-plugins/forc-lsp/Cargo.toml
  forc-util/Cargo.toml
  forc/Cargo.toml
  sway-ast/Cargo.toml
  sway-core/Cargo.toml
  sway-error/Cargo.toml
  sway-ir/Cargo.toml
  sway-ir/sway-ir-macros/Cargo.toml
  sway-lsp/Cargo.toml
  sway-parse/Cargo.toml
  sway-types/Cargo.toml
  sway-utils/Cargo.toml
  swayfmt/Cargo.toml
Labels: release

#3028 Add the `sway-error` crate to the top level `Cargo.toml`
  Cargo.toml
Labels: dependencies

#3033 Add `const` attributes to `TyProgram`
  sway-core/src/language/ty/declaration/constant.rs
  sway-core/src/semantic_analysis/ast_node/mod.rs
Labels: forc, blocked

#3027 Add `enum variant` attributes to `TyProgram`
  sway-core/src/language/ty/declaration/enum.rs
  sway-core/src/semantic_analysis/ast_node/declaration/enum.rs
  sway-core/src/type_system/mod.rs
Labels: forc, blocked

#3036 Add `trait` attributes to `TyProgram`
  sway-core/src/language/ty/declaration/trait.rs
  sway-core/src/semantic_analysis/ast_node/declaration/trait.rs
Labels: forc, blocked

#2938 Introduce `unify_right`
  sway-core/src/semantic_analysis/ast_node/declaration/function.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/function_application.rs
  sway-core/src/type_system/mod.rs
  sway-core/src/type_system/type_binding.rs
  sway-core/src/type_system/type_engine.rs
  sway-core/src/type_system/type_id.rs
  sway-core/src/type_system/type_mapping.rs
  sway-core/src/type_system/type_parameter.rs
  sway-core/src/type_system/unify.rs
  test/src/e2e_vm_tests/test_programs/should_fail/simple_generics/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/simple_generics/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/simple_generics/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/simple_generics/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/logging/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/language/match_expressions_inside_generic_functions/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/require/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/multiple_impl/json_abi_oracle.json
Labels: bug, P: critical, compiler: frontend

#3038 Add `abi` attributes to `TyProgram`
  sway-core/src/convert_parse_tree.rs
  sway-core/src/language/parsed/declaration/abi.rs
  sway-core/src/language/ty/declaration/abi.rs
  sway-core/src/semantic_analysis/ast_node/declaration/abi.rs
Labels: forc, ABI, documentation

#2919 LSP synchronize workspace
  Cargo.lock
  forc-pkg/src/manifest.rs
  forc/Cargo.toml
  sway-lsp/Cargo.toml
  sway-lsp/src/capabilities/highlight.rs
  sway-lsp/src/capabilities/hover.rs
  sway-lsp/src/capabilities/rename.rs
  sway-lsp/src/core/session.rs
  sway-lsp/src/error.rs
  sway-lsp/src/server.rs
  sway-lsp/src/test_utils.rs
  sway-lsp/src/utils/mod.rs
  sway-lsp/src/utils/sync.rs
Labels: bug, language server

#3041 fix: add missing leaf span collection for final_expr_opt of asm blocks
  examples/asm_return_tuple_pointer/src/main.sw
  swayfmt/src/utils/language/expr/asm_block.rs
Labels: bug, formatter, P: critical

#3049 Remove the dead `IsConstant` type
  sway-core/src/language/ty/expression/expression.rs
  sway-core/src/semantic_analysis/ast_node/declaration/function/function_parameter.rs
  sway-core/src/semantic_analysis/ast_node/expression/match_expression/typed/matcher.rs
  sway-core/src/semantic_analysis/ast_node/expression/match_expression/typed/typed_match_branch.rs
  sway-core/src/semantic_analysis/ast_node/expression/match_expression/typed/typed_match_expression.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/enum_instantiation.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/function_application.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/if_expression.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/lazy_operator.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/method_application.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/struct_field_access.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/tuple_index_access.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/unsafe_downcast.rs
  sway-core/src/semantic_analysis/ast_node/mod.rs
Labels: code quality

#3046 Create the `transform` and `to_parsed_lang` modules.
  sway-core/src/language/parsed/declaration/abi.rs
  sway-core/src/language/parsed/declaration/constant.rs
  sway-core/src/language/parsed/declaration/enum.rs
  sway-core/src/language/parsed/declaration/function.rs
  sway-core/src/language/parsed/declaration/storage.rs
  sway-core/src/language/parsed/declaration/struct.rs
  sway-core/src/language/parsed/declaration/trait.rs
  sway-core/src/language/ty/declaration/abi.rs
  sway-core/src/language/ty/declaration/constant.rs
  sway-core/src/language/ty/declaration/enum.rs
  sway-core/src/language/ty/declaration/function.rs
  sway-core/src/language/ty/declaration/storage.rs
  sway-core/src/language/ty/declaration/struct.rs
  sway-core/src/language/ty/declaration/trait.rs
  sway-core/src/language/ty/declaration/trait_fn.rs
  sway-core/src/lib.rs
  sway-core/src/semantic_analysis/ast_node/declaration/storage.rs
  sway-core/src/semantic_analysis/namespace/module.rs
  sway-core/src/transform/attribute.rs
  sway-core/src/transform/mod.rs
  sway-core/src/transform/to_parsed_lang/convert_parse_tree.rs
  sway-core/src/transform/to_parsed_lang/error.rs
  sway-core/src/transform/to_parsed_lang/mod.rs
  sway-core/src/type_system/mod.rs
  sway-lsp/src/utils/attributes.rs
Labels: code quality, compiler: frontend, compiler: collection

#3042 Issue #3040; docs corrections
  docs/src/advanced/traits.md
  docs/src/basics/variables.md
  docs/src/blockchain-development/identifiers.md
  docs/src/examples/subcurrency.md
  docs/src/introduction/overview.md
  docs/src/introduction/standard_library.md
Labels: The Sway Book

#3045 Issue#3044 Update minor mistakes in README.md and src/reentrancy.sw
  sway-lib-std/README.md
  sway-lib-std/src/reentrancy.sw
Labels: lib: std, P: low

#3029 Parse generic traits.
  sway-ast/src/item/item_trait.rs
  sway-core/src/language/parsed/declaration/impl_trait.rs
  sway-core/src/language/parsed/declaration/trait.rs
  sway-core/src/language/ty/declaration/impl_trait.rs
  sway-core/src/semantic_analysis/ast_node/declaration/impl_trait.rs
  sway-core/src/semantic_analysis/ast_node/declaration/trait.rs
  sway-core/src/semantic_analysis/node_dependencies.rs
  sway-core/src/transform/to_parsed_lang/convert_parse_tree.rs
  sway-core/src/type_system/type_argument.rs
  sway-lsp/src/core/traverse_parse_tree.rs
  sway-parse/src/item/item_trait.rs
  sway-types/src/span.rs
  test/src/e2e_vm_tests/test_programs/should_fail/generic_traits/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/generic_traits/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/generic_traits/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/generic_traits/test.toml
Labels: language feature, compiler: frontend, compiler: parser

#3051 Make `StructExpression` take an `Ident` instead of a `TypeInfo`.
  sway-core/src/language/parsed/expression/mod.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/node_dependencies.rs
  sway-core/src/transform/to_parsed_lang/convert_parse_tree.rs
  sway-core/src/type_system/type_id.rs
  sway-core/src/type_system/type_info.rs
  sway-lsp/src/core/traverse_parse_tree.rs
Labels: compiler: frontend, compiler: collection

#3048 Move any general methods to live within the same file as the definition for their parent.
  sway-core/src/language/ty/ast_node.rs
  sway-core/src/language/ty/declaration/declaration.rs
  sway-core/src/language/ty/declaration/enum.rs
  sway-core/src/language/ty/declaration/function.rs
  sway-core/src/language/ty/declaration/storage.rs
  sway-core/src/language/ty/declaration/struct.rs
  sway-core/src/language/ty/expression/expression.rs
  sway-core/src/language/ty/expression/expression_variant.rs
  sway-core/src/language/ty/program.rs
  sway-core/src/semantic_analysis.rs
  sway-core/src/semantic_analysis/ast_node/declaration.rs
  sway-core/src/semantic_analysis/ast_node/declaration/enum.rs
  sway-core/src/semantic_analysis/ast_node/declaration/function.rs
  sway-core/src/semantic_analysis/ast_node/declaration/function/function_parameter.rs
  sway-core/src/semantic_analysis/ast_node/declaration/storage.rs
  sway-core/src/semantic_analysis/ast_node/declaration/struct.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/function_application.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/method_application.rs
  sway-core/src/semantic_analysis/ast_node/mod.rs
  sway-core/src/semantic_analysis/program.rs
Labels: code quality, compiler: frontend, compiler: collection

#3015 LSP: Add Inlay Hints functionality for variables
  Cargo.lock
  forc-plugins/forc-lsp/src/main.rs
  sway-lsp/Cargo.toml
  sway-lsp/src/capabilities/inlay_hints.rs
  sway-lsp/src/capabilities/mod.rs
  sway-lsp/src/core/config.rs
  sway-lsp/src/core/mod.rs
  sway-lsp/src/core/session.rs
  sway-lsp/src/core/token.rs
  sway-lsp/src/lib.rs
  sway-lsp/src/server.rs
  sway-lsp/src/utils/debug.rs
Labels: enhancement, language server

#3039 Port `TypedExpressionVariant::FunctionApplication` to the declaration engine.
  sway-core/src/declaration_engine/declaration_id.rs
  sway-core/src/ir_generation/const_eval.rs
  sway-core/src/ir_generation/function.rs
  sway-core/src/language/ty/expression/expression.rs
  sway-core/src/language/ty/expression/expression_variant.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/function_application.rs
  sway-lsp/src/core/traverse_typed_tree.rs
Labels: compiler: frontend

#3056 Use Handler in Purity checking
  sway-core/src/ir_generation.rs
  sway-core/src/ir_generation/purity.rs
  sway-core/src/lib.rs
Labels: enhancement, code quality, compiler: ui

#3066 Fix span calculations for errors at the end of a file with no final `\n`
  sway-parse/src/parser.rs
  test/src/e2e_vm_tests/test_programs/should_fail/no_newline/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/no_newline/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/no_newline/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/no_newline/test.toml
Labels: bug, P: critical, compiler: parser

#3072 LSP: code reorganize to support multiple projects simultaneously
  sway-lsp/src/capabilities/highlight.rs
  sway-lsp/src/capabilities/hover.rs
  sway-lsp/src/capabilities/inlay_hints.rs
  sway-lsp/src/capabilities/rename.rs
  sway-lsp/src/capabilities/semantic_tokens.rs
  sway-lsp/src/core/session.rs
  sway-lsp/src/error.rs
  sway-lsp/src/lib.rs
  sway-lsp/src/server.rs
  sway-lsp/src/utils/sync.rs
Labels: bug, enhancement, language server

#2796 Revamped implementation of `send_message`
  sway-lib-std/src/lib.sw
  sway-lib-std/src/message.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/logging/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/require/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/multiple_impl/json_abi_oracle.json
  test/src/sdk-harness/test_projects/token_ops/mod.rs
  test/src/sdk-harness/test_projects/token_ops/src/main.sw
Labels: lib: std, P: high

#3092 Fixed testing-with-rust docs
  docs/src/testing/testing-with-rust.md
Labels: The Sway Book

#3088 Add `span` field to `const` for `forc doc`
  sway-core/src/language/parsed/declaration/constant.rs
  sway-core/src/language/ty/declaration/constant.rs
  sway-core/src/semantic_analysis/ast_node/mod.rs
  sway-core/src/transform/to_parsed_lang/convert_parse_tree.rs
Labels: forc, documentation

#3090 Add `span` field to `trait` for `forc doc`
  sway-core/src/language/parsed/declaration/trait.rs
  sway-core/src/language/ty/declaration/trait.rs
  sway-core/src/semantic_analysis/ast_node/declaration/trait.rs
  sway-core/src/transform/to_parsed_lang/convert_parse_tree.rs
Labels: forc, documentation

#3075 Allow signing forc-client transactions without prompting
  Cargo.lock
  forc-plugins/forc-client/Cargo.toml
  forc-plugins/forc-client/src/ops/deploy/cmd.rs
  forc-plugins/forc-client/src/ops/deploy/op.rs
  forc-plugins/forc-client/src/ops/mod.rs
  forc-plugins/forc-client/src/ops/parameters.rs
  forc-plugins/forc-client/src/ops/run/cmd.rs
  forc-plugins/forc-client/src/ops/run/op.rs
  forc-plugins/forc-client/src/ops/tx_util.rs
  test/src/e2e_vm_tests/harness.rs
Labels: forc

#3095 Don't clone the whole graph on each trait impl connection during DCA
  sway-core/src/control_flow_analysis/dead_code_analysis.rs
Labels: enhancement, compiler, compiler: frontend

#2909 Bitwise not for all unsigned integers
  sway-core/src/lib.rs
  sway-core/src/transform/to_parsed_lang/convert_parse_tree.rs
  sway-lib-core/src/ops.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/bitwise_not/.gitignore
  test/src/e2e_vm_tests/test_programs/should_pass/language/bitwise_not/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/bitwise_not/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/bitwise_not/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/language/bitwise_not/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/bitwise_not/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/diverging_exprs/src/main.sw
Labels: lib: core

#3091 Type engine bug fixes and improvements.
  sway-core/src/declaration_engine/declaration_id.rs
  sway-core/src/declaration_engine/declaration_wrapper.rs
  sway-core/src/language/ty/ast_node.rs
  sway-core/src/language/ty/code_block.rs
  sway-core/src/language/ty/declaration/declaration.rs
  sway-core/src/language/ty/declaration/enum.rs
  sway-core/src/language/ty/declaration/function.rs
  sway-core/src/language/ty/declaration/impl_trait.rs
  sway-core/src/language/ty/declaration/struct.rs
  sway-core/src/language/ty/declaration/trait.rs
  sway-core/src/language/ty/declaration/trait_fn.rs
  sway-core/src/language/ty/declaration/variable.rs
  sway-core/src/language/ty/expression/asm.rs
  sway-core/src/language/ty/expression/expression.rs
  sway-core/src/language/ty/expression/expression_variant.rs
  sway-core/src/language/ty/expression/intrinsic_function.rs
  sway-core/src/language/ty/expression/reassignment.rs
  sway-core/src/language/ty/expression/struct_exp_field.rs
  sway-core/src/lib.rs
  sway-core/src/semantic_analysis/ast_node/declaration/impl_trait.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/enum_instantiation.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/function_application.rs
  sway-core/src/type_system/copy_types.rs
  sway-core/src/type_system/type_argument.rs
  sway-core/src/type_system/type_engine.rs
  sway-core/src/type_system/type_id.rs
  sway-core/src/type_system/type_mapping.rs
  sway-core/src/type_system/type_parameter.rs
  sway-core/src/type_system/unify.rs
Labels: code quality, compiler: frontend

#3096 Speedup bytecode-gen by applying an upper bound on `read_exact`
  sway-core/src/asm_generation/finalized_asm.rs
Labels: code quality, compiler: codegen

#3099 Speedup `remove_redudant_moves()` by using a `HashSet` instead of a `BTreeSet`
  sway-core/src/asm_generation/abstract_instruction_set.rs
Labels: code quality, compiler: codegen

#3080 Add const probing to delineated path type check
  sway-core/src/language/ty/declaration/declaration.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/constant_decleration.rs
  sway-error/src/error.rs
  test/src/e2e_vm_tests/test_programs/should_pass/language/const_decl_with_call_path/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/const_decl_with_call_path/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/const_decl_with_call_path/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/language/const_decl_with_call_path/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/const_decl_with_call_path/src/test_lib.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/const_decl_with_call_path/test.toml
Labels: bug, compiler: frontend

#3102 Speedup `simplify_cfg` by avoiding Vec alloc in hot loop
  sway-ir/src/block.rs
Labels: compiler, compiler: ir, compiler: optimization

#3098 Bug fixes for type checking trait declarations.
  sway-core/src/language/ty/declaration/function.rs
  sway-core/src/semantic_analysis/ast_node/declaration/abi.rs
  sway-core/src/semantic_analysis/ast_node/declaration/function.rs
  sway-core/src/semantic_analysis/ast_node/declaration/function/function_parameter.rs
  sway-core/src/semantic_analysis/ast_node/declaration/impl_trait.rs
  sway-core/src/semantic_analysis/ast_node/declaration/trait.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/ast_node/mod.rs
  sway-ir/src/parser.rs
  sway-ir/src/printer.rs
Labels: code quality, compiler: frontend

#3082 Expose CROO opcode through the std-lib
  sway-lib-std/src/b512.sw
  sway-lib-std/src/ecr.sw
  sway-lib-std/src/external.sw
  sway-lib-std/src/lib.sw
  sway-lib-std/src/storage.sw
  sway-lib-std/src/u128.sw
  sway-lib-std/src/u256.sw
  sway-lib-std/src/vm/evm/ecr.sw
  test/src/sdk-harness/test_projects/contract_bytecode/.gitignore
  test/src/sdk-harness/test_projects/contract_bytecode/Forc.lock
  test/src/sdk-harness/test_projects/contract_bytecode/Forc.toml
  test/src/sdk-harness/test_projects/contract_bytecode/mod.rs
  test/src/sdk-harness/test_projects/contract_bytecode/src/main.sw
  test/src/sdk-harness/test_projects/harness.rs
Labels: lib: std

#3100 Bump to `v0.27.0`
  Cargo.lock
  forc-pkg/Cargo.toml
  forc-plugins/forc-client/Cargo.toml
  forc-plugins/forc-explore/Cargo.toml
  forc-plugins/forc-fmt/Cargo.toml
  forc-plugins/forc-lsp/Cargo.toml
  forc-util/Cargo.toml
  forc/Cargo.toml
  sway-ast/Cargo.toml
  sway-core/Cargo.toml
  sway-error/Cargo.toml
  sway-ir/Cargo.toml
  sway-ir/sway-ir-macros/Cargo.toml
  sway-lsp/Cargo.toml
  sway-parse/Cargo.toml
  sway-types/Cargo.toml
  sway-utils/Cargo.toml
  swayfmt/Cargo.toml
Labels: release

#2925 [LSP] Replace logging with tracing
  Cargo.lock
  forc-util/src/lib.rs
  forc/src/cli/mod.rs
  sway-lsp/Cargo.toml
  sway-lsp/src/lib.rs
  sway-lsp/src/server.rs
  sway-lsp/src/utils/debug.rs
Labels: enhancement, language server

#3094 More error handling in sway-lsp
  sway-lsp/src/capabilities/formatting.rs
  sway-lsp/src/capabilities/semantic_tokens.rs
  sway-lsp/src/core/session.rs
  sway-lsp/src/error.rs
  sway-lsp/src/server.rs
  sway-lsp/src/utils/sync.rs
Labels: language server

#3108 refactor(forc): extract tracing utils from `forc-util` into dedicated `forc-tracing`
  Cargo.lock
  Cargo.toml
  forc-pkg/Cargo.toml
  forc-pkg/src/lock.rs
  forc-pkg/src/manifest.rs
  forc-plugins/forc-client/Cargo.toml
  forc-plugins/forc-client/src/bin/deploy/main.rs
  forc-plugins/forc-client/src/bin/run/main.rs
  forc-plugins/forc-explore/Cargo.toml
  forc-plugins/forc-explore/src/main.rs
  forc-plugins/forc-fmt/Cargo.toml
  forc-plugins/forc-fmt/src/main.rs
  forc-tracing/Cargo.toml
  forc-tracing/src/lib.rs
  forc-util/Cargo.toml
  forc-util/src/lib.rs
  forc/Cargo.toml
  forc/src/cli/mod.rs
  sway-lsp/Cargo.toml
  sway-lsp/src/lib.rs
  swayfmt/Cargo.toml
  swayfmt/src/config/manifest.rs
  swayfmt/src/items/item_enum/tests.rs
  swayfmt/src/items/item_fn/tests.rs
  swayfmt/src/items/item_impl/tests.rs
  swayfmt/src/items/item_storage/tests.rs
  swayfmt/src/items/item_struct/tests.rs
  swayfmt/src/items/item_use/tests.rs
  swayfmt/src/utils/language/expr/tests.rs
  test/Cargo.toml
  test/src/e2e_vm_tests/mod.rs
Labels: forc

#3119 Simplify doc example for `contract-dependencies`
  docs/src/forc/manifest_reference.md
Labels: forc, documentation

#3079 Improve E2E test CLI
  Cargo.lock
  forc-pkg/src/pkg.rs
  test/Cargo.toml
  test/src/e2e_vm_tests/README.md
  test/src/e2e_vm_tests/harness.rs
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/token_ops_test/src/main.sw
  test/src/e2e_vm_tests/util.rs
  test/src/ir_generation/mod.rs
  test/src/main.rs
Labels: testing

#2828 Add `raw_ptr` type
  forc-pkg/src/pkg.rs
  sway-core/src/ir_generation/convert.rs
  sway-core/src/ir_generation/function.rs
  sway-core/src/language/ty/program.rs
  sway-core/src/semantic_analysis/ast_node/expression/intrinsic_function.rs
  sway-core/src/semantic_analysis/node_dependencies.rs
  sway-core/src/transform/to_parsed_lang/convert_parse_tree.rs
  sway-core/src/type_system/type_id.rs
  sway-core/src/type_system/type_info.rs
  sway-core/src/type_system/type_mapping.rs
  sway-core/src/type_system/unify.rs
  sway-error/src/error.rs
  sway-lib-core/src/lib.sw
  sway-lib-core/src/ops.sw
  sway-lib-core/src/prelude.sw
  sway-lib-core/src/raw_ptr.sw
  sway-lib-std/src/address.sw
  sway-lib-std/src/alloc.sw
  sway-lib-std/src/context/call_frames.sw
  sway-lib-std/src/context/registers.sw
  sway-lib-std/src/contract_id.sw
  sway-lib-std/src/external.sw
  sway-lib-std/src/inputs.sw
  sway-lib-std/src/lib.sw
  sway-lib-std/src/mem.sw
  sway-lib-std/src/message.sw
  sway-lib-std/src/outputs.sw
  sway-lib-std/src/reentrancy.sw
  sway-lib-std/src/storage.sw
  sway-lib-std/src/tx.sw
  sway-lib-std/src/u128.sw
  sway-lib-std/src/u256.sw
  sway-lib-std/src/vec.sw
  sway-lib-std/src/vm/evm/evm_address.sw
  test/src/e2e_vm_tests/test_programs/should_fail/raw_ptr/raw_ptr_ret/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/raw_ptr/raw_ptr_ret/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/raw_ptr/raw_ptr_ret/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/raw_ptr/raw_ptr_ret/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/raw_ptr/vec_ret/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/raw_ptr/vec_ret/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/raw_ptr/vec_ret/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/raw_ptr/vec_ret/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/addrof_intrinsic/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_basic_storage/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/alloc/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/raw_ptr/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/raw_ptr/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/raw_ptr/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/raw_ptr/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/raw_ptr/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/basic_storage/src/main.sw
  test/src/sdk-harness/test_artifacts/tx_contract/src/main.sw
  test/src/sdk-harness/test_projects/call_frames/src/main.sw
  test/src/sdk-harness/test_projects/registers/src/main.sw
  test/src/sdk-harness/test_projects/token_ops/mod.rs
  test/src/sdk-harness/test_projects/token_ops/src/main.sw
Labels: lib: std, language feature, breaking, compiler: frontend

#3110 docs: update cargo-generate docs with --force option
  docs/src/testing/testing-with-rust.md
Labels: forc, documentation

#3114 Bump to `v0.28.0`
  Cargo.lock
  forc-pkg/Cargo.toml
  forc-plugins/forc-client/Cargo.toml
  forc-plugins/forc-explore/Cargo.toml
  forc-plugins/forc-fmt/Cargo.toml
  forc-plugins/forc-lsp/Cargo.toml
  forc-tracing/Cargo.toml
  forc-util/Cargo.toml
  forc/Cargo.toml
  sway-ast/Cargo.toml
  sway-core/Cargo.toml
  sway-error/Cargo.toml
  sway-ir/Cargo.toml
  sway-ir/sway-ir-macros/Cargo.toml
  sway-lsp/Cargo.toml
  sway-parse/Cargo.toml
  sway-types/Cargo.toml
  sway-utils/Cargo.toml
  swayfmt/Cargo.toml
Labels: release

#3121 ci: verify tag for `forc-tracing`
  .github/workflows/ci.yml
Labels: forc, ci

#3124 Fix to not return an error if all the E2E tests are filtered out.
  test/src/e2e_vm_tests/mod.rs
Labels: compiler, testing

#3125 Let IRgen compile predicate IR modules specifically.
  sway-core/src/asm_generation/from_ir.rs
  sway-core/src/asm_generation/programs.rs
  sway-core/src/asm_generation/programs/final.rs
  sway-core/src/ir_generation.rs
  sway-core/src/ir_generation/compile.rs
  sway-ir/src/parser.rs
  sway-ir/src/printer.rs
  test/src/ir_generation/tests/predicate.sw
Labels: compiler: ir

#3140 Enable printing contract-id and accept Bech32 address in `forc-deploy`
  forc-plugins/forc-client/src/ops/deploy/op.rs
  forc-plugins/forc-client/src/ops/tx_util.rs
Labels: bug, forc, P: critical

#3070 Expand the definition of `TraitMap` in preperation of trait constraints and generic traits.
  sway-core/src/declaration_engine/declaration_id.rs
  sway-core/src/declaration_engine/declaration_wrapper.rs
  sway-core/src/language/ty/ast_node.rs
  sway-core/src/language/ty/code_block.rs
  sway-core/src/language/ty/declaration/declaration.rs
  sway-core/src/language/ty/declaration/enum.rs
  sway-core/src/language/ty/declaration/function.rs
  sway-core/src/language/ty/declaration/impl_trait.rs
  sway-core/src/language/ty/declaration/struct.rs
  sway-core/src/language/ty/declaration/trait.rs
  sway-core/src/language/ty/declaration/trait_fn.rs
  sway-core/src/language/ty/declaration/variable.rs
  sway-core/src/language/ty/expression/asm.rs
  sway-core/src/language/ty/expression/expression.rs
  sway-core/src/language/ty/expression/expression_variant.rs
  sway-core/src/language/ty/expression/intrinsic_function.rs
  sway-core/src/language/ty/expression/reassignment.rs
  sway-core/src/language/ty/expression/struct_exp_field.rs
  sway-core/src/semantic_analysis/ast_node/declaration/function.rs
  sway-core/src/semantic_analysis/ast_node/declaration/impl_trait.rs
  sway-core/src/semantic_analysis/ast_node/expression/match_expression/typed/typed_scrutinee.rs
  sway-core/src/semantic_analysis/namespace/items.rs
  sway-core/src/semantic_analysis/namespace/module.rs
  sway-core/src/semantic_analysis/namespace/namespace.rs
  sway-core/src/semantic_analysis/namespace/root.rs
  sway-core/src/semantic_analysis/namespace/trait_map.rs
  sway-core/src/semantic_analysis/type_check_context.rs
  sway-core/src/type_system/type_binding.rs
  sway-core/src/type_system/type_engine.rs
  sway-core/src/type_system/type_info.rs
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_basic_storage/src/main.sw
Labels: code quality, compiler: frontend

#3143 Improve parsing of trait constraints
  sway-core/src/language/ty/expression/intrinsic_function.rs
  sway-core/src/semantic_analysis/ast_node/declaration/enum.rs
  sway-core/src/semantic_analysis/ast_node/declaration/function.rs
  sway-core/src/semantic_analysis/ast_node/declaration/impl_trait.rs
  sway-core/src/semantic_analysis/ast_node/declaration/struct.rs
  sway-core/src/semantic_analysis/ast_node/mod.rs
  sway-core/src/semantic_analysis/node_dependencies.rs
  sway-core/src/transform/to_parsed_lang/convert_parse_tree.rs
  sway-core/src/type_system/trait_constraint.rs
  sway-core/src/type_system/type_argument.rs
  sway-core/src/type_system/type_parameter.rs
  test/src/e2e_vm_tests/test_programs/should_fail/where_clause_adts/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/where_clause_adts/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/where_clause_adts/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/where_clause_adts/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/where_clause_functions/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/where_clause_functions/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/where_clause_functions/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/where_clause_functions/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/where_clause_impls/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/where_clause_impls/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/where_clause_impls/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/where_clause_impls/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/where_clause_with_generic_traits/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/where_clause_with_generic_traits/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/where_clause_with_generic_traits/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/where_clause_with_generic_traits/test.toml
Labels: language feature, compiler: frontend

#2869 Implement `forc doc`
  Cargo.lock
  Cargo.toml
  examples/structs/Forc.lock
  forc-plugins/forc-doc/Cargo.toml
  forc-plugins/forc-doc/src/cli.rs
  forc-plugins/forc-doc/src/descriptor.rs
  forc-plugins/forc-doc/src/doc.rs
  forc-plugins/forc-doc/src/main.rs
  forc-plugins/forc-doc/src/render.rs
  sway-core/src/declaration_engine/declaration_engine.rs
  sway-core/src/declaration_engine/declaration_wrapper.rs
  sway-core/src/language/parsed/declaration/trait.rs
  sway-core/src/language/ty/declaration/abi.rs
  sway-core/src/language/ty/declaration/constant.rs
  sway-core/src/language/ty/declaration/enum.rs
  sway-core/src/language/ty/declaration/function.rs
  sway-core/src/language/ty/declaration/impl_trait.rs
  sway-core/src/language/ty/declaration/struct.rs
  sway-core/src/language/ty/declaration/trait.rs
  sway-core/src/semantic_analysis.rs
Labels: enhancement, forc, big, documentation

#3123 LSP: Code clean up, remove unused code, add missing docs
  sway-lsp/src/capabilities/completion.rs
  sway-lsp/src/capabilities/diagnostic.rs
  sway-lsp/src/capabilities/document_symbol.rs
  sway-lsp/src/capabilities/hover.rs
  sway-lsp/src/capabilities/inlay_hints.rs
  sway-lsp/src/capabilities/rename.rs
  sway-lsp/src/capabilities/semantic_tokens.rs
  sway-lsp/src/core/session.rs
  sway-lsp/src/server.rs
  sway-lsp/src/utils/common.rs
  sway-lsp/src/utils/debug.rs
  sway-lsp/src/utils/function.rs
  sway-lsp/src/utils/mod.rs
  sway-lsp/src/utils/sync.rs
  sway-lsp/src/utils/token.rs
Labels: language server, code quality

#3148 Remove monomorphization cache implementation from the declaration engine.
  sway-core/src/concurrent_slab.rs
  sway-core/src/declaration_engine/declaration_engine.rs
  sway-core/src/declaration_engine/mod.rs
  sway-core/src/semantic_analysis/program.rs
  sway-core/src/type_system/type_binding.rs
  sway-core/src/type_system/type_engine.rs
  test/src/e2e_vm_tests/test_programs/should_fail/where_clause_with_generic_trait/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/where_clause_with_generic_trait/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/where_clause_with_generic_trait/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/where_clause_with_generic_trait/test.toml
Labels: compiler: frontend, compiler: collection

#3149 Remove debug print of DeclarationEngine from `TyProgram::type_check`
  sway-core/src/semantic_analysis/program.rs
Labels: bug, compiler, compiler: frontend

#3150 Add a `--tests` flag to `forc build` (and sway-core) in preparation for building unit tests
  forc-pkg/src/manifest.rs
  forc-pkg/src/pkg.rs
  forc-plugins/forc-client/src/ops/deploy/op.rs
  forc-plugins/forc-client/src/ops/run/op.rs
  forc/src/cli/commands/build.rs
  forc/src/ops/forc_build.rs
  sway-core/src/build_config.rs
  sway-core/src/lib.rs
Labels: compiler, forc, testing, compiler: frontend

#3151 Include `#[test]` functions as entry points during dead code analysis
  sway-core/src/control_flow_analysis/dead_code_analysis.rs
  sway-core/src/language/ty/declaration/function.rs
Labels: compiler, compiler: frontend

#3139 Use `raw_ptr` methods in `message.sw`
  sway-lib-std/src/message.sw
Labels: lib: std

#3129 Provide a way to detect type of manifest files and general refactor for workspace builds
  forc-pkg/src/manifest.rs
  forc-pkg/src/pkg.rs
  forc-plugins/forc-client/src/ops/deploy/op.rs
  forc-plugins/forc-client/src/ops/run/op.rs
  forc/src/ops/forc_build.rs
  test/src/e2e_vm_tests/harness.rs
Labels: forc, dependencies, P: high

#3128 Promote local memory to SSA registers
  Cargo.lock
  sway-core/src/asm_generation/asm_builder.rs
  sway-core/src/ir_generation/const_eval.rs
  sway-core/src/lib.rs
  sway-ir/Cargo.toml
  sway-ir/src/analysis.rs
  sway-ir/src/analysis/dominator.rs
  sway-ir/src/bin/opt.rs
  sway-ir/src/block.rs
  sway-ir/src/function.rs
  sway-ir/src/instruction.rs
  sway-ir/src/lib.rs
  sway-ir/src/optimize.rs
  sway-ir/src/optimize/dce.rs
  sway-ir/src/optimize/mem2reg.rs
  sway-ir/src/value.rs
  sway-ir/tests/mem2reg/is_prime.ir
  sway-ir/tests/mem2reg/while_loops.ir
  sway-ir/tests/tests.rs
  sway-utils/src/lib.rs
  sway-utils/src/mapped_stack.rs
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_basic_storage/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_increment_contract/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/nested_struct_args_caller/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/alloc/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/raw_ptr/src/main.sw
Labels: compiler: optimization

#3133 Add `StorageMap` to the standard library prelude
  docs/src/common-collections/storage_map.md
  docs/src/introduction/standard_library.md
  examples/storage_map/Forc.lock
  examples/storage_map/src/main.sw
  examples/subcurrency/Forc.lock
  examples/subcurrency/src/main.sw
  sway-lib-std/src/address.sw
  sway-lib-std/src/prelude.sw
  test/src/e2e_vm_tests/test_programs/should_fail/storage_types/src/main.sw
  test/src/sdk-harness/test_projects/option_field_order/src/main.sw
  test/src/sdk-harness/test_projects/storage_map/src/main.sw
Labels: lib: std

#3152 Add method to `TyProgram` for retrieving all `#[test]` functions
  sway-core/src/language/ty/module.rs
  sway-core/src/language/ty/program.rs
Labels: compiler, compiler: frontend

#3084 LSP: Show formatted documentation on hover
  sway-lsp/src/capabilities/hover.rs
  sway-lsp/src/core/traverse_typed_tree.rs
  sway-lsp/src/server.rs
  sway-lsp/src/utils/markdown.rs
  sway-lsp/src/utils/markup.rs
  sway-lsp/src/utils/mod.rs
Labels: enhancement, language server

#3154 Patch to fix malformed test + non-determinism in trait lookup via iterating through a hashmap
  sway-core/src/language/call_path.rs
  sway-core/src/semantic_analysis/namespace/trait_map.rs
  sway-core/src/type_system/mod.rs
  sway-core/src/type_system/type_engine.rs
  sway-core/src/type_system/type_id.rs
  sway-core/src/type_system/unify.rs
Labels: bug

#3132 Remove `raw_ptr::addr()`
  sway-lib-core/src/raw_ptr.sw
  test/src/sdk-harness/test_artifacts/tx_contract/src/main.sw
  test/src/sdk-harness/test_projects/registers/src/main.sw
Labels: lib: std, breaking

#3167 Fix `TyModule::submodules_recursive` iterator
  sway-core/src/language/ty/module.rs
Labels: bug, compiler, compiler: frontend

#3166 Refactor `forc_pkg::BuildOptions` into its parts
  forc-pkg/src/pkg.rs
  forc-plugins/forc-client/Cargo.toml
  forc-plugins/forc-client/src/ops/deploy/op.rs
  forc-plugins/forc-client/src/ops/run/cmd.rs
  forc-plugins/forc-client/src/ops/run/op.rs
  forc/src/cli/commands/build.rs
  forc/src/cli/commands/test.rs
  forc/src/cli/mod.rs
  forc/src/cli/shared.rs
  forc/src/ops/forc_build.rs
  test/src/e2e_vm_tests/harness.rs
Labels: forc

#3158 Fixes issue with multiline collections formatting.
  swayfmt/src/formatter/mod.rs
  swayfmt/src/utils/language/punctuated.rs
Labels: bug, formatter

#3054 Bump all fuel dependencies (to `fuel-core 0.11.2`)
  .github/workflows/ci.yml
  Cargo.lock
  forc-pkg/Cargo.toml
  forc-plugins/forc-client/Cargo.toml
  forc/Cargo.toml
  sway-core/Cargo.toml
  sway-types/Cargo.toml
  templates/sway-test-rs/template/Cargo.toml
  templates/sway-test-rs/template/tests/harness.rs
  test-sig-gen-util/Cargo.toml
  test/Cargo.toml
  test/src/sdk-harness/Cargo.toml
  test/src/sdk-harness/test_projects/auth/mod.rs
  test/src/sdk-harness/test_projects/block/mod.rs
  test/src/sdk-harness/test_projects/call_frames/mod.rs
  test/src/sdk-harness/test_projects/context/mod.rs
  test/src/sdk-harness/test_projects/contract_bytecode/mod.rs
  test/src/sdk-harness/test_projects/evm/mod.rs
  test/src/sdk-harness/test_projects/exponentiation/mod.rs
  test/src/sdk-harness/test_projects/hashing/mod.rs
  test/src/sdk-harness/test_projects/methods/mod.rs
  test/src/sdk-harness/test_projects/option_field_order/mod.rs
  test/src/sdk-harness/test_projects/option_in_abi/mod.rs
  test/src/sdk-harness/test_projects/parsing_logs/mod.rs
  test/src/sdk-harness/test_projects/reentrancy/mod.rs
  test/src/sdk-harness/test_projects/registers/mod.rs
  test/src/sdk-harness/test_projects/result_in_abi/mod.rs
  test/src/sdk-harness/test_projects/storage/mod.rs
  test/src/sdk-harness/test_projects/storage_map/mod.rs
  test/src/sdk-harness/test_projects/storage_vec/array/utils.rs
  test/src/sdk-harness/test_projects/storage_vec/b256/utils.rs
  test/src/sdk-harness/test_projects/storage_vec/bool/utils.rs
  test/src/sdk-harness/test_projects/storage_vec/enum/utils.rs
  test/src/sdk-harness/test_projects/storage_vec/str/utils.rs
  test/src/sdk-harness/test_projects/storage_vec/struct/utils.rs
  test/src/sdk-harness/test_projects/storage_vec/tuple/utils.rs
  test/src/sdk-harness/test_projects/storage_vec/u16/utils.rs
  test/src/sdk-harness/test_projects/storage_vec/u32/utils.rs
  test/src/sdk-harness/test_projects/storage_vec/u64/utils.rs
  test/src/sdk-harness/test_projects/storage_vec/u8/utils.rs
  test/src/sdk-harness/test_projects/token_ops/mod.rs
  test/src/sdk-harness/test_projects/tx_fields/mod.rs
Labels: dependencies

#3178 Initialize tracing based on user setting
  sway-lsp/src/core/config.rs
  sway-lsp/src/lib.rs
  sway-lsp/src/server.rs
Labels: language server

#3183 ci: release `forc-doc`
  .github/workflows/ci.yml
Labels: ci, forc-doc

#3184 forc-lsp: re-add App::parse
  forc-plugins/forc-lsp/src/main.rs
Labels: bug, language server

#3186 Use a call-graph in the inliner
  sway-core/src/lib.rs
  sway-ir/src/analysis.rs
  sway-ir/src/analysis/call_graph.rs
  sway-ir/src/optimize/inline.rs
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_basic_storage/src/main.sw
Labels: enhancement, compiler: optimization

#3187 Revert changes to the `token_ops` test made in #2922
  test/src/sdk-harness/test_projects/token_ops/mod.rs
  test/src/sdk-harness/test_projects/token_ops/src/main.sw
Labels: testing

#3199 Update section title
  docs/src/SUMMARY.md
  docs/src/introduction/overview.md
Labels: The Sway Book

#3198 update getting started section to include links to the developer quickstart
  docs/src/introduction/overview.md
Labels: The Sway Book

#3193 Fixes parser and printer of metadata strings
  sway-ir/src/parser.rs
  sway-ir/tests/serialize/metadata.ir
Labels: compiler: ir

#3207 Detect and disallow multiple methods with the same name.
  sway-core/src/semantic_analysis/ast_node/declaration/impl_trait.rs
  sway-core/src/semantic_analysis/ast_node/declaration/trait.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/ast_node/mod.rs
  sway-core/src/semantic_analysis/namespace/items.rs
  sway-core/src/semantic_analysis/namespace/trait_map.rs
  sway-error/src/error.rs
  sway-lib-core/src/ops.sw
  test/src/e2e_vm_tests/test_programs/should_fail/multiple_methods_with_the_same_name/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/multiple_methods_with_the_same_name/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/multiple_methods_with_the_same_name/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_fail/multiple_methods_with_the_same_name/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/multiple_methods_with_the_same_name/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/generic_traits/src/main.sw
Labels: compiler: frontend

#3065 Math functions and traits
  sway-lib-std/src/math.sw
  sway-lib-std/src/u128.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/logarithmic_test/.gitignore
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/logarithmic_test/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/logarithmic_test/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/logarithmic_test/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/logarithmic_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/logarithmic_test/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/u128_log_test/.gitignore
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/u128_log_test/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/u128_log_test/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/u128_log_test/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/u128_log_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/u128_log_test/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/u128_root_test/.gitignore
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/u128_root_test/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/u128_root_test/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/u128_root_test/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/u128_root_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/u128_root_test/test.toml
Labels: lib: std

#3203 Do not reuse registers for insert/extract element, they may be live
  sway-core/src/asm_generation/asm_builder.rs
  test/src/e2e_vm_tests/test_programs/should_pass/language/insert_element_reg_reuse/.gitignore
  test/src/e2e_vm_tests/test_programs/should_pass/language/insert_element_reg_reuse/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/insert_element_reg_reuse/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/insert_element_reg_reuse/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/language/insert_element_reg_reuse/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/insert_element_reg_reuse/test.toml
Labels: bug, P: critical, compiler: codegen

#3182 forc documenter refactor
  docs/src/SUMMARY.md
  docs/src/forc/plugins/forc_client/forc_deploy.md
  docs/src/forc/plugins/forc_client/forc_run.md
  docs/src/forc/plugins/forc_client/index.md
  docs/src/forc/plugins/forc_explore.md
  docs/src/forc/plugins/forc_fmt.md
  docs/src/forc/plugins/forc_lsp.md
  docs/src/forc/plugins/index.md
  scripts/mdbook-forc-documenter/src/lib.rs
  scripts/mdbook-forc-documenter/src/plugins.rs
Labels: forc, code quality, documentation

#2926 ci: update forc-explore CI related steps
  .github/workflows/ci.yml
  .github/workflows/gh-pages.yml
Labels: forc, ci

#3185 Adds inline annotation to the compiler
  sway-core/src/ir_generation/compile.rs
  sway-core/src/language/inline.rs
  sway-core/src/language/mod.rs
  sway-core/src/language/ty/declaration/function.rs
  sway-core/src/lib.rs
  sway-core/src/metadata.rs
  sway-core/src/transform/attribute.rs
  sway-core/src/transform/to_parsed_lang/convert_parse_tree.rs
  sway-types/src/constants.rs
  test/src/ir_generation/mod.rs
  test/src/ir_generation/tests/inline_annotation.sw
Labels: compiler: ir, compiler: frontend, compiler: parser

#3206 Test using consts in libraries
  test/src/e2e_vm_tests/test_programs/should_pass/language/const_decl_and_use_in_library/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/const_decl_and_use_in_library/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/const_decl_and_use_in_library/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/language/const_decl_and_use_in_library/src/consts.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/const_decl_and_use_in_library/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/const_decl_and_use_in_library/test.toml
Labels: testing

#3222 v0.29.0
  Cargo.lock
  forc-pkg/Cargo.toml
  forc-plugins/forc-client/Cargo.toml
  forc-plugins/forc-doc/Cargo.toml
  forc-plugins/forc-explore/Cargo.toml
  forc-plugins/forc-fmt/Cargo.toml
  forc-plugins/forc-lsp/Cargo.toml
  forc-tracing/Cargo.toml
  forc-util/Cargo.toml
  forc/Cargo.toml
  sway-ast/Cargo.toml
  sway-core/Cargo.toml
  sway-error/Cargo.toml
  sway-ir/Cargo.toml
  sway-ir/sway-ir-macros/Cargo.toml
  sway-lsp/Cargo.toml
  sway-parse/Cargo.toml
  sway-types/Cargo.toml
  sway-utils/Cargo.toml
  swayfmt/Cargo.toml
Labels: release

#3062 as_u128 added to U256
  sway-lib-std/src/u256.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/u256_test/src/main.sw
Labels: enhancement, lib: std

#3227 Make ReturnData expecting tests check the data instead of its digest
  test/src/e2e_vm_tests/harness.rs
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/should_pass/language/enum_padding/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/ret_small_string/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/ret_string_in_struct/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/retd_b256/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/retd_small_array/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/retd_struct/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/retd_zero_len_array/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/unit_type_variants/test.toml
Labels: testing
