Repository FuelLabs/sway, pull requests merged in 2022-01, with the labels that each got.

#570 :hammer: Fix Small Typo :construction:
  docs/src/examples/subcurrency.md
Labels: The Sway Book

#399 Implement tuples
  sway-core/src/asm_generation/declaration/reassignment.rs
  sway-core/src/asm_generation/expression/mod.rs
  sway-core/src/asm_generation/expression/structs.rs
  sway-core/src/asm_generation/expression/subfield.rs
  sway-core/src/asm_generation/mod.rs
  sway-core/src/control_flow_analysis/analyze_return_paths.rs
  sway-core/src/control_flow_analysis/dead_code_analysis.rs
  sway-core/src/hll.pest
  sway-core/src/parse_tree/declaration.rs
  sway-core/src/parse_tree/declaration/constant.rs
  sway-core/src/parse_tree/declaration/enum.rs
  sway-core/src/parse_tree/declaration/function.rs
  sway-core/src/parse_tree/declaration/reassignment.rs
  sway-core/src/parse_tree/declaration/struct.rs
  sway-core/src/parse_tree/declaration/trait.rs
  sway-core/src/parse_tree/expression/asm.rs
  sway-core/src/parse_tree/expression/match_branch.rs
  sway-core/src/parse_tree/expression/mod.rs
  sway-core/src/parse_tree/return_statement.rs
  sway-core/src/parse_tree/while_loop.rs
  sway-core/src/semantic_analysis/ast_node/code_block.rs
  sway-core/src/semantic_analysis/ast_node/expression/enum_instantiation.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression_variant.rs
  sway-core/src/semantic_analysis/ast_node/mod.rs
  sway-core/src/semantic_analysis/node_dependencies.rs
  sway-core/src/type_engine/engine.rs
  sway-core/src/type_engine/type_info.rs
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/tuple_types/Forc.toml
  test/src/e2e_vm_tests/test_programs/tuple_types/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/tuple_types/src/main.sw
Labels: compiler

#576 fix incorrect enum method syntax
  docs/src/basics/custom_types.md
Labels: The Sway Book

#462 Disallow type name shadowing.
  sway-core/src/error.rs
  sway-core/src/semantic_analysis/ast_node/mod.rs
  sway-core/src/semantic_analysis/namespace.rs
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/name_shadowing/Forc.toml
  test/src/e2e_vm_tests/test_programs/name_shadowing/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/name_shadowing/src/main.sw
Labels: compiler

#573 Implement tuple desugaring in match expressions
  sway-core/src/asm_generation/declaration/reassignment.rs
  sway-core/src/asm_generation/expression/mod.rs
  sway-core/src/asm_generation/expression/structs.rs
  sway-core/src/asm_generation/expression/subfield.rs
  sway-core/src/control_flow_analysis/dead_code_analysis.rs
  sway-core/src/error.rs
  sway-core/src/hll.pest
  sway-core/src/parse_tree/expression/matcher.rs
  sway-core/src/parse_tree/expression/mod.rs
  sway-core/src/parse_tree/expression/scrutinee.rs
  sway-core/src/semantic_analysis/ast_node/declaration.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression_variant.rs
  sway-core/src/semantic_analysis/namespace.rs
  sway-core/src/semantic_analysis/node_dependencies.rs
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/tuple_desugaring/Forc.toml
  test/src/e2e_vm_tests/test_programs/tuple_desugaring/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/tuple_desugaring/src/main.sw
Labels: compiler

#586 Rename the arg to unowned_stack_allocate_memory().
  sway-core/src/asm_lang/mod.rs
Labels: compiler, code quality

#583 clippy doesn't fail on warnings
  .github/workflows/clippy_check.yml
  sway-core/src/semantic_analysis/namespace.rs
Labels: bug, ci, internship

#588 fix trait implementation imports in star imports
  sway-core/src/semantic_analysis/namespace.rs
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/trait_import_with_star/Forc.toml
  test/src/e2e_vm_tests/test_programs/trait_import_with_star/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/trait_import_with_star/src/main.sw
  test/src/e2e_vm_tests/test_programs/trait_import_with_star/src/shiftable.sw
Labels: bug, compiler

#592 Bump to v0.2.0.
  docstrings/Cargo.toml
  forc/Cargo.toml
  parser/Cargo.toml
  sway-core/Cargo.toml
  sway-fmt/Cargo.toml
  sway-server/Cargo.toml
  sway-types/Cargo.toml
  sway-utils/Cargo.toml
  test/Cargo.toml
Labels: release

#584 Handle multiple imports in one use statement
  sway-core/src/error.rs
  sway-core/src/hll.pest
  sway-core/src/lib.rs
  sway-core/src/parse_tree/use_statement.rs
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/b256_ops/src/main.sw
  test/src/e2e_vm_tests/test_programs/bal_opcode/src/main.sw
  test/src/e2e_vm_tests/test_programs/block_height/src/main.sw
  test/src/e2e_vm_tests/test_programs/call_basic_storage/src/main.sw
  test/src/e2e_vm_tests/test_programs/caller_auth_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/caller_context_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/dependencies/src/main.sw
  test/src/e2e_vm_tests/test_programs/dependencies_parsing_error/src/main.sw
  test/src/e2e_vm_tests/test_programs/increment_contract/src/main.sw
  test/src/e2e_vm_tests/test_programs/multi_item_import/Forc.toml
  test/src/e2e_vm_tests/test_programs/multi_item_import/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/multi_item_import/src/bar.sw
  test/src/e2e_vm_tests/test_programs/multi_item_import/src/inner/double_bar.sw
  test/src/e2e_vm_tests/test_programs/multi_item_import/src/main.sw
Labels: enhancement, compiler

#594 Re-specify pest version.
  Cargo.lock
  sway-core/Cargo.toml
Labels: bug, dependencies

#593 Bump to v0.2.1.
  Cargo.lock
  docstrings/Cargo.toml
  forc/Cargo.toml
  parser/Cargo.toml
  sway-core/Cargo.toml
  sway-fmt/Cargo.toml
  sway-server/Cargo.toml
  sway-types/Cargo.toml
  sway-utils/Cargo.toml
  test/Cargo.toml
Labels: release

#602 Grammatical Tweaks to the Docs
  docs/src/advanced/assembly.md
  docs/src/advanced/generic_types.md
  docs/src/advanced/traits.md
  docs/src/basics/built_in_types.md
  docs/src/basics/custom_types.md
  docs/src/basics/reference_types.md
  docs/src/basics/variables.md
  docs/src/blockchain-concepts/identifiers.md
  docs/src/blockchain-concepts/native_assets.md
  docs/src/getting-started/sway-toolchain.md
  docs/src/smart-contract-development/purity.md
  docs/src/smart-contract-development/storage.md
  docs/src/sway-on-chain/libraries.md
  docs/src/sway-on-chain/predicates.md
  docs/src/sway-on-chain/program_types.md
  docs/src/sway-on-chain/scripts.md
  docs/src/sway-on-chain/smart_contracts.md
Labels: The Sway Book

#611 Update to the dependency name to avoid download collisions in `forc_build`.
  forc/src/ops/forc_abi_json.rs
  forc/src/ops/forc_build.rs
Labels: bug, internship

#568 fix: fix hover and add variable types on hover
  sway-server/src/core/token.rs
  sway-server/src/utils/common.rs
Labels: bug, language server

#618 Fix display bug.
  sway-server/src/utils/common.rs
Labels: bug, language server

#612 Display unimplemented error instead of panicking on generic traits
  sway-core/src/parse_tree/declaration/function.rs
  sway-core/src/parse_tree/declaration/trait.rs
Labels: bug, compiler

#620 fix OOG in tests
  test/src/e2e_vm_tests/harness.rs
Labels: bug, testing

#597 Build & Publish Sway Docker Image
  .github/workflows/ci.yml
  deployment/Dockerfile
Labels: ci

#623 Remove Example Project
  example_project/example_dependency/Forc.toml
  example_project/example_dependency/src/main.sw
  example_project/fuel_project/Forc.toml
  example_project/fuel_project/src/main.sw
Labels: documentation

#432 Implementing an ec-recover function for the stdlib
  Cargo.lock
  Cargo.toml
  sig-gen-util/Cargo.toml
  sig-gen-util/src/main.rs
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/ec_recover_test/Forc.toml
  test/src/e2e_vm_tests/test_programs/ec_recover_test/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/ec_recover_test/src/main.sw
Labels: stdlib

#596 Sway IR crate.
  .github/workflows/ci.yml
  Cargo.toml
  sway-ir/Cargo.toml
  sway-ir/README.md
  sway-ir/src/asm.rs
  sway-ir/src/bin/opt.rs
  sway-ir/src/block.rs
  sway-ir/src/constant.rs
  sway-ir/src/context.rs
  sway-ir/src/function.rs
  sway-ir/src/instruction.rs
  sway-ir/src/irtype.rs
  sway-ir/src/lib.rs
  sway-ir/src/module.rs
  sway-ir/src/optimize.rs
  sway-ir/src/optimize/constants.rs
  sway-ir/src/optimize/inline.rs
  sway-ir/src/parser.rs
  sway-ir/src/pointer.rs
  sway-ir/src/printer.rs
  sway-ir/src/value.rs
  sway-ir/src/verify.rs
  sway-ir/tests/ir_to_ir/constants_insert_value.in_ir
  sway-ir/tests/ir_to_ir/constants_insert_value.out_ir
  sway-ir/tests/ir_to_ir/inline_bigger.in_ir
  sway-ir/tests/ir_to_ir/inline_bigger.out_ir
  sway-ir/tests/ir_to_ir/inline_fiddly.in_ir
  sway-ir/tests/ir_to_ir/inline_fiddly.out_ir
  sway-ir/tests/ir_to_ir/inline_simple.in_ir
  sway-ir/tests/ir_to_ir/inline_simple.out_ir
  sway-ir/tests/tests.rs
Labels: compiler, big

#627 Hash the dependency name and source before writing to avoid bad characters
  forc/src/utils/dependency.rs
Labels: bug, forc

#638 Add "differences from Rust" chapter
  docs/src/SUMMARY.md
  docs/src/getting-started/index.md
  docs/src/getting-started/rust_differences.md
Labels: The Sway Book

#616 feat(forc): add manifest formatter
  Cargo.lock
  docs/src/getting-started/temporary_workarounds.md
  forc/Cargo.toml
  forc/src/ops/forc_fmt.rs
  test/src/e2e_vm_tests/test_programs/ec_recover_test/Forc.toml
Labels: enhancement, forc

#626 Adds the missing `ec_recover` tests.
  test/src/e2e_vm_tests/test_programs/ec_recover_test/src/main.sw
Labels: enhancement

#643 Fix some incorrectly parsed tokens.
  sway-core/src/hll.pest
  sway-core/src/parse_tree/expression/mod.rs
Labels: bug, compiler

#650 Rename HLL to Sway.
  sway-core/src/asm_generation/from_ir.rs
  sway-core/src/asm_generation/mod.rs
  sway-core/src/control_flow_analysis/flow_graph/mod.rs
  sway-core/src/lib.rs
  sway-core/src/optimize.rs
  sway-core/src/parser.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/method_application.rs
  sway-core/src/sway.pest
  sway-core/utils/selector_debug.rs
  sway-fmt/src/traversal.rs
Labels: bikeshedding, compiler

#631 feat(forc): add "organization" field in forc manifest
  forc/src/utils/defaults.rs
  forc/src/utils/manifest.rs
Labels: enhancement, forc

#651 Remove direct dependency on `curl`
  Cargo.lock
  forc/Cargo.toml
  forc/src/utils/dependency.rs
Labels: forc, dependencies

#654 Add publish delay to CI
  .github/workflows/ci.yml
Labels: enhancement, ci

#655 sway-fmt with FormattingOptions
  forc/src/cli/commands/format.rs
  forc/src/ops/forc_fmt.rs
  sway-fmt/src/fmt.rs
  sway-fmt/src/lib.rs
  sway-server/src/capabilities/formatting.rs
  sway-server/src/core/session.rs
  sway-server/src/lib.rs
  sway-server/src/server.rs
  sway-server/src/sway_config.rs
Labels: enhancement, formatter

#660 Add details in "A Forc Project"
  docs/src/getting-started/forc_project.md
Labels: The Sway Book

#661 Bump fuel-tx to 0.2
  Cargo.lock
  forc/Cargo.toml
  forc/src/utils/defaults.rs
  forc/src/utils/manifest.rs
  sig-gen-util/Cargo.toml
  sway-core/Cargo.toml
  sway-types/Cargo.toml
  test/Cargo.toml
  test/src/e2e_vm_tests/test_programs/bal_opcode/Forc.toml
  test/src/e2e_vm_tests/test_programs/call_basic_storage/Forc.toml
  test/src/e2e_vm_tests/test_programs/call_increment_contract/Forc.toml
  test/src/e2e_vm_tests/test_programs/caller_auth_test/Forc.toml
  test/src/e2e_vm_tests/test_programs/caller_context_test/Forc.toml
  test/src/e2e_vm_tests/test_programs/contract_call/Forc.toml
Labels: dependencies

#663 Bump to v0.3.0
  Cargo.lock
  docstrings/Cargo.toml
  forc/Cargo.toml
  parser/Cargo.toml
  sway-core/Cargo.toml
  sway-fmt/Cargo.toml
  sway-ir/Cargo.toml
  sway-server/Cargo.toml
  sway-types/Cargo.toml
  sway-utils/Cargo.toml
  test/Cargo.toml
Labels: release

#666 Remove comment with typo
  forc/Cargo.toml
Labels: documentation

#664 Set version of non-published crates to 0.0.0
  Cargo.lock
  docstrings/Cargo.toml
  sig-gen-util/Cargo.toml
  test/Cargo.toml
Labels: release

#669 Rename signature gen util for added clarity
  Cargo.lock
  Cargo.toml
  test-sig-gen-util/Cargo.toml
  test-sig-gen-util/src/main.rs
Labels: testing

#648 lsp: handle file deletion
  sway-server/src/capabilities/file_sync.rs
  sway-server/src/core/session.rs
Labels: language server

#649 lsp: fix exhaustive symbol check
  sway-server/src/capabilities/document_symbol.rs
Labels: language server

#673 Fix bug with reporting number of tests run.
  test/src/e2e_vm_tests/mod.rs
Labels: bug, testing

#680 Refactor usage of namespaces to improve compiler performance
  .github/workflows/ci.yml
  Cargo.lock
  core_lang/src/parse_tree/expression/match_condition.rs
  core_lang/src/semantic_analysis/ast_node/expression/match_branch.rs
  core_lang/src/semantic_analysis/ast_node/expression/match_condition.rs
  core_lang/src/semantic_analysis/type_check_arguments.rs
  forc/src/ops/forc_abi_json.rs
  forc/src/ops/forc_build.rs
  sway-core/Cargo.toml
  sway-core/src/asm_generation/mod.rs
  sway-core/src/lib.rs
  sway-core/src/optimize.rs
  sway-core/src/parse_tree/call_path.rs
  sway-core/src/parse_tree/declaration/enum.rs
  sway-core/src/parse_tree/visibility.rs
  sway-core/src/semantic_analysis.rs
  sway-core/src/semantic_analysis/ast_node/code_block.rs
  sway-core/src/semantic_analysis/ast_node/declaration.rs
  sway-core/src/semantic_analysis/ast_node/declaration/function.rs
  sway-core/src/semantic_analysis/ast_node/declaration/variable.rs
  sway-core/src/semantic_analysis/ast_node/expression/enum_instantiation.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/method_application.rs
  sway-core/src/semantic_analysis/ast_node/impl_trait.rs
  sway-core/src/semantic_analysis/ast_node/mod.rs
  sway-core/src/semantic_analysis/namespace.rs
  sway-core/src/semantic_analysis/namespace/arena.rs
  sway-core/src/semantic_analysis/node_dependencies.rs
  sway-core/src/semantic_analysis/syntax_tree.rs
  sway-core/src/semantic_analysis/type_check_arguments.rs
  sway-core/src/type_engine/type_info.rs
  sway-core/utils/selector_debug.rs
  sway-types/src/span.rs
  test/src/e2e_vm_tests/test_programs/bal_opcode/Forc.toml
  test/src/e2e_vm_tests/test_programs/call_basic_storage/Forc.toml
  test/src/e2e_vm_tests/test_programs/call_increment_contract/Forc.toml
  test/src/e2e_vm_tests/test_programs/caller_auth_test/Forc.toml
  test/src/e2e_vm_tests/test_programs/caller_context_test/Forc.toml
  test/src/e2e_vm_tests/test_programs/trait_override_bug/src/main.sw
Labels: enhancement, compiler

#675 Remove use of `[[tx-input]]` for tests
  forc/src/cli/commands/run.rs
  forc/src/ops/forc_deploy.rs
  forc/src/ops/forc_run.rs
  forc/src/utils/manifest.rs
  test/src/e2e_vm_tests/harness.rs
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/bal_opcode/Forc.toml
  test/src/e2e_vm_tests/test_programs/call_basic_storage/Forc.toml
  test/src/e2e_vm_tests/test_programs/call_increment_contract/Forc.toml
  test/src/e2e_vm_tests/test_programs/caller_auth_test/Forc.toml
  test/src/e2e_vm_tests/test_programs/caller_context_test/Forc.toml
  test/src/e2e_vm_tests/test_programs/contract_call/Forc.toml
Labels: enhancement, forc, testing

#683 Pin our std and core deps in the test suite
  docs/src/getting-started/forc_project.md
  docs/src/getting-started/temporary_workarounds.md
  forc/src/ops/forc_fmt.rs
  test/src/e2e_vm_tests/test_programs/address_test/Forc.toml
  test/src/e2e_vm_tests/test_programs/aliased_imports/Forc.toml
  test/src/e2e_vm_tests/test_programs/array_basics/Forc.toml
  test/src/e2e_vm_tests/test_programs/assert_test/Forc.toml
  test/src/e2e_vm_tests/test_programs/auth_testing_contract/Forc.toml
  test/src/e2e_vm_tests/test_programs/b256_bad_jumps/Forc.toml
  test/src/e2e_vm_tests/test_programs/b256_ops/Forc.toml
  test/src/e2e_vm_tests/test_programs/b512_struct_alignment/Forc.toml
  test/src/e2e_vm_tests/test_programs/b512_test/Forc.toml
  test/src/e2e_vm_tests/test_programs/bal_opcode/Forc.toml
  test/src/e2e_vm_tests/test_programs/balance_test_contract/Forc.toml
  test/src/e2e_vm_tests/test_programs/basic_func_decl/Forc.toml
  test/src/e2e_vm_tests/test_programs/basic_storage/Forc.toml
  test/src/e2e_vm_tests/test_programs/block_height/Forc.toml
  test/src/e2e_vm_tests/test_programs/call_increment_contract/Forc.toml
  test/src/e2e_vm_tests/test_programs/caller_auth_test/Forc.toml
  test/src/e2e_vm_tests/test_programs/caller_context_test/Forc.toml
  test/src/e2e_vm_tests/test_programs/const_decl/Forc.toml
  test/src/e2e_vm_tests/test_programs/const_decl_in_library/Forc.toml
  test/src/e2e_vm_tests/test_programs/context_testing_abi/Forc.toml
  test/src/e2e_vm_tests/test_programs/context_testing_contract/Forc.toml
  test/src/e2e_vm_tests/test_programs/contract_abi_impl/Forc.toml
  test/src/e2e_vm_tests/test_programs/contract_call/Forc.toml
  test/src/e2e_vm_tests/test_programs/contract_id_test/Forc.toml
  test/src/e2e_vm_tests/test_programs/dependencies/Forc.toml
  test/src/e2e_vm_tests/test_programs/dependencies_parsing_error/Forc.toml
  test/src/e2e_vm_tests/test_programs/ec_recover_test/Forc.toml
  test/src/e2e_vm_tests/test_programs/empty_method_initializer/Forc.toml
  test/src/e2e_vm_tests/test_programs/enum_in_fn_decl/Forc.toml
  test/src/e2e_vm_tests/test_programs/eq_4_test/Forc.toml
  test/src/e2e_vm_tests/test_programs/excess_fn_arguments/Forc.toml
  test/src/e2e_vm_tests/test_programs/fix_opcode_bug/Forc.toml
  test/src/e2e_vm_tests/test_programs/generic_enum/Forc.toml
  test/src/e2e_vm_tests/test_programs/if_elseif_enum/Forc.toml
  test/src/e2e_vm_tests/test_programs/increment_contract/Forc.toml
  test/src/e2e_vm_tests/test_programs/infinite_dependencies/Forc.toml
  test/src/e2e_vm_tests/test_programs/local_impl_for_ord/Forc.toml
  test/src/e2e_vm_tests/test_programs/match_expressions/Forc.toml
  test/src/e2e_vm_tests/test_programs/match_expressions_enums/Forc.toml
  test/src/e2e_vm_tests/test_programs/match_expressions_structs/Forc.toml
  test/src/e2e_vm_tests/test_programs/match_expressions_wrong_struct/Forc.toml
  test/src/e2e_vm_tests/test_programs/missing_fn_arguments/Forc.toml
  test/src/e2e_vm_tests/test_programs/modulo_uint_test/Forc.toml
  test/src/e2e_vm_tests/test_programs/multi_item_import/Forc.toml
  test/src/e2e_vm_tests/test_programs/neq_4_test/Forc.toml
  test/src/e2e_vm_tests/test_programs/op_precedence/Forc.toml
  test/src/e2e_vm_tests/test_programs/out_of_order_decl/Forc.toml
  test/src/e2e_vm_tests/test_programs/struct_field_access/Forc.toml
  test/src/e2e_vm_tests/test_programs/struct_field_reassignment/Forc.toml
  test/src/e2e_vm_tests/test_programs/trait_override_bug/Forc.toml
  test/src/e2e_vm_tests/test_programs/tuple_desugaring/Forc.toml
  test/src/e2e_vm_tests/test_programs/tuple_types/Forc.toml
  test/src/e2e_vm_tests/test_programs/unary_not_basic/Forc.toml
  test/src/e2e_vm_tests/test_programs/unary_not_basic_2/Forc.toml
  test/src/e2e_vm_tests/test_programs/xos_opcode/Forc.toml
Labels: testing

#692 Clean up Forc readme.
  forc/README.md
Labels: documentation

#690 Add link and formatting fix.
  docs/src/getting-started/forc_project.md
  docs/src/getting-started/temporary_workarounds.md
Labels: The Sway Book

#689 Pin lib version
  test/src/e2e_vm_tests/test_programs/use_full_path_names/Forc.toml
Labels: testing

#691 Update and fix toolchain documentation.
  docs/src/getting-started/sway-toolchain.md
Labels: The Sway Book

#686 fix: fix manifest formatter in `forc fmt`
  forc/src/ops/forc_fmt.rs
Labels: bug, forc, formatter

#688 Bump to version v0.3.1
  Cargo.lock
  forc/Cargo.toml
  parser/Cargo.toml
  sway-core/Cargo.toml
  sway-fmt/Cargo.toml
  sway-ir/Cargo.toml
  sway-server/Cargo.toml
  sway-types/Cargo.toml
  sway-utils/Cargo.toml
  test/Cargo.toml
Labels: release

#693 Embed Fuel-Core docker image within CI
  .github/workflows/ci.yml
Labels: ci

#679 Adding tests for `mint` and `burn`
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/test_fuel_coin_abi/Forc.toml
  test/src/e2e_vm_tests/test_programs/test_fuel_coin_abi/src/main.sw
  test/src/e2e_vm_tests/test_programs/test_fuel_coin_contract/Forc.toml
  test/src/e2e_vm_tests/test_programs/test_fuel_coin_contract/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/test_fuel_coin_contract/src/main.sw
  test/src/e2e_vm_tests/test_programs/token_ops_test/Forc.toml
  test/src/e2e_vm_tests/test_programs/token_ops_test/src/main.sw
Labels: stdlib

#696 Fix new lints from the latest clippy
  .github/workflows/ci.yml
  .github/workflows/clippy_check.yml
  forc/src/ops/forc_dep_check.rs
  forc/src/ops/forc_fmt.rs
  sway-core/src/asm_generation/from_ir.rs
  sway-core/src/control_flow_analysis/flow_graph/mod.rs
  sway-core/src/optimize.rs
  sway-core/src/parse_tree/literal.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/node_dependencies.rs
  sway-core/src/style.rs
  sway-core/src/type_engine/type_info.rs
  sway-ir/src/block.rs
  sway-ir/src/context.rs
  sway-ir/src/instruction.rs
  sway-ir/src/irtype.rs
  sway-ir/src/verify.rs
  sway-ir/tests/tests.rs
Labels: bug, ci

#700 Fix unhelpful error found when there is an unimplemented feature.
  sway-core/src/type_engine/engine.rs
Labels: compiler

#714 feature to uwu-ify compile errors and warnings
  Cargo.lock
  forc/Cargo.toml
  forc/src/utils/helpers.rs
  test/src/e2e_vm_tests/test_programs/if_elseif_enum/Forc.toml
Labels: enhancement, compiler, forc

#715 bump to v0.3.3
  Cargo.lock
  forc/Cargo.toml
  parser/Cargo.toml
  sway-core/Cargo.toml
  sway-fmt/Cargo.toml
  sway-ir/Cargo.toml
  sway-server/Cargo.toml
  sway-types/Cargo.toml
  sway-utils/Cargo.toml
  test/Cargo.toml
Labels: release

#712 Fix starting line of warning spans
  forc/src/utils/helpers.rs
  sway-core/src/error.rs
Labels: bug, compiler

#656 Implement initial support for source mapping
  Cargo.lock
  forc/src/cli/commands/build.rs
  forc/src/cli/commands/deploy.rs
  forc/src/cli/commands/run.rs
  forc/src/ops/forc_build.rs
  forc/src/ops/forc_deploy.rs
  forc/src/ops/forc_fmt.rs
  forc/src/ops/forc_run.rs
  sway-core/Cargo.toml
  sway-core/src/asm_generation/finalized_asm.rs
  sway-core/src/lib.rs
  sway-core/src/source_map.rs
  test/src/e2e_vm_tests/harness.rs
Labels: enhancement, compiler, forc

#672 Add tests for implementing the Eq trait for Address
  test/src/e2e_vm_tests/test_programs/address_test/Forc.toml
  test/src/e2e_vm_tests/test_programs/address_test/src/main.sw
Labels: stdlib

#703 Version Bump Default Cargo.toml
  forc/src/utils/defaults.rs
Labels: forc

#707 Add environment variable knobs to customise the E2E test runs.
  test/src/e2e_vm_tests/harness.rs
Labels: testing

#708 ci: build with all features
  .github/workflows/ci.yml
Labels: ci

#639 Revert instead of return when no function selectors match
  sway-core/src/asm_generation/mod.rs
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/bal_opcode/src/main.sw
  test/src/e2e_vm_tests/test_programs/call_basic_storage/src/main.sw
  test/src/e2e_vm_tests/test_programs/call_increment_contract/src/main.sw
  test/src/e2e_vm_tests/test_programs/caller_auth_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/caller_context_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/contract_call/src/main.sw
Labels: compiler

#711 Defer integer literal type resolution until after type checking
  sway-core/src/asm_generation/mod.rs
  sway-core/src/optimize.rs
  sway-core/src/parse_tree/literal.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression_variant.rs
  sway-core/src/sway.pest
  sway-core/src/type_engine/engine.rs
  sway-core/src/type_engine/type_info.rs
  sway-server/src/utils/common.rs
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/literal_too_large_for_type/Forc.toml
  test/src/e2e_vm_tests/test_programs/literal_too_large_for_type/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/literal_too_large_for_type/src/main.sw
Labels: enhancement, compiler

#697 Adding tests for force_transfer function.
  test/src/e2e_vm_tests/test_programs/test_fuel_coin_abi/Forc.toml
  test/src/e2e_vm_tests/test_programs/test_fuel_coin_abi/src/main.sw
  test/src/e2e_vm_tests/test_programs/test_fuel_coin_contract/Forc.toml
  test/src/e2e_vm_tests/test_programs/test_fuel_coin_contract/src/main.sw
  test/src/e2e_vm_tests/test_programs/token_ops_test/Forc.toml
  test/src/e2e_vm_tests/test_programs/token_ops_test/src/main.sw
Labels: stdlib
