Repository FuelLabs/sway, pull requests merged in 2023-05, with the labels that each got.

#4510 Fix `--finalized-asm` output and docs
  docs/book/src/forc/manifest_reference.md
  docs/book/src/introduction/forc_project.md
  forc-pkg/src/manifest.rs
  sway-core/src/asm_generation/programs/final.rs
Labels: forc, The Sway Book, compiler: ui

#4514 add constants page to summary
  docs/book/src/SUMMARY.md
  docs/book/src/basics/constants.md
Labels: The Sway Book

#4526 Allow loops in predicates
  docs/reference/src/documentation/language/program-types/predicate.md
  sway-core/src/asm_generation/fuel/checks.rs
  sway-core/src/ir_generation/function.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/type_check_context.rs
  sway-error/src/error.rs
  test/src/e2e_vm_tests/test_programs/should_fail/predicate_while/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/predicate_while/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/predicate_while_dep/src/loop.sw
  test/src/e2e_vm_tests/test_programs/should_fail/predicate_while_dep/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/predicate_while/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/predicate_while/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/predicate_while/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/predicate_while/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/predicate_while_dep/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/predicate_while_dep/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/predicate_while_dep/src/loop.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/predicate_while_dep/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/predicate_while_dep/test.toml
Labels: enhancement, language feature, compiler: frontend, compiler: codegen, The Sway Reference

#4527 Fix ordering bug in `U256`
  sway-lib-std/src/u256.sw
Labels: bug, lib: std

#4531 docs: add section comments for devrel
  docs/book/src/basics/blockchain_types.md
  docs/book/src/basics/built_in_types.md
  docs/book/src/basics/comments_and_logging.md
  docs/book/src/basics/commonly_used_library_types.md
  docs/book/src/basics/constants.md
  docs/book/src/basics/control_flow.md
  docs/book/src/basics/functions.md
  docs/book/src/basics/index.md
  docs/book/src/basics/methods_and_associated_functions.md
  docs/book/src/basics/structs_tuples_and_enums.md
  docs/book/src/basics/variables.md
  docs/book/src/blockchain-development/access_control.md
  docs/book/src/blockchain-development/native_assets.md
  docs/book/src/blockchain-development/purity.md
  docs/book/src/blockchain-development/storage.md
  docs/book/src/common-collections/storage_map.md
  docs/book/src/introduction/forc_project.md
  docs/book/src/introduction/standard_library.md
  docs/book/src/reference/solidity_differences.md
  docs/book/src/reference/style_guide.md
  docs/book/src/sway-program-types/index.md
  docs/book/src/sway-program-types/libraries.md
  docs/book/src/sway-program-types/smart_contracts.md
  docs/book/src/testing/unit-testing.md
Labels: The Sway Book, documentation

#4530 chore: rename `fn_args_layout` to `fn_params_layout` in `rustfmt.toml`
  rustfmt.toml
Labels: code quality

#4389 feat(`forc doc`): Add `impl_trait` representation to `ItemBody`
  examples/abi_supertraits/src/main.sw
  forc-plugins/forc-doc/src/assets/ayu.css
  forc-plugins/forc-doc/src/assets/swaydoc.css
  forc-plugins/forc-doc/src/doc/descriptor.rs
  forc-plugins/forc-doc/src/doc/mod.rs
  forc-plugins/forc-doc/src/render/item/components.rs
  forc-plugins/forc-doc/src/render/item/context.rs
  forc-plugins/forc-doc/src/tests/data/impl_traits/Forc.lock
  forc-plugins/forc-doc/src/tests/data/impl_traits/Forc.toml
  forc-plugins/forc-doc/src/tests/data/impl_traits/src/bar.sw
  forc-plugins/forc-doc/src/tests/data/impl_traits/src/foo.sw
  forc-plugins/forc-doc/src/tests/data/impl_traits/src/lib.sw
Labels: enhancement, forc-doc

#4539 Goto links for LSP hover
  Cargo.lock
  sway-lsp/Cargo.toml
  sway-lsp/src/capabilities/code_actions/struct_decl/struct_new.rs
  sway-lsp/src/capabilities/hover/hover_link_contents.rs
  sway-lsp/src/capabilities/hover/mod.rs
  sway-lsp/src/capabilities/rename.rs
  sway-lsp/src/core/session.rs
  sway-lsp/src/core/sync.rs
  sway-lsp/src/core/token_map.rs
  sway-lsp/src/error.rs
  sway-lsp/src/utils/document.rs
  sway-lsp/src/utils/markup.rs
  sway-lsp/src/utils/mod.rs
  sway-lsp/tests/integration/lsp.rs
  sway-lsp/tests/lib.rs
Labels: language server

#4522 Parse `__ptr[T]` and `__slice[T]`
  sway-ast/src/keywords.rs
  sway-ast/src/ty/mod.rs
  sway-core/src/abi_generation/evm_json_abi.rs
  sway-core/src/abi_generation/fuel_json_abi.rs
  sway-core/src/ir_generation/convert.rs
  sway-core/src/monomorphize/solve/solver.rs
  sway-core/src/semantic_analysis/node_dependencies.rs
  sway-core/src/transform/to_parsed_lang/convert_parse_tree.rs
  sway-core/src/type_system/id.rs
  sway-core/src/type_system/info.rs
  sway-core/src/type_system/substitute/subst_map.rs
  sway-error/src/parser_error.rs
  sway-parse/src/item/item_impl.rs
  sway-parse/src/keywords.rs
  sway-parse/src/ty/mod.rs
  swayfmt/src/utils/language/ty.rs
Labels: breaking, compiler: frontend, compiler: parser

#4543 Fix `StorageVec` bugs with use of `field_id`
  sway-lib-std/src/storage/storage_vec.sw
  test/src/e2e_vm_tests/test_programs/should_pass/empty_fields_in_storage_struct/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/empty_fields_in_storage_struct/src/main.sw
Labels: bug, lib: std

#4541 Update `StorageBytes` to use `field_id` over `slot`
  sway-lib-std/src/storage/storage_bytes.sw
  test/src/e2e_vm_tests/test_programs/should_pass/empty_fields_in_storage_struct/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/empty_fields_in_storage_struct/src/wallet.sw
  test/src/e2e_vm_tests/test_programs/should_pass/empty_fields_in_storage_struct/src/wallet_abi.sw
Labels: bug, lib: std

#4548 feat(fmt): improve newline insertion when comments are in between leaf spans
  swayfmt/src/utils/map/newline.rs
  swayfmt/tests/mod.rs
Labels: formatter

#4553 Use intrinsics for base integer operations
  docs/book/src/reference/compiler_intrinsics.md
  sway-ast/src/intrinsics.rs
  sway-core/src/asm_generation/fuel/fuel_asm_builder.rs
  sway-core/src/ir_generation/const_eval.rs
  sway-core/src/ir_generation/function.rs
  sway-core/src/semantic_analysis/ast_node/expression/intrinsic_function.rs
  sway-core/src/semantic_analysis/cei_pattern_analysis.rs
  sway-ir/src/instruction.rs
  sway-ir/src/parser.rs
  sway-ir/src/printer.rs
  sway-lib-core/src/ops.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/binop_intrinsics/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/configurable_consts/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/language/configurable_consts/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/const_inits/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_basic_storage/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_increment_contract/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/storage_access_caller/src/main.sw
  test/src/ir_generation/tests/binops.sw
Labels: compiler: ir, breaking, lib: core, compiler: frontend

#4567 Add intrinsics tests
  sway-ir/src/printer.rs
  test/src/ir_generation/tests/addr_of.sw
  test/src/ir_generation/tests/eq.sw
  test/src/ir_generation/tests/gt.sw
  test/src/ir_generation/tests/is_reference_type.sw
  test/src/ir_generation/tests/lt.sw
  test/src/ir_generation/tests/ptr_add.sw
  test/src/ir_generation/tests/ptr_sub.sw
  test/src/ir_generation/tests/size_of.sw
  test/src/ir_generation/tests/size_of_val.sw
  test/src/ir_generation/tests/state_load_quad.sw
  test/src/ir_generation/tests/state_load_word.sw
  test/src/ir_generation/tests/state_store_quad.sw
  test/src/ir_generation/tests/state_store_word.sw
Labels: bug, compiler, testing, compiler: ir

#4554 feat: add a way to specify expected revert code to `forc-test`
  docs/book/src/testing/unit-testing.md
  forc-pkg/src/pkg.rs
  forc-test/src/lib.rs
  test/src/e2e_vm_tests/test_programs/should_pass/unit_tests/should_revert/src/lib.sw
  test/src/e2e_vm_tests/test_programs/should_pass/unit_tests/should_revert/test.toml
Labels: enhancement, forc-test

#4572 Remove aggressive predicate inlining
  sway-core/src/asm_generation/fuel/checks.rs
  sway-core/src/lib.rs
  sway-ir/src/optimize/inline.rs
  sway-ir/src/pass_manager.rs
  test/src/ir_generation/mod.rs
Labels: bug, compiler: optimization

#4578 ci: use `--locked` while installing `cargo-generate`
  .github/workflows/ci.yml
Labels: bug, ci

#4546 `forc doc`: Generate dependency documentation
  Cargo.lock
  forc-plugins/forc-doc/Cargo.toml
  forc-plugins/forc-doc/src/doc/mod.rs
  forc-plugins/forc-doc/src/doc/module.rs
  forc-plugins/forc-doc/src/licenses/README.md
  forc-plugins/forc-doc/src/main.rs
  forc-plugins/forc-doc/src/render/index.rs
  forc-plugins/forc-doc/src/render/item/components.rs
  forc-plugins/forc-doc/src/render/mod.rs
  forc-plugins/forc-doc/src/render/sidebar.rs
  forc-plugins/forc-doc/src/static.files/FiraSans-Medium.woff2
  forc-plugins/forc-doc/src/static.files/FiraSans-Regular.woff2
  forc-plugins/forc-doc/src/static.files/NanumBarunGothic.ttf.woff2
  forc-plugins/forc-doc/src/static.files/SourceCodePro-It.ttf.woff2
  forc-plugins/forc-doc/src/static.files/SourceCodePro-Regular.ttf.woff2
  forc-plugins/forc-doc/src/static.files/SourceCodePro-Semibold.ttf.woff2
  forc-plugins/forc-doc/src/static.files/SourceSerif4-Bold.ttf.woff2
  forc-plugins/forc-doc/src/static.files/SourceSerif4-It.ttf.woff2
  forc-plugins/forc-doc/src/static.files/SourceSerif4-Regular.ttf.woff2
  forc-plugins/forc-doc/src/static.files/ayu.css
  forc-plugins/forc-doc/src/static.files/ayu.min.css
  forc-plugins/forc-doc/src/static.files/clipboard.svg
  forc-plugins/forc-doc/src/static.files/down-arrow.svg
  forc-plugins/forc-doc/src/static.files/highlight.js
  forc-plugins/forc-doc/src/static.files/normalize.css
  forc-plugins/forc-doc/src/static.files/sway-logo.svg
  forc-plugins/forc-doc/src/static.files/swaydoc.css
  forc-plugins/forc-doc/src/static.files/toggle-minus.svg
  forc-plugins/forc-doc/src/static.files/toggle-plus.svg
  forc-plugins/forc-doc/src/static.files/wheel.svg
  scripts/highlightjs/build.sh
Labels: enhancement, forc-doc

#4566 feat: implement `forc-test` filter
  Cargo.toml
  forc-test/src/lib.rs
  forc-test/test_data/test_library/.gitignore
  forc-test/test_data/test_library/Forc.lock
  forc-test/test_data/test_library/Forc.toml
  forc-test/test_data/test_library/src/lib.sw
  forc/src/cli/commands/test.rs
  test/src/e2e_vm_tests/harness.rs
Labels: enhancement, forc, forc-test

#4584 Enables where clauses for traits.
  sway-core/src/semantic_analysis/ast_node/declaration/enum.rs
  sway-core/src/semantic_analysis/ast_node/declaration/function.rs
  sway-core/src/semantic_analysis/ast_node/declaration/function/function_parameter.rs
  sway-core/src/semantic_analysis/ast_node/declaration/impl_trait.rs
  sway-core/src/semantic_analysis/ast_node/declaration/struct.rs
  sway-core/src/semantic_analysis/ast_node/declaration/trait.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/enum_instantiation.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/struct_instantiation.rs
  sway-core/src/type_system/ast_elements/type_parameter.rs
  sway-core/src/type_system/id.rs
  sway-error/src/error.rs
  test/src/e2e_vm_tests/test_programs/should_fail/where_clause_traits/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/where_clause_traits/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/where_clause_traits/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/where_clause_traits/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/where_clause_traits/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/where_clause_traits/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/where_clause_traits/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/language/where_clause_traits/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/where_clause_traits/test.toml
Labels: enhancement, language feature, P: critical

#4574 Stabilize module privacy
  forc-pkg/src/manifest.rs
  forc-pkg/src/pkg.rs
  forc-plugins/forc-client/src/op/deploy.rs
  forc-plugins/forc-client/src/op/run.rs
  forc-plugins/forc-doc/src/main.rs
  forc-test/src/lib.rs
  forc/src/cli/commands/check.rs
  forc/src/cli/commands/test.rs
  forc/src/cli/shared.rs
  forc/src/ops/forc_build.rs
  forc/src/ops/forc_check.rs
  forc/src/ops/forc_contract_id.rs
  forc/src/ops/forc_predicate_root.rs
  sway-core/src/build_config.rs
  sway-core/src/lib.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/method_application.rs
  sway-core/src/semantic_analysis/ast_node/mod.rs
  sway-core/src/semantic_analysis/namespace/module.rs
  sway-core/src/semantic_analysis/namespace/namespace.rs
  sway-core/src/semantic_analysis/namespace/root.rs
  sway-core/src/semantic_analysis/program.rs
  sway-core/src/semantic_analysis/type_check_context.rs
  sway-core/src/type_system/ast_elements/binding.rs
  sway-core/src/type_system/engine.rs
  sway-lsp/src/core/session.rs
  test/src/e2e_vm_tests/harness.rs
  test/src/ir_generation/mod.rs
Labels: breaking, compiler: ui

#4590 fix: `std` publish directory
  .github/workflows/gh-pages.yml
Labels: bug, ci, lib: std, forc-doc

#4597 ci-fix: use latest (sourced via path) version of std while testing sway reference examples
  ci_checks.sh
  docs/reference/src/code/Forc.lock
  docs/reference/src/code/Forc.toml
  docs/reference/src/code/examples/access-control/ownership/Forc.toml
  docs/reference/src/code/examples/counter/Forc.toml
  docs/reference/src/code/examples/fizzbuzz/Forc.toml
  docs/reference/src/code/examples/wallet_example/Forc.toml
  docs/reference/src/code/language/annotations/Forc.toml
  docs/reference/src/code/language/built-ins/arrays/Forc.toml
  docs/reference/src/code/language/built-ins/booleans/Forc.toml
  docs/reference/src/code/language/built-ins/bytes/Forc.toml
  docs/reference/src/code/language/built-ins/enums/Forc.toml
  docs/reference/src/code/language/built-ins/numerics/Forc.toml
  docs/reference/src/code/language/built-ins/strings/Forc.toml
  docs/reference/src/code/language/built-ins/structs/Forc.toml
  docs/reference/src/code/language/built-ins/tuples/Forc.toml
  docs/reference/src/code/language/comments/Forc.toml
  docs/reference/src/code/language/control_flow/Forc.toml
  docs/reference/src/code/language/functions/Forc.toml
  docs/reference/src/code/language/program-types/contracts/interface/Forc.toml
  docs/reference/src/code/language/program-types/contracts/wallet/Forc.toml
  docs/reference/src/code/language/program-types/libraries/external/my_library/Forc.toml
  docs/reference/src/code/language/program-types/libraries/external/my_other_library/Forc.toml
  docs/reference/src/code/language/program-types/libraries/internal/my_lib/Forc.toml
  docs/reference/src/code/language/program-types/predicates/simple_predicate/Forc.toml
  docs/reference/src/code/language/program-types/scripts/simple_script/Forc.toml
  docs/reference/src/code/language/style-guide/annotation_style/Forc.toml
  docs/reference/src/code/language/style-guide/enum_style/Forc.toml
  docs/reference/src/code/language/style-guide/getters/Forc.toml
  docs/reference/src/code/language/style-guide/letter_casing/Forc.toml
  docs/reference/src/code/language/style-guide/struct_shorthand/Forc.toml
  docs/reference/src/code/language/variables/Forc.toml
  docs/reference/src/code/misc/advanced-concepts/enum_advanced/Forc.toml
  docs/reference/src/code/misc/known-issues/string_issue/Forc.toml
  docs/reference/src/code/operations/assertions/Forc.toml
  docs/reference/src/code/operations/asset_operations/Forc.toml
  docs/reference/src/code/operations/call_data/Forc.toml
  docs/reference/src/code/operations/contract_calling/call/Forc.toml
  docs/reference/src/code/operations/contract_calling/contract_interface/Forc.toml
  docs/reference/src/code/operations/hashing/Forc.toml
  docs/reference/src/code/operations/logging/Forc.toml
  docs/reference/src/code/operations/namespace/Forc.toml
  docs/reference/src/code/operations/storage/empty_storage_init/Forc.toml
  docs/reference/src/code/operations/storage/reading_writing_to_storage/Forc.toml
  docs/reference/src/code/operations/storage/storage_init/Forc.toml
  docs/reference/src/code/operations/storage/storage_map/Forc.toml
  docs/reference/src/code/operations/storage/storage_vec/Forc.toml
  docs/reference/src/code/operations/storage/store_get/Forc.toml
Labels: bug, ci

#4591 fix: `std` publish directory -- deploy step
  .github/workflows/gh-pages.yml
Labels: bug, ci, lib: std, forc-doc

#4606 fix: `std` publish dir deploy
  .github/workflows/gh-pages.yml
Labels: ci, lib: std

#4601 release: bump to v0.40.0
  Cargo.lock
  forc-pkg/Cargo.toml
  forc-plugins/forc-client/Cargo.toml
  forc-plugins/forc-doc/Cargo.toml
  forc-plugins/forc-fmt/Cargo.toml
  forc-plugins/forc-lsp/Cargo.toml
  forc-plugins/forc-tx/Cargo.toml
  forc-test/Cargo.toml
  forc-tracing/Cargo.toml
  forc-util/Cargo.toml
  forc/Cargo.toml
  sway-ast/Cargo.toml
  sway-core/Cargo.toml
  sway-error/Cargo.toml
  sway-ir/Cargo.toml
  sway-ir/sway-ir-macros/Cargo.toml
  sway-lsp/Cargo.toml
  sway-parse/Cargo.toml
  sway-types/Cargo.toml
  sway-utils/Cargo.toml
  swayfmt/Cargo.toml
Labels: release

#4594 Fix forc-run-benchmarks checkout steps for non-PR CI builds
  .github/workflows/ci.yml
Labels: compiler, ci

#4593 Remove duplicate type checker definitions in favor of `UnifyCheck`
  sway-core/src/semantic_analysis/namespace/namespace.rs
  sway-core/src/semantic_analysis/namespace/trait_map.rs
  sway-core/src/type_system/engine.rs
  sway-core/src/type_system/info.rs
  sway-core/src/type_system/priv_prelude.rs
  sway-core/src/type_system/unify/unify_check.rs
Labels: code quality, compiler: frontend

#4607 fix: Change order of master deploy
  .github/workflows/gh-pages.yml
Labels: bug, ci
