Repository FuelLabs/sway, pull requests merged in 2024-07, with the labels that each got.

#6163 Fix u256 logarithm rounding errors
  sway-lib-std/src/flags.sw
  sway-lib-std/src/lib.sw
  sway-lib-std/src/math.sw
  test/src/in_language_tests/test_programs/math_inline_tests/src/main.sw
Labels: bug, lib: std

#6201 Fixes method application unwrap panic.
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/method_application.rs
Labels: bug, compiler: frontend

#6206 Enables tests that prove #418 is solved.
  test/src/e2e_vm_tests/test_programs/should_fail/multiple_enums_with_the_same_name/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/multiple_structs_with_the_same_name/test.toml
Labels: compiler

#6166 Refactor `StorageVec`'s `load_vec()` and `store_vec()` to handle types of less than 8 bytes
  sway-lib-std/src/storage/storage_vec.sw
  test/src/sdk-harness/test_projects/storage_vec_to_vec/mod.rs
  test/src/sdk-harness/test_projects/storage_vec_to_vec/src/main.sw
Labels: bug, lib: std

#6207 Bump to v0.61.1
  Cargo.lock
  docs/reference/src/documentation/introduction/installation/cargo.md
  docs/reference/src/documentation/introduction/installation/index.md
  docs/reference/src/documentation/introduction/installation/source.md
  docs/reference/src/index.md
  forc-pkg/Cargo.toml
  forc-plugins/forc-client/Cargo.toml
  forc-plugins/forc-crypto/Cargo.toml
  forc-plugins/forc-debug/Cargo.toml
  forc-plugins/forc-doc/Cargo.toml
  forc-plugins/forc-fmt/Cargo.toml
  forc-plugins/forc-lsp/Cargo.toml
  forc-plugins/forc-tx/Cargo.toml
  forc-test/Cargo.toml
  forc-tracing/Cargo.toml
  forc-util/Cargo.toml
  forc/Cargo.toml
  sway-ast/Cargo.toml
  sway-core/Cargo.toml
  sway-error/Cargo.toml
  sway-ir/Cargo.toml
  sway-ir/sway-ir-macros/Cargo.toml
  sway-lsp/Cargo.toml
  sway-parse/Cargo.toml
  sway-types/Cargo.toml
  sway-utils/Cargo.toml
  swayfmt/Cargo.toml
Labels: release

#6212 fix: deployment estimation deferred to sdk
  .github/workflows/ci.yml
  Cargo.lock
  forc-plugins/forc-client/Cargo.toml
  forc-plugins/forc-client/src/constants.rs
  forc-plugins/forc-client/src/op/deploy.rs
  forc-plugins/forc-client/src/op/mod.rs
  forc-plugins/forc-client/src/op/run/mod.rs
  forc-plugins/forc-client/src/util/gas.rs
  forc-plugins/forc-client/src/util/tx.rs
  forc-plugins/forc-client/tests/deploy.rs
Labels: P: critical, forc-client, forc-deploy

#6208 feat: Add helper function for consistent forc output
  Cargo.lock
  forc-pkg/src/lock.rs
  forc-pkg/src/pkg.rs
  forc-pkg/src/source/git/mod.rs
  forc-pkg/src/source/ipfs.rs
  forc-plugins/forc-doc/Cargo.toml
  forc-plugins/forc-doc/src/lib.rs
  forc-tracing/Cargo.toml
  forc-tracing/src/lib.rs
  forc-util/src/lib.rs
  forc/src/cli/commands/test.rs
  forc/src/ops/forc_template.rs
Labels: forc

#6213 Bump to v0.61.2
  Cargo.lock
  forc-pkg/Cargo.toml
  forc-plugins/forc-client/Cargo.toml
  forc-plugins/forc-crypto/Cargo.toml
  forc-plugins/forc-debug/Cargo.toml
  forc-plugins/forc-doc/Cargo.toml
  forc-plugins/forc-fmt/Cargo.toml
  forc-plugins/forc-lsp/Cargo.toml
  forc-plugins/forc-tx/Cargo.toml
  forc-test/Cargo.toml
  forc-tracing/Cargo.toml
  forc-util/Cargo.toml
  forc/Cargo.toml
  sway-ast/Cargo.toml
  sway-core/Cargo.toml
  sway-error/Cargo.toml
  sway-ir/Cargo.toml
  sway-ir/sway-ir-macros/Cargo.toml
  sway-lsp/Cargo.toml
  sway-parse/Cargo.toml
  sway-types/Cargo.toml
  sway-utils/Cargo.toml
  swayfmt/Cargo.toml
Labels: release

#6214 feat: Print the formatted bytecode size on forc build
  Cargo.lock
  forc-pkg/Cargo.toml
  forc-pkg/src/pkg.rs
Labels: forc

#6236 fix: typo in comment for ipfs fetching in forc-pkg
  forc-pkg/src/source/ipfs.rs
Labels: bug, ci

#6243 Add string slices to supported types message in match expressions
  sway-core/src/type_system/info.rs
Labels: compiler, compiler: frontend

#6235 chore: remove snapshot, as accounts are funded by default
  .github/workflows/ci.yml
  .github/workflows/local-testnode/chain_config.json
  .github/workflows/local-testnode/metadata.json
  .github/workflows/local-testnode/state_config.json
  .github/workflows/local-testnode/state_transition_bytecode.wasm
  forc-plugins/forc-client/tests/deploy.rs
Labels: ci, code quality

#6142 Fix `Bytes`, `Vec` and `String` buffer ownership
  forc-plugins/forc-client/tests/deploy.rs
  sway-core/src/ir_generation/function.rs
  sway-core/src/language/ty/declaration/function.rs
  sway-core/src/semantic_analysis/ast_node/expression/intrinsic_function.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/method_application.rs
  sway-core/src/type_system/id.rs
  sway-core/src/type_system/priv_prelude.rs
  sway-lib-core/src/codec.sw
  sway-lib-std/src/alloc.sw
  sway-lib-std/src/bytes.sw
  sway-lib-std/src/string.sw
  sway-lib-std/src/vec.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/configurable_consts/json_abi_oracle_new_encoding.json
  test/src/e2e_vm_tests/test_programs/should_pass/language/slice/slice_contract/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/string_slice/string_slice_contract/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/u256/u256_abi/json_abi_oracle_new_encoding.json
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/array_of_structs_caller/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/asset_ops_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/bal_opcode/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_abi_with_tuples/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_basic_storage/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_contract_with_type_aliases/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_increment_contract/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_storage_enum/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/caller_auth_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/caller_context_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/nested_struct_args_caller/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/storage_access_caller/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/unit_tests/workspace_test/contract_multi_test/src/main.sw
  test/src/in_language_tests/test_programs/bytes_inline_tests/src/main.sw
  test/src/in_language_tests/test_programs/string_inline_tests/src/main.sw
  test/src/in_language_tests/test_programs/vec_inline_tests/src/main.sw
  test/update-contract-ids.sh
Labels: breaking

#6231 Correctly handle `Input::Message` when calling `msg_sender()`
  sway-lib-std/src/auth.sw
  test/src/sdk-harness/test_artifacts/auth_testing_contract/src/main.sw
  test/src/sdk-harness/test_projects/auth/mod.rs
Labels: bug, lib: std

#6251 Unify AST nodes for parsed and typed `impl self` and `impl trait`.
  forc-plugins/forc-doc/src/doc/mod.rs
  forc-plugins/forc-doc/src/render/item/context.rs
  forc-plugins/forc-doc/src/render/title.rs
  sway-core/src/control_flow_analysis/analyze_return_paths.rs
  sway-core/src/control_flow_analysis/dead_code_analysis.rs
  sway-core/src/decl_engine/engine.rs
  sway-core/src/decl_engine/id.rs
  sway-core/src/decl_engine/parsed_engine.rs
  sway-core/src/decl_engine/ref.rs
  sway-core/src/ir_generation/function.rs
  sway-core/src/language/parsed/declaration.rs
  sway-core/src/language/parsed/declaration/impl_trait.rs
  sway-core/src/language/ty/ast_node.rs
  sway-core/src/language/ty/declaration/declaration.rs
  sway-core/src/language/ty/declaration/function.rs
  sway-core/src/language/ty/declaration/impl_trait.rs
  sway-core/src/language/ty/expression/expression.rs
  sway-core/src/language/ty/expression/expression_variant.rs
  sway-core/src/language/ty/program.rs
  sway-core/src/semantic_analysis/ast_node/declaration/auto_impl.rs
  sway-core/src/semantic_analysis/ast_node/declaration/declaration.rs
  sway-core/src/semantic_analysis/ast_node/declaration/impl_trait.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/method_application.rs
  sway-core/src/semantic_analysis/cei_pattern_analysis.rs
  sway-core/src/semantic_analysis/module.rs
  sway-core/src/semantic_analysis/node_dependencies.rs
  sway-core/src/semantic_analysis/type_check_analysis.rs
  sway-core/src/semantic_analysis/type_check_context.rs
  sway-core/src/transform/to_parsed_lang/convert_parse_tree.rs
  sway-lsp/src/capabilities/code_actions/struct_decl/struct_new.rs
  sway-lsp/src/capabilities/rename.rs
  sway-lsp/src/traverse/parsed_tree.rs
  sway-lsp/src/traverse/typed_tree.rs
Labels: compiler: frontend

#6239 Add LRU Session Cache to Reduce RAM Usage
  sway-lsp/src/server_state.rs
Labels: language server

#6194 Add `Output::ContractCreated` transaction to `Output` enum
  sway-lib-std/src/outputs.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/asset_ops_test/src/main.sw
  test/src/in_language_tests/Forc.toml
  test/src/in_language_tests/test_programs/output_inline_tests/Forc.toml
  test/src/in_language_tests/test_programs/output_inline_tests/src/main.sw
  test/src/sdk-harness/Forc.lock
  test/src/sdk-harness/Forc.toml
  test/src/sdk-harness/test_artifacts/tx_output_contract_creation_predicate/Forc.lock
  test/src/sdk-harness/test_artifacts/tx_output_contract_creation_predicate/Forc.toml
  test/src/sdk-harness/test_artifacts/tx_output_contract_creation_predicate/src/main.sw
  test/src/sdk-harness/test_projects/tx_fields/mod.rs
Labels: lib: std, breaking

#6238 Add tracing span macro calls to the language server for better debugging
  forc-tracing/src/lib.rs
  sway-lsp/src/capabilities/code_lens.rs
  sway-lsp/src/capabilities/formatting.rs
  sway-lsp/src/capabilities/highlight.rs
  sway-lsp/src/capabilities/inlay_hints.rs
  sway-lsp/src/capabilities/rename.rs
  sway-lsp/src/capabilities/semantic_tokens.rs
  sway-lsp/src/core/session.rs
  sway-lsp/src/handlers/request.rs
  sway-lsp/src/server.rs
  sway-lsp/src/server_state.rs
Labels: language server

#6252 chore: bump to use fuel-core v0.31.0 and sdk v0.65.1
  Cargo.lock
  Cargo.toml
  test/src/sdk-harness/Cargo.lock
  test/src/sdk-harness/Cargo.toml
  test/src/sdk-harness/test_projects/auth/mod.rs
  test/src/sdk-harness/test_projects/ec_recover_and_match_predicate/mod.rs
  test/src/sdk-harness/test_projects/predicate_data_simple/mod.rs
  test/src/sdk-harness/test_projects/predicate_data_struct/mod.rs
  test/src/sdk-harness/test_projects/storage_string/mod.rs
  test/src/sdk-harness/test_projects/string_slice/mod.rs
  test/src/sdk-harness/test_projects/tx_fields/mod.rs
  test/src/sdk-harness/test_projects/vec_in_abi/mod.rs
Labels: dependencies

#6281 Cache Build Plans in language server
  sway-lsp/benches/lsp_benchmarks/compile.rs
  sway-lsp/src/core/session.rs
  sway-lsp/src/core/sync.rs
  sway-lsp/src/error.rs
Labels: language server, performance

#6289 Forbid configurables in pattern matching and shadowing
  sway-core/src/language/ty/expression/scrutinee.rs
  sway-core/src/semantic_analysis/ast_node/expression/match_expression/analysis/match_pattern_variables.rs
  sway-core/src/semantic_analysis/ast_node/expression/match_expression/analysis/mod.rs
  sway-core/src/semantic_analysis/ast_node/expression/match_expression/analysis/pattern.rs
  sway-core/src/semantic_analysis/ast_node/expression/match_expression/typed/matcher.rs
  sway-core/src/semantic_analysis/ast_node/expression/match_expression/typed/typed_match_branch.rs
  sway-core/src/semantic_analysis/ast_node/expression/match_expression/typed/typed_scrutinee.rs
  sway-core/src/semantic_analysis/namespace/lexical_scope.rs
  sway-error/src/diagnostic.rs
  sway-error/src/error.rs
  sway-lsp/src/traverse/typed_tree.rs
  test/src/e2e_vm_tests/test_programs/should_fail/deduplication_of_shadowing_errors/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/language/reexport/multiple_imports_of_same_reexport/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/shadow_import/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/shadowing/shadowed_configurables/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/shadowing/shadowed_configurables/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/shadowing/shadowed_configurables/src/lib.sw
  test/src/e2e_vm_tests/test_programs/should_fail/shadowing/shadowed_configurables/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/shadowing/shadowed_configurables/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/shadowing/shadowed_configurables_in_pattern_matching/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/shadowing/shadowed_configurables_in_pattern_matching/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/shadowing/shadowed_configurables_in_pattern_matching/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/shadowing/shadowed_configurables_in_pattern_matching/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/shadowing/shadowed_consts_and_vars/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/shadowing/shadowed_consts_and_vars/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/shadowing/shadowed_consts_and_vars_alias/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/superabi_duplicate_methods1/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/superabi_duplicate_methods2/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/superabi_duplicate_methods6/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/superabi_duplicate_methods7/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/superabi_duplicate_methods8/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/superabi_duplicate_methods9/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/match_expressions_constants/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/language/match_expressions_constants/json_abi_oracle_new_encoding.json
  test/src/e2e_vm_tests/test_programs/should_pass/language/match_expressions_constants/src/in_structs.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/match_expressions_constants/src/lib.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/match_expressions_constants/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/match_expressions_constants/src/top_level.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/match_expressions_constants/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/shadowing/shadowed_glob_imports/src/lib.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/shadowing/shadowed_glob_imports/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/shadowing/shadowed_glob_imports/test.toml
Labels: compiler, breaking, compiler: frontend

#6278 feat: Enhance forc-deploy UX with dialoguer
  Cargo.lock
  forc-plugins/forc-client/Cargo.toml
  forc-plugins/forc-client/src/constants.rs
  forc-plugins/forc-client/src/op/deploy.rs
  forc-plugins/forc-client/src/op/run/mod.rs
  forc-plugins/forc-client/src/util/target.rs
  forc-plugins/forc-client/src/util/tx.rs
  forc-plugins/forc-client/test/data/contract_with_dep/Forc.lock
  forc-plugins/forc-client/test/data/contract_with_dep/Forc.toml
  forc-plugins/forc-client/test/data/contract_with_dep_with_salt_conflict/Forc.toml
  forc-plugins/forc-client/test/data/standalone_contract/Forc.lock
  forc-plugins/forc-client/test/data/standalone_contract/Forc.toml
  forc-plugins/forc-client/test/data/standalone_contract_b/Forc.toml
  forc-plugins/forc-client/tests/deploy.rs
Labels: forc-deploy

#6297 cache pid lock files to reduce IO operations
  sway-lsp/src/core/document.rs
  sway-lsp/src/handlers/notification.rs
  sway-lsp/src/server.rs
  sway-lsp/src/server_state.rs
Labels: language server

#6315 Re-pin LSP tests to published version of `std` and re-enable commented out tests
  sway-lsp/tests/fixtures/tokens/abi/Forc.toml
  sway-lsp/tests/fixtures/tokens/consts/Forc.toml
  sway-lsp/tests/fixtures/tokens/fields/Forc.toml
  sway-lsp/tests/fixtures/tokens/matches/Forc.toml
  sway-lsp/tests/fixtures/tokens/paths/Forc.toml
  sway-lsp/tests/fixtures/tokens/paths/src/deep_mod.sw
  sway-lsp/tests/fixtures/tokens/paths/src/deep_mod/deeper_mod.sw
  sway-lsp/tests/fixtures/tokens/paths/src/main.sw
  sway-lsp/tests/fixtures/tokens/storage/Forc.toml
  sway-lsp/tests/fixtures/tokens/structs/Forc.toml
  sway-lsp/tests/fixtures/tokens/turbofish/Forc.toml
  sway-lsp/tests/fixtures/tokens/variables/Forc.toml
  sway-lsp/tests/lib.rs
Labels: language server, testing

#6311 chore: bump forc-pkg deps and fix clippy warnings
  Cargo.lock
  forc-pkg/Cargo.toml
  forc-util/src/fs_locking.rs
Labels: dependencies
