Repository FuelLabs/sway, pull requests merged in 2024-08, with the labels that each got.

#6304 Correct code_size function implementation
  sway-lib-std/src/call_frames.sw
  test/src/sdk-harness/test_projects/call_frames/mod.rs
Labels: bug, lib: std

#6069 feat: create and deploy a reference proxy contract for contracts with `[proxy]` enabled
  Cargo.lock
  Cargo.toml
  docs/book/src/forc/plugins/forc_client/index.md
  forc-pkg/src/manifest/mod.rs
  forc-pkg/src/pkg.rs
  forc-plugins/forc-client/Cargo.toml
  forc-plugins/forc-client/proxy_abi/README.md
  forc-plugins/forc-client/proxy_abi/proxy_contract-abi.json
  forc-plugins/forc-client/proxy_abi/proxy_contract-storage_slots.json
  forc-plugins/forc-client/proxy_abi/proxy_contract.bin
  forc-plugins/forc-client/src/cmd/run.rs
  forc-plugins/forc-client/src/lib.rs
  forc-plugins/forc-client/src/op/deploy.rs
  forc-plugins/forc-client/src/util/mod.rs
  forc-plugins/forc-client/src/util/pkg.rs
  forc-plugins/forc-client/src/util/tx.rs
  forc-plugins/forc-client/test/data/contract_with_dep/Forc.lock
  forc-plugins/forc-client/test/data/standalone_contract/Forc.lock
  forc-plugins/forc-client/test/data/standalone_contract/standalone_contract-abi.json
  forc-plugins/forc-client/tests/deploy.rs
Labels: enhancement, big, P: critical, forc-client, forc-deploy

#6364 Fixes assert in type_check_encode_buffer_empty.
  sway-core/src/semantic_analysis/ast_node/expression/intrinsic_function.rs
  test/src/e2e_vm_tests/test_programs/should_fail/encode_buffer_empty_with_args/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/encode_buffer_empty_with_args/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/encode_buffer_empty_with_args/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_fail/encode_buffer_empty_with_args/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/encode_buffer_empty_with_args/test.toml
Labels: bug, compiler: frontend

#6340 Revert when overflow using pow for u8, u16, u32
  sway-lib-std/src/math.sw
  test/src/in_language_tests/test_programs/math_inline_tests/src/main.sw
  test/src/sdk-harness/test_projects/exponentiation/mod.rs
Labels: bug, lib: std

#6280 Implement Typed Module Caching
  sway-core/src/decl_engine/engine.rs
  sway-core/src/decl_engine/parsed_engine.rs
  sway-core/src/engine_threading.rs
  sway-core/src/language/ty/module.rs
  sway-core/src/language/ty/program.rs
  sway-core/src/lib.rs
  sway-core/src/query_engine/mod.rs
  sway-core/src/semantic_analysis/module.rs
  sway-core/src/semantic_analysis/node_dependencies.rs
  sway-core/src/semantic_analysis/program.rs
  sway-core/src/type_system/engine.rs
  sway-lsp/src/capabilities/diagnostic.rs
  sway-lsp/src/core/session.rs
  sway-lsp/src/server_state.rs
  sway-lsp/tests/integration/lsp.rs
  sway-lsp/tests/lib.rs
  sway-parse/src/module.rs
Labels: language server, compiler: frontend, performance

#6423 Update README.md
  swayfmt/README.md
Labels: formatter, documentation

#6419 Allow variable length message in ed_verify
  sway-lib-std/src/ecr.sw
  test/src/in_language_tests/test_programs/ecr_inline_tests/src/main.sw
Labels: lib: std, breaking

#6405 Increase Safety when introspecting transaction inputs
  sway-lib-std/src/auth.sw
  sway-lib-std/src/inputs.sw
  test/src/sdk-harness/test_artifacts/auth_predicate/src/main.sw
  test/src/sdk-harness/test_artifacts/tx_contract/src/main.sw
  test/src/sdk-harness/test_projects/auth/mod.rs
  test/src/sdk-harness/test_projects/predicate_data_simple/src/main.sw
  test/src/sdk-harness/test_projects/predicate_data_struct/src/main.sw
  test/src/sdk-harness/test_projects/tx_fields/mod.rs
Labels: lib: std, breaking

#6418 Increase Safety when introspecting transactions
  sway-lib-std/src/tx.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/gtf_intrinsic/src/main.sw
  test/src/sdk-harness/test_artifacts/tx_contract/src/main.sw
  test/src/sdk-harness/test_projects/script_bytecode/src/main.sw
  test/src/sdk-harness/test_projects/script_data/src/main.sw
  test/src/sdk-harness/test_projects/tx_fields/mod.rs
Labels: lib: std, breaking

#6414 Increase Safety when introspecting transaction outputs
  sway-lib-std/src/asset.sw
  sway-lib-std/src/outputs.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/asset_ops_test/src/main.sw
  test/src/sdk-harness/test_artifacts/tx_contract/src/main.sw
  test/src/sdk-harness/test_artifacts/tx_output_contract_creation_predicate/src/main.sw
  test/src/sdk-harness/test_projects/tx_fields/mod.rs
Labels: lib: std, breaking

#6422 Update rust version in forc docker image
  deployment/Dockerfile
Labels: ci

#6250 feat: Implement ldc based automatic contract chunking
  .github/workflows/ci.yml
  docs/book/src/forc/plugins/forc_client/index.md
  forc-plugins/forc-client/src/op/deploy.rs
  forc-plugins/forc-client/src/util/pkg.rs
  forc-plugins/forc-client/test/data/big_contract/.gitignore
  forc-plugins/forc-client/test/data/big_contract/Forc.toml
  forc-plugins/forc-client/test/data/big_contract/big_contract-abi.json
  forc-plugins/forc-client/test/data/big_contract/src/main.sw
  forc-plugins/forc-client/tests/deploy.rs
Labels: enhancement, forc, P: critical, forc-deploy

#6429 fix: use proxy bin with storage slots in a namespace
  forc-plugins/forc-client/proxy_abi/proxy_contract-abi.json
  forc-plugins/forc-client/proxy_abi/proxy_contract-storage_slots.json
  forc-plugins/forc-client/proxy_abi/proxy_contract.bin
  forc-plugins/forc-client/tests/deploy.rs
Labels: enhancement, forc-deploy

#6424 Fix broken forc command docs
  docs/book/spell-check-custom-words.txt
  docs/book/src/SUMMARY.md
  docs/book/src/forc/commands/forc_addr2line.md
  docs/book/src/forc/commands/forc_build.md
  docs/book/src/forc/commands/forc_check.md
  docs/book/src/forc/commands/forc_clean.md
  docs/book/src/forc/commands/forc_completions.md
  docs/book/src/forc/commands/forc_contract-id.md
  docs/book/src/forc/commands/forc_init.md
  docs/book/src/forc/commands/forc_new.md
  docs/book/src/forc/commands/forc_parse-bytecode.md
  docs/book/src/forc/commands/forc_plugins.md
  docs/book/src/forc/commands/forc_predicate-root.md
  docs/book/src/forc/commands/forc_template.md
  docs/book/src/forc/commands/forc_test.md
  docs/book/src/forc/commands/forc_update.md
  docs/book/src/forc/plugins/forc_client/forc_deploy.md
  docs/book/src/forc/plugins/forc_client/forc_run.md
  docs/book/src/forc/plugins/forc_client/forc_submit.md
  docs/book/src/forc/plugins/forc_client/index.md
  docs/book/src/forc/plugins/forc_crypto.md
  docs/book/src/forc/plugins/forc_doc.md
  docs/book/src/forc/plugins/forc_explore.md
  docs/book/src/forc/plugins/forc_fmt.md
  docs/book/src/forc/plugins/forc_lsp.md
  scripts/mdbook-forc-documenter/src/bin/mdbook-forc-documenter.rs
  scripts/mdbook-forc-documenter/src/commands.rs
Labels: bug, forc, documentation

#6421 chore: bump to 0.63.0
  .github/workflows/ci.yml
  Cargo.lock
  forc-pkg/Cargo.toml
  forc-plugins/forc-client/Cargo.toml
  forc-plugins/forc-client/proxy_abi/README.md
  forc-plugins/forc-crypto/Cargo.toml
  forc-plugins/forc-debug/Cargo.toml
  forc-plugins/forc-doc/Cargo.toml
  forc-plugins/forc-fmt/Cargo.toml
  forc-plugins/forc-lsp/Cargo.toml
  forc-plugins/forc-tx/Cargo.toml
  forc-test/Cargo.toml
  forc-tracing/Cargo.toml
  forc-util/Cargo.toml
  forc/Cargo.toml
  sway-ast/Cargo.toml
  sway-core/Cargo.toml
  sway-error/Cargo.toml
  sway-ir/Cargo.toml
  sway-ir/sway-ir-macros/Cargo.toml
  sway-lsp/Cargo.toml
  sway-lsp/tests/fixtures/tokens/abi/Forc.toml
  sway-lsp/tests/fixtures/tokens/consts/Forc.toml
  sway-lsp/tests/fixtures/tokens/fields/Forc.toml
  sway-lsp/tests/fixtures/tokens/matches/Forc.toml
  sway-lsp/tests/fixtures/tokens/paths/Forc.toml
  sway-lsp/tests/fixtures/tokens/storage/Forc.toml
  sway-lsp/tests/fixtures/tokens/structs/Forc.toml
  sway-lsp/tests/fixtures/tokens/turbofish/Forc.toml
  sway-lsp/tests/fixtures/tokens/variables/Forc.toml
  sway-parse/Cargo.toml
  sway-types/Cargo.toml
  sway-utils/Cargo.toml
  swayfmt/Cargo.toml
Labels: release

#6433 test: add more chunking tests
  forc-plugins/forc-client/test/data/big_contract/big_contract-abi.json
  forc-plugins/forc-client/test/data/big_contract/src/main.sw
  forc-plugins/forc-client/tests/deploy.rs
Labels: forc, testing, forc-client

#6438 Bump version to 0.63.1
  Cargo.lock
  forc-pkg/Cargo.toml
  forc-plugins/forc-client/Cargo.toml
  forc-plugins/forc-client/proxy_abi/README.md
  forc-plugins/forc-crypto/Cargo.toml
  forc-plugins/forc-debug/Cargo.toml
  forc-plugins/forc-doc/Cargo.toml
  forc-plugins/forc-fmt/Cargo.toml
  forc-plugins/forc-lsp/Cargo.toml
  forc-plugins/forc-tx/Cargo.toml
  forc-test/Cargo.toml
  forc-tracing/Cargo.toml
  forc-util/Cargo.toml
  forc/Cargo.toml
  sway-ast/Cargo.toml
  sway-core/Cargo.toml
  sway-error/Cargo.toml
  sway-ir/Cargo.toml
  sway-ir/sway-ir-macros/Cargo.toml
  sway-lsp/Cargo.toml
  sway-parse/Cargo.toml
  sway-types/Cargo.toml
  sway-utils/Cargo.toml
  swayfmt/Cargo.toml
Labels: release

#6446 Fix sway templates
  .github/workflows/ci.yml
  templates/sway-predicate-test-rs/template/Cargo.toml
  templates/sway-script-test-rs/template/Cargo.toml
  templates/sway-test-rs/template/Cargo.toml
Labels: ci

#6444 Optimize manifest directory lookup with efficient caching
  sway-lsp/src/server_state.rs
Labels: language server, performance

#6454 Updated the emitted event in the search page
  forc-plugins/forc-doc/src/render/search.rs
  forc-plugins/forc-doc/src/tests/expects/impl_trait/mod.rs
Labels: The Sway Reference

#6457 Add `RUST_BACKTRACE: full` to lsp CI tests
  .github/workflows/ci.yml
Labels: ci, language server

#6449 std-lib/auth: update in-line docs for `caller_address()`
  sway-lib-std/src/auth.sw
Labels: lib: std

#6434 Fixes panic on unwrapping in type_check_trait_implementation.
  sway-core/src/semantic_analysis/ast_node/declaration/impl_trait.rs
  test/src/e2e_vm_tests/test_programs/should_fail/associated_type_not_in_trait/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/associated_type_not_in_trait/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/associated_type_not_in_trait/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/associated_type_not_in_trait/test.toml
Labels: bug, compiler: frontend

#6450 Add the `indoc` crate to `swayfmt` tests for better readability.
  Cargo.lock
  swayfmt/Cargo.toml
  swayfmt/tests/mod.rs
Labels: code quality, formatter

#6439 Handle Out of Bounds Read In Input Message Data
  sway-lib-std/src/inputs.sw
  test/src/sdk-harness/test_artifacts/tx_contract/src/main.sw
  test/src/sdk-harness/test_projects/tx_fields/mod.rs
Labels: bug, lib: std

#6451 Handle formatting new types in `StorageField`
  swayfmt/src/items/item_storage/mod.rs
  swayfmt/src/utils/language/punctuated.rs
  swayfmt/tests/mod.rs
Labels: bug, formatter

#6461 Fixes Numeric type propagation
  sway-core/src/decl_engine/id.rs
  sway-core/src/decl_engine/ref.rs
  sway-core/src/language/ty/ast_node.rs
  sway-core/src/language/ty/code_block.rs
  sway-core/src/language/ty/declaration/configurable.rs
  sway-core/src/language/ty/declaration/constant.rs
  sway-core/src/language/ty/declaration/declaration.rs
  sway-core/src/language/ty/declaration/enum.rs
  sway-core/src/language/ty/declaration/function.rs
  sway-core/src/language/ty/declaration/impl_trait.rs
  sway-core/src/language/ty/declaration/struct.rs
  sway-core/src/language/ty/declaration/trait.rs
  sway-core/src/language/ty/declaration/trait_fn.rs
  sway-core/src/language/ty/declaration/trait_type.rs
  sway-core/src/language/ty/declaration/type_alias.rs
  sway-core/src/language/ty/declaration/variable.rs
  sway-core/src/language/ty/expression/asm.rs
  sway-core/src/language/ty/expression/expression.rs
  sway-core/src/language/ty/expression/expression_variant.rs
  sway-core/src/language/ty/expression/intrinsic_function.rs
  sway-core/src/language/ty/expression/reassignment.rs
  sway-core/src/language/ty/expression/struct_exp_field.rs
  sway-core/src/semantic_analysis/ast_node/code_block.rs
  sway-core/src/semantic_analysis/ast_node/declaration/configurable.rs
  sway-core/src/semantic_analysis/ast_node/declaration/constant.rs
  sway-core/src/semantic_analysis/ast_node/declaration/declaration.rs
  sway-core/src/semantic_analysis/ast_node/declaration/function.rs
  sway-core/src/semantic_analysis/ast_node/declaration/impl_trait.rs
  sway-core/src/semantic_analysis/ast_node/declaration/trait.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/function_application.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/method_application.rs
  sway-core/src/semantic_analysis/module.rs
  sway-core/src/semantic_analysis/namespace/lexical_scope.rs
  sway-core/src/semantic_analysis/namespace/mod.rs
  sway-core/src/semantic_analysis/namespace/root.rs
  sway-core/src/semantic_analysis/namespace/trait_map.rs
  sway-core/src/semantic_analysis/type_check_context.rs
  sway-core/src/transform/to_parsed_lang/context.rs
  sway-core/src/transform/to_parsed_lang/convert_parse_tree.rs
  sway-core/src/type_system/ast_elements/trait_constraint.rs
  sway-core/src/type_system/ast_elements/type_argument.rs
  sway-core/src/type_system/ast_elements/type_parameter.rs
  sway-core/src/type_system/engine.rs
  sway-core/src/type_system/id.rs
  sway-core/src/type_system/priv_prelude.rs
  sway-core/src/type_system/substitute/subst_list.rs
  sway-core/src/type_system/substitute/subst_map.rs
  sway-core/src/type_system/substitute/subst_types.rs
  sway-core/src/type_system/unify/unifier.rs
  sway-types/src/ident.rs
  test/src/e2e_vm_tests/test_programs/should_fail/struct_instantiation_type_mismatch/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/struct_instantiation_type_mismatch/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/type_check_analyze_errors/stdout.snap
  test/src/e2e_vm_tests/test_programs/should_pass/language/numeric_type_propagation/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/numeric_type_propagation/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/numeric_type_propagation/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/numeric_type_propagation/test.toml
Labels: bug, P: high, audit-report

#6479 Reduces memory footprint of collecting unifications.
  sway-core/src/semantic_analysis/ast_node/code_block.rs
  sway-core/src/semantic_analysis/ast_node/declaration/declaration.rs
  sway-core/src/semantic_analysis/namespace/lexical_scope.rs
  sway-core/src/semantic_analysis/namespace/module.rs
Labels: compiler: frontend, performance

#6480 Fix error handling in LSP to guard against empty results from the compiler.
  sway-lsp/src/core/session.rs
Labels: bug, language server

#6464 Optimize `TokenMap` updates and traversals for modified files only
  sway-lsp/benches/lsp_benchmarks/compile.rs
  sway-lsp/src/core/session.rs
  sway-lsp/src/core/token_map.rs
  sway-lsp/src/traverse/lexed_tree.rs
Labels: language server, performance

#6469 add overflow and unsafe math tests
  test/src/in_language_tests/test_programs/math_inline_tests/Forc.toml
  test/src/in_language_tests/test_programs/math_inline_tests/src/main.sw
Labels: testing

#6483 Bump to v0.63.3
  Cargo.lock
  forc-pkg/Cargo.toml
  forc-plugins/forc-client/Cargo.toml
  forc-plugins/forc-client/proxy_abi/README.md
  forc-plugins/forc-crypto/Cargo.toml
  forc-plugins/forc-debug/Cargo.toml
  forc-plugins/forc-doc/Cargo.toml
  forc-plugins/forc-fmt/Cargo.toml
  forc-plugins/forc-lsp/Cargo.toml
  forc-plugins/forc-tx/Cargo.toml
  forc-test/Cargo.toml
  forc-tracing/Cargo.toml
  forc-util/Cargo.toml
  forc/Cargo.toml
  sway-ast/Cargo.toml
  sway-core/Cargo.toml
  sway-error/Cargo.toml
  sway-ir/Cargo.toml
  sway-ir/sway-ir-macros/Cargo.toml
  sway-lsp/Cargo.toml
  sway-parse/Cargo.toml
  sway-types/Cargo.toml
  sway-utils/Cargo.toml
  swayfmt/Cargo.toml
Labels: release

#6481 ci: Benchmark with codspeed
  .github/workflows/bench-lsp.yml
  .github/workflows/benchmark.yml
  Cargo.lock
  sway-lsp/Cargo.toml
  sway-lsp/README.md
  sway-lsp/benches/bench_main.rs
  sway-lsp/benches/lsp_benchmarks/compile.rs
  sway-lsp/benches/lsp_benchmarks/requests.rs
  sway-lsp/benches/lsp_benchmarks/token_map.rs
Labels: ci, performance

#6484 Support FuelVM `wqxx` instructions in ASM blocks
  Cargo.lock
  sway-ast/src/expr/op_code.rs
  sway-core/src/asm_lang/allocated_ops.rs
  sway-core/src/asm_lang/mod.rs
  sway-core/src/asm_lang/virtual_ops.rs
  sway-error/Cargo.toml
  sway-error/src/error.rs
  sway-error/src/formatting.rs
  sway-error/src/parser_error.rs
  sway-parse/src/expr/op_code.rs
  test/src/e2e_vm_tests/test_programs/should_fail/asm_unrecognized_opcode/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/asm_unrecognized_opcode/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/asm_unrecognized_opcode/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/asm_unrecognized_opcode/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/unrecognized_opcode/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/unrecognized_opcode/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/unrecognized_opcode/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/asm_wqxx_instructions/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/asm_wqxx_instructions/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/asm_wqxx_instructions/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/asm_wqxx_instructions/test.toml
Labels: compiler, compiler: ir, compiler: parser, compiler: codegen
