Repository FuelLabs/sway, pull requests merged in 2024-03, with the labels that each got.

#5690 Add client heartbeat to shutdown LSP zombie processes
  sway-lsp/src/handlers/request.rs
  sway-lsp/src/server_state.rs
Labels: language server

#5596 Rename `predicate_id()` to `predicate_address()` and additional Predicate docs
  docs/book/src/sway-program-types/predicates.md
  sway-lib-std/src/auth.sw
  test/src/sdk-harness/test_artifacts/auth_predicate/src/main.sw
  test/src/sdk-harness/test_projects/auth/mod.rs
Labels: lib: std, The Sway Book, breaking

#5687 Add --version to forc-debug
  forc-plugins/forc-debug/src/main.rs
Labels: forc-debug

#5697 Refactor: Imports must use absolute paths
  forc-pkg/src/pkg.rs
  sway-core/src/ir_generation/const_eval.rs
  sway-core/src/language/call_path.rs
  sway-core/src/lib.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/ast_node/mod.rs
  sway-core/src/semantic_analysis/namespace/lexical_scope.rs
  sway-core/src/semantic_analysis/namespace/module.rs
  sway-core/src/semantic_analysis/namespace/namespace.rs
  sway-core/src/semantic_analysis/namespace/root.rs
  sway-core/src/semantic_analysis/program.rs
  sway-core/src/semantic_analysis/type_check_context.rs
  test/src/ir_generation/mod.rs
Labels: compiler, compiler: frontend

#5704 Enable LSP Garbage Collection test for CI
  sway-core/src/decl_engine/engine.rs
  sway-core/src/decl_engine/parsed_engine.rs
  sway-core/src/type_system/engine.rs
  sway-lsp/tests/lib.rs
Labels: ci

#5708 docs: add type conversions page
  docs/book/src/SUMMARY.md
  docs/book/src/basics/converting_types.md
  examples/Forc.lock
  examples/Forc.toml
  examples/converting_types/.gitignore
  examples/converting_types/Forc.toml
  examples/converting_types/src/byte_arrays.sw
  examples/converting_types/src/bytes.sw
  examples/converting_types/src/identity.sw
  examples/converting_types/src/main.sw
  examples/converting_types/src/strings.sw
  examples/converting_types/src/to_u16.sw
  examples/converting_types/src/to_u256.sw
  examples/converting_types/src/to_u32.sw
  examples/converting_types/src/to_u64.sw
  examples/converting_types/src/to_u8.sw
Labels: documentation

#5694 Adds unification of method application type params with impl self type params.
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/method_application.rs
  test/src/e2e_vm_tests/test_programs/should_pass/language/where_clause_methods/src/main.sw
Labels: bug, compiler: frontend

#5717 Improves error handling of method application args type checking.
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/method_application.rs
  test/src/e2e_vm_tests/test_programs/should_fail/method_type_args_variable_non_existing/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/method_type_args_variable_non_existing/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/method_type_args_variable_non_existing/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_fail/method_type_args_variable_non_existing/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/method_type_args_variable_non_existing/test.toml
Labels: bug, compiler: frontend

#5720 feat: change default script and predicate program generated at init
  forc/src/utils/defaults.rs
Labels: enhancement, forc

#5715 Advanced Storage Docs
  docs/book/src/SUMMARY.md
  docs/book/src/advanced/advanced_storage.md
  docs/book/src/advanced/index.md
  docs/book/src/blockchain-development/storage.md
  examples/Forc.lock
  examples/Forc.toml
  examples/advanced_storage_variables/Forc.toml
  examples/advanced_storage_variables/src/main.sw
  examples/basic_storage_variables/Forc.toml
  examples/basic_storage_variables/src/main.sw
  examples/nested_storage_variables/Forc.toml
  examples/nested_storage_variables/src/main.sw
  examples/storage_variables/src/main.sw
  examples/struct_storage_variables/Forc.toml
  examples/struct_storage_variables/src/main.sw
  sway-lib-std/src/storage/storage_bytes.sw
  sway-lib-std/src/storage/storage_key.sw
  sway-lib-std/src/storage/storage_string.sw
Labels: The Sway Book, documentation, dev-experience

#5730 Remove warning comments
  sway-core/src/decl_engine/engine.rs
  sway-core/src/decl_engine/parsed_engine.rs
  sway-core/src/type_system/engine.rs
Labels: code quality

#5725 Only copy sway relevant files into LSP tmp memory
  sway-lsp/src/core/sync.rs
Labels: language server

#5699 remove repetitive words
  forc-plugins/forc-doc/src/render/search.rs
  sway-core/src/asm_generation/fuel/functions.rs
  sway-core/src/transform/to_parsed_lang/convert_parse_tree.rs
  sway-core/src/type_system/unify/unify_check.rs
  sway-lib-std/src/external.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/option/src/data_structures.sw
Labels: code quality

#5738 Remove U256
  sway-lib-std/src/lib.sw
  sway-lib-std/src/u256.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/args_on_stack/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/deprecated/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/deprecated/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/assert_eq_u256_revert/.gitignore
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/assert_eq_u256_revert/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/assert_eq_u256_revert/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/assert_eq_u256_revert/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/assert_eq_u256_revert/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/assert_eq_u256_revert/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/u256_div_test/.gitignore
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/u256_div_test/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/u256_div_test/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/u256_div_test/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/u256_div_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/u256_div_test/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/u256_mul_test/.gitignore
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/u256_mul_test/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/u256_mul_test/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/u256_mul_test/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/u256_mul_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/u256_mul_test/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/u256_ops_test/.gitignore
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/u256_ops_test/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/u256_ops_test/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/u256_ops_test/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/u256_ops_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/u256_ops_test/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/u256_test/.gitignore
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/u256_test/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/u256_test/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/u256_test/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/u256_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/u256_test/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/unit_tests/stack_indexing_overflow/src/main.sw
Labels: breaking

#5238 feat: Add predicate and script templates
  .github/workflows/ci.yml
  docs/book/src/testing/testing-with-rust.md
  templates/README.md
  templates/sway-predicate-test-rs/README.md
  templates/sway-predicate-test-rs/template/Cargo.toml
  templates/sway-predicate-test-rs/template/cargo-generate.toml
  templates/sway-predicate-test-rs/template/tests/harness.rs
  templates/sway-script-test-rs/README.md
  templates/sway-script-test-rs/template/Cargo.toml
  templates/sway-script-test-rs/template/cargo-generate.toml
  templates/sway-script-test-rs/template/tests/harness.rs
Labels: forc

#5755 Enable commented tests for references and enums in `match` expressions
  test/src/e2e_vm_tests/test_programs/should_pass/language/match_expressions_enums/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/match_expressions_or/src/lib_enum.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/match_expressions_or/src/lib_tuple.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/references/referencing_local_vars_and_values/src/main.sw
Labels: testing

#5455 refactor: `forc init` generate unexpected project_name when project dir contains dot
  forc-pkg/src/manifest/mod.rs
  forc-util/src/lib.rs
  forc-util/src/restricted.rs
  forc/src/cli/commands/new.rs
  forc/src/ops/forc_init.rs
  forc/src/ops/forc_template.rs
Labels: enhancement, forc

#5754 Optimizing AST Traversal with Adaptive Iteration
  Cargo.lock
  sway-lsp/Cargo.toml
  sway-lsp/src/traverse/lexed_tree.rs
  sway-lsp/src/traverse/mod.rs
  sway-lsp/src/traverse/parsed_tree.rs
  sway-lsp/src/traverse/typed_tree.rs
Labels: language server

#5764 Enhance LSP Testing Strategy for Better Reliability
  .github/workflows/ci.yml
  sway-lsp/tests/lib.rs
Labels: ci, language server

#5771 Fix LSP initialisation bug.
  sway-lsp/src/handlers/request.rs
  sway-lsp/src/server_state.rs
  sway-lsp/tests/lib.rs
Labels: bug, language server
