Repository FuelLabs/sway, pull requests merged in 2024-04, with the labels that each got.

#5807 Fix dead links
  docs/book/src/blockchain-development/access_control.md
  docs/book/src/sway-program-types/libraries.md
  docs/reference/src/documentation/operations/reentrancy.md
Labels: bug, The Sway Book, The Sway Reference

#5801 Fixes compiler asking for unnecessary disambiguation for trait methods.
  sway-core/src/type_system/unify/unify_check.rs
  test/src/e2e_vm_tests/test_programs/should_pass/language/method_unambiguous/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/method_unambiguous/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/method_unambiguous/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/method_unambiguous/test.toml
Labels: bug, compiler: frontend

#5815 From<u8> for u16 implementation
  sway-lib-std/src/primitive_conversions/u16.sw
Labels: enhancement, lib: std

#5819 fix: make sure to check std is taken from sway-lib-std folder
  forc-pkg/src/manifest/mod.rs
Labels: bug, forc, lib: std, P: critical

#5799 Fixes ignored where clause.
  sway-core/src/decl_engine/engine.rs
  sway-core/src/decl_engine/ref.rs
  sway-core/src/engine_threading.rs
  sway-core/src/ir_generation/function.rs
  sway-core/src/language/call_path.rs
  sway-core/src/language/parsed/declaration/function.rs
  sway-core/src/language/parsed/declaration/trait.rs
  sway-core/src/language/parsed/expression/mod.rs
  sway-core/src/language/ty/ast_node.rs
  sway-core/src/language/ty/code_block.rs
  sway-core/src/language/ty/declaration/abi.rs
  sway-core/src/language/ty/declaration/constant.rs
  sway-core/src/language/ty/declaration/declaration.rs
  sway-core/src/language/ty/declaration/enum.rs
  sway-core/src/language/ty/declaration/function.rs
  sway-core/src/language/ty/declaration/impl_trait.rs
  sway-core/src/language/ty/declaration/storage.rs
  sway-core/src/language/ty/declaration/struct.rs
  sway-core/src/language/ty/declaration/trait.rs
  sway-core/src/language/ty/declaration/trait_fn.rs
  sway-core/src/language/ty/declaration/trait_type.rs
  sway-core/src/language/ty/declaration/type_alias.rs
  sway-core/src/language/ty/declaration/variable.rs
  sway-core/src/language/ty/expression/asm.rs
  sway-core/src/language/ty/expression/expression.rs
  sway-core/src/language/ty/expression/expression_variant.rs
  sway-core/src/language/ty/expression/intrinsic_function.rs
  sway-core/src/language/ty/expression/reassignment.rs
  sway-core/src/language/ty/expression/storage.rs
  sway-core/src/language/ty/expression/struct_exp_field.rs
  sway-core/src/semantic_analysis/ast_node/declaration/impl_trait.rs
  sway-core/src/semantic_analysis/ast_node/expression/intrinsic_function.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/struct_instantiation.rs
  sway-core/src/semantic_analysis/namespace/trait_map.rs
  sway-core/src/type_system/ast_elements/binding.rs
  sway-core/src/type_system/ast_elements/trait_constraint.rs
  sway-core/src/type_system/ast_elements/type_argument.rs
  sway-core/src/type_system/ast_elements/type_parameter.rs
  sway-core/src/type_system/engine.rs
  sway-core/src/type_system/id.rs
  sway-core/src/type_system/info.rs
  sway-core/src/type_system/mod.rs
  sway-core/src/type_system/substitute/subst_list.rs
  sway-core/src/type_system/substitute/subst_map.rs
  sway-core/src/type_system/unify/unifier.rs
  sway-core/src/type_system/unify/unify_check.rs
  test/src/e2e_vm_tests/test_programs/should_pass/language/where_clause_generic_tuple/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/where_clause_generic_tuple/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/where_clause_generic_tuple/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/language/where_clause_generic_tuple/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/where_clause_generic_tuple/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/where_clause_methods/src/main.sw
Labels: bug, compiler: frontend

#5816 From<u8, u16> for u32
  sway-lib-std/src/primitive_conversions/u32.sw
Labels: enhancement, lib: std

#5822 chore: bump to v0.52.1
  Cargo.lock
  docs/reference/src/documentation/introduction/installation/cargo.md
  docs/reference/src/documentation/introduction/installation/index.md
  docs/reference/src/documentation/introduction/installation/source.md
  docs/reference/src/index.md
  forc-pkg/Cargo.toml
  forc-plugins/forc-client/Cargo.toml
  forc-plugins/forc-crypto/Cargo.toml
  forc-plugins/forc-debug/Cargo.toml
  forc-plugins/forc-doc/Cargo.toml
  forc-plugins/forc-fmt/Cargo.toml
  forc-plugins/forc-lsp/Cargo.toml
  forc-plugins/forc-tx/Cargo.toml
  forc-test/Cargo.toml
  forc-tracing/Cargo.toml
  forc-util/Cargo.toml
  forc/Cargo.toml
  sway-ast/Cargo.toml
  sway-core/Cargo.toml
  sway-error/Cargo.toml
  sway-ir/Cargo.toml
  sway-ir/sway-ir-macros/Cargo.toml
  sway-lsp/Cargo.toml
  sway-lsp/tests/fixtures/tokens/storage/Forc.toml
  sway-parse/Cargo.toml
  sway-types/Cargo.toml
  sway-utils/Cargo.toml
  swayfmt/Cargo.toml
Labels: release

#5817 From<u8, u16, u32> for u64 implementations
  sway-lib-std/src/primitive_conversions/u64.sw
Labels: enhancement, lib: std

#5810 Refactor trait map and module symbol resolution code to allow usage for parsed declarations
  sway-core/src/ir_generation/const_eval.rs
  sway-core/src/language/parsed/declaration.rs
  sway-core/src/language/parsed/declaration/abi.rs
  sway-core/src/language/parsed/declaration/constant.rs
  sway-core/src/language/parsed/declaration/enum.rs
  sway-core/src/language/parsed/declaration/function.rs
  sway-core/src/language/parsed/declaration/impl_trait.rs
  sway-core/src/language/parsed/declaration/storage.rs
  sway-core/src/language/parsed/declaration/struct.rs
  sway-core/src/language/parsed/declaration/trait.rs
  sway-core/src/language/parsed/declaration/type_alias.rs
  sway-core/src/language/parsed/declaration/variable.rs
  sway-core/src/semantic_analysis/ast_node/declaration/declaration.rs
  sway-core/src/semantic_analysis/ast_node/declaration/impl_trait.rs
  sway-core/src/semantic_analysis/ast_node/declaration/supertrait.rs
  sway-core/src/semantic_analysis/ast_node/expression/match_expression/typed/typed_scrutinee.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/method_application.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/struct_instantiation.rs
  sway-core/src/semantic_analysis/coins_analysis.rs
  sway-core/src/semantic_analysis/namespace/lexical_scope.rs
  sway-core/src/semantic_analysis/namespace/mod.rs
  sway-core/src/semantic_analysis/namespace/module.rs
  sway-core/src/semantic_analysis/namespace/namespace.rs
  sway-core/src/semantic_analysis/namespace/trait_map.rs
  sway-core/src/semantic_analysis/type_check_context.rs
  sway-core/src/type_system/ast_elements/trait_constraint.rs
  sway-core/src/type_system/ast_elements/type_parameter.rs
  sway-lsp/src/capabilities/completion.rs
Labels: compiler, compiler: frontend, compiler: collection

#5829 Add `ZERO_U256` constant
  sway-lib-std/src/constants.sw
Labels: enhancement, lib: std

#5808 Expand Native Asset Docs
  docs/book/spell-check-custom-words.txt
  docs/book/src/SUMMARY.md
  docs/book/src/blockchain-development/native_assets.md
  docs/book/src/examples/liquidity_pool.md
  examples/native_asset/src/main.sw
Labels: The Sway Book

#5824 Fix and improve errors when the entry fns cannot be generated
  sway-core/src/ir_generation/const_eval.rs
  sway-core/src/semantic_analysis/ast_node/declaration/auto_impl.rs
  sway-core/src/semantic_analysis/module.rs
  sway-core/src/semantic_analysis/type_check_context.rs
  sway-core/src/type_system/engine.rs
  sway-error/src/error.rs
  sway-ir/src/parser.rs
  sway-lib-core/generate.sh
  sway-lib-core/src/codec.sw
  sway-parse/src/attribute.rs
  sway-parse/src/parse.rs
  swayfmt/src/utils/map/byte_span.rs
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/array_of_structs_caller/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_contract_with_type_aliases/src/main.sw
Labels: breaking

#5841 Fixes compiler performance in mega_example.
  sway-core/src/decl_engine/mapping.rs
  sway-core/src/decl_engine/ref.rs
  sway-core/src/language/ty/expression/expression_variant.rs
  test/src/e2e_vm_tests/test_programs/should_pass/language/mega_example/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/mega_example/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/mega_example/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/mega_example/test.toml
Labels: compiler: frontend, performance

#5832 Fixes FQP root type not found when inside a library.
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/method_application.rs
  test/src/e2e_vm_tests/test_programs/should_pass/language/fqp_in_lib/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/fqp_in_lib/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/fqp_in_lib/src/lib.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/fqp_in_lib/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/fqp_in_lib/test.toml
Labels: bug, compiler: frontend

#5759 chore:bump sdk to v0.56, fuel-core to 0.23.0, fuel-vm to 0.47.1
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  forc-plugins/forc-client/src/op/deploy.rs
  forc-plugins/forc-client/src/op/run/encode.rs
  forc-plugins/forc-client/src/op/run/mod.rs
  forc-plugins/forc-client/src/op/submit.rs
  forc-plugins/forc-client/src/util/gas.rs
  forc-plugins/forc-debug/docs/walkthrough.md
  forc-plugins/forc-debug/examples/example_tx.json
  forc-plugins/forc-debug/src/server/handlers/handle_launch.rs
  forc-plugins/forc-tx/src/lib.rs
  forc-test/src/execute.rs
  forc-test/src/lib.rs
  test/src/e2e_vm_tests/harness.rs
  test/src/e2e_vm_tests/test_programs/should_pass/language/raw_ptr/raw_ptr_ret/test.toml
Labels: enhancement, dependencies, breaking

#5813 Fix critical GC <> LSP bug and enable dynamic GC configuration.
  .github/workflows/ci.yml
  Cargo.lock
  sway-core/src/build_config.rs
  sway-core/src/lib.rs
  sway-core/src/query_engine/mod.rs
  sway-core/src/semantic_analysis/module.rs
  sway-lsp/benches/lsp_benchmarks/compile.rs
  sway-lsp/benches/lsp_benchmarks/mod.rs
  sway-lsp/src/config.rs
  sway-lsp/src/core/session.rs
  sway-lsp/src/handlers/notification.rs
  sway-lsp/src/server_state.rs
  sway-lsp/tests/fixtures/garbage_collection/storage_contract/.gitignore
  sway-lsp/tests/fixtures/garbage_collection/storage_contract/Forc.toml
  sway-lsp/tests/fixtures/garbage_collection/storage_contract/src/main.sw
  sway-lsp/tests/integration/lsp.rs
  sway-lsp/tests/lib.rs
  sway-lsp/tests/utils/Cargo.toml
  sway-lsp/tests/utils/src/lib.rs
Labels: bug, language server, compiler: frontend

#5831 chore: bump to v0.53.0
  Cargo.lock
  docs/reference/src/documentation/introduction/installation/cargo.md
  docs/reference/src/documentation/introduction/installation/index.md
  docs/reference/src/documentation/introduction/installation/source.md
  docs/reference/src/index.md
  forc-pkg/Cargo.toml
  forc-plugins/forc-client/Cargo.toml
  forc-plugins/forc-crypto/Cargo.toml
  forc-plugins/forc-debug/Cargo.toml
  forc-plugins/forc-doc/Cargo.toml
  forc-plugins/forc-fmt/Cargo.toml
  forc-plugins/forc-lsp/Cargo.toml
  forc-plugins/forc-tx/Cargo.toml
  forc-test/Cargo.toml
  forc-tracing/Cargo.toml
  forc-util/Cargo.toml
  forc/Cargo.toml
  sway-ast/Cargo.toml
  sway-core/Cargo.toml
  sway-error/Cargo.toml
  sway-ir/Cargo.toml
  sway-ir/sway-ir-macros/Cargo.toml
  sway-lsp/Cargo.toml
  sway-lsp/tests/fixtures/tokens/storage/Forc.toml
  sway-parse/Cargo.toml
  sway-types/Cargo.toml
  sway-utils/Cargo.toml
  swayfmt/Cargo.toml
Labels: release

#5431 Add expect to option and result
  sway-lib-std/src/option.sw
  sway-lib-std/src/result.sw
  test/src/sdk-harness/Forc.lock
  test/src/sdk-harness/Forc.toml
  test/src/sdk-harness/test_projects/harness.rs
  test/src/sdk-harness/test_projects/result_option_expect/.gitignore
  test/src/sdk-harness/test_projects/result_option_expect/Forc.lock
  test/src/sdk-harness/test_projects/result_option_expect/Forc.toml
  test/src/sdk-harness/test_projects/result_option_expect/mod.rs
  test/src/sdk-harness/test_projects/result_option_expect/src/main.sw
Labels: enhancement, lib: std

#5726 Improves DCA warnings after divergent expressions.
  sway-core/src/control_flow_analysis/dead_code_analysis.rs
  sway-core/src/control_flow_analysis/flow_graph/mod.rs
  sway-core/src/type_system/info.rs
  sway-types/src/span.rs
  test/src/e2e_vm_tests/mod.rs
  test/src/e2e_vm_tests/test_programs/should_fail/return_in_strange_positions/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/break_in_strange_positions/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/continue_in_strange_positions/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/diverging_exprs/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/implicit_casting/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/return_in_strange_positions/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/return_in_strange_positions/test.toml
Labels: compiler: frontend, DCA

#5844 chore: bump fuel-core to 0.24.2, fuel-vm to 0.48.0, sdk to 0.57.0
  .github/workflows/ci.yml
  .github/workflows/local-testnode/chain_config.json
  .github/workflows/local-testnode/metadata.json
  .github/workflows/local-testnode/state_config.json
  Cargo.lock
  Cargo.toml
  forc-plugins/forc-client/Cargo.toml
  forc-plugins/forc-client/src/op/deploy.rs
  forc-plugins/forc-client/src/util/gas.rs
  forc-plugins/forc-client/src/util/tx.rs
  forc-plugins/forc-debug/docs/walkthrough.md
  forc-plugins/forc-debug/examples/example_tx.json
  forc-plugins/forc-tx/Cargo.toml
  forc-plugins/forc-tx/src/lib.rs
  forc-test/Cargo.toml
  forc-test/src/execute.rs
  forc-test/src/lib.rs
  test/src/e2e_vm_tests/harness.rs
  test/src/e2e_vm_tests/test_programs/should_pass/language/raw_ptr/raw_ptr_ret/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_basic_storage/src/main.sw
Labels: dependencies, breaking

#5847 Fix and improve `Unimplemented` compile errors
  sway-ast/src/pattern.rs
  sway-core/src/semantic_analysis/ast_node/declaration/function.rs
  sway-core/src/semantic_analysis/ast_node/declaration/impl_trait.rs
  sway-core/src/semantic_analysis/ast_node/declaration/supertrait.rs
  sway-core/src/semantic_analysis/ast_node/expression/match_expression/typed/typed_scrutinee.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/transform/to_parsed_lang/convert_parse_tree.rs
  sway-core/src/type_system/ast_elements/trait_constraint.rs
  sway-core/src/type_system/info.rs
  sway-error/src/convert_parse_tree_error.rs
  sway-error/src/error.rs
  test/src/e2e_vm_tests/test_programs/should_fail/generic_traits/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/generic_traits/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/impl_invalid_self_type/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/impl_invalid_self_type/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/impl_invalid_self_type/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/impl_invalid_self_type/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/match_expressions_non_literal_constant/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/match_expressions_not_implemented_for_aliased_type/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/match_expressions_not_implemented_for_aliased_type/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/match_expressions_not_implemented_for_aliased_type/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/match_expressions_not_implemented_for_aliased_type/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/match_expressions_ref_mut_not_implemented/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/match_expressions_ref_mut_not_implemented/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/match_expressions_ref_mut_not_implemented/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/match_expressions_ref_mut_not_implemented/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/module_path_is_not_expression/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/module_path_is_not_expression/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/module_path_is_not_expression/src/lib.sw
  test/src/e2e_vm_tests/test_programs/should_fail/module_path_is_not_expression/src/lib/submodule.sw
  test/src/e2e_vm_tests/test_programs/should_fail/module_path_is_not_expression/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/module_path_is_not_expression/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/nested_functions/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/ref_var_pattern/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/ref_var_pattern/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_fail/ref_var_pattern/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/ref_var_pattern/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/traits_with_call_paths/test.toml
Labels: bug, compiler, compiler: frontend, compiler: ui

#5858 Update test SDK Harness to fuel-core v0.24.2 and Fuels v0.57.0
  sway-lib-std/src/inputs.sw
  sway-lib-std/src/tx.sw
  test/src/sdk-harness/Cargo.lock
  test/src/sdk-harness/Cargo.toml
  test/src/sdk-harness/test_artifacts/auth_predicate/src/main.sw
  test/src/sdk-harness/test_artifacts/call_frames_test_abi/src/main.sw
  test/src/sdk-harness/test_artifacts/context_caller_contract/src/main.sw
  test/src/sdk-harness/test_artifacts/methods_contract/src/main.sw
  test/src/sdk-harness/test_artifacts/tx_contract/src/main.sw
  test/src/sdk-harness/test_artifacts/tx_output_predicate/src/main.sw
  test/src/sdk-harness/test_projects/abi_impl_methods_callable/Forc.toml
  test/src/sdk-harness/test_projects/abi_impl_methods_callable/src/main.sw
  test/src/sdk-harness/test_projects/asset_ops/mod.rs
  test/src/sdk-harness/test_projects/asset_ops/src/main.sw
  test/src/sdk-harness/test_projects/auth/mod.rs
  test/src/sdk-harness/test_projects/configurables_in_contract/mod.rs
  test/src/sdk-harness/test_projects/configurables_in_script/mod.rs
  test/src/sdk-harness/test_projects/context/mod.rs
  test/src/sdk-harness/test_projects/ec_recover_and_match_predicate/mod.rs
  test/src/sdk-harness/test_projects/evm_ec_recover/mod.rs
  test/src/sdk-harness/test_projects/generics_in_abi/src/main.sw
  test/src/sdk-harness/test_projects/harness.rs
  test/src/sdk-harness/test_projects/hashing/src/main.sw
  test/src/sdk-harness/test_projects/low_level_call/mod.rs
  test/src/sdk-harness/test_projects/low_level_call/src/main.sw
  test/src/sdk-harness/test_projects/low_level_call_bytes/mod.rs
  test/src/sdk-harness/test_projects/low_level_call_bytes/src/main.sw
  test/src/sdk-harness/test_projects/option_in_abi/src/main.sw
  test/src/sdk-harness/test_projects/parsing_logs/mod.rs
  test/src/sdk-harness/test_projects/predicate_data_simple/mod.rs
  test/src/sdk-harness/test_projects/predicate_data_struct/mod.rs
  test/src/sdk-harness/test_projects/private_struct_fields_in_storage_and_abi/mod.rs
  test/src/sdk-harness/test_projects/private_struct_fields_in_storage_and_abi/src/lib.sw
  test/src/sdk-harness/test_projects/private_struct_fields_in_storage_and_abi/src/main.sw
  test/src/sdk-harness/test_projects/registers/src/main.sw
  test/src/sdk-harness/test_projects/result_in_abi/src/main.sw
  test/src/sdk-harness/test_projects/result_option_expect/mod.rs
  test/src/sdk-harness/test_projects/run_external_proxy/mod.rs
  test/src/sdk-harness/test_projects/run_external_proxy/src/main.sw
  test/src/sdk-harness/test_projects/run_external_target/src/main.sw
  test/src/sdk-harness/test_projects/script_data/mod.rs
  test/src/sdk-harness/test_projects/storage/src/main.sw
  test/src/sdk-harness/test_projects/storage_access/mod.rs
  test/src/sdk-harness/test_projects/storage_access/src/main.sw
  test/src/sdk-harness/test_projects/storage_init/src/main.sw
  test/src/sdk-harness/test_projects/storage_map/src/main.sw
  test/src/sdk-harness/test_projects/storage_map/try_insert.rs
  test/src/sdk-harness/test_projects/storage_map_nested/src/main.sw
  test/src/sdk-harness/test_projects/storage_namespace/src/main.sw
  test/src/sdk-harness/test_projects/storage_vec_to_vec/src/main.sw
  test/src/sdk-harness/test_projects/superabi_supertrait/src/main.sw
  test/src/sdk-harness/test_projects/tx_fields/mod.rs
  test/src/sdk-harness/test_projects/type_aliases/src/main.sw
  test/src/sdk-harness/test_projects/vec_in_abi/src/main.sw
Labels: lib: std, testing, breaking

#5861 Improves debug build times.
  sway-core/src/lib.rs
Labels: compiler: ir, performance

#5871 Use `ModuleId` instead of `SourceId` as the metrics map key
  sway-lsp/src/core/session.rs
  sway-lsp/src/error.rs
  sway-lsp/src/handlers/request.rs
  sway-lsp/src/server_state.rs
  sway-lsp/tests/lib.rs
  sway-types/src/source_engine.rs
Labels: bug, language server, P: critical

#5872 chore: bump to v0.55.0
  Cargo.lock
  docs/reference/src/documentation/introduction/installation/cargo.md
  docs/reference/src/documentation/introduction/installation/index.md
  docs/reference/src/documentation/introduction/installation/source.md
  docs/reference/src/index.md
  forc-pkg/Cargo.toml
  forc-plugins/forc-client/Cargo.toml
  forc-plugins/forc-crypto/Cargo.toml
  forc-plugins/forc-debug/Cargo.toml
  forc-plugins/forc-doc/Cargo.toml
  forc-plugins/forc-fmt/Cargo.toml
  forc-plugins/forc-lsp/Cargo.toml
  forc-plugins/forc-tx/Cargo.toml
  forc-test/Cargo.toml
  forc-tracing/Cargo.toml
  forc-util/Cargo.toml
  forc/Cargo.toml
  sway-ast/Cargo.toml
  sway-core/Cargo.toml
  sway-error/Cargo.toml
  sway-ir/Cargo.toml
  sway-ir/sway-ir-macros/Cargo.toml
  sway-lsp/Cargo.toml
  sway-lsp/tests/fixtures/tokens/storage/Forc.toml
  sway-parse/Cargo.toml
  sway-types/Cargo.toml
  sway-utils/Cargo.toml
  swayfmt/Cargo.toml
Labels: release

#5867 Remove `contract_id()` in favor of `ContractId::this()`
  examples/liquidity_pool/src/main.sw
  sway-lib-std/src/asset.sw
  sway-lib-std/src/call_frames.sw
  sway-lib-std/src/context.sw
  sway-lib-std/src/identity.sw
  test/src/e2e_vm_tests/test_programs/should_pass/static_analysis/cei_pattern_violation_more_complex_logic/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/context_testing_contract/src/main.sw
  test/src/sdk-harness/test_artifacts/call_frames_test_abi/src/main.sw
  test/src/sdk-harness/test_artifacts/context_caller_contract/src/main.sw
  test/src/sdk-harness/test_projects/call_frames/mod.rs
  test/src/sdk-harness/test_projects/call_frames/src/main.sw
Labels: lib: std, breaking

#5877 Update docs on how to disable LSP
  docs/book/src/lsp/troubleshooting.md
Labels: language server, documentation

#5869 feat!: add `call_with_function_selector` version for new encoding
  Cargo.lock
  sway-lib-std/src/low_level_call.sw
  test/src/sdk-harness/Forc.lock
  test/src/sdk-harness/Forc.toml
  test/src/sdk-harness/test_projects/harness.rs
  test/src/sdk-harness/test_projects/low_level_call/Forc.lock
  test/src/sdk-harness/test_projects/low_level_call/mod.rs
  test/src/sdk-harness/test_projects/low_level_call/src/main.sw
  test/src/sdk-harness/test_projects/low_level_call_bytes/Forc.lock
  test/src/sdk-harness/test_projects/low_level_call_bytes/Forc.toml
  test/src/sdk-harness/test_projects/low_level_call_bytes/mod.rs
  test/src/sdk-harness/test_projects/low_level_call_bytes/src/main.sw
Labels: lib: std, breaking

#5823 Fixes type inference on inlined method applications.
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/method_application.rs
  sway-core/src/semantic_analysis/namespace/trait_map.rs
  sway-core/src/type_system/id.rs
  sway-error/src/error.rs
  sway-error/src/handler.rs
  test/src/e2e_vm_tests/test_programs/should_fail/struct_field_privacy_storage/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/trait_method_and_generic_trait_impl/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/trait_method_and_generic_trait_impl/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/method_indirect_inference/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/method_indirect_inference/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/method_indirect_inference/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/method_indirect_inference/test.toml
Labels: bug, compiler: frontend

#5910 Adds test that proves unexpected error no longer occcurs.
  test/src/e2e_vm_tests/test_programs/should_pass/language/generic_struct_instantiation/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/generic_struct_instantiation/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/generic_struct_instantiation/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/generic_struct_instantiation/test.toml
Labels: bug, compiler: frontend

#5825 Allow conversions between native u types and U128
  sway-lib-std/src/u128.sw
Labels: enhancement, lib: std

#5919 Bump to v0.56.0
  Cargo.lock
  Cargo.toml
  docs/reference/src/code/Forc.lock
  docs/reference/src/code/language/traits/associated-consts/Forc.toml
  docs/reference/src/documentation/introduction/installation/cargo.md
  docs/reference/src/documentation/introduction/installation/index.md
  docs/reference/src/documentation/introduction/installation/source.md
  docs/reference/src/index.md
  forc-pkg/Cargo.toml
  forc-plugins/forc-client/Cargo.toml
  forc-plugins/forc-crypto/Cargo.toml
  forc-plugins/forc-debug/Cargo.toml
  forc-plugins/forc-doc/Cargo.toml
  forc-plugins/forc-fmt/Cargo.toml
  forc-plugins/forc-lsp/Cargo.toml
  forc-plugins/forc-tx/Cargo.toml
  forc-test/Cargo.toml
  forc-tracing/Cargo.toml
  forc-util/Cargo.toml
  forc/Cargo.toml
  sway-ast/Cargo.toml
  sway-core/Cargo.toml
  sway-error/Cargo.toml
  sway-ir/Cargo.toml
  sway-ir/sway-ir-macros/Cargo.toml
  sway-lsp/Cargo.toml
  sway-parse/Cargo.toml
  sway-types/Cargo.toml
  sway-utils/Cargo.toml
  swayfmt/Cargo.toml
Labels: release

#5930 ci: add a job for checking fuel-core versions between sdk-harness and test suite
  .github/workflows/ci.yml
  .github/workflows/scripts/check-sdk-harness-version.sh
Labels: enhancement, ci

#5889 Add conversion methods for u256,b256 from tuple of u64s
  sway-lib-std/src/primitive_conversions/b256.sw
  sway-lib-std/src/primitive_conversions/u256.sw
Labels: enhancement, lib: std

#5933 chore: use rust-sdk v0.58.0
  Cargo.lock
  Cargo.toml
  forc-plugins/forc-client/src/op/run/encode.rs
Labels: dependencies

#5934 chore: update ci_checks script to represent current ci better
  ci_checks.sh
Labels: ci, code quality

#5887 Implement From< U128 > for u256, b256
  sway-lib-std/src/lib.sw
  sway-lib-std/src/primitive_conversions/b256.sw
  sway-lib-std/src/primitive_conversions/u256.sw
  sway-lib-std/src/u128.sw
  test/src/e2e_vm_tests/reduced_std_libs/sway-lib-std-conversions/reduced_lib.config
  test/src/e2e_vm_tests/reduced_std_libs/sway-lib-std-conversions/src/lib.sw
  test/src/e2e_vm_tests/reduced_std_libs/sway-lib-std-conversions/src/prelude.sw
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/issue_1512_repro/src/main.sw
Labels: enhancement, lib: std
