Repository FuelLabs/sway, pull requests merged in 2024-10, with the labels that each got.

#6598 fix: Capture more declarations for sway autocomplete
  sway-lsp/src/capabilities/code_actions/diagnostic/auto_import.rs
Labels: language server

#6609 Code suggestions for blob deployments for scripts and predicates
  forc-plugins/forc-client/src/op/deploy.rs
Labels: forc-client

#6607 feat: add blob deployments for scripts and predicates
  Cargo.lock
  Cargo.toml
  docs/book/src/forc/plugins/forc_client/index.md
  forc-plugins/forc-client/src/op/deploy.rs
  forc-plugins/forc-client/src/op/mod.rs
  forc-plugins/forc-client/test/data/deployed_predicate/.gitignore
  forc-plugins/forc-client/test/data/deployed_predicate/Forc.lock
  forc-plugins/forc-client/test/data/deployed_predicate/Forc.toml
  forc-plugins/forc-client/test/data/deployed_predicate/deployed_predicate-abi.json
  forc-plugins/forc-client/test/data/deployed_predicate/src/main.sw
  forc-plugins/forc-client/test/data/deployed_script/.gitignore
  forc-plugins/forc-client/test/data/deployed_script/Forc.toml
  forc-plugins/forc-client/test/data/deployed_script/deployed_script-abi.json
  forc-plugins/forc-client/test/data/deployed_script/src/main.sw
  forc-plugins/forc-client/tests/deploy.rs
  forc-plugins/forc-tx/Cargo.toml
  forc-util/Cargo.toml
  test/src/e2e_vm_tests/harness.rs
  test/src/sdk-harness/Cargo.lock
  test/src/sdk-harness/Cargo.toml
Labels: enhancement, P: critical, forc-client, forc-deploy

#6610 chore: bump to 0.65.0
  Cargo.lock
  Cargo.toml
Labels: release

#6611 feat: generate a loader abi of loaders generated for predicates and scripts
  Cargo.lock
  forc-plugins/forc-client/Cargo.toml
  forc-plugins/forc-client/src/op/deploy.rs
  forc-plugins/forc-client/test/data/deployed_script/deployed_script-loader-abi.json
  forc-plugins/forc-client/test/data/deployed_script/deployed_script.bin
  forc-plugins/forc-client/tests/deploy.rs
Labels: enhancement, forc, P: critical, forc-deploy

#6612 chore: bump to v0.65.1
  Cargo.lock
  Cargo.toml
Labels: release

#6616 fix: pin forc-deploy to use 100kb blob size by default
  docs/book/src/forc/plugins/forc_client/index.md
  forc-plugins/forc-client/src/op/deploy.rs
Labels: forc, P: critical, forc-deploy

#6617 chore: bump to v0.65.2
  Cargo.lock
  Cargo.toml
Labels: release

#6634 remove beta and devnet refs
  docs/book/src/forc/plugins/forc_client/index.md
  forc-plugins/forc-client/src/cmd/deploy.rs
  forc-plugins/forc-client/src/constants.rs
  forc-plugins/forc-client/src/lib.rs
  forc-plugins/forc-client/src/util/node_url.rs
  forc-plugins/forc-client/src/util/target.rs
Labels: forc-client

#6621 add new target to forc
  docs/book/src/forc/plugins/forc_client/index.md
  forc-plugins/forc-client/src/cmd/deploy.rs
  forc-plugins/forc-client/src/constants.rs
  forc-plugins/forc-client/src/lib.rs
  forc-plugins/forc-client/src/op/deploy.rs
  forc-plugins/forc-client/src/util/node_url.rs
  forc-plugins/forc-client/src/util/target.rs
  forc-plugins/forc-client/src/util/tx.rs
  forc-plugins/forc-client/tests/deploy.rs
Labels: enhancement, forc-client

#6630 feat: bump fuel-core to v0.40.0 and sdk to v0.66.9 + show checksum addresses in forc-deploy
  Cargo.lock
  Cargo.toml
  forc-plugins/forc-client/src/util/target.rs
  forc-plugins/forc-client/src/util/tx.rs
  test/src/sdk-harness/Cargo.lock
  test/src/sdk-harness/Cargo.toml
Labels: enhancement, dependencies

#6637 chore: bump to v0.66.0
  Cargo.lock
  Cargo.toml
Labels: release

#6639 chore: bump to v0.66.1
  Cargo.lock
  Cargo.toml
Labels: release

#6632 style: update troubleshooting.md
  docs/book/src/lsp/troubleshooting.md
Labels: documentation

#6650 Properly treat `FuelVMInstruction`s in the `memcpyopt`
  sway-ir/src/optimize/memcpyopt.rs
  sway-ir/tests/memcpyopt/no_memcpyopt_wide_binary_operator.ir
  sway-ir/tests/memcpyopt/no_memcpyopt_wide_unary_operator.ir
Labels: bug, compiler, compiler: ir

#6649 caller_addresses: use input_message_recipient
  sway-lib-std/src/auth.sw
Labels: bug, lib: std

#6647 Fix u128 log rounding errors, and overflow reverts
  sway-lib-std/src/u128.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/u128_log_test/src/main.sw
  test/src/in_language_tests/test_programs/u128_inline_tests/src/main.sw
Labels: bug, lib: std

#6643 chore: bump to v0.66.2
  Cargo.lock
  Cargo.toml
  templates/sway-predicate-test-rs/template/Cargo.toml
  templates/sway-script-test-rs/template/Cargo.toml
  templates/sway-test-rs/template/Cargo.toml
Labels: release

#6615 Refactor monomorphization/type resolving code out of `TypeCheckContext`.
  sway-core/src/decl_engine/id.rs
  sway-core/src/decl_engine/ref.rs
  sway-core/src/language/ty/ast_node.rs
  sway-core/src/language/ty/code_block.rs
  sway-core/src/language/ty/declaration/configurable.rs
  sway-core/src/language/ty/declaration/constant.rs
  sway-core/src/language/ty/declaration/declaration.rs
  sway-core/src/language/ty/declaration/enum.rs
  sway-core/src/language/ty/declaration/function.rs
  sway-core/src/language/ty/declaration/impl_trait.rs
  sway-core/src/language/ty/declaration/struct.rs
  sway-core/src/language/ty/declaration/trait.rs
  sway-core/src/language/ty/declaration/trait_fn.rs
  sway-core/src/language/ty/declaration/trait_type.rs
  sway-core/src/language/ty/declaration/type_alias.rs
  sway-core/src/language/ty/declaration/variable.rs
  sway-core/src/language/ty/expression/asm.rs
  sway-core/src/language/ty/expression/expression.rs
  sway-core/src/language/ty/expression/expression_variant.rs
  sway-core/src/language/ty/expression/intrinsic_function.rs
  sway-core/src/language/ty/expression/reassignment.rs
  sway-core/src/language/ty/expression/struct_exp_field.rs
  sway-core/src/semantic_analysis.rs
  sway-core/src/semantic_analysis/ast_node/declaration/configurable.rs
  sway-core/src/semantic_analysis/ast_node/declaration/constant.rs
  sway-core/src/semantic_analysis/ast_node/declaration/declaration.rs
  sway-core/src/semantic_analysis/ast_node/declaration/enum.rs
  sway-core/src/semantic_analysis/ast_node/declaration/function.rs
  sway-core/src/semantic_analysis/ast_node/declaration/function/function_parameter.rs
  sway-core/src/semantic_analysis/ast_node/declaration/impl_trait.rs
  sway-core/src/semantic_analysis/ast_node/declaration/struct.rs
  sway-core/src/semantic_analysis/ast_node/declaration/supertrait.rs
  sway-core/src/semantic_analysis/ast_node/declaration/trait.rs
  sway-core/src/semantic_analysis/ast_node/declaration/trait_fn.rs
  sway-core/src/semantic_analysis/ast_node/declaration/trait_type.rs
  sway-core/src/semantic_analysis/ast_node/declaration/variable.rs
  sway-core/src/semantic_analysis/ast_node/expression/intrinsic_function.rs
  sway-core/src/semantic_analysis/ast_node/expression/match_expression/typed/typed_scrutinee.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/method_application.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/struct_instantiation.rs
  sway-core/src/semantic_analysis/namespace/lexical_scope.rs
  sway-core/src/semantic_analysis/namespace/module.rs
  sway-core/src/semantic_analysis/namespace/root.rs
  sway-core/src/semantic_analysis/namespace/trait_map.rs
  sway-core/src/semantic_analysis/symbol_resolve_context.rs
  sway-core/src/semantic_analysis/type_check_context.rs
  sway-core/src/semantic_analysis/type_resolve.rs
  sway-core/src/type_system/ast_elements/binding.rs
  sway-core/src/type_system/ast_elements/trait_constraint.rs
  sway-core/src/type_system/ast_elements/type_argument.rs
  sway-core/src/type_system/ast_elements/type_parameter.rs
  sway-core/src/type_system/id.rs
  sway-core/src/type_system/mod.rs
  sway-core/src/type_system/monomorphization.rs
  sway-core/src/type_system/substitute/subst_list.rs
  sway-core/src/type_system/substitute/subst_types.rs
Labels: compiler, compiler: frontend

#6656 ci: move to buildjet
  .github/workflows/ci.yml
Labels: enhancement, ci

#6662 Fixes ContractCaller type propagation.
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/type_system/info.rs
  test/src/e2e_vm_tests/test_programs/should_pass/language/abi_cast_nested_method/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/abi_cast_nested_method/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/abi_cast_nested_method/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/abi_cast_nested_method/test.toml
Labels: bug, compiler: frontend

#6658 Fixes issue with nested method type args.
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/method_application.rs
  sway-core/src/type_system/info.rs
  sway-core/src/type_system/substitute/subst_map.rs
  test/src/e2e_vm_tests/test_programs/should_pass/language/method_nested_type_args/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/method_nested_type_args/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/method_nested_type_args/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/method_nested_type_args/test.toml
Labels: bug, compiler: frontend

#6633 Add `TypeInfo::UntypedEnum` and `TypeInfo::UntypedStruct`.
  sway-core/src/abi_generation/abi_str.rs
  sway-core/src/abi_generation/evm_abi.rs
  sway-core/src/decl_engine/mod.rs
  sway-core/src/decl_engine/parsed_engine.rs
  sway-core/src/decl_engine/parsed_id.rs
  sway-core/src/ir_generation/convert.rs
  sway-core/src/semantic_analysis/namespace/trait_map.rs
  sway-core/src/semantic_analysis/node_dependencies.rs
  sway-core/src/semantic_analysis/type_check_context.rs
  sway-core/src/type_system/engine.rs
  sway-core/src/type_system/id.rs
  sway-core/src/type_system/info.rs
  sway-core/src/type_system/substitute/subst_map.rs
Labels: compiler: frontend

#6661 forc-crypto: vanity address generation
  Cargo.lock
  forc-plugins/forc-crypto/Cargo.toml
  forc-plugins/forc-crypto/benches/bench_main.rs
  forc-plugins/forc-crypto/src/args.rs
  forc-plugins/forc-crypto/src/keys/mod.rs
  forc-plugins/forc-crypto/src/keys/vanity.rs
  forc-plugins/forc-crypto/src/lib.rs
  forc-plugins/forc-crypto/src/main.rs
Labels: enhancement, forc

#6665 Add parallel garbage collection test runner
  sway-lsp/tests/lib.rs
  sway-lsp/tests/utils/src/lib.rs
Labels: language server, compiler: frontend

#6585 Optimise TokenMap to only hold either a typed or parsed AST token
  sway-lsp/src/capabilities/code_actions/diagnostic/auto_import.rs
  sway-lsp/src/capabilities/code_actions/mod.rs
  sway-lsp/src/capabilities/code_actions/struct_decl/struct_new.rs
  sway-lsp/src/capabilities/hover/mod.rs
  sway-lsp/src/capabilities/inlay_hints.rs
  sway-lsp/src/capabilities/rename.rs
  sway-lsp/src/core/session.rs
  sway-lsp/src/core/token.rs
  sway-lsp/src/core/token_map.rs
  sway-lsp/src/traverse/dependency.rs
  sway-lsp/src/traverse/lexed_tree.rs
  sway-lsp/src/traverse/parsed_tree.rs
  sway-lsp/src/traverse/typed_tree.rs
  sway-lsp/src/utils/attributes.rs
  sway-lsp/src/utils/debug.rs
Labels: language server
