Repository FuelLabs/sway, pull requests merged in 2024-09, with the labels that each got.

#6445 Add flag check functions
  sway-lib-std/src/flags.sw
  sway-lib-std/src/math.sw
  test/src/in_language_tests/test_programs/flags_inline_tests/src/main.sw
Labels: enhancement, lib: std, code quality

#6490 Adds function return type unification.
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/function_application.rs
  test/src/e2e_vm_tests/test_programs/should_fail/bad_generic_annotation/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/language/reexport/shadowing_in_reexporting_module/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/recursive_type_unification/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/function_return_type_unification/.gitignore
  test/src/e2e_vm_tests/test_programs/should_pass/language/function_return_type_unification/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/function_return_type_unification/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/function_return_type_unification/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/function_return_type_unification/test.toml
Labels: bug, compiler: frontend

#6494 Fixes ABI alias metadata types.
  sway-core/src/abi_generation/abi_str.rs
  test/src/e2e_vm_tests/test_programs/should_pass/language/main_args/main_args_generics/json_abi_oracle_new_encoding.json
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/abi_with_alias/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/abi_with_alias/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/abi_with_alias/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/abi_with_alias/json_abi_oracle_new_encoding.json
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/abi_with_alias/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/abi_with_alias/test.toml
Labels: ABI

#6497 Change `msg_sender()`'s `Input::Message` from sender to recipient
  sway-lib-std/src/auth.sw
  test/src/sdk-harness/test_projects/auth/mod.rs
Labels: bug, lib: std

#6503 Bump to v0.63.4
  Cargo.lock
  forc-pkg/Cargo.toml
  forc-plugins/forc-client/Cargo.toml
  forc-plugins/forc-client/proxy_abi/README.md
  forc-plugins/forc-crypto/Cargo.toml
  forc-plugins/forc-debug/Cargo.toml
  forc-plugins/forc-doc/Cargo.toml
  forc-plugins/forc-fmt/Cargo.toml
  forc-plugins/forc-lsp/Cargo.toml
  forc-plugins/forc-tx/Cargo.toml
  forc-test/Cargo.toml
  forc-tracing/Cargo.toml
  forc-util/Cargo.toml
  forc/Cargo.toml
  sway-ast/Cargo.toml
  sway-core/Cargo.toml
  sway-error/Cargo.toml
  sway-ir/Cargo.toml
  sway-ir/sway-ir-macros/Cargo.toml
  sway-lsp/Cargo.toml
  sway-parse/Cargo.toml
  sway-types/Cargo.toml
  sway-utils/Cargo.toml
  swayfmt/Cargo.toml
Labels: release

#6505 Emit unreachable arm warning for OR match arms
  sway-core/src/semantic_analysis/ast_node/expression/match_expression/analysis/usefulness.rs
  test/src/e2e_vm_tests/test_programs/should_pass/language/match_expressions_unreachable_or/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/match_expressions_unreachable_or/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/match_expressions_unreachable_or/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/match_expressions_unreachable_or/test.toml
Labels: bug, compiler, compiler: frontend, compiler: ui

#6506 chore: use fuel-core 0.35.0 and sdk 0.66.4
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  test/src/sdk-harness/Cargo.lock
  test/src/sdk-harness/Cargo.toml
Labels: dependencies

#6508 chore: bump to v0.63.5
  Cargo.lock
  forc-pkg/Cargo.toml
  forc-plugins/forc-client/Cargo.toml
  forc-plugins/forc-client/proxy_abi/README.md
  forc-plugins/forc-crypto/Cargo.toml
  forc-plugins/forc-debug/Cargo.toml
  forc-plugins/forc-doc/Cargo.toml
  forc-plugins/forc-fmt/Cargo.toml
  forc-plugins/forc-lsp/Cargo.toml
  forc-plugins/forc-tx/Cargo.toml
  forc-test/Cargo.toml
  forc-tracing/Cargo.toml
  forc-util/Cargo.toml
  forc/Cargo.toml
  sway-ast/Cargo.toml
  sway-core/Cargo.toml
  sway-error/Cargo.toml
  sway-ir/Cargo.toml
  sway-ir/sway-ir-macros/Cargo.toml
  sway-lsp/Cargo.toml
  sway-parse/Cargo.toml
  sway-types/Cargo.toml
  sway-utils/Cargo.toml
  swayfmt/Cargo.toml
Labels: release

#6452 Correctly check for overflow in add, mul and pow
  sway-lib-core/src/ops.sw
  sway-lib-std/src/math.sw
  test/src/in_language_tests/test_programs/math_inline_tests/src/main.sw
Labels: bug, lib: std, audit-report

#6515 Replace cargo deps with built-in cargo tree (#6179)
  .github/workflows/ci.yml
Labels: ci, code quality, forc-pkg

#6518 fix: forc-test log decoding in libraries
  sway-core/src/abi_generation/fuel_abi.rs
  test/src/e2e_vm_tests/test_programs/should_pass/unit_tests/lib_log_decode/.gitignore
  test/src/e2e_vm_tests/test_programs/should_pass/unit_tests/lib_log_decode/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/unit_tests/lib_log_decode/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/unit_tests/lib_log_decode/src/lib.sw
  test/src/e2e_vm_tests/test_programs/should_pass/unit_tests/lib_log_decode/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/unit_tests/script_log_decode/.gitignore
  test/src/e2e_vm_tests/test_programs/should_pass/unit_tests/script_log_decode/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/unit_tests/script_log_decode/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/unit_tests/script_log_decode/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/unit_tests/script_log_decode/test.toml
Labels: forc-test

#6521 Use cargo-nextest with retries for flaky LSP test
  .github/workflows/ci.yml
  sway-lsp/tests/lib.rs
  sway-lsp/tests/nextest.toml
Labels: ci, language server

#6520 Update proxy contract binary shipped with `forc-deploy`
  forc-plugins/forc-client/proxy_abi/README.md
  forc-plugins/forc-client/proxy_abi/proxy_contract-abi.json
  forc-plugins/forc-client/proxy_abi/proxy_contract-storage_slots.json
  forc-plugins/forc-client/proxy_abi/proxy_contract.bin
  forc-plugins/forc-client/src/op/deploy.rs
  forc-plugins/forc-client/tests/deploy.rs
Labels: enhancement, forc-deploy

#6514 Add Caller addresses function
  sway-lib-std/src/auth.sw
  test/src/sdk-harness/test_artifacts/auth_testing_abi/src/main.sw
  test/src/sdk-harness/test_artifacts/auth_testing_contract/src/main.sw
  test/src/sdk-harness/test_projects/auth/mod.rs
Labels: enhancement, lib: std

#6528 feat: Add --raw-logs option for forc-test
  .github/workflows/ci.yml
  Cargo.lock
  forc/Cargo.toml
  forc/src/cli/commands/test.rs
  forc/tests/cli_integration.rs
  forc/tests/fixtures/test_contract/.gitignore
  forc/tests/fixtures/test_contract/Forc.lock
  forc/tests/fixtures/test_contract/Forc.toml
  forc/tests/fixtures/test_contract/src/main.sw
Labels: forc-test

#6545 Add tests for recursive `const` definitions and associated consts usages
  test/src/e2e_vm_tests/test_programs/should_fail/const_block_level_no_expr/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/const_block_level_no_expr/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/const_top_level_no_expr/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/recursive_calls/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/recursive_const_associated/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/recursive_const_associated/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/recursive_const_associated/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/recursive_const_associated/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/recursive_const_associated_over_associated_function/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/recursive_const_associated_over_associated_function/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/recursive_const_associated_over_associated_function/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/recursive_const_associated_over_associated_function/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/recursive_const_associated_over_module_function/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/recursive_const_associated_over_module_function/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/recursive_const_associated_over_module_function/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/recursive_const_associated_over_module_function/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/recursive_const_module/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/recursive_const_module/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/recursive_const_module/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/recursive_const_module/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/recursive_const_module_over_associated_const/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/recursive_const_module_over_associated_const/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/recursive_const_module_over_associated_const/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/recursive_const_module_over_associated_const/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/recursive_const_module_over_associated_function/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/recursive_const_module_over_associated_function/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/recursive_const_module_over_associated_function/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/recursive_const_module_over_associated_function/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/recursive_const_module_over_module_function/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/recursive_const_module_over_module_function/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/recursive_const_module_over_module_function/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/recursive_const_module_over_module_function/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/recursive_const_stack_overflow/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/recursive_const_stack_overflow/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/recursive_const_stack_overflow/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/recursive_const_stack_overflow/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/recursive_enum/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/recursive_enum/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/recursive_struct/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/recursive_struct/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/recursive_type_chain/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/recursive_type_chain/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/recursive_type_unification/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/recursive_type_unification/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/associated_const_in_decls_of_other_constants/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/associated_const_in_decls_of_other_constants/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/associated_const_in_decls_of_other_constants/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/associated_const_in_decls_of_other_constants/test.toml
Labels: testing

#6553 Fixes unreachable on invalid cfg attribute arg.
  sway-core/src/transform/to_parsed_lang/convert_parse_tree.rs
  sway-error/src/convert_parse_tree_error.rs
  test/src/e2e_vm_tests/test_programs/should_fail/invalid_cfg_arg/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/invalid_cfg_arg/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/invalid_cfg_arg/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/invalid_cfg_arg/test.toml
Labels: bug, audit-report

#6551 Fixes OOB in type_check_analyze of ImplTrait.
  sway-core/src/semantic_analysis/ast_node/declaration/impl_trait.rs
  test/src/e2e_vm_tests/test_programs/should_fail/mismatch_closing_delimiters/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/mismatch_closing_delimiters/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/mismatch_closing_delimiters/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/mismatch_closing_delimiters/test.toml
Labels: bug, audit-report

#6552 Fixes panic error on decl_to_type_info.
  sway-core/src/semantic_analysis/namespace/root.rs
  test/src/e2e_vm_tests/test_programs/should_fail/parser_associated_type_error/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/parser_associated_type_error/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/parser_associated_type_error/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/parser_associated_type_error/test.toml
Labels: bug, audit-report

#6555 Fix `function_cache` garbage collection bug
  .vscode/launch.json
  sway-core/src/engine_threading.rs
  sway-core/src/query_engine/mod.rs
  sway-lsp/src/config.rs
  sway-lsp/src/server_state.rs
  sway-lsp/tests/fixtures/garbage_collection/minimal_script/.gitignore
  sway-lsp/tests/fixtures/garbage_collection/minimal_script/Forc.toml
  sway-lsp/tests/fixtures/garbage_collection/minimal_script/src/main.sw
  sway-lsp/tests/lib.rs
Labels: bug, language server, compiler: frontend

#6556 chore: bump to v0.63.6
  Cargo.lock
  forc-pkg/Cargo.toml
  forc-plugins/forc-client/Cargo.toml
  forc-plugins/forc-client/proxy_abi/README.md
  forc-plugins/forc-crypto/Cargo.toml
  forc-plugins/forc-debug/Cargo.toml
  forc-plugins/forc-doc/Cargo.toml
  forc-plugins/forc-fmt/Cargo.toml
  forc-plugins/forc-lsp/Cargo.toml
  forc-plugins/forc-tx/Cargo.toml
  forc-test/Cargo.toml
  forc-tracing/Cargo.toml
  forc-util/Cargo.toml
  forc/Cargo.toml
  sway-ast/Cargo.toml
  sway-core/Cargo.toml
  sway-error/Cargo.toml
  sway-ir/Cargo.toml
  sway-ir/sway-ir-macros/Cargo.toml
  sway-lsp/Cargo.toml
  sway-parse/Cargo.toml
  sway-types/Cargo.toml
  sway-utils/Cargo.toml
  swayfmt/Cargo.toml
Labels: release

#6561 fix: forc-client build script should update proxy abi also for deployment tests
  forc-plugins/forc-client/build.rs
  forc-plugins/forc-client/tests/deploy.rs
Labels: bug, code quality, forc-client

#6570 fix: forc-deploy block url
  forc-plugins/forc-client/src/op/deploy.rs
Labels: forc-client, forc-deploy

#6563 Move all crate dependencies to the workspace Cargo.toml (#6179)
  Cargo.lock
  Cargo.toml
  forc-pkg/Cargo.toml
  forc-plugins/forc-client/Cargo.toml
  forc-plugins/forc-crypto/Cargo.toml
  forc-plugins/forc-debug/Cargo.toml
  forc-plugins/forc-doc/Cargo.toml
  forc-plugins/forc-fmt/Cargo.toml
  forc-plugins/forc-lsp/Cargo.toml
  forc-plugins/forc-tx/Cargo.toml
  forc-test/Cargo.toml
  forc-tracing/Cargo.toml
  forc-util/Cargo.toml
  forc/Cargo.toml
  scripts/mdbook-forc-documenter/Cargo.toml
  sway-ast/Cargo.toml
  sway-core/Cargo.toml
  sway-error/Cargo.toml
  sway-ir/Cargo.toml
  sway-ir/sway-ir-macros/Cargo.toml
  sway-lsp/Cargo.toml
  sway-lsp/tests/utils/Cargo.toml
  sway-parse/Cargo.toml
  sway-types/Cargo.toml
  sway-utils/Cargo.toml
  swayfmt/Cargo.toml
  test/Cargo.toml
  test/src/sdk-harness/Cargo.toml
Labels: ci, code quality, dependencies, dev-experience

#6575 fix OOB slab panic when creating runnables on a did_save event
  sway-lsp/src/core/session.rs
  sway-lsp/src/handlers/notification.rs
Labels: bug, language server, P: critical

#6571 Version bump all crate dependencies after the workspace move
  Cargo.lock
  Cargo.toml
  sway-lsp/Cargo.toml
  sway-lsp/tests/utils/Cargo.toml
Labels: ci, code quality, dependencies, dev-experience

#6579 Version bump the remaining crate dependencies
  Cargo.lock
  Cargo.toml
  forc-plugins/forc-client/src/util/pkg.rs
  forc-plugins/forc-client/tests/deploy.rs
  forc/src/ops/forc_template.rs
  sway-ir/sway-ir-macros/src/lib.rs
  sway-lsp/Cargo.toml
  sway-lsp/src/core/sync.rs
  sway-lsp/src/utils/keyword_docs.rs
  test/src/e2e_vm_tests/harness.rs
  test/src/e2e_vm_tests/mod.rs
Labels: compiler, ci, code quality, dependencies, documentation, dev-experience

#6513 Add inlay hints for function parameters
  sway-lsp/src/capabilities/inlay_hints.rs
  sway-lsp/src/handlers/request.rs
  sway-lsp/tests/fixtures/inlay_hints/.gitignore
  sway-lsp/tests/fixtures/inlay_hints/Forc.toml
  sway-lsp/tests/fixtures/inlay_hints/src/main.sw
  sway-lsp/tests/integration/lsp.rs
  sway-lsp/tests/lib.rs
Labels: language server

#6580 fix: use build script for proxy deployments as well
  forc-plugins/forc-client/build.rs
  forc-plugins/forc-client/src/op/deploy.rs
Labels: code quality, forc-client, forc-deploy

#6582 chore: update fuel-core to 0.36.0, fuels-* to 0.66.5
  Cargo.lock
  Cargo.toml
  forc-plugins/forc-client/src/util/tx.rs
  test/src/sdk-harness/Cargo.lock
  test/src/sdk-harness/Cargo.toml
  test/src/sdk-harness/test_projects/tx_fields/mod.rs
Labels: dependencies, breaking

#6562 Support `Output::Change` in `output_asset_to()` and `output_asset_id()`
  sway-lib-std/src/outputs.sw
  test/src/sdk-harness/Forc.lock
  test/src/sdk-harness/Forc.toml
  test/src/sdk-harness/test_artifacts/tx_output_change_contract/Forc.toml
  test/src/sdk-harness/test_artifacts/tx_output_change_contract/src/main.sw
  test/src/sdk-harness/test_artifacts/tx_output_predicate/src/main.sw
  test/src/sdk-harness/test_projects/tx_fields/mod.rs
Labels: enhancement, lib: std

#6578 feat: AWS kms signer support for forc-client
  Cargo.lock
  Cargo.toml
  forc-plugins/forc-client/Cargo.toml
  forc-plugins/forc-client/src/cmd/deploy.rs
  forc-plugins/forc-client/src/op/deploy.rs
  forc-plugins/forc-client/src/op/run/mod.rs
  forc-plugins/forc-client/src/util/account.rs
  forc-plugins/forc-client/src/util/aws.rs
  forc-plugins/forc-client/src/util/gas.rs
  forc-plugins/forc-client/src/util/mod.rs
  forc-plugins/forc-client/src/util/tx.rs
  forc-plugins/forc-client/tests/deploy.rs
Labels: enhancement, forc-client

#6584 chore: bump to v0.64.0
  Cargo.lock
  Cargo.toml
Labels: release

#6594 Update single and multi asset example in docs hub
  docs/book/src/blockchain-development/native_assets.md
Labels: The Sway Book, documentation

#6592 Fix release check script to check new version specs
  .github/workflows/ci.yml
  .github/workflows/scripts/verify_tag.sh
Labels: ci
