Repository FuelLabs/sway, pull requests merged in 2024-02, with the labels that each got.

#5544 Separate forc-debug CI tests
  .github/workflows/ci.yml
Labels: ci

#5548 Remove Arcs from QE
  sway-core/src/query_engine/mod.rs
Labels: bug, language server, compiler: frontend

#5541 Fixes `ReplaceDecls` to no longer depend on filter hack.
  sway-core/src/decl_engine/associated_item_decl_id.rs
  sway-core/src/decl_engine/mapping.rs
  sway-core/src/decl_engine/ref.rs
  sway-core/src/language/ty/declaration/function.rs
  sway-core/src/language/ty/declaration/trait.rs
  sway-core/src/language/ty/declaration/trait_fn.rs
  sway-core/src/language/ty/expression/expression_variant.rs
  sway-core/src/semantic_analysis/ast_node/declaration/abi.rs
  sway-core/src/semantic_analysis/ast_node/declaration/declaration.rs
  sway-core/src/semantic_analysis/ast_node/declaration/function.rs
  sway-core/src/semantic_analysis/ast_node/declaration/impl_trait.rs
  sway-core/src/semantic_analysis/ast_node/declaration/trait.rs
  sway-core/src/semantic_analysis/ast_node/declaration/trait_fn.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  test/src/e2e_vm_tests/test_programs/should_pass/language/trait_nested/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/trait_nested/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/trait_nested/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/trait_nested/test.toml
Labels: P: critical, compiler: frontend

#5553 Adds test case that covers PR #3818.
  test/src/e2e_vm_tests/test_programs/should_pass/language/where_clause_functions/src/main.sw
Labels: compiler: frontend

#5545 ci: use buildjet cache for steps using buildjet runners
  .github/workflows/ci.yml
Labels: enhancement, ci

#5552 Dereferencing operator `.` on tuple element access
  sway-core/src/ir_generation/function.rs
  sway-core/src/language/ty/expression/expression_variant.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/struct_field_access.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/tuple_index_access.rs
  sway-core/src/semantic_analysis/namespace/items.rs
  sway-core/src/type_system/info.rs
  sway-error/src/error.rs
  test/src/e2e_vm_tests/test_programs/should_pass/language/references/dereferencing_operator_dot_on_tuples/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/references/dereferencing_operator_dot_on_tuples/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/references/dereferencing_operator_dot_on_tuples/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/language/references/dereferencing_operator_dot_on_tuples/src/impls.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/references/dereferencing_operator_dot_on_tuples/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/references/dereferencing_operator_dot_on_tuples/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/references/dereferencing_operator_star/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/references/referencing_function_parameters/src/main.sw
Labels: compiler, language feature, compiler: frontend

#5556 Only run docs CI checks when docs have changed
  .github/workflows/docs.yml
Labels: ci, documentation

#5555 Disable DCA and writing diagnostics on did_change events
  Cargo.lock
  forc-pkg/src/manifest.rs
  forc-pkg/src/pkg.rs
  forc-plugins/forc-doc/src/main.rs
  forc/src/ops/forc_check.rs
  sway-core/src/build_config.rs
  sway-core/src/lib.rs
  sway-lsp/Cargo.toml
  sway-lsp/benches/lsp_benchmarks/compile.rs
  sway-lsp/benches/lsp_benchmarks/mod.rs
  sway-lsp/src/core/session.rs
  sway-lsp/src/core/token_map.rs
  sway-lsp/src/handlers/notification.rs
  sway-lsp/src/server_state.rs
  sway-lsp/tests/lib.rs
Labels: language server, compiler: frontend

#5569 Turn struct field privacy warnings into errors
  sway-core/src/language/ty/declaration/storage.rs
  sway-core/src/semantic_analysis/ast_node/expression/match_expression/typed/typed_scrutinee.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/struct_field_access.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/struct_instantiation.rs
  sway-core/src/semantic_analysis/namespace/items.rs
  sway-error/src/warning.rs
  sway-lsp/tests/fixtures/tokens/storage/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/struct_field_privacy_deconstructing/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/struct_field_privacy_field_access/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/struct_field_privacy_instantiation/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/struct_field_privacy_pattern_matching/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/struct_field_privacy_reassignment/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/struct_field_privacy_storage/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/struct_field_privacy_workspace/test.toml
Labels: compiler, language feature, breaking, compiler: frontend

#5584 Enforce deterministic order in hashmaps
  .github/workflows/ci.yml
  Cargo.lock
  forc/src/ops/forc_init.rs
  sway-ast/Cargo.toml
  sway-core/Cargo.toml
  sway-core/src/asm_generation/finalized_asm.rs
  sway-core/src/asm_generation/fuel/allocated_abstract_instruction_set.rs
  sway-core/src/asm_generation/fuel/analyses.rs
  sway-core/src/asm_generation/fuel/register_allocator.rs
  sway-core/src/asm_generation/miden_vm/miden_vm_asm_builder.rs
  sway-core/src/asm_lang/mod.rs
  sway-core/src/asm_lang/virtual_ops.rs
  sway-core/src/control_flow_analysis/flow_graph/namespace.rs
  sway-core/src/ir_generation/function.rs
  sway-core/src/language/ty/expression/expression_variant.rs
  sway-core/src/lib.rs
  sway-core/src/semantic_analysis/ast_node/expression/match_expression/analysis/duplicates.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/function_application.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/method_application.rs
  sway-core/src/transform/attribute.rs
  sway-core/src/transform/to_parsed_lang/convert_parse_tree.rs
  sway-core/src/type_system/id.rs
  sway-error/Cargo.toml
  sway-ir/Cargo.toml
  sway-ir/src/analysis/call_graph.rs
  sway-ir/src/analysis/dominator.rs
  sway-ir/src/analysis/memory_utils.rs
  sway-ir/src/optimize/const_demotion.rs
  sway-ir/src/optimize/mem2reg.rs
  sway-ir/src/optimize/memcpyopt.rs
  sway-ir/sway-ir-macros/Cargo.toml
  sway-lsp/Cargo.toml
  sway-lsp/src/capabilities/code_actions/common/generate_impl.rs
  sway-lsp/src/core/sync.rs
  sway-parse/Cargo.toml
  sway-types/Cargo.toml
  sway-types/src/lib.rs
  sway-utils/Cargo.toml
  sway-utils/src/helpers.rs
  test/src/e2e_vm_tests/test_programs/should_pass/language/configurable_consts/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_basic_storage/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_storage_enum/src/main.sw
Labels: breaking

#5587 Moves for loop handling to a function.
  sway-core/src/transform/to_parsed_lang/convert_parse_tree.rs
Labels: bug, code quality

#5586 Fix `balance_of()` and `this_balance()` inline docs
  sway-lib-std/src/context.sw
Labels: bug, lib: std, documentation

#5546 Run LSP benchmarks in CI
  .github/workflows/bench-lsp.yml
  sway-lsp/README.md
Labels: ci

#5578 swayfmt: fix indentation after where in fn (#5468)
  sway-lib-std/src/storage/storage_map.sw
  swayfmt/src/items/item_fn/mod.rs
  swayfmt/tests/mod.rs
Labels: formatter

#5600 Introduce lexical scopes to namespace modules
  sway-core/src/ir_generation/compile.rs
  sway-core/src/ir_generation/const_eval.rs
  sway-core/src/language/call_path.rs
  sway-core/src/semantic_analysis/ast_node/declaration/abi.rs
  sway-core/src/semantic_analysis/ast_node/declaration/auto_impl.rs
  sway-core/src/semantic_analysis/ast_node/declaration/declaration.rs
  sway-core/src/semantic_analysis/ast_node/declaration/function/function_parameter.rs
  sway-core/src/semantic_analysis/ast_node/declaration/impl_trait.rs
  sway-core/src/semantic_analysis/ast_node/declaration/trait.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/struct_instantiation.rs
  sway-core/src/semantic_analysis/namespace/lexical_scope.rs
  sway-core/src/semantic_analysis/namespace/mod.rs
  sway-core/src/semantic_analysis/namespace/module.rs
  sway-core/src/semantic_analysis/namespace/namespace.rs
  sway-core/src/semantic_analysis/type_check_context.rs
  sway-core/src/type_system/ast_elements/type_parameter.rs
  sway-core/src/type_system/id.rs
  sway-lsp/src/capabilities/hover/hover_link_contents.rs
  sway-lsp/src/core/session.rs
  sway-lsp/src/traverse/typed_tree.rs
Labels: compiler, compiler: frontend

#5609 Make forc-deploy create release builds by default
  .gitignore
  forc-pkg/src/lib.rs
  forc-pkg/src/manifest/build_profile.rs
  forc-pkg/src/manifest/mod.rs
  forc-pkg/src/pkg.rs
  forc-pkg/tests/sections/Forc.toml
  forc-pkg/tests/sections/src/main.sw
  forc-plugins/forc-client/src/cmd/deploy.rs
  forc-plugins/forc-client/src/op/deploy.rs
  forc-plugins/forc-client/src/op/run/mod.rs
  forc-test/src/lib.rs
  forc/src/cli/commands/test.rs
  forc/src/cli/shared.rs
  forc/src/ops/forc_build.rs
  forc/src/ops/forc_contract_id.rs
  forc/src/ops/forc_predicate_root.rs
  sway-core/src/build_config.rs
  test/src/e2e_vm_tests/harness.rs
Labels: forc, forc-client

#5601 Storage namespace annotation
  docs/book/src/blockchain-development/storage.md
  docs/reference/src/code/language/annotations/src/main.sw
  docs/reference/src/documentation/language/annotations/attributes/namespace.md
  examples/storage_namespace/Forc.toml
  examples/storage_namespace/src/main.sw
  sway-core/src/ir_generation/function.rs
  sway-core/src/ir_generation/storage.rs
  sway-core/src/language/ty/declaration/storage.rs
  sway-core/src/language/ty/expression/storage.rs
  sway-core/src/semantic_analysis/ast_node/declaration/storage.rs
  sway-core/src/transform/attribute.rs
  sway-core/src/transform/to_parsed_lang/convert_parse_tree.rs
  sway-types/src/constants.rs
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/storage_namespace/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/storage_namespace/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/storage_namespace/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/storage_namespace/json_abi_oracle_flat.json
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/storage_namespace/json_storage_slots_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/storage_namespace/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/storage_namespace/test.toml
  test/src/sdk-harness/test_projects/storage_namespace/Forc.lock
  test/src/sdk-harness/test_projects/storage_namespace/Forc.toml
  test/src/sdk-harness/test_projects/storage_namespace/mod.rs
  test/src/sdk-harness/test_projects/storage_namespace/src/main.sw
Labels: enhancement, compiler, storage

#5629 Replace unmaintained generational-arena with slotmap
  Cargo.lock
  sway-ir/Cargo.toml
  sway-ir/src/block.rs
  sway-ir/src/context.rs
  sway-ir/src/function.rs
  sway-ir/src/instruction.rs
  sway-ir/src/irtype.rs
  sway-ir/src/lib.rs
  sway-ir/src/local_var.rs
  sway-ir/src/metadata.rs
  sway-ir/src/module.rs
  sway-ir/src/pass_manager.rs
  sway-ir/src/value.rs
  sway-ir/src/verify.rs
  test/src/e2e_vm_tests/test_programs/should_pass/language/configurable_consts/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_basic_storage/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_storage_enum/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/storage_access_caller/src/main.sw
Labels: code quality, compiler: ir, breaking

#5625 Refactor forc-pkg with generic manifest trait
  forc-pkg/src/manifest/mod.rs
  forc-pkg/src/pkg.rs
  forc-pkg/src/source/git/mod.rs
  forc-pkg/src/source/ipfs.rs
  forc-pkg/src/source/member.rs
  forc-pkg/src/source/mod.rs
  forc-pkg/src/source/path.rs
  forc-plugins/forc-client/src/op/deploy.rs
  forc-plugins/forc-client/src/util/pkg.rs
  forc-plugins/forc-debug/src/server/handlers/handle_launch.rs
  forc-plugins/forc-doc/src/main.rs
  forc-plugins/forc-fmt/src/main.rs
  forc/src/ops/forc_check.rs
  forc/src/ops/forc_clean.rs
  forc/src/ops/forc_update.rs
  sway-lsp/src/core/session.rs
  sway-lsp/src/core/sync.rs
  sway-lsp/src/server_state.rs
Labels: forc-pkg

#5588 cfei: don't generate if frame size is zero
  sway-core/src/asm_generation/fuel/allocated_abstract_instruction_set.rs
  sway-core/src/asm_lang/allocated_ops.rs
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/array_of_structs_caller/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/asset_ops_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/bal_opcode/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_abi_with_tuples/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_basic_storage/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_storage_enum/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/caller_auth_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/caller_context_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/nested_struct_args_caller/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/unit_tests/workspace_test/contract_multi_test/src/main.sw
  test/src/ir_generation/tests/empty.sw
Labels: compiler: ir, breaking, compiler: optimization

#5630 Encapsulation of Storage Types
  sway-lib-core/src/storage.sw
  sway-lib-std/src/storage/storage_bytes.sw
  sway-lib-std/src/storage/storage_key.sw
  sway-lib-std/src/storage/storage_map.sw
  sway-lib-std/src/storage/storage_string.sw
  sway-lib-std/src/storage/storage_vec.sw
  test/src/e2e_vm_tests/test_programs/should_fail/generics_in_contract/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_basic_storage/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_storage_enum/src/main.sw
Labels: lib: std, breaking

#5640 Encapsulation Numeric Types
  sway-lib-std/src/b512.sw
  sway-lib-std/src/ecr.sw
  sway-lib-std/src/u128.sw
  sway-lib-std/src/u256.sw
  sway-lib-std/src/vm/evm/ecr.sw
  sway-lib-std/src/vm/evm/evm_address.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/complex_cfg/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/empty_method_initializer/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/assert_eq/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/assert_ne/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/b512_struct_alignment/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/b512_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/u128_div_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/u128_mul_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/u128_test/src/main.sw
Labels: lib: std, breaking

#5613 Private Struct Fields for Blockchain Types
  docs/reference/src/code/operations/namespace/src/lib.sw
  examples/liquidity_pool/src/main.sw
  examples/signatures/src/main.sw
  sway-lib-std/src/address.sw
  sway-lib-std/src/asset.sw
  sway-lib-std/src/asset_id.sw
  sway-lib-std/src/call_frames.sw
  sway-lib-std/src/context.sw
  sway-lib-std/src/contract_id.sw
  sway-lib-std/src/external.sw
  sway-lib-std/src/identity.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/const_inits/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/contract_caller_as_ret/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/enum_if_let/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/type_alias/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/asset_ops_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/caller_context_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/address_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/assert_eq/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/assert_ne/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/contract_id_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/context_testing_contract/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/contract_with_type_aliases/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/storage_configurable/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/test_fuel_coin_contract/json_abi_oracle.json
  test/src/sdk-harness/test_artifacts/context_caller_contract/src/main.sw
  test/src/sdk-harness/test_artifacts/tx_output_predicate/src/main.sw
  test/src/sdk-harness/test_projects/asset_ops/src/main.sw
  test/src/sdk-harness/test_projects/configurables_in_contract/mod.rs
  test/src/sdk-harness/test_projects/configurables_in_contract/src/main.sw
  test/src/sdk-harness/test_projects/context/src/main.sw
  test/src/sdk-harness/test_projects/ec_recover_and_match_predicate/src/main.sw
  test/src/sdk-harness/test_projects/parsing_logs/mod.rs
  test/src/sdk-harness/test_projects/parsing_logs/src/main.sw
Labels: lib: std, breaking

#5362 fix: several typos in the documentation
  docs/book/src/advanced/generic_types.md
  docs/book/src/basics/built_in_types.md
  docs/book/src/blockchain-development/access_control.md
  docs/book/src/forc/manifest_reference.md
  docs/book/src/reference/attributes.md
  docs/book/src/reference/contributing_to_sway.md
  docs/book/src/reference/keywords.md
  docs/book/src/reference/solidity_differences.md
  docs/book/src/testing/unit-testing.md
Labels: documentation
