Repository FuelLabs/sway, pull requests merged in 2024-01, with the labels that each got.

#5426 Added `assert_ne(x, y)` function
  docs/book/src/introduction/standard_library.md
  docs/reference/src/SUMMARY.md
  docs/reference/src/code/operations/assertions/src/lib.sw
  docs/reference/src/documentation/misc/prelude.md
  docs/reference/src/documentation/operations/assertions/assert-ne.md
  docs/reference/src/documentation/operations/assertions/index.md
  sway-lib-std/src/assert.sw
  sway-lib-std/src/error_signals.sw
  sway-lib-std/src/prelude.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/assert_ne/.gitignore
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/assert_ne/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/assert_ne/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/assert_ne/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/assert_ne/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/assert_ne/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/assert_ne_revert/.gitignore
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/assert_ne_revert/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/assert_ne_revert/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/assert_ne_revert/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/assert_ne_revert/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/assert_ne_revert/test.toml
Labels: enhancement, lib: std

#5425 Introduce `predicate_id()` to the std-lib
  sway-lib-std/src/auth.sw
  test/src/sdk-harness/Forc.lock
  test/src/sdk-harness/Forc.toml
  test/src/sdk-harness/test_artifacts/auth_predicate/.gitignore
  test/src/sdk-harness/test_artifacts/auth_predicate/Forc.lock
  test/src/sdk-harness/test_artifacts/auth_predicate/Forc.toml
  test/src/sdk-harness/test_artifacts/auth_predicate/src/main.sw
  test/src/sdk-harness/test_projects/auth/mod.rs
Labels: enhancement, lib: std

#5428 Revert TE `slab` to hold `TypeSourceInfo` and perform GC on DE `parents` and TE `id_map`
  sway-core/src/decl_engine/engine.rs
  sway-core/src/type_system/ast_elements/type_parameter.rs
  sway-core/src/type_system/engine.rs
  sway-core/src/type_system/info.rs
  sway-core/src/type_system/unify/unifier.rs
Labels: compiler

#5400 Changes `ConcurrentSlab` to store values in map.
  sway-core/src/concurrent_slab.rs
  sway-core/src/decl_engine/engine.rs
  sway-core/src/type_system/ast_elements/type_parameter.rs
  sway-core/src/type_system/engine.rs
  sway-core/src/type_system/info.rs
  sway-core/src/type_system/unify/unifier.rs
  sway-error/src/error.rs
Labels: compiler

#5435 ci: use rust 1.75 in CI
  .github/workflows/ci.yml
  forc/src/cli/plugin.rs
  sway-ast/src/priv_prelude.rs
  sway-core/src/asm_lang/mod.rs
  sway-core/src/control_flow_analysis/mod.rs
  sway-core/src/decl_engine/mapping.rs
  sway-core/src/language/ty/expression/expression_variant.rs
  sway-core/src/semantic_analysis/ast_node/declaration/function.rs
  sway-core/src/semantic_analysis/ast_node/declaration/mod.rs
  sway-core/src/semantic_analysis/ast_node/expression/intrinsic_function.rs
  sway-core/src/semantic_analysis/ast_node/expression/mod.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/method_application.rs
  sway-core/src/semantic_analysis/type_check_context.rs
  sway-ir/src/optimize/sroa.rs
  sway-lsp/src/core/token.rs
  sway-parse/src/parser.rs
  sway-parse/src/priv_prelude.rs
  sway-parse/src/token.rs
  test/src/sdk-harness/test_projects/auth/mod.rs
  test/src/sdk-harness/test_projects/low_level_call/mod.rs
  test/src/sdk-harness/test_projects/low_level_call_bytes/mod.rs
  test/src/sdk-harness/test_projects/storage_access/mod.rs
  test/src/sdk-harness/test_projects/tx_fields/mod.rs
Labels: ci, code quality

#5440 Major Performance Boost in `line_col` Function with `bytecount` Integration
  Cargo.lock
  sway-types/Cargo.toml
  sway-types/src/span.rs
Labels: language server, compiler: frontend

#5433 chore: use sdk v0.54.0 to enable forc-client deployments to beta5
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  forc-plugins/forc-client/Cargo.toml
  forc-plugins/forc-client/src/op/submit.rs
  forc-plugins/forc-client/src/util/tx.rs
  test/src/sdk-harness/Cargo.lock
  test/src/sdk-harness/Cargo.toml
Labels: dependencies, P: critical, forc-client

#5429 Implement a more responsive compilation thread in the the language server.
  Cargo.lock
  forc-pkg/src/pkg.rs
  forc-plugins/forc-doc/src/main.rs
  forc/src/ops/forc_check.rs
  sway-core/src/decl_engine/engine.rs
  sway-core/src/engine_threading.rs
  sway-core/src/ir_generation/const_eval.rs
  sway-core/src/lib.rs
  sway-core/src/query_engine/mod.rs
  sway-core/src/type_system/engine.rs
  sway-error/src/handler.rs
  sway-lsp/Cargo.toml
  sway-lsp/benches/lsp_benchmarks/compile.rs
  sway-lsp/benches/lsp_benchmarks/mod.rs
  sway-lsp/src/capabilities/code_actions/mod.rs
  sway-lsp/src/capabilities/hover/mod.rs
  sway-lsp/src/capabilities/inlay_hints.rs
  sway-lsp/src/capabilities/rename.rs
  sway-lsp/src/capabilities/semantic_tokens.rs
  sway-lsp/src/core/session.rs
  sway-lsp/src/error.rs
  sway-lsp/src/handlers/notification.rs
  sway-lsp/src/handlers/request.rs
  sway-lsp/src/lib.rs
  sway-lsp/src/server.rs
  sway-lsp/src/server_state.rs
  sway-lsp/tests/fixtures/benchmark/Forc.toml
  sway-lsp/tests/integration/lsp.rs
  sway-lsp/tests/lib.rs
  sway-lsp/tests/utils/Cargo.toml
  sway-types/src/source_engine.rs
  test/src/ir_generation/mod.rs
Labels: language server, compiler: frontend

#5439 Create the `asset_id.sw` file and move `AssetId` out of `contract_id.sw`
  sway-lib-std/src/address.sw
  sway-lib-std/src/asset_id.sw
  sway-lib-std/src/call_frames.sw
  sway-lib-std/src/constants.sw
  sway-lib-std/src/context.sw
  sway-lib-std/src/contract_id.sw
  sway-lib-std/src/identity.sw
  sway-lib-std/src/inputs.sw
  sway-lib-std/src/lib.sw
  sway-lib-std/src/low_level_call.sw
  sway-lib-std/src/outputs.sw
  sway-lib-std/src/prelude.sw
  sway-lib-std/src/token.sw
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/context_testing_contract/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/test_fuel_coin_contract/json_abi_oracle.json
  test/src/sdk-harness/test_projects/token_ops/mod.rs
  test/src/sdk-harness/test_projects/token_ops/src/main.sw
Labels: enhancement, lib: std, breaking

#5442 Large integers in aggregates cannot be scalarised
  sway-ir/src/optimize/sroa.rs
  test/src/e2e_vm_tests/test_programs/should_pass/language/largeint_sroa/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/largeint_sroa/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/largeint_sroa/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/language/largeint_sroa/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/largeint_sroa/test.toml
Labels: bug, compiler: ir, compiler: optimization

#5446 refactor: update error message for `forc deploy` when password is mismatch
  forc-plugins/forc-client/src/util/tx.rs
Labels: enhancement, forc-client, forc-deploy

#5457 fix: point std to local version for forc-client cli tests
  forc-plugins/forc-client/tests/Forc.lock
  forc-plugins/forc-client/tests/Forc.toml
Labels: testing, forc-client, forc-deploy

#5441 Add `try_insert` to storage map
  sway-lib-std/src/storage/storage_map.sw
  test/src/sdk-harness/Cargo.lock
  test/src/sdk-harness/Cargo.toml
  test/src/sdk-harness/test_projects/storage_map/mod.rs
  test/src/sdk-harness/test_projects/storage_map/src/main.sw
  test/src/sdk-harness/test_projects/storage_map/try_insert.rs
Labels: enhancement, lib: std

#5466 chore: replaced `filter().map()` with `filter_map()` in `sway-core`.
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
Labels: code quality

#5460 feat: add beta-5 network to supported networks
  forc-plugins/forc-client/src/constants.rs
  forc-plugins/forc-client/src/util/node_url.rs
  forc-plugins/forc-client/src/util/target.rs
  forc-plugins/forc-client/src/util/tx.rs
Labels: enhancement, blocked, forc-client, forc-submit, forc-deploy

#5447 refactor: improve the flow of `forc deploy` when selecting an account that doesn't exist
  forc-plugins/forc-client/src/util/tx.rs
Labels: enhancement, forc-client, forc-deploy

#5461 Formalize Asset and Coin Terminology in the std-lib
  docs/book/src/blockchain-development/native_assets.md
  docs/book/src/examples/subcurrency.md
  docs/reference/src/code/examples/wallet_example/src/main.sw
  docs/reference/src/code/operations/asset_operations/src/lib.sw
  docs/reference/src/documentation/operations/asset/burn.md
  docs/reference/src/documentation/operations/asset/mint/index.md
  docs/reference/src/documentation/operations/asset/transfer/index.md
  examples/Forc.lock
  examples/Forc.toml
  examples/identity/src/main.sw
  examples/liquidity_pool/src/main.sw
  examples/native_asset/Forc.toml
  examples/native_asset/src/main.sw
  examples/subcurrency/src/main.sw
  examples/wallet_smart_contract/src/main.sw
  sway-lib-std/src/asset.sw
  sway-lib-std/src/asset_id.sw
  sway-lib-std/src/call_frames.sw
  sway-lib-std/src/context.sw
  sway-lib-std/src/contract_id.sw
  sway-lib-std/src/error_signals.sw
  sway-lib-std/src/lib.sw
  test/src/e2e_vm_tests/test_programs/should_fail/non_payable_non_zero_coins_const/src/wallet.sw
  test/src/e2e_vm_tests/test_programs/should_fail/non_payable_non_zero_coins_let_binding/src/wallet.sw
  test/src/e2e_vm_tests/test_programs/should_fail/non_payable_non_zero_coins_literal/src/wallet.sw
  test/src/e2e_vm_tests/test_programs/should_fail/recover_at_level_top/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/non_payable_implicit_zero_coins/src/wallet.sw
  test/src/e2e_vm_tests/test_programs/should_pass/non_payable_zero_coins_let_binding/src/wallet.sw
  test/src/e2e_vm_tests/test_programs/should_pass/payable_non_zero_coins/src/wallet.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/asset_ops_test/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/asset_ops_test/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/asset_ops_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/asset_ops_test/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/bal_opcode/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/caller_context_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/token_ops_test/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/static_analysis/cei_pattern_violation_in_asm_block_tr/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/static_analysis/cei_pattern_violation_in_asm_block_tro/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/test_fuel_coin_contract/src/main.sw
  test/src/sdk-harness/Forc.lock
  test/src/sdk-harness/Forc.toml
  test/src/sdk-harness/test_artifacts/context_caller_contract/src/main.sw
  test/src/sdk-harness/test_projects/asset_ops/Forc.lock
  test/src/sdk-harness/test_projects/asset_ops/Forc.toml
  test/src/sdk-harness/test_projects/asset_ops/mod.rs
  test/src/sdk-harness/test_projects/asset_ops/src/main.sw
  test/src/sdk-harness/test_projects/context/mod.rs
  test/src/sdk-harness/test_projects/harness.rs
  test/src/sdk-harness/test_projects/messages/mod.rs
Labels: enhancement, lib: std, breaking

#5471 Fix broken link to book in README
  templates/sway-test-rs/README.md
Labels: documentation

#5473 LSP Optimization: Use rayon for `parse_ast_to_typed_tokens` function
  sway-lsp/src/core/session.rs
  sway-lsp/src/core/token_map.rs
  sway-lsp/src/traverse/dependency.rs
  sway-lsp/src/traverse/typed_tree.rs
Labels: language server

#5487 LSP Optimization: Add par_iters to the `traverse::typed_tree` module
  sway-lsp/src/core/token_map.rs
  sway-lsp/src/traverse/typed_tree.rs
Labels: language server

#5452 chore: bump to v0.49.0
  Cargo.lock
  deployment/Dockerfile
  docs/reference/src/documentation/introduction/installation/cargo.md
  docs/reference/src/documentation/introduction/installation/index.md
  docs/reference/src/documentation/introduction/installation/source.md
  docs/reference/src/index.md
  forc-pkg/Cargo.toml
  forc-plugins/forc-client/Cargo.toml
  forc-plugins/forc-crypto/Cargo.toml
  forc-plugins/forc-debug/Cargo.toml
  forc-plugins/forc-doc/Cargo.toml
  forc-plugins/forc-fmt/Cargo.toml
  forc-plugins/forc-lsp/Cargo.toml
  forc-plugins/forc-tx/Cargo.toml
  forc-test/Cargo.toml
  forc-tracing/Cargo.toml
  forc-util/Cargo.toml
  forc/Cargo.toml
  sway-ast/Cargo.toml
  sway-core/Cargo.toml
  sway-error/Cargo.toml
  sway-ir/Cargo.toml
  sway-ir/sway-ir-macros/Cargo.toml
  sway-lsp/Cargo.toml
  sway-parse/Cargo.toml
  sway-types/Cargo.toml
  sway-utils/Cargo.toml
  swayfmt/Cargo.toml
Labels: release

#5475 Remove Subcurrency from examples
  docs/book/spell-check-custom-words.txt
  docs/book/src/SUMMARY.md
  docs/book/src/examples/index.md
  docs/book/src/examples/subcurrency.md
  docs/book/src/sway-program-types/smart_contracts.md
  examples/Forc.lock
  examples/Forc.toml
  examples/subcurrency/Forc.toml
  examples/subcurrency/src/main.sw
Labels: The Sway Book

#5494 ci: switch katyo/publish-crates@v2 to xgreenx/publish-crates@v1
  .github/workflows/ci.yml
Labels: bug, ci

#5495 chore: bump version to 0.49.1
  Cargo.lock
  docs/reference/src/documentation/introduction/installation/cargo.md
  docs/reference/src/documentation/introduction/installation/index.md
  docs/reference/src/documentation/introduction/installation/source.md
  docs/reference/src/index.md
  forc-pkg/Cargo.toml
  forc-plugins/forc-client/Cargo.toml
  forc-plugins/forc-crypto/Cargo.toml
  forc-plugins/forc-debug/Cargo.toml
  forc-plugins/forc-doc/Cargo.toml
  forc-plugins/forc-fmt/Cargo.toml
  forc-plugins/forc-lsp/Cargo.toml
  forc-plugins/forc-tx/Cargo.toml
  forc-test/Cargo.toml
  forc-tracing/Cargo.toml
  forc-util/Cargo.toml
  forc/Cargo.toml
  sway-ast/Cargo.toml
  sway-core/Cargo.toml
  sway-error/Cargo.toml
  sway-ir/Cargo.toml
  sway-ir/sway-ir-macros/Cargo.toml
  sway-lsp/Cargo.toml
  sway-parse/Cargo.toml
  sway-types/Cargo.toml
  sway-utils/Cargo.toml
  swayfmt/Cargo.toml
Labels: release

#5497 Forbid configurables in constants
  sway-core/src/ir_generation/const_eval.rs
  sway-core/src/ir_generation/function.rs
  sway-core/src/semantic_analysis/ast_node/declaration/storage.rs
  test/src/e2e_vm_tests/test_programs/should_fail/configurables_are_not_const/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/configurables_are_not_const/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/configurables_are_not_const/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/configurables_are_not_const/test.toml
Labels: breaking

#5501 Change auto_import test to use git tag of std lib
  sway-lsp/tests/fixtures/auto_import/Forc.toml
Labels: language server

#5516 LSP Optimization: Remove `ParseResult` and write to session types directly
  sway-lsp/benches/lsp_benchmarks/compile.rs
  sway-lsp/benches/lsp_benchmarks/mod.rs
  sway-lsp/src/core/session.rs
  sway-lsp/src/server_state.rs
Labels: language server

#5509 Significant `TokenMap` optimisation by removing clones and returning refs instead.
  sway-lsp/src/capabilities/code_actions/diagnostic/auto_import.rs
  sway-lsp/src/capabilities/code_actions/mod.rs
  sway-lsp/src/capabilities/code_actions/struct_decl/struct_new.rs
  sway-lsp/src/capabilities/document_symbol.rs
  sway-lsp/src/capabilities/hover/mod.rs
  sway-lsp/src/capabilities/inlay_hints.rs
  sway-lsp/src/capabilities/rename.rs
  sway-lsp/src/capabilities/semantic_tokens.rs
  sway-lsp/src/core/session.rs
  sway-lsp/src/core/token_map.rs
  sway-lsp/src/core/token_map_ext.rs
  sway-lsp/src/utils/debug.rs
Labels: language server

#5259 Redesign From trait into From/Into pair
  docs/reference/src/code/operations/namespace/src/lib.sw
  sway-lib-std/src/address.sw
  sway-lib-std/src/asset_id.sw
  sway-lib-std/src/b512.sw
  sway-lib-std/src/bytes.sw
  sway-lib-std/src/bytes_conversions/b256.sw
  sway-lib-std/src/bytes_conversions/u256.sw
  sway-lib-std/src/contract_id.sw
  sway-lib-std/src/convert.sw
  sway-lib-std/src/primitive_conversions/u64.sw
  sway-lib-std/src/string.sw
  sway-lib-std/src/u128.sw
  sway-lib-std/src/u256.sw
  sway-lib-std/src/vec.sw
  sway-lib-std/src/vm/evm/evm_address.sw
  test/src/e2e_vm_tests/test_programs/should_fail/generic_trait_tuple_without_type_ascription/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/generic_trait_tuple_without_type_ascription/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/const_decl_with_call_path/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/generic_trait_constraints/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/caller_context_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/address_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/b512_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/contract_id_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/contract_id_type/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/u256_test/src/main.sw
  test/src/sdk-harness/test_artifacts/context_caller_contract/src/main.sw
  test/src/sdk-harness/test_projects/ec_recover/src/main.sw
  test/src/sdk-harness/test_projects/evm_ec_recover/src/main.sw
Labels: breaking

#5526 Fixes associated type not found in libraries.
  sway-core/src/semantic_analysis/namespace/module.rs
  sway-core/src/semantic_analysis/namespace/root.rs
  sway-core/src/semantic_analysis/type_check_context.rs
  test/src/e2e_vm_tests/test_programs/should_pass/language/associated_type_container_in_library/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/associated_type_container_in_library/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/associated_type_container_in_library/src/container.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/associated_type_container_in_library/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/associated_type_container_in_library/test.toml
Labels: P: high, compiler: frontend

#5528 Fix ABI when logging generic types
  sway-core/src/abi_generation/fuel_abi.rs
Labels: bug, compiler

#5532 Fix missing shadowing errors due to error deduplication
  sway-core/src/semantic_analysis/namespace/items.rs
  sway-core/src/semantic_analysis/namespace/module.rs
  sway-error/src/error.rs
  test/src/e2e_vm_tests/test_programs/should_fail/deduplication_of_shadowing_errors/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/deduplication_of_shadowing_errors/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/deduplication_of_shadowing_errors/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_fail/deduplication_of_shadowing_errors/src/lib.sw
  test/src/e2e_vm_tests/test_programs/should_fail/deduplication_of_shadowing_errors/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/deduplication_of_shadowing_errors/test.toml
Labels: bug, compiler, compiler: frontend
