Repository FuelLabs/sway, pull requests merged in 2024-06, with the labels that each got.

#6090 chore: bump fuel-core to v0.27.0
  Cargo.lock
  Cargo.toml
  forc-pkg/src/manifest/mod.rs
  forc-pkg/src/pkg.rs
  test/src/e2e_vm_tests/test_programs/should_fail/contract_dependencies_conflicting_salt/contract_a/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/forc/contract_dependencies/contract_a/Forc.toml
  test/src/sdk-harness/Cargo.lock
  test/src/sdk-harness/Cargo.toml
Labels: dependencies

#6095 Update codeowners `application-dev` to `swayex`
  .github/CODEOWNERS
Labels: P: critical

#6105 Add primitive conversions submodules to the prelude
  docs/book/src/basics/converting_types.md
  examples/converting_types/src/strings.sw
  examples/converting_types/src/to_u16.sw
  examples/converting_types/src/to_u32.sw
  examples/converting_types/src/to_u64.sw
  examples/converting_types/src/to_u8.sw
  sway-lib-std/src/prelude.sw
  test/src/e2e_vm_tests/reduced_std_libs/sway-lib-std-conversions/src/prelude.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/fqp_in_lib/src/lib.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/integer_type_inference/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/method_indirect_inference/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/method_unambiguous/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/issue_1512_repro/src/main.sw
  test/src/sdk-harness/test_projects/asset_ops/src/main.sw
Labels: lib: std

#5967 Adds method and function deduplication to frontend.
  sway-core/src/ir_generation/compile.rs
  sway-core/src/language/ty/declaration/function.rs
  sway-core/src/query_engine/mod.rs
  sway-core/src/semantic_analysis/ast_node/declaration/function.rs
  sway-core/src/semantic_analysis/ast_node/declaration/trait_fn.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/function_application.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/method_application.rs
  sway-core/src/type_system/id.rs
  sway-core/src/type_system/info.rs
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/asset_ops_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_basic_storage/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_increment_contract/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_storage_enum/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/storage_access_caller/src/main.sw
  test/src/ir_generation/tests/fn_dedup.sw
Labels: compiler: frontend, performance

#6135 Change `StorageMap`'s `remove()` to use `sha256(key, self.field_id())` instead of `sha256(key, self.slot())`
  sway-lib-std/src/storage/storage_map.sw
  test/src/sdk-harness/test_projects/storage_map_nested/src/main.sw
Labels: bug, lib: std

#6136 Resolve memory overflow when `b256::TryFrom<Bytes>` is not 32 bytes
  sway-lib-std/src/primitive_conversions/b256.sw
  test/src/in_language_tests/test_programs/primitive_conversions_b256_inline_tests/src/main.sw
Labels: bug, lib: std

#6117 Add `Input::Message` case to `predicate_address()`
  sway-lib-std/src/auth.sw
  test/src/sdk-harness/test_projects/auth/mod.rs
Labels: bug, lib: std

#6165 fix: fix panic and improve error output in forc-debug
  Cargo.lock
  forc-plugins/forc-debug/Cargo.toml
  forc-plugins/forc-debug/src/main.rs
Labels: forc-debug

#6175 Incomplete escape analysis and referred symbols in IR optimizations
  sway-core/src/asm_generation/fuel/fuel_asm_builder.rs
  sway-core/src/ir_generation.rs
  sway-core/src/ir_generation/compile.rs
  sway-ir/src/analysis/memory_utils.rs
  sway-ir/src/function.rs
  sway-ir/src/optimize/dce.rs
  sway-ir/src/optimize/inline.rs
  sway-ir/src/optimize/memcpyopt.rs
  sway-ir/src/optimize/sroa.rs
  sway-ir/src/parser.rs
  sway-ir/src/printer.rs
  sway-ir/tests/dce/dce_cast_ptr.ir
  sway-ir/tests/dce/dce_dead_config_assignment.ir
  sway-ir/tests/dce/dce_dead_constant_assignment.ir
  sway-ir/tests/dce/dce_int_to_ptr.ir
  sway-ir/tests/dce/dce_load_from_b256.ir
  sway-ir/tests/dce/dce_load_from_struct.ir
  test/src/e2e_vm_tests/test_programs/should_pass/language/abort_control_flow_good/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/break_and_continue_block_ret/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/configurable_consts/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/language/configurable_consts/json_abi_oracle_new_encoding.json
  test/src/e2e_vm_tests/test_programs/should_pass/language/slice/slice_contract/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/string_slice/string_slice_contract/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/u256/u256_abi/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/language/u256/u256_abi/json_abi_oracle_new_encoding.json
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/array_of_structs_caller/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/asset_ops_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/bal_opcode/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_abi_with_tuples/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_basic_storage/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_contract_with_type_aliases/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_increment_contract/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_storage_enum/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/caller_auth_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/caller_context_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/nested_struct_args_caller/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/storage_access_caller/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/test_abis/abi_with_tuples/src/some_module.sw
  test/src/e2e_vm_tests/test_programs/should_pass/unit_tests/workspace_test/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/unit_tests/workspace_test/contract_multi_test/src/main.sw
  test/src/sdk-harness/test_projects/auth/mod.rs
Labels: compiler, compiler: ir, P: high, compiler: optimization

#6168 Remove `storage_vec_to_vec` inline tests from sdk-harness
  test/src/sdk-harness/test_projects/storage_vec_to_vec/src/main.sw
Labels: testing

#6177 Verify that entry block does not have predecessors
  sway-ir/src/error.rs
  sway-ir/src/verify.rs
  sway-ir/tests/tests.rs
  sway-ir/tests/verify/entry_block_dominance_frontier.ir
  sway-ir/tests/verify/entry_block_mem2reg.ir
  sway-ir/tests/verify/entry_block_simplify_cfg.ir
Labels: compiler, compiler: ir

#6186 Use `$one` for `true` in ASM instead of using data section
  sway-core/src/asm_generation/fuel/fuel_asm_builder.rs
  test/src/e2e_vm_tests/test_programs/should_pass/language/configurable_consts/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_pass/language/configurable_consts/json_abi_oracle_new_encoding.json
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_abi_with_tuples/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_basic_storage/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_storage_enum/src/main.sw
Labels: compiler, compiler: codegen

#6181 fix: only support hover links for vscode
  sway-lsp/benches/lsp_benchmarks/requests.rs
  sway-lsp/src/capabilities/hover/mod.rs
  sway-lsp/src/config.rs
  sway-lsp/src/handlers/request.rs
  sway-lsp/src/utils/markup.rs
  sway-lsp/tests/lib.rs
Labels: language server

#6187 chore: bump fuels-rs to v0.64.0, fuel-core to v0.28.0
  Cargo.lock
  Cargo.toml
  forc-plugins/forc-client/src/util/gas.rs
  forc-plugins/forc-client/src/util/tx.rs
  forc-test/src/execute.rs
  forc-test/src/lib.rs
  test/src/e2e_vm_tests/harness.rs
  test/src/sdk-harness/Cargo.lock
  test/src/sdk-harness/Cargo.toml
  test/src/sdk-harness/test_projects/asset_ops/mod.rs
  test/src/sdk-harness/test_projects/predicate_data_simple/mod.rs
  test/src/sdk-harness/test_projects/predicate_data_struct/mod.rs
  test/src/sdk-harness/test_projects/run_external_proxy/mod.rs
  test/src/sdk-harness/test_projects/script_data/mod.rs
  test/src/sdk-harness/test_projects/storage_vec_of_storage_string/mod.rs
  test/src/sdk-harness/test_projects/string_slice/mod.rs
  test/src/sdk-harness/test_projects/tx_fields/mod.rs
Labels: dependencies
