Repository FuelLabs/sway, pull requests merged in 2025-05, with the labels that each got.

#7140 chore: bump to 0.68.2
  Cargo.lock
  Cargo.toml
Labels: release

#7133 sway-book: fix forc call examples
  docs/book/src/SUMMARY.md
  docs/book/src/forc/plugins/forc_client/forc_call.md
  docs/book/src/testing/testing_with_forc_call.md
  forc-plugins/forc-client/src/cmd/call.rs
Labels: good first issue, The Sway Book, documentation, forc-call

#7145 sway-lsp: Fix the double read-lock bug in session
  sway-lsp/src/core/session.rs
Labels: language server, cla:signed

#7148 Add documentation for the `abi` keyword for LSP
  sway-lsp/src/utils/keyword_docs.rs
Labels: language server

#7109 codegen optimization: symbolic fuel-vm interpretation
  forc-plugins/forc-client/tests/deploy.rs
  forc-plugins/forc-debug/tests/server_integration.rs
  forc/tests/cli_integration.rs
  sway-core/src/asm_generation/fuel/abstract_instruction_set.rs
  sway-core/src/asm_generation/fuel/fuel_asm_builder.rs
  sway-core/src/asm_generation/fuel/optimizations/const_indexed_aggregates.rs
  sway-core/src/asm_generation/fuel/optimizations/constant_propagate.rs
  sway-core/src/asm_generation/fuel/optimizations/misc.rs
  sway-core/src/asm_generation/fuel/optimizations/mod.rs
  sway-core/src/asm_generation/fuel/optimizations/reachability.rs
  sway-core/src/asm_generation/fuel/optimizations/verify.rs
  sway-core/src/asm_generation/fuel/programs/abstract.rs
  sway-core/src/asm_lang/mod.rs
  sway-core/src/asm_lang/virtual_ops.rs
  sway-core/src/build_config.rs
  test/src/e2e_vm_tests/test_programs/should_fail/language/const_generics/stdout.snap
  test/src/e2e_vm_tests/test_programs/should_pass/language/attributes_deprecated/stdout.snap
  test/src/e2e_vm_tests/test_programs/should_pass/language/configurable_consts/json_abi_oracle_new_encoding.json
  test/src/e2e_vm_tests/test_programs/should_pass/language/configurable_dedup_decode/stdout.snap
  test/src/e2e_vm_tests/test_programs/should_pass/language/intrinsics/dbg/stdout.snap
  test/src/e2e_vm_tests/test_programs/should_pass/language/intrinsics/dbg_release/stdout.snap
  test/src/e2e_vm_tests/test_programs/should_pass/language/panic_expression/panicking_contract/stdout.snap
  test/src/e2e_vm_tests/test_programs/should_pass/language/panic_expression/panicking_lib/stdout.snap
  test/src/e2e_vm_tests/test_programs/should_pass/language/panic_expression/panicking_script/stdout.snap
  test/src/e2e_vm_tests/test_programs/should_pass/language/u256/u256_abi/json_abi_oracle_new_encoding.json
  test/src/e2e_vm_tests/test_programs/should_pass/panic_in_non_statement_positions/stdout.snap
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/array_of_structs_caller/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/asset_ops_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/bal_opcode/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_abi_with_tuples/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_basic_storage/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_contract_with_type_aliases/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_increment_contract/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_storage_enum/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/caller_auth_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/caller_context_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/nested_struct_args_caller/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/storage_access_caller/src/main.sw
  test/src/ir_generation/mod.rs
  test/src/ir_generation/tests/asm_block.sw
  test/src/ir_generation/tests/fn_call.sw
  test/src/ir_generation/tests/fn_call_noargs_nolocals.sw
  test/src/ir_generation/tests/fn_call_nolocals.sw
  test/src/ir_generation/tests/predicate_data_mult_args.sw
  test/src/ir_generation/tests/predicate_data_single_arg.sw
  test/src/sdk-harness/test_projects/auth/mod.rs
Labels: compiler: codegen

#7147 Replace Tokio Thread File Watcher with LSP Client File Watcher
  Cargo.lock
  Cargo.toml
  sway-lsp/Cargo.toml
  sway-lsp/src/core/session.rs
  sway-lsp/src/core/sync.rs
  sway-lsp/src/error.rs
  sway-lsp/src/handlers/notification.rs
  sway-lsp/src/server.rs
  sway-lsp/src/server_state.rs
  sway-lsp/tests/integration/lsp.rs
  sway-lsp/tests/lib.rs
Labels: language server

#7122 Rename AllocatedOpcode to AllocatedInstruction to follow fuel-spec/fuel-asm terminology
  sway-core/src/asm_generation/finalized_asm.rs
  sway-core/src/asm_generation/fuel/allocated_abstract_instruction_set.rs
  sway-core/src/asm_generation/fuel/checks.rs
  sway-core/src/asm_generation/fuel/programs/abstract.rs
  sway-core/src/asm_lang/allocated_ops.rs
  sway-core/src/asm_lang/mod.rs
  sway-core/src/asm_lang/virtual_ops.rs
Labels: cla:signed

#7155 Support new expiry policy in std-lib
  sway-lib-std/src/tx.sw
  test/src/sdk-harness/test_artifacts/tx_contract/src/main.sw
  test/src/sdk-harness/test_projects/tx_fields/mod.rs
Labels: lib: std

#7151 Optimize `crypto` module for bytecode size and gas usage
  sway-lib-std/src/bytes.sw
  sway-lib-std/src/crypto/ed25519.sw
  sway-lib-std/src/crypto/message.sw
  sway-lib-std/src/crypto/point2d.sw
  sway-lib-std/src/crypto/public_key.sw
  sway-lib-std/src/crypto/scalar.sw
  sway-lib-std/src/crypto/secp256k1.sw
  sway-lib-std/src/crypto/secp256r1.sw
Labels: lib: std

#7154 ci: Ensure that std-lib version matches forc version
  .github/workflows/ci.yml
  .github/workflows/scripts/check-forc-manifest-version/Cargo.lock
  .github/workflows/scripts/check-forc-manifest-version/Cargo.toml
  .github/workflows/scripts/check-forc-manifest-version/src/main.rs
  sway-lib-std/Forc.toml
Labels: ci

#7146 Support doc comments and attributes on nested items
  sway-parse/src/expr/mod.rs
  sway-parse/src/item/mod.rs
  test/src/e2e_vm_tests/test_programs/should_fail/attributes_missing_annotated_item/src/nested_annotations.sw
  test/src/e2e_vm_tests/test_programs/should_fail/attributes_missing_annotated_item/stdout.snap
Labels: cla:signed

#7162 Optimize `vec` and `bytes` modules for bytecode size and gas usage
  sway-lib-std/src/bytes.sw
  sway-lib-std/src/vec.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/configurable_consts/json_abi_oracle_new_encoding.json
  test/src/e2e_vm_tests/test_programs/should_pass/language/intrinsics/dbg/stdout.snap
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_basic_storage/src/main.sw
  test/src/in_language_tests/test_programs/crypto_ed25519_inline_tests/src/main.sw
  test/src/in_language_tests/test_programs/crypto_secp256k1_inline_tests/src/main.sw
  test/src/in_language_tests/test_programs/crypto_secp256r1_inline_tests/src/main.sw
Labels: lib: std

#7164 Remove double IR-compilation of contract methods
  forc-plugins/forc-client/tests/deploy.rs
  forc/tests/cli_integration.rs
  sway-core/src/ir_generation/compile.rs
  sway-ir/src/printer.rs
  test/src/e2e_vm_tests/test_programs/should_pass/language/attributes_deprecated/stdout.snap
  test/src/e2e_vm_tests/test_programs/should_pass/language/panic_expression/panicking_contract/stdout.snap
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/array_of_structs_caller/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/asset_ops_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/bal_opcode/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_basic_storage/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_contract_with_type_aliases/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_increment_contract/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/caller_context_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/storage_access_caller/src/main.sw
Labels: compiler, compiler: ir

#7167 chore: bump to 0.68.3
  Cargo.lock
  Cargo.toml
  sway-lib-std/Forc.toml
Labels: release

#7166 Refactor: Move `SyncWorkspace` from `Session` into `ServerState`
  sway-core/src/semantic_analysis/namespace/package.rs
  sway-lsp/benches/lsp_benchmarks/compile.rs
  sway-lsp/benches/lsp_benchmarks/mod.rs
  sway-lsp/benches/lsp_benchmarks/requests.rs
  sway-lsp/benches/lsp_benchmarks/token_map.rs
  sway-lsp/src/capabilities/hover/hover_link_contents.rs
  sway-lsp/src/capabilities/hover/mod.rs
  sway-lsp/src/capabilities/rename.rs
  sway-lsp/src/core/document.rs
  sway-lsp/src/core/mod.rs
  sway-lsp/src/core/session.rs
  sway-lsp/src/core/sync.rs
  sway-lsp/src/error.rs
  sway-lsp/src/handlers/notification.rs
  sway-lsp/src/handlers/request.rs
  sway-lsp/src/lib.rs
  sway-lsp/src/server.rs
  sway-lsp/src/server_state.rs
  sway-lsp/tests/fixtures/diagnostics/dead_code/Forc.toml
  sway-lsp/tests/fixtures/diagnostics/multi_file/Forc.toml
  sway-lsp/tests/integration/lsp.rs
  sway-lsp/tests/lib.rs
  sway-lsp/tests/utils/src/lib.rs
Labels: language server

#7178 feat: use SSE in forc-publish for long-running uploads
  Cargo.lock
  Cargo.toml
  forc-plugins/forc-publish/Cargo.toml
  forc-plugins/forc-publish/src/error.rs
  forc-plugins/forc-publish/src/forc_pub_client.rs
  forc-plugins/forc-publish/src/main.rs
Labels: forc-publish

#7139 Use a workspace level `TokenMap` and `Engines`
  sway-lsp/benches/lsp_benchmarks/compile.rs
  sway-lsp/benches/lsp_benchmarks/mod.rs
  sway-lsp/benches/lsp_benchmarks/requests.rs
  sway-lsp/benches/lsp_benchmarks/token_map.rs
  sway-lsp/src/capabilities/code_actions/mod.rs
  sway-lsp/src/capabilities/highlight.rs
  sway-lsp/src/capabilities/hover/mod.rs
  sway-lsp/src/capabilities/inlay_hints.rs
  sway-lsp/src/capabilities/rename.rs
  sway-lsp/src/capabilities/semantic_tokens.rs
  sway-lsp/src/core/session.rs
  sway-lsp/src/core/token.rs
  sway-lsp/src/core/token_map.rs
  sway-lsp/src/handlers/notification.rs
  sway-lsp/src/handlers/request.rs
  sway-lsp/src/server.rs
  sway-lsp/src/server_state.rs
  sway-lsp/src/traverse/lexed_tree.rs
  sway-lsp/src/utils/attributes.rs
  sway-lsp/src/utils/markup.rs
  sway-lsp/tests/integration/lsp.rs
  sway-lsp/tests/lib.rs
Labels: language server, performance

#7183 ci: install Forc plugins by iterating the plugins in the forc-plugins directory
  .github/workflows/ci.yml
Labels: ci, cla:signed

#7189 fix: Prevent panic in semantic highlighting for unknown token types
  sway-lsp/src/capabilities/semantic_tokens.rs
  sway-lsp/tests/lib.rs
  sway-lsp/tests/utils/src/lib.rs
Labels: bug, language server

#7190 Check for typed program errors before unwrapping to prevent panics.
  sway-lsp/src/core/session.rs
Labels: language server

#7143 feat: implement `forc add` and `forc remove` to add/remove dependencies
  Cargo.lock
  Cargo.toml
  docs/book/src/SUMMARY.md
  docs/book/src/forc/commands/forc_add.md
  docs/book/src/forc/commands/forc_remove.md
  docs/book/src/forc/dependencies.md
  forc-pkg/Cargo.toml
  forc-pkg/src/manifest/dep_modifier.rs
  forc-pkg/src/manifest/mod.rs
  forc/src/cli/commands/add.rs
  forc/src/cli/commands/mod.rs
  forc/src/cli/commands/remove.rs
  forc/src/cli/mod.rs
  forc/src/cli/shared.rs
Labels: cla:signed

#7194 fix: ensure forc-node ignition fetches ignition chain config
  forc-plugins/forc-node/src/consts.rs
  forc-plugins/forc-node/src/ignition/op.rs
Labels: forc-node

#7208 feat: more descriptive publish error message for forc-publish
  forc-plugins/forc-publish/src/error.rs
Labels: enhancement, forc-publish

#7196 feat: forc call tracing
  Cargo.lock
  docs/book/src/testing/testing_with_forc_call.md
  forc-plugins/forc-client/Cargo.toml
  forc-plugins/forc-client/src/op/call/call_function.rs
  forc-plugins/forc-client/src/op/call/mod.rs
  forc-plugins/forc-client/src/op/call/transaction_trace.rs
  forc-plugins/forc-client/src/op/call/transfer.rs
Labels: enhancement, forc, dev-experience, forc-call, team:tooling

#7206 Introduce the Time Library
  docs/book/spell-check-custom-words.txt
  docs/book/src/SUMMARY.md
  docs/book/src/blockchain-development/time.md
  examples/Forc.lock
  examples/Forc.toml
  examples/time/Forc.toml
  examples/time/src/main.sw
  sway-lib-std/src/block.sw
  sway-lib-std/src/lib.sw
  sway-lib-std/src/time.sw
  test/src/in_language_tests/Forc.toml
  test/src/in_language_tests/test_programs/time_inline_tests/Forc.toml
  test/src/in_language_tests/test_programs/time_inline_tests/src/main.sw
  test/src/sdk-harness/Forc.lock
  test/src/sdk-harness/Forc.toml
  test/src/sdk-harness/test_projects/harness.rs
  test/src/sdk-harness/test_projects/time/Forc.toml
  test/src/sdk-harness/test_projects/time/mod.rs
  test/src/sdk-harness/test_projects/time/src/main.sw
Labels: enhancement, lib: std
