Repository FuelLabs/sway, pull requests merged in 2025-02, with the labels that each got.

#6856 `forc-debug`: Add ABI support for decoding log values
  Cargo.lock
  docs/book/spell-check-custom-words.txt
  docs/book/src/debugging/debugging_with_cli.md
  forc-plugins/forc-debug/Cargo.toml
  forc-plugins/forc-debug/examples/example_abi.json
  forc-plugins/forc-debug/examples/example_tx.json
  forc-plugins/forc-debug/src/cli/commands.rs
  forc-plugins/forc-debug/src/cli/state.rs
  forc-plugins/forc-debug/src/error.rs
  forc-plugins/forc-debug/src/types.rs
  forc-plugins/forc-debug/tests/cli_integration.rs
Labels: documentation, forc-debug

#6832 Std-lib support for ZK opcodes
  sway-lib-std/src/crypto.sw
  sway-lib-std/src/crypto/alt_bn128.sw
  sway-lib-std/src/crypto/point2d.sw
  sway-lib-std/src/crypto/scalar.sw
  sway-lib-std/src/crypto/signature_error.sw
  test/src/in_language_tests/Forc.toml
  test/src/in_language_tests/test_programs/crypto_point2d_inline_tests/Forc.toml
  test/src/in_language_tests/test_programs/crypto_point2d_inline_tests/src/main.sw
  test/src/in_language_tests/test_programs/crypto_scalar_inline_tests/Forc.toml
  test/src/in_language_tests/test_programs/crypto_scalar_inline_tests/src/main.sw
  test/src/in_language_tests/test_programs/crypto_zk_inline_tests/Forc.toml
  test/src/in_language_tests/test_programs/crypto_zk_inline_tests/src/main.sw
Labels: enhancement, lib: std

#6791 plugin: forc-call
  Cargo.lock
  docs/book/spell-check-custom-words.txt
  docs/book/src/SUMMARY.md
  docs/book/src/forc/plugins/forc_client/forc_call.md
  forc-plugins/forc-client/Cargo.toml
  forc-plugins/forc-client/src/bin/call.rs
  forc-plugins/forc-client/src/cmd/call.rs
  forc-plugins/forc-client/src/cmd/mod.rs
  forc-plugins/forc-client/src/constants.rs
  forc-plugins/forc-client/src/lib.rs
  forc-plugins/forc-client/src/op/call/missing_contracts.rs
  forc-plugins/forc-client/src/op/call/mod.rs
  forc-plugins/forc-client/src/op/call/parser.rs
  forc-plugins/forc-client/src/op/mod.rs
  forc-plugins/forc-client/src/util/node_url.rs
  forc-plugins/forc-client/src/util/target.rs
  forc-plugins/forc-client/src/util/tx.rs
  forc-plugins/forc-client/test/data/contract_with_types/Forc.toml
  forc-plugins/forc-client/test/data/contract_with_types/contract_with_types-abi.json
  forc-plugins/forc-client/test/data/contract_with_types/contract_with_types-storage_slots.json
  forc-plugins/forc-client/test/data/contract_with_types/contract_with_types.bin
  forc-plugins/forc-client/test/data/contract_with_types/src/main.sw
  forc-plugins/forc-client/tests/deploy.rs
  forc-plugins/forc-tx/Cargo.toml
  forc-plugins/forc-tx/src/lib.rs
  swayfmt/src/parse.rs
  test/src/sdk-harness/test_projects/tx_fields/mod.rs
Labels: ABI, forc-client, forc-call

#6842 CompileError::ContractIdConstantNotAConstDecl
  sway-core/src/semantic_analysis/namespace/contract_helpers.rs
  sway-error/src/error.rs
Labels: cla:signed

#6871 Implement marker traits
  .github/workflows/ci.yml
  docs/book/src/advanced/traits.md
  sway-core/src/language/call_path.rs
  sway-core/src/lib.rs
  sway-core/src/marker_traits.rs
  sway-core/src/semantic_analysis/ast_node/declaration/auto_impl/abi_encoding.rs
  sway-core/src/semantic_analysis/ast_node/declaration/auto_impl/marker_traits.rs
  sway-core/src/semantic_analysis/ast_node/declaration/auto_impl/mod.rs
  sway-core/src/semantic_analysis/ast_node/declaration/impl_trait.rs
  sway-core/src/semantic_analysis/module.rs
  sway-core/src/semantic_analysis/namespace/trait_map.rs
  sway-core/src/type_system/ast_elements/type_parameter.rs
  sway-core/src/type_system/unify/unify_check.rs
  sway-error/src/error.rs
  sway-features/src/lib.rs
  sway-lib-core/src/lib.sw
  sway-lib-core/src/marker.sw
  sway-lib-core/src/prelude.sw
  test/src/e2e_vm_tests/test_programs/should_fail/invalid_cfg_arg/stdout.snap
  test/src/e2e_vm_tests/test_programs/should_fail/language/import_star_name_clash/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/marker_trait_cannot_be_explicitly_implemented/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/marker_trait_cannot_be_explicitly_implemented/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/marker_trait_cannot_be_explicitly_implemented/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/marker_trait_cannot_be_explicitly_implemented/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/marker_trait_enum_not_implemented_for_non_enum/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/marker_trait_enum_not_implemented_for_non_enum/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/marker_trait_enum_not_implemented_for_non_enum/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/marker_trait_enum_not_implemented_for_non_enum/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/marker_trait_error_not_implemented_for_non_error_types/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/marker_trait_error_not_implemented_for_non_error_types/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/marker_trait_error_not_implemented_for_non_error_types/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/marker_trait_error_not_implemented_for_non_error_types/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/marker_traits/marker_trait_enum_implemented_for_all_enums/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/marker_traits/marker_trait_enum_implemented_for_all_enums/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/marker_traits/marker_trait_enum_implemented_for_all_enums/src/enums_01.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/marker_traits/marker_trait_enum_implemented_for_all_enums/src/enums_02.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/marker_traits/marker_trait_enum_implemented_for_all_enums/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/marker_traits/marker_trait_enum_implemented_for_all_enums/src/use_error_explicitly.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/marker_traits/marker_trait_enum_implemented_for_all_enums/src/use_error_via_glob.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/marker_traits/marker_trait_enum_implemented_for_all_enums/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/marker_traits/marker_trait_error_implemented_for_str/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/marker_traits/marker_trait_error_implemented_for_str/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/marker_traits/marker_trait_error_implemented_for_str/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/marker_traits/marker_trait_error_implemented_for_str/src/use_error_explicitly.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/marker_traits/marker_trait_error_implemented_for_str/src/use_error_via_glob.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/marker_traits/marker_trait_error_implemented_for_str/test.toml
  test/src/in_language_tests/test_programs/storage_vec_iter_tests/src/main.sw
Labels: compiler, language feature, compiler: frontend

#5909 Fixes argument errors not displayed.
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/method_application.rs
  test/src/e2e_vm_tests/test_programs/should_fail/variable_does_not_exist/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/variable_does_not_exist/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/variable_does_not_exist/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/variable_does_not_exist/test.toml
Labels: bug, compiler: frontend

#6888 feat: disallow dependency package name collision in forc-pkg
  forc-pkg/src/manifest/mod.rs
Labels: bug, forc-pkg

#6902 fix: remove invalid unpacking logic for IPFS pinned pkg sources
  Cargo.lock
  Cargo.toml
  forc-pkg/Cargo.toml
  forc-pkg/src/source/ipfs.rs
Labels: bug, forc-pkg, forc-registry

#6890 feat: Add forc-publish plugin
  Cargo.lock
  Cargo.toml
  forc-plugins/forc-publish/Cargo.toml
  forc-plugins/forc-publish/README.md
  forc-plugins/forc-publish/src/credentials.rs
  forc-plugins/forc-publish/src/error.rs
  forc-plugins/forc-publish/src/forc_pub_client.rs
  forc-plugins/forc-publish/src/lib.rs
  forc-plugins/forc-publish/src/main.rs
  forc-plugins/forc-publish/src/tarball.rs
Labels: forc-publish

#6867 Removes TraitMap::insert_for_type.
  sway-core/src/language/ty/declaration/function.rs
  sway-core/src/language/ty/expression/expression_variant.rs
  sway-core/src/semantic_analysis/ast_node/declaration/abi.rs
  sway-core/src/semantic_analysis/ast_node/declaration/impl_trait.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/method_application.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression/struct_instantiation.rs
  sway-core/src/semantic_analysis/namespace/mod.rs
  sway-core/src/semantic_analysis/namespace/root.rs
  sway-core/src/semantic_analysis/namespace/trait_map.rs
  sway-core/src/semantic_analysis/type_check_analysis.rs
  sway-core/src/semantic_analysis/type_check_context.rs
  sway-core/src/type_system/ast_elements/type_parameter.rs
  sway-core/src/type_system/id.rs
  sway-core/src/type_system/substitute/subst_map.rs
  sway-core/src/type_system/unify/unify_check.rs
  test/src/e2e_vm_tests/test_programs/should_fail/for_mismatch_pattern_type/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/generic_traits/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/generic_traits_bad_type_inference/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/generics_in_contract/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/type_alias_shadowing_methods/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/type_propagation/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/vec/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/asset_id_into_bytes/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/asset_id_into_bytes/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/asset_id_into_bytes/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/stdlib/asset_id_into_bytes/test.toml
Labels: code quality, compiler: frontend

#6473 feat: add forc-node command for easily bootstrapping a node
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  docs/book/src/SUMMARY.md
  docs/book/src/forc/plugins/forc_node.md
  forc-plugins/forc-node/Cargo.toml
  forc-plugins/forc-node/src/chain_config.rs
  forc-plugins/forc-node/src/cmd.rs
  forc-plugins/forc-node/src/consts.rs
  forc-plugins/forc-node/src/ignition/cmd.rs
  forc-plugins/forc-node/src/ignition/mod.rs
  forc-plugins/forc-node/src/ignition/op.rs
  forc-plugins/forc-node/src/lib.rs
  forc-plugins/forc-node/src/local/cmd.rs
  forc-plugins/forc-node/src/local/mod.rs
  forc-plugins/forc-node/src/local/op.rs
  forc-plugins/forc-node/src/main.rs
  forc-plugins/forc-node/src/op.rs
  forc-plugins/forc-node/src/run_opts.rs
  forc-plugins/forc-node/src/testnet/cmd.rs
  forc-plugins/forc-node/src/testnet/mod.rs
  forc-plugins/forc-node/src/testnet/op.rs
  forc-plugins/forc-node/src/util.rs
  forc-plugins/forc-node/tests/local.rs
Labels: enhancement, forc

#6939 docs: added a twitter shield
  README.md
Labels: cla:signed

#6940 Fix issue with `__transmute` type checking
  sway-core/src/ir_generation/const_eval.rs
  sway-core/src/semantic_analysis/ast_node/expression/intrinsic_function.rs
  test/src/e2e_vm_tests/test_programs/should_pass/language/const_inits/src/main.sw
Labels: bug

#6947 ECAL opcode support
  sway-ast/src/expr/op_code.rs
  sway-core/src/asm_lang/allocated_ops.rs
  sway-core/src/asm_lang/mod.rs
  sway-core/src/asm_lang/virtual_ops.rs
  sway-parse/src/expr/op_code.rs
  test/src/e2e_vm_tests/test_programs/should_pass/ecall/ecall_basic/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/ecall/ecall_basic/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/ecall/ecall_basic/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/ecall/ecall_basic/test.toml
Labels: enhancement, compiler

#6944 Extend `#[deprecated]` support
  sway-core/src/language/ty/code_block.rs
  sway-core/src/language/ty/expression/expression.rs
  sway-lib-std/src/ecr.sw
  sway-lib-std/src/vm/evm/ecr.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/deprecated/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/deprecated/test.toml
Labels: team:compiler

#6964 Allow `ldc` opcode in predicates
  sway-core/src/asm_generation/fuel/checks.rs
  test/src/e2e_vm_tests/test_programs/should_fail/predicate_invalid_opcodes/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/predicate_invalid_opcodes/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/asm/instructions/ldc/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/asm/instructions/ldc/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/asm/instructions/ldc/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/asm/instructions/ldc/test.toml
Labels: compiler, compiler: codegen

#6959 Add `ProgramId` to root module.
  forc-pkg/src/pkg.rs
  sway-core/src/ir_generation/const_eval.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/namespace/contract_helpers.rs
  sway-core/src/semantic_analysis/namespace/root.rs
  sway-lsp/src/core/session.rs
  sway-types/src/source_engine.rs
  test/src/ir_generation/mod.rs
Labels: compiler: frontend
