Repository FuelLabs/sway, pull requests merged in 2025-06, with the labels that each got.

#7215 Optimisation: only traverse AST's if the cache is stale.
  sway-lsp/benches/lsp_benchmarks/compile.rs
  sway-lsp/benches/lsp_benchmarks/mod.rs
  sway-lsp/src/core/session.rs
  sway-lsp/src/server_state.rs
Labels: language server, performance

#7204 feat: implicitly depend on std from registry, not via git
  forc-pkg/src/manifest/mod.rs
  forc-plugins/forc-publish/src/credentials.rs
  sway-lsp/tests/lib.rs
  test/src/e2e_vm_tests/test_programs/should_pass/forc/dependency_patching/Forc.lock
Labels: enhancement, forc-pkg, forc-registry

#7219 Bump to 0.68.7
  Cargo.lock
  Cargo.toml
  sway-lib-std/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/forc/dependency_patching/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/forc/dependency_patching/Forc.toml
Labels: release

#7222 Support `GM_GET_CHAIN_ID` GM opcode with `chain_id()` function
  sway-lib-std/src/block.sw
  test/src/sdk-harness/test_artifacts/block_test_abi/src/main.sw
  test/src/sdk-harness/test_projects/block/mod.rs
  test/src/sdk-harness/test_projects/block/src/main.sw
Labels: lib: std

#6967 IR: Taking function arg address and representing references as pointers
  forc-plugins/forc-client/test/data/big_contract/src/main.sw
  forc-plugins/forc-client/tests/deploy.rs
  forc-plugins/forc-debug/tests/server_integration.rs
  forc/tests/cli_integration.rs
  sway-core/src/asm_generation/fuel/fuel_asm_builder.rs
  sway-core/src/ir_generation.rs
  sway-core/src/ir_generation/compile.rs
  sway-core/src/ir_generation/convert.rs
  sway-core/src/ir_generation/function.rs
  sway-ir/src/analysis/memory_utils.rs
  sway-ir/src/instruction.rs
  sway-ir/src/irtype.rs
  sway-ir/src/optimize/inline.rs
  sway-ir/src/optimize/mem2reg.rs
  sway-ir/src/parser.rs
  sway-ir/src/verify.rs
  test/src/e2e_vm_tests/test_programs/should_fail/language/const_generics/stdout.snap
  test/src/e2e_vm_tests/test_programs/should_pass/language/attributes_deprecated/stdout.snap
  test/src/e2e_vm_tests/test_programs/should_pass/language/configurable_consts/json_abi_oracle_new_encoding.json
  test/src/e2e_vm_tests/test_programs/should_pass/language/configurable_consts/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/configurable_dedup_decode/stdout.snap
  test/src/e2e_vm_tests/test_programs/should_pass/language/configurable_tests/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/const_generics/stdout.snap
  test/src/e2e_vm_tests/test_programs/should_pass/language/intrinsics/dbg/stdout.snap
  test/src/e2e_vm_tests/test_programs/should_pass/language/intrinsics/dbg_release/stdout.snap
  test/src/e2e_vm_tests/test_programs/should_pass/language/memcpy/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/panic_expression/panic_handling_in_unit_tests/stdout.snap
  test/src/e2e_vm_tests/test_programs/should_pass/language/panic_expression/panicking_contract/stdout.snap
  test/src/e2e_vm_tests/test_programs/should_pass/language/panic_expression/panicking_lib/stdout.snap
  test/src/e2e_vm_tests/test_programs/should_pass/language/panic_expression/panicking_script/stdout.snap
  test/src/e2e_vm_tests/test_programs/should_pass/language/references/referencing_function_parameters/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/references/referencing_function_parameters/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/references/referencing_function_parameters_simple/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/references/referencing_function_parameters_simple/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/references/referencing_function_parameters_simple/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/references/referencing_function_parameters_simple/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/u256/u256_abi/json_abi_oracle_new_encoding.json
  test/src/e2e_vm_tests/test_programs/should_pass/panic_in_non_statement_positions/stdout.snap
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/array_of_structs_caller/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/asset_ops_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/bal_opcode/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_abi_with_tuples/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_basic_storage/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_contract_with_type_aliases/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_increment_contract/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_storage_enum/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/caller_auth_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/caller_context_test/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/nested_struct_args_caller/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/storage_access_caller/src/main.sw
  test/src/ir_generation/tests/fn_call.sw
  test/src/ir_generation/tests/fn_call_ret_by_ref_implicit.sw
  test/src/ir_generation/tests/impl_self_reassignment.sw
  test/src/ir_generation/tests/predicate_data_mult_args.sw
  test/src/ir_generation/tests/predicate_data_single_arg.sw
  test/src/ir_generation/tests/revert.sw
  test/src/ir_generation/tests/shadowed_struct_init.sw
  test/src/ir_generation/tests/takes_string_returns_string.sw
  test/src/ir_generation/tests/trait.sw
  test/src/sdk-harness/test_projects/auth/mod.rs
Labels: compiler, compiler: ir

#7235 Bump to 0.68.8
  Cargo.lock
  Cargo.toml
  sway-lib-std/Forc.toml
Labels: release

#7211 Trait coherence fixes
  sway-core/src/engine_threading.rs
  sway-core/src/semantic_analysis/namespace/trait_coherence.rs
  sway-core/src/semantic_analysis/namespace/trait_map.rs
  sway-core/src/semantic_analysis/program.rs
  sway-core/src/type_system/info.rs
  sway-error/src/error.rs
  test/src/e2e_vm_tests/test_programs/should_fail/trait_coherence/orphan_rules/impl_orphan/snapshot.toml
  test/src/e2e_vm_tests/test_programs/should_fail/trait_coherence/orphan_rules/impl_orphan/stdout.snap
  test/src/e2e_vm_tests/test_programs/should_fail/trait_coherence/orphan_rules/impl_orphan/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/trait_coherence/trait_impl_constraint_overlap/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/trait_coherence/trait_impl_constraint_overlap2/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/trait_coherence/trait_impl_constraint_overlap3/test.toml
  test/src/e2e_vm_tests/test_programs/should_fail/trait_coherence/trait_impl_overlap/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/trait_coherence/trait_coherence_dup/standards/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/trait_coherence/trait_coherence_dup/standards/src/src5.sw
  test/src/e2e_vm_tests/test_programs/should_pass/trait_coherence/trait_coherence_dup/standards/src/standards.sw
  test/src/e2e_vm_tests/test_programs/should_pass/trait_coherence/trait_coherence_dup/sway_libs/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/trait_coherence/trait_coherence_dup/sway_libs/src/lib.sw
  test/src/e2e_vm_tests/test_programs/should_pass/trait_coherence/trait_coherence_dup/trait_coherence_dup/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/trait_coherence/trait_coherence_dup/trait_coherence_dup/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/trait_coherence/trait_coherence_dup/trait_coherence_dup/src/lib.sw
  test/src/e2e_vm_tests/test_programs/should_pass/trait_coherence/trait_coherence_dup/trait_coherence_dup/test.toml
Labels: compiler, compiler: frontend

#7244 Update Merkle library link to current documentation
  docs/book/src/sway-program-types/libraries.md
Labels: cla:signed

#7228 Bump fuel deps
  Cargo.lock
  Cargo.toml
  forc-pkg/Cargo.toml
  forc-plugins/forc-client/Cargo.toml
  forc-plugins/forc-client/src/cmd/call.rs
  forc-plugins/forc-client/src/op/call/call_function.rs
  forc-plugins/forc-client/src/op/call/missing_contracts.rs
  forc-plugins/forc-client/src/op/call/mod.rs
  forc-plugins/forc-client/src/op/call/transfer.rs
  forc-plugins/forc-client/src/op/deploy.rs
  forc-plugins/forc-client/src/op/run/mod.rs
  forc-plugins/forc-client/src/util/account.rs
  forc-plugins/forc-client/src/util/aws.rs
  forc-plugins/forc-client/src/util/tx.rs
  forc-plugins/forc-client/tests/deploy.rs
  forc-plugins/forc-crypto/src/address.rs
  forc-plugins/forc-crypto/src/keys/get_public_key.rs
  forc-plugins/forc-crypto/src/keys/vanity.rs
  forc-plugins/forc-migrate/Cargo.toml
  forc-plugins/forc-node/Cargo.toml
  forc-test/src/execute.rs
  forc-test/src/lib.rs
  forc-util/Cargo.toml
  forc/Cargo.toml
  scripts/mdbook-forc-documenter/Cargo.toml
  sway-core/Cargo.toml
  sway-core/src/asm_generation/finalized_asm.rs
  sway-error/Cargo.toml
  sway-lsp/Cargo.toml
  sway-types/Cargo.toml
  test/src/e2e_vm_tests/harness.rs
  test/src/e2e_vm_tests/test_programs/should_pass/language/panic_expression/panicking_contract/stdout.snap
  test/src/sdk-harness/Cargo.lock
  test/src/sdk-harness/Cargo.toml
  test/src/sdk-harness/test_projects/asset_id/mod.rs
  test/src/sdk-harness/test_projects/asset_ops/mod.rs
  test/src/sdk-harness/test_projects/auth/mod.rs
  test/src/sdk-harness/test_projects/context/mod.rs
  test/src/sdk-harness/test_projects/contract_bytecode/mod.rs
  test/src/sdk-harness/test_projects/ec_recover/mod.rs
  test/src/sdk-harness/test_projects/ec_recover_and_match_predicate/mod.rs
  test/src/sdk-harness/test_projects/evm_ec_recover/mod.rs
  test/src/sdk-harness/test_projects/messages/mod.rs
  test/src/sdk-harness/test_projects/predicate_data_simple/mod.rs
  test/src/sdk-harness/test_projects/predicate_data_struct/mod.rs
  test/src/sdk-harness/test_projects/string_slice/mod.rs
  test/src/sdk-harness/test_projects/tx_fields/mod.rs
Labels: dependencies, breaking

#7255 support `__addr_of` for all types
  docs/book/src/reference/compiler_intrinsics.md
  sway-core/src/semantic_analysis/ast_node/expression/intrinsic_function.rs
  test/src/e2e_vm_tests/test_programs/should_fail/addrof_intrinsic/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_fail/addrof_intrinsic/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_fail/addrof_intrinsic/json_abi_oracle.json
  test/src/e2e_vm_tests/test_programs/should_fail/addrof_intrinsic/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_fail/addrof_intrinsic/test.toml
  test/src/e2e_vm_tests/test_programs/should_pass/language/addrof_intrinsic/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/language/addrof_intrinsic/json_abi_oracle_new_encoding.json
  test/src/e2e_vm_tests/test_programs/should_pass/language/addrof_intrinsic/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/language/addrof_intrinsic/test.toml
Labels: compiler, compiler: frontend

#7257 remove archived `forc-explore` plugin from CI and docs
  .github/workflows/ci.yml
  .github/workflows/gh-pages.yml
  ci_checks.sh
  docs/book/README.md
  docs/book/src/SUMMARY.md
  docs/book/src/forc/plugins/forc_explore.md
  docs/book/src/forc/plugins/index.md
  scripts/mdbook-forc-documenter/README.md
  scripts/mdbook-forc-documenter/src/commands.rs
Labels: ci, documentation
