Repository FuelLabs/sway, pull requests merged in 2025-08, with the labels that each got.

#7309 chore: fix broken link in libraries.md
  docs/book/src/sway-program-types/libraries.md
Labels: cla:signed

#7320 feat: forc-debug as lib
  forc-plugins/forc-debug/src/cli/commands.rs
  forc-plugins/forc-debug/src/cli/mod.rs
  forc-plugins/forc-debug/src/cli/state.rs
  forc-plugins/forc-debug/src/debugger/commands.rs
  forc-plugins/forc-debug/src/debugger/mod.rs
  forc-plugins/forc-debug/src/error.rs
  forc-plugins/forc-debug/src/lib.rs
Labels: enhancement, forc-debug, dev-experience, team:tooling

#7323 feat: forc-call debugger integration
  Cargo.lock
  docs/book/src/SUMMARY.md
  docs/book/src/debugging/debugging_with_forc_call.md
  forc-plugins/forc-client/Cargo.toml
  forc-plugins/forc-client/src/cmd/call.rs
  forc-plugins/forc-client/src/op/call/call_function.rs
  forc-plugins/forc-mcp/src/forc_call/mod.rs
Labels: enhancement, forc-debug, dev-experience, forc-call, team:tooling

#7319 fix(docs): update Fuel VM instruction set link to new docs site
  forc-plugins/forc-client/src/op/call/trace/storage.rs
Labels: cla:signed

#7339 Don't duplicate source pointers in spans
  sway-core/src/lib.rs
  sway-types/src/source_engine.rs
  sway-types/src/span.rs
Labels: compiler, compiler: frontend, compiler: parser

#7343 `arg` and `ret` demotion passes should be module passes
  sway-ir/src/optimize/arg_demotion.rs
  sway-ir/src/optimize/ret_demotion.rs
  test/src/e2e_vm_tests/test_programs/should_pass/language/const_generics/stdout.snap
  test/src/e2e_vm_tests/test_programs/should_pass/language/panic_expression/panicking_lib/stdout.snap
Labels: compiler, compiler: ir

#7348 Eliminate `mem_copy_val`s when accessing global constants
  sway-ir/src/analysis/memory_utils.rs
  test/src/e2e_vm_tests/test_programs/should_pass/language/array/array_repeat/stdout.snap
  test/src/e2e_vm_tests/test_programs/should_pass/language/const_generics/stdout.snap
  test/src/e2e_vm_tests/test_programs/should_pass/language/intrinsics/dbg/stdout.snap
  test/src/e2e_vm_tests/test_programs/should_pass/language/panic_expression/panic_handling_in_unit_tests/stdout.snap
  test/src/e2e_vm_tests/test_programs/should_pass/language/panic_expression/panicking_contract/stdout.snap
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_basic_storage/src/main.sw
  test/src/ir_generation/tests/global_constants_usage.sw
Labels: compiler, compiler: ir

#7358 chore: fix typos
  sway-core/src/lib.rs
  sway-core/src/metadata.rs
  sway-core/src/semantic_analysis/ast_node/expression/match_expression/typed/matcher.rs
  sway-core/src/semantic_analysis/ast_node/expression/match_expression/typed/typed_match_branch.rs
  sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
  sway-core/src/semantic_analysis/module.rs
  sway-ir/src/analysis/memory_utils.rs
Labels: cla:signed

#7357 Optimize storage access compilation
  forc-plugins/forc-client/tests/deploy.rs
  sway-core/src/asm_generation/evm/evm_asm_builder.rs
  sway-core/src/asm_generation/fuel/fuel_asm_builder.rs
  sway-core/src/ir_generation/function.rs
  sway-core/src/ir_generation/storage.rs
  sway-ir/src/analysis/memory_utils.rs
  sway-ir/src/context.rs
  sway-ir/src/error.rs
  sway-ir/src/instruction.rs
  sway-ir/src/lib.rs
  sway-ir/src/module.rs
  sway-ir/src/optimize/cse.rs
  sway-ir/src/optimize/fn_dedup.rs
  sway-ir/src/optimize/inline.rs
  sway-ir/src/parser.rs
  sway-ir/src/printer.rs
  sway-ir/src/storage_key.rs
  sway-ir/src/verify.rs
  sway-ir/tests/serialize/get_storage_key.ir
  sway-types/src/u256.rs
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_basic_storage/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_increment_contract/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_storage_enum/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/storage_access_caller/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/storage_element_key_modification/Forc.lock
  test/src/e2e_vm_tests/test_programs/should_pass/storage_element_key_modification/Forc.toml
  test/src/e2e_vm_tests/test_programs/should_pass/storage_element_key_modification/src/main.sw
  test/src/e2e_vm_tests/test_programs/should_pass/storage_element_key_modification/test.toml
Labels: compiler, compiler: ir
