Repository FuelLabs/sway, pull requests merged in 2025-09, with the labels that each got.

#7367 bugfix: forc call explicit support for no external contracts
  forc-plugins/forc-client/src/cmd/call.rs
  forc-plugins/forc-client/src/op/call/call_function.rs
Labels: forc-call

#7365 fix: move std library assets into docs directory to fix GitHub Pages deployment
  .github/workflows/gh-pages.yml
Labels: bug, documentation

#7352 docs: improve docs around proxy contract deployments
  docs/book/spell-check-custom-words.txt
  docs/book/src/forc/plugins/forc_client/index.md
Labels: documentation

#7353 refactor: forc-node as lib
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  forc-plugins/forc-node/Cargo.toml
  forc-plugins/forc-node/src/ignition/op.rs
  forc-plugins/forc-node/src/lib.rs
  forc-plugins/forc-node/src/local/cmd.rs
  forc-plugins/forc-node/src/local/mod.rs
  forc-plugins/forc-node/src/local/op.rs
  forc-plugins/forc-node/src/main.rs
  forc-plugins/forc-node/src/op.rs
  forc-plugins/forc-node/src/testnet/op.rs
  forc-plugins/forc-node/src/util.rs
  forc-plugins/forc-node/tests/local.rs
Labels: forc, forc-client, forc-node

#7375 Remove emitting of `ConvertParseThreeError::SelfImplForContract`
  sway-core/src/transform/to_parsed_lang/convert_parse_tree.rs
  sway-error/src/convert_parse_tree_error.rs
Labels: compiler, compiler: frontend, compiler: parser

#7377 feat: improved reliability for failing fetches through forc-pkg
  Cargo.lock
  forc-pkg/Cargo.toml
  forc-pkg/src/source/reg/mod.rs
Labels: forc-pkg

#7400 Update nightly toolchain for cargo-udeps CI job
  .github/workflows/ci.yml
Labels: ci

#7399 Fix SourceEngine cache to refresh buffers after file edits
  sway-types/src/source_engine.rs
Labels: bug, language server, compiler: frontend

#7408 rocksdb compilation error fix
  .github/workflows/ci.yml
Labels: ci

#7416 Add "Experimental Features" chapter to The Sway Book
  docs/book/spell-check-custom-words.txt
  docs/book/src/SUMMARY.md
  docs/book/src/forc/manifest_reference.md
  docs/book/src/reference/attributes.md
  docs/book/src/reference/experimental_features.md
  docs/book/src/reference/index.md
Labels: The Sway Book
